.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001A500
    /* 1B100 8001A500 3C028007 */  lui        $v0, %hi(D_8006C6C6)
    /* 1B104 8001A504 3C038007 */  lui        $v1, %hi(D_8006C6C0)
    /* 1B108 8001A508 2463C6C0 */  addiu      $v1, $v1, %lo(D_8006C6C0)
    /* 1B10C 8001A50C 2442C6C6 */  addiu      $v0, $v0, %lo(D_8006C6C6)
    /* 1B110 8001A510 A4400000 */  sh         $zero, 0x0($v0)
    /* 1B114 8001A514 A4600000 */  sh         $zero, 0x0($v1)
    /* 1B118 8001A518 3C018007 */  lui        $at, %hi(D_8006C6C2)
    /* 1B11C 8001A51C 3C058007 */  lui        $a1, %hi(D_8006C6CC)
    /* 1B120 8001A520 A420C6C2 */  sh         $zero, %lo(D_8006C6C2)($at)
    /* 1B124 8001A524 24A5C6CC */  addiu      $a1, $a1, %lo(D_8006C6CC)
    /* 1B128 8001A528 A4A00000 */  sh         $zero, 0x0($a1)
    /* 1B12C 8001A52C 3C018007 */  lui        $at, %hi(D_8006C6CE)
    /* 1B130 8001A530 A420C6CE */  sh         $zero, %lo(D_8006C6CE)($at)
    /* 1B134 8001A534 3C018007 */  lui        $at, %hi(D_8006C6D0)
    /* 1B138 8001A538 AC24C6D0 */  sw         $a0, %lo(D_8006C6D0)($at)
    /* 1B13C 8001A53C 3C018007 */  lui        $at, %hi(D_8006C6D4)
    /* 1B140 8001A540 2419FFFF */  addiu      $t9, $zero, -0x1
    /* 1B144 8001A544 03E00008 */  jr         $ra
    /* 1B148 8001A548 A439C6D4 */   sh        $t9, %lo(D_8006C6D4)($at)

glabel func_8001A54C
    /* 1B14C 8001A54C 90820000 */  lbu        $v0, 0x0($a0)
    /* 1B150 8001A550 3C018007 */  lui        $at, %hi(D_8006C6D8)
    /* 1B154 8001A554 3C038007 */  lui        $v1, %hi(D_8006C6D9)
    /* 1B158 8001A558 2463C6D9 */  addiu      $v1, $v1, %lo(D_8006C6D9)
    /* 1B15C 8001A55C 24840001 */  addiu      $a0, $a0, 0x1
    /* 1B160 8001A560 10400006 */  beqz       $v0, .L8001A57C
    /* 1B164 8001A564 A022C6D8 */   sb        $v0, %lo(D_8006C6D8)($at)
  .L8001A568:
    /* 1B168 8001A568 90820000 */  lbu        $v0, 0x0($a0)
    /* 1B16C 8001A56C 24630001 */  addiu      $v1, $v1, 0x1
    /* 1B170 8001A570 24840001 */  addiu      $a0, $a0, 0x1
    /* 1B174 8001A574 1440FFFC */  bnez       $v0, .L8001A568
    /* 1B178 8001A578 A062FFFF */   sb        $v0, -0x1($v1)
  .L8001A57C:
    /* 1B17C 8001A57C 240E000A */  addiu      $t6, $zero, 0xA
    /* 1B180 8001A580 A06E0000 */  sb         $t6, 0x0($v1)
    /* 1B184 8001A584 3C0F8005 */  lui        $t7, %hi(D_80052AD8)
    /* 1B188 8001A588 8DEF2AD8 */  lw         $t7, %lo(D_80052AD8)($t7)
    /* 1B18C 8001A58C 3C018005 */  lui        $at, %hi(D_80053C8C)
    /* 1B190 8001A590 03E00008 */  jr         $ra
    /* 1B194 8001A594 AC2F3C8C */   sw        $t7, %lo(D_80053C8C)($at)

glabel func_8001A598
    /* 1B198 8001A598 3C078007 */  lui        $a3, %hi(D_8006C6C2)
    /* 1B19C 8001A59C 24E7C6C2 */  addiu      $a3, $a3, %lo(D_8006C6C2)
    /* 1B1A0 8001A5A0 94EE0000 */  lhu        $t6, 0x0($a3)
    /* 1B1A4 8001A5A4 90860000 */  lbu        $a2, 0x0($a0)
    /* 1B1A8 8001A5A8 3C188007 */  lui        $t8, %hi(D_8006C580)
    /* 1B1AC 8001A5AC 000E7880 */  sll        $t7, $t6, 2
    /* 1B1B0 8001A5B0 01EE7821 */  addu       $t7, $t7, $t6
    /* 1B1B4 8001A5B4 000F78C0 */  sll        $t7, $t7, 3
    /* 1B1B8 8001A5B8 2718C580 */  addiu      $t8, $t8, %lo(D_8006C580)
    /* 1B1BC 8001A5BC 01F81021 */  addu       $v0, $t7, $t8
    /* 1B1C0 8001A5C0 24050001 */  addiu      $a1, $zero, 0x1
    /* 1B1C4 8001A5C4 10C00018 */  beqz       $a2, .L8001A628
    /* 1B1C8 8001A5C8 00C01825 */   or        $v1, $a2, $zero
    /* 1B1CC 8001A5CC 3C098003 */  lui        $t1, %hi(D_800313D0)
    /* 1B1D0 8001A5D0 252913D0 */  addiu      $t1, $t1, %lo(D_800313D0)
    /* 1B1D4 8001A5D4 24080003 */  addiu      $t0, $zero, 0x3
  .L8001A5D8:
    /* 1B1D8 8001A5D8 30790080 */  andi       $t9, $v1, 0x80
    /* 1B1DC 8001A5DC 5320000A */  beql       $t9, $zero, .L8001A608
    /* 1B1E0 8001A5E0 28A30028 */   slti      $v1, $a1, 0x28
    /* 1B1E4 8001A5E4 852A0000 */  lh         $t2, 0x0($t1)
    /* 1B1E8 8001A5E8 550A0007 */  bnel       $t0, $t2, .L8001A608
    /* 1B1EC 8001A5EC 28A30028 */   slti      $v1, $a1, 0x28
    /* 1B1F0 8001A5F0 A0460000 */  sb         $a2, 0x0($v0)
    /* 1B1F4 8001A5F4 24420001 */  addiu      $v0, $v0, 0x1
    /* 1B1F8 8001A5F8 24840001 */  addiu      $a0, $a0, 0x1
    /* 1B1FC 8001A5FC 90860000 */  lbu        $a2, 0x0($a0)
    /* 1B200 8001A600 24A50001 */  addiu      $a1, $a1, 0x1
    /* 1B204 8001A604 28A30028 */  slti       $v1, $a1, 0x28
  .L8001A608:
    /* 1B208 8001A608 24A50001 */  addiu      $a1, $a1, 0x1
    /* 1B20C 8001A60C A0460000 */  sb         $a2, 0x0($v0)
    /* 1B210 8001A610 24420001 */  addiu      $v0, $v0, 0x1
    /* 1B214 8001A614 10600004 */  beqz       $v1, .L8001A628
    /* 1B218 8001A618 24840001 */   addiu     $a0, $a0, 0x1
    /* 1B21C 8001A61C 90860000 */  lbu        $a2, 0x0($a0)
    /* 1B220 8001A620 14C0FFED */  bnez       $a2, .L8001A5D8
    /* 1B224 8001A624 00C01825 */   or        $v1, $a2, $zero
  .L8001A628:
    /* 1B228 8001A628 A0400000 */  sb         $zero, 0x0($v0)
    /* 1B22C 8001A62C 94EB0000 */  lhu        $t3, 0x0($a3)
    /* 1B230 8001A630 24010008 */  addiu      $at, $zero, 0x8
    /* 1B234 8001A634 256C0001 */  addiu      $t4, $t3, 0x1
    /* 1B238 8001A638 318DFFFF */  andi       $t5, $t4, 0xFFFF
    /* 1B23C 8001A63C 15A10002 */  bne        $t5, $at, .L8001A648
    /* 1B240 8001A640 A4EC0000 */   sh        $t4, 0x0($a3)
    /* 1B244 8001A644 A4E00000 */  sh         $zero, 0x0($a3)
  .L8001A648:
    /* 1B248 8001A648 03E00008 */  jr         $ra
    /* 1B24C 8001A64C 00000000 */   nop

glabel func_8001A650
    /* 1B250 8001A650 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 1B254 8001A654 3C0F8007 */  lui        $t7, %hi(D_8006C6D4)
    /* 1B258 8001A658 85EFC6D4 */  lh         $t7, %lo(D_8006C6D4)($t7)
    /* 1B25C 8001A65C AFB00020 */  sw         $s0, 0x20($sp)
    /* 1B260 8001A660 00048400 */  sll        $s0, $a0, 16
    /* 1B264 8001A664 00107403 */  sra        $t6, $s0, 16
    /* 1B268 8001A668 01C08025 */  or         $s0, $t6, $zero
    /* 1B26C 8001A66C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1B270 8001A670 15CF0004 */  bne        $t6, $t7, .L8001A684
    /* 1B274 8001A674 AFA40028 */   sw        $a0, 0x28($sp)
    /* 1B278 8001A678 3C188007 */  lui        $t8, %hi(D_8006C6C6)
    /* 1B27C 8001A67C 9718C6C6 */  lhu        $t8, %lo(D_8006C6C6)($t8)
    /* 1B280 8001A680 17000042 */  bnez       $t8, .L8001A78C
  .L8001A684:
    /* 1B284 8001A684 24010001 */   addiu     $at, $zero, 0x1
    /* 1B288 8001A688 12010005 */  beq        $s0, $at, .L8001A6A0
    /* 1B28C 8001A68C 00002025 */   or        $a0, $zero, $zero
    /* 1B290 8001A690 24010017 */  addiu      $at, $zero, 0x17
    /* 1B294 8001A694 12010002 */  beq        $s0, $at, .L8001A6A0
    /* 1B298 8001A698 24010018 */   addiu     $at, $zero, 0x18
    /* 1B29C 8001A69C 16010007 */  bne        $s0, $at, .L8001A6BC
  .L8001A6A0:
    /* 1B2A0 8001A6A0 3C018004 */   lui       $at, %hi(D_80039830)
    /* 1B2A4 8001A6A4 C4249830 */  lwc1       $ft0, %lo(D_80039830)($at)
    /* 1B2A8 8001A6A8 2405017B */  addiu      $a1, $zero, 0x17B
    /* 1B2AC 8001A6AC 24060000 */  addiu      $a2, $zero, 0x0
    /* 1B2B0 8001A6B0 00003825 */  or         $a3, $zero, $zero
    /* 1B2B4 8001A6B4 0C00528F */  jal        func_80014A3C
    /* 1B2B8 8001A6B8 E7A40010 */   swc1      $ft0, 0x10($sp)
  .L8001A6BC:
    /* 1B2BC 8001A6BC 3C018007 */  lui        $at, %hi(D_8006C6D4)
    /* 1B2C0 8001A6C0 A430C6D4 */  sh         $s0, %lo(D_8006C6D4)($at)
    /* 1B2C4 8001A6C4 2A010019 */  slti       $at, $s0, 0x19
    /* 1B2C8 8001A6C8 1020001C */  beqz       $at, .L8001A73C
    /* 1B2CC 8001A6CC 3C028003 */   lui       $v0, %hi(D_800313D0)
    /* 1B2D0 8001A6D0 844213D0 */  lh         $v0, %lo(D_800313D0)($v0)
    /* 1B2D4 8001A6D4 24010001 */  addiu      $at, $zero, 0x1
    /* 1B2D8 8001A6D8 0010C8C0 */  sll        $t9, $s0, 3
    /* 1B2DC 8001A6DC 10400006 */  beqz       $v0, .L8001A6F8
    /* 1B2E0 8001A6E0 3C048003 */   lui       $a0, %hi(D_800344B4)
    /* 1B2E4 8001A6E4 10410009 */  beq        $v0, $at, .L8001A70C
    /* 1B2E8 8001A6E8 001040C0 */   sll       $t0, $s0, 3
    /* 1B2EC 8001A6EC 24010002 */  addiu      $at, $zero, 0x2
    /* 1B2F0 8001A6F0 1041000C */  beq        $v0, $at, .L8001A724
    /* 1B2F4 8001A6F4 001048C0 */   sll       $t1, $s0, 3
  .L8001A6F8:
    /* 1B2F8 8001A6F8 00992021 */  addu       $a0, $a0, $t9
    /* 1B2FC 8001A6FC 0C006966 */  jal        func_8001A598
    /* 1B300 8001A700 8C8444B4 */   lw        $a0, %lo(D_800344B4)($a0)
    /* 1B304 8001A704 10000022 */  b          .L8001A790
    /* 1B308 8001A708 8FBF0024 */   lw        $ra, 0x24($sp)
  .L8001A70C:
    /* 1B30C 8001A70C 3C048003 */  lui        $a0, %hi(D_80034C44)
    /* 1B310 8001A710 00882021 */  addu       $a0, $a0, $t0
    /* 1B314 8001A714 0C006966 */  jal        func_8001A598
    /* 1B318 8001A718 8C844C44 */   lw        $a0, %lo(D_80034C44)($a0)
    /* 1B31C 8001A71C 1000001C */  b          .L8001A790
    /* 1B320 8001A720 8FBF0024 */   lw        $ra, 0x24($sp)
  .L8001A724:
    /* 1B324 8001A724 3C048003 */  lui        $a0, %hi(D_80034D0C)
    /* 1B328 8001A728 00892021 */  addu       $a0, $a0, $t1
    /* 1B32C 8001A72C 0C006966 */  jal        func_8001A598
    /* 1B330 8001A730 8C844D0C */   lw        $a0, %lo(D_80034D0C)($a0)
    /* 1B334 8001A734 10000016 */  b          .L8001A790
    /* 1B338 8001A738 8FBF0024 */   lw        $ra, 0x24($sp)
  .L8001A73C:
    /* 1B33C 8001A73C 240100D6 */  addiu      $at, $zero, 0xD6
    /* 1B340 8001A740 1601000D */  bne        $s0, $at, .L8001A778
    /* 1B344 8001A744 3C048004 */   lui       $a0, %hi(D_800397DC)
    /* 1B348 8001A748 0C00731B */  jal        func_8001CC6C
    /* 1B34C 8001A74C 248497DC */   addiu     $a0, $a0, %lo(D_800397DC)
    /* 1B350 8001A750 3C028003 */  lui        $v0, %hi(D_800313D0)
    /* 1B354 8001A754 844213D0 */  lh         $v0, %lo(D_800313D0)($v0)
    /* 1B358 8001A758 24010001 */  addiu      $at, $zero, 0x1
    /* 1B35C 8001A75C 54410003 */  bnel       $v0, $at, .L8001A76C
    /* 1B360 8001A760 24010002 */   addiu     $at, $zero, 0x2
    /* 1B364 8001A764 241000F0 */  addiu      $s0, $zero, 0xF0
    /* 1B368 8001A768 24010002 */  addiu      $at, $zero, 0x2
  .L8001A76C:
    /* 1B36C 8001A76C 54410003 */  bnel       $v0, $at, .L8001A77C
    /* 1B370 8001A770 001050C0 */   sll       $t2, $s0, 3
    /* 1B374 8001A774 241000F1 */  addiu      $s0, $zero, 0xF1
  .L8001A778:
    /* 1B378 8001A778 001050C0 */  sll        $t2, $s0, 3
  .L8001A77C:
    /* 1B37C 8001A77C 3C048003 */  lui        $a0, %hi(D_800344B4)
    /* 1B380 8001A780 008A2021 */  addu       $a0, $a0, $t2
    /* 1B384 8001A784 0C006966 */  jal        func_8001A598
    /* 1B388 8001A788 8C8444B4 */   lw        $a0, %lo(D_800344B4)($a0)
  .L8001A78C:
    /* 1B38C 8001A78C 8FBF0024 */  lw         $ra, 0x24($sp)
  .L8001A790:
    /* 1B390 8001A790 8FB00020 */  lw         $s0, 0x20($sp)
    /* 1B394 8001A794 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 1B398 8001A798 03E00008 */  jr         $ra
    /* 1B39C 8001A79C 00000000 */   nop

glabel func_8001A7A0
    /* 1B3A0 8001A7A0 AFA40000 */  sw         $a0, 0x0($sp)
    /* 1B3A4 8001A7A4 00047400 */  sll        $t6, $a0, 16
    /* 1B3A8 8001A7A8 000E2403 */  sra        $a0, $t6, 16
    /* 1B3AC 8001A7AC 28810019 */  slti       $at, $a0, 0x19
    /* 1B3B0 8001A7B0 10200018 */  beqz       $at, .L8001A814
    /* 1B3B4 8001A7B4 000448C0 */   sll       $t1, $a0, 3
    /* 1B3B8 8001A7B8 3C028003 */  lui        $v0, %hi(D_800313D0)
    /* 1B3BC 8001A7BC 844213D0 */  lh         $v0, %lo(D_800313D0)($v0)
    /* 1B3C0 8001A7C0 24010001 */  addiu      $at, $zero, 0x1
    /* 1B3C4 8001A7C4 0004C0C0 */  sll        $t8, $a0, 3
    /* 1B3C8 8001A7C8 10400006 */  beqz       $v0, .L8001A7E4
    /* 1B3CC 8001A7CC 00000000 */   nop
    /* 1B3D0 8001A7D0 10410008 */  beq        $v0, $at, .L8001A7F4
    /* 1B3D4 8001A7D4 0004C8C0 */   sll       $t9, $a0, 3
    /* 1B3D8 8001A7D8 24010002 */  addiu      $at, $zero, 0x2
    /* 1B3DC 8001A7DC 10410009 */  beq        $v0, $at, .L8001A804
    /* 1B3E0 8001A7E0 000440C0 */   sll       $t0, $a0, 3
  .L8001A7E4:
    /* 1B3E4 8001A7E4 3C028003 */  lui        $v0, %hi(D_800344B4)
    /* 1B3E8 8001A7E8 00581021 */  addu       $v0, $v0, $t8
    /* 1B3EC 8001A7EC 03E00008 */  jr         $ra
    /* 1B3F0 8001A7F0 8C4244B4 */   lw        $v0, %lo(D_800344B4)($v0)
  .L8001A7F4:
    /* 1B3F4 8001A7F4 3C028003 */  lui        $v0, %hi(D_80034C44)
    /* 1B3F8 8001A7F8 00591021 */  addu       $v0, $v0, $t9
    /* 1B3FC 8001A7FC 03E00008 */  jr         $ra
    /* 1B400 8001A800 8C424C44 */   lw        $v0, %lo(D_80034C44)($v0)
  .L8001A804:
    /* 1B404 8001A804 3C028003 */  lui        $v0, %hi(D_80034D0C)
    /* 1B408 8001A808 00481021 */  addu       $v0, $v0, $t0
    /* 1B40C 8001A80C 03E00008 */  jr         $ra
    /* 1B410 8001A810 8C424D0C */   lw        $v0, %lo(D_80034D0C)($v0)
  .L8001A814:
    /* 1B414 8001A814 3C028003 */  lui        $v0, %hi(D_800344B4)
    /* 1B418 8001A818 00491021 */  addu       $v0, $v0, $t1
    /* 1B41C 8001A81C 8C4244B4 */  lw         $v0, %lo(D_800344B4)($v0)
    /* 1B420 8001A820 03E00008 */  jr         $ra
    /* 1B424 8001A824 00000000 */   nop

glabel func_8001A828
    /* 1B428 8001A828 3C0E8004 */  lui        $t6, %hi(D_80047F90)
    /* 1B42C 8001A82C 8DCE7F90 */  lw         $t6, %lo(D_80047F90)($t6)
    /* 1B430 8001A830 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 1B434 8001A834 24010001 */  addiu      $at, $zero, 0x1
    /* 1B438 8001A838 15C1000B */  bne        $t6, $at, .L8001A868
    /* 1B43C 8001A83C AFBF001C */   sw        $ra, 0x1C($sp)
    /* 1B440 8001A840 240F0078 */  addiu      $t7, $zero, 0x78
    /* 1B444 8001A844 3C018005 */  lui        $at, %hi(D_80053BF8)
    /* 1B448 8001A848 A42F3BF8 */  sh         $t7, %lo(D_80053BF8)($at)
    /* 1B44C 8001A84C 3C018005 */  lui        $at, %hi(D_80053BFA)
    /* 1B450 8001A850 241800C8 */  addiu      $t8, $zero, 0xC8
    /* 1B454 8001A854 A4383BFA */  sh         $t8, %lo(D_80053BFA)($at)
    /* 1B458 8001A858 3C018005 */  lui        $at, %hi(D_80053BFC)
    /* 1B45C 8001A85C 2419001E */  addiu      $t9, $zero, 0x1E
    /* 1B460 8001A860 1000000A */  b          .L8001A88C
    /* 1B464 8001A864 A4393BFC */   sh        $t9, %lo(D_80053BFC)($at)
  .L8001A868:
    /* 1B468 8001A868 2408001E */  addiu      $t0, $zero, 0x1E
    /* 1B46C 8001A86C 3C018005 */  lui        $at, %hi(D_80053BF8)
    /* 1B470 8001A870 A4283BF8 */  sh         $t0, %lo(D_80053BF8)($at)
    /* 1B474 8001A874 3C018005 */  lui        $at, %hi(D_80053BFA)
    /* 1B478 8001A878 2409008C */  addiu      $t1, $zero, 0x8C
    /* 1B47C 8001A87C A4293BFA */  sh         $t1, %lo(D_80053BFA)($at)
    /* 1B480 8001A880 3C018005 */  lui        $at, %hi(D_80053BFC)
    /* 1B484 8001A884 240A00F0 */  addiu      $t2, $zero, 0xF0
    /* 1B488 8001A888 A42A3BFC */  sh         $t2, %lo(D_80053BFC)($at)
  .L8001A88C:
    /* 1B48C 8001A88C 3C0B8007 */  lui        $t3, %hi(D_8006C6D8)
    /* 1B490 8001A890 256BC6D8 */  addiu      $t3, $t3, %lo(D_8006C6D8)
    /* 1B494 8001A894 3C048004 */  lui        $a0, %hi(D_800397EC)
    /* 1B498 8001A898 248497EC */  addiu      $a0, $a0, %lo(D_800397EC)
    /* 1B49C 8001A89C AFAB0010 */  sw         $t3, 0x10($sp)
    /* 1B4A0 8001A8A0 00002825 */  or         $a1, $zero, $zero
    /* 1B4A4 8001A8A4 24060080 */  addiu      $a2, $zero, 0x80
    /* 1B4A8 8001A8A8 0C002929 */  jal        func_8000A4A4
    /* 1B4AC 8001A8AC 00003825 */   or        $a3, $zero, $zero
    /* 1B4B0 8001A8B0 3C0C8007 */  lui        $t4, %hi(D_8006C6C2)
    /* 1B4B4 8001A8B4 3C0D8007 */  lui        $t5, %hi(D_8006C6C0)
    /* 1B4B8 8001A8B8 95ADC6C0 */  lhu        $t5, %lo(D_8006C6C0)($t5)
    /* 1B4BC 8001A8BC 958CC6C2 */  lhu        $t4, %lo(D_8006C6C2)($t4)
    /* 1B4C0 8001A8C0 3C068007 */  lui        $a2, %hi(D_8006C6C6)
    /* 1B4C4 8001A8C4 24C6C6C6 */  addiu      $a2, $a2, %lo(D_8006C6C6)
    /* 1B4C8 8001A8C8 158D0004 */  bne        $t4, $t5, .L8001A8DC
    /* 1B4CC 8001A8CC 3C0F8005 */   lui       $t7, %hi(D_80052AD0)
    /* 1B4D0 8001A8D0 94CE0000 */  lhu        $t6, 0x0($a2)
    /* 1B4D4 8001A8D4 51C000BC */  beql       $t6, $zero, .L8001ABC8
    /* 1B4D8 8001A8D8 8FBF001C */   lw        $ra, 0x1C($sp)
  .L8001A8DC:
    /* 1B4DC 8001A8DC 8DEF2AD0 */  lw         $t7, %lo(D_80052AD0)($t7)
    /* 1B4E0 8001A8E0 51E000B9 */  beql       $t7, $zero, .L8001ABC8
    /* 1B4E4 8001A8E4 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1B4E8 8001A8E8 0C0062B2 */  jal        func_80018AC8
    /* 1B4EC 8001A8EC 00000000 */   nop
    /* 1B4F0 8001A8F0 3C068007 */  lui        $a2, %hi(D_8006C6C6)
    /* 1B4F4 8001A8F4 14400040 */  bnez       $v0, .L8001A9F8
    /* 1B4F8 8001A8F8 24C6C6C6 */   addiu     $a2, $a2, %lo(D_8006C6C6)
    /* 1B4FC 8001A8FC 94C30000 */  lhu        $v1, 0x0($a2)
    /* 1B500 8001A900 3C088007 */  lui        $t0, %hi(D_8006C6C8)
    /* 1B504 8001A904 3C028007 */  lui        $v0, %hi(D_8006C6C0)
    /* 1B508 8001A908 1060000A */  beqz       $v1, .L8001A934
    /* 1B50C 8001A90C 28610009 */   slti      $at, $v1, 0x9
    /* 1B510 8001A910 14200039 */  bnez       $at, .L8001A9F8
    /* 1B514 8001A914 28610012 */   slti      $at, $v1, 0x12
    /* 1B518 8001A918 10200037 */  beqz       $at, .L8001A9F8
    /* 1B51C 8001A91C 3C188007 */   lui       $t8, %hi(D_8006C6C2)
    /* 1B520 8001A920 3C198007 */  lui        $t9, %hi(D_8006C6C0)
    /* 1B524 8001A924 9739C6C0 */  lhu        $t9, %lo(D_8006C6C0)($t9)
    /* 1B528 8001A928 9718C6C2 */  lhu        $t8, %lo(D_8006C6C2)($t8)
    /* 1B52C 8001A92C 53190033 */  beql       $t8, $t9, .L8001A9FC
    /* 1B530 8001A930 94CB0000 */   lhu       $t3, 0x0($a2)
  .L8001A934:
    /* 1B534 8001A934 9442C6C0 */  lhu        $v0, %lo(D_8006C6C0)($v0)
    /* 1B538 8001A938 9508C6C8 */  lhu        $t0, %lo(D_8006C6C8)($t0)
    /* 1B53C 8001A93C 3C018007 */  lui        $at, %hi(D_8006C6CC)
    /* 1B540 8001A940 A423C6CC */  sh         $v1, %lo(D_8006C6CC)($at)
    /* 1B544 8001A944 24490007 */  addiu      $t1, $v0, 0x7
    /* 1B548 8001A948 3C018007 */  lui        $at, %hi(D_8006C6CE)
    /* 1B54C 8001A94C 00025880 */  sll        $t3, $v0, 2
    /* 1B550 8001A950 3C0C8007 */  lui        $t4, %hi(D_8006C580)
    /* 1B554 8001A954 01625821 */  addu       $t3, $t3, $v0
    /* 1B558 8001A958 A428C6CE */  sh         $t0, %lo(D_8006C6CE)($at)
    /* 1B55C 8001A95C 3C018007 */  lui        $at, %hi(D_8006C6C8 + 0x2)
    /* 1B560 8001A960 05210004 */  bgez       $t1, .L8001A974
    /* 1B564 8001A964 312A0007 */   andi      $t2, $t1, 0x7
    /* 1B568 8001A968 11400002 */  beqz       $t2, .L8001A974
    /* 1B56C 8001A96C 00000000 */   nop
    /* 1B570 8001A970 254AFFF8 */  addiu      $t2, $t2, -0x8
  .L8001A974:
    /* 1B574 8001A974 000B58C0 */  sll        $t3, $t3, 3
    /* 1B578 8001A978 258CC580 */  addiu      $t4, $t4, %lo(D_8006C580)
    /* 1B57C 8001A97C A42AC6CA */  sh         $t2, %lo(D_8006C6C8 + 0x2)($at)
    /* 1B580 8001A980 016C2021 */  addu       $a0, $t3, $t4
    /* 1B584 8001A984 0C0028AE */  jal        func_8000A2B8
    /* 1B588 8001A988 00002825 */   or        $a1, $zero, $zero
    /* 1B58C 8001A98C 244D0050 */  addiu      $t5, $v0, 0x50
    /* 1B590 8001A990 24010003 */  addiu      $at, $zero, 0x3
    /* 1B594 8001A994 01A1001A */  div        $zero, $t5, $at
    /* 1B598 8001A998 00007012 */  mflo       $t6
    /* 1B59C 8001A99C 3C068007 */  lui        $a2, %hi(D_8006C6C6)
    /* 1B5A0 8001A9A0 24C6C6C6 */  addiu      $a2, $a2, %lo(D_8006C6C6)
    /* 1B5A4 8001A9A4 25CF0010 */  addiu      $t7, $t6, 0x10
    /* 1B5A8 8001A9A8 A4CF0000 */  sh         $t7, 0x0($a2)
    /* 1B5AC 8001A9AC 3C188007 */  lui        $t8, %hi(D_8006C6CC)
    /* 1B5B0 8001A9B0 9718C6CC */  lhu        $t8, %lo(D_8006C6CC)($t8)
    /* 1B5B4 8001A9B4 31E3FFFF */  andi       $v1, $t7, 0xFFFF
    /* 1B5B8 8001A9B8 3C018007 */  lui        $at, %hi(D_8006C6C4)
    /* 1B5BC 8001A9BC 13000003 */  beqz       $t8, .L8001A9CC
    /* 1B5C0 8001A9C0 A423C6C4 */   sh        $v1, %lo(D_8006C6C4)($at)
    /* 1B5C4 8001A9C4 2479FFF8 */  addiu      $t9, $v1, -0x8
    /* 1B5C8 8001A9C8 A4D90000 */  sh         $t9, 0x0($a2)
  .L8001A9CC:
    /* 1B5CC 8001A9CC 3C028007 */  lui        $v0, %hi(D_8006C6C0)
    /* 1B5D0 8001A9D0 3C018007 */  lui        $at, %hi(D_8006C6C8)
    /* 1B5D4 8001A9D4 2442C6C0 */  addiu      $v0, $v0, %lo(D_8006C6C0)
    /* 1B5D8 8001A9D8 A420C6C8 */  sh         $zero, %lo(D_8006C6C8)($at)
    /* 1B5DC 8001A9DC 94480000 */  lhu        $t0, 0x0($v0)
    /* 1B5E0 8001A9E0 24010008 */  addiu      $at, $zero, 0x8
    /* 1B5E4 8001A9E4 25090001 */  addiu      $t1, $t0, 0x1
    /* 1B5E8 8001A9E8 312AFFFF */  andi       $t2, $t1, 0xFFFF
    /* 1B5EC 8001A9EC 15410002 */  bne        $t2, $at, .L8001A9F8
    /* 1B5F0 8001A9F0 A4490000 */   sh        $t1, 0x0($v0)
    /* 1B5F4 8001A9F4 A4400000 */  sh         $zero, 0x0($v0)
  .L8001A9F8:
    /* 1B5F8 8001A9F8 94CB0000 */  lhu        $t3, 0x0($a2)
  .L8001A9FC:
    /* 1B5FC 8001A9FC 51600072 */  beql       $t3, $zero, .L8001ABC8
    /* 1B600 8001AA00 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 1B604 8001AA04 0C0062B2 */  jal        func_80018AC8
    /* 1B608 8001AA08 00000000 */   nop
    /* 1B60C 8001AA0C 3C068007 */  lui        $a2, %hi(D_8006C6C6)
    /* 1B610 8001AA10 1440006C */  bnez       $v0, .L8001ABC4
    /* 1B614 8001AA14 24C6C6C6 */   addiu     $a2, $a2, %lo(D_8006C6C6)
    /* 1B618 8001AA18 94CC0000 */  lhu        $t4, 0x0($a2)
    /* 1B61C 8001AA1C 3C0F8007 */  lui        $t7, %hi(D_8006C6C4)
    /* 1B620 8001AA20 3C048004 */  lui        $a0, %hi(D_800397F8)
    /* 1B624 8001AA24 258DFFFF */  addiu      $t5, $t4, -0x1
    /* 1B628 8001AA28 A4CD0000 */  sh         $t5, 0x0($a2)
    /* 1B62C 8001AA2C 95EFC6C4 */  lhu        $t7, %lo(D_8006C6C4)($t7)
    /* 1B630 8001AA30 31AEFFFF */  andi       $t6, $t5, 0xFFFF
    /* 1B634 8001AA34 248497F8 */  addiu      $a0, $a0, %lo(D_800397F8)
    /* 1B638 8001AA38 25F8FFF8 */  addiu      $t8, $t7, -0x8
    /* 1B63C 8001AA3C 030E082A */  slt        $at, $t8, $t6
    /* 1B640 8001AA40 14200060 */  bnez       $at, .L8001ABC4
    /* 1B644 8001AA44 24050078 */   addiu     $a1, $zero, 0x78
    /* 1B648 8001AA48 241900CC */  addiu      $t9, $zero, 0xCC
    /* 1B64C 8001AA4C AFB90010 */  sw         $t9, 0x10($sp)
    /* 1B650 8001AA50 240600B8 */  addiu      $a2, $zero, 0xB8
    /* 1B654 8001AA54 0C002929 */  jal        func_8000A4A4
    /* 1B658 8001AA58 240700BE */   addiu     $a3, $zero, 0xBE
    /* 1B65C 8001AA5C 3C048004 */  lui        $a0, %hi(D_800397FC)
    /* 1B660 8001AA60 240800FF */  addiu      $t0, $zero, 0xFF
    /* 1B664 8001AA64 AFA80010 */  sw         $t0, 0x10($sp)
    /* 1B668 8001AA68 248497FC */  addiu      $a0, $a0, %lo(D_800397FC)
    /* 1B66C 8001AA6C 240500FF */  addiu      $a1, $zero, 0xFF
    /* 1B670 8001AA70 240600FF */  addiu      $a2, $zero, 0xFF
    /* 1B674 8001AA74 0C002929 */  jal        func_8000A4A4
    /* 1B678 8001AA78 240700FF */   addiu     $a3, $zero, 0xFF
    /* 1B67C 8001AA7C 3C048004 */  lui        $a0, %hi(D_80039804)
    /* 1B680 8001AA80 24849804 */  addiu      $a0, $a0, %lo(D_80039804)
    /* 1B684 8001AA84 0C002929 */  jal        func_8000A4A4
    /* 1B688 8001AA88 2405004E */   addiu     $a1, $zero, 0x4E
    /* 1B68C 8001AA8C 3C058007 */  lui        $a1, %hi(D_8006C6C8)
    /* 1B690 8001AA90 94A5C6C8 */  lhu        $a1, %lo(D_8006C6C8)($a1)
    /* 1B694 8001AA94 3C048004 */  lui        $a0, %hi(D_80039808)
    /* 1B698 8001AA98 24849808 */  addiu      $a0, $a0, %lo(D_80039808)
    /* 1B69C 8001AA9C 00054880 */  sll        $t1, $a1, 2
    /* 1B6A0 8001AAA0 0C002929 */  jal        func_8000A4A4
    /* 1B6A4 8001AAA4 01202825 */   or        $a1, $t1, $zero
    /* 1B6A8 8001AAA8 3C0C8007 */  lui        $t4, %hi(D_8006C6C0)
    /* 1B6AC 8001AAAC 958CC6C0 */  lhu        $t4, %lo(D_8006C6C0)($t4)
    /* 1B6B0 8001AAB0 3C0A8007 */  lui        $t2, %hi(D_8006C6C8)
    /* 1B6B4 8001AAB4 954AC6C8 */  lhu        $t2, %lo(D_8006C6C8)($t2)
    /* 1B6B8 8001AAB8 258D0007 */  addiu      $t5, $t4, 0x7
    /* 1B6BC 8001AABC 3C188007 */  lui        $t8, %hi(D_8006C580)
    /* 1B6C0 8001AAC0 3C018007 */  lui        $at, %hi(D_8006C6C8)
    /* 1B6C4 8001AAC4 2718C580 */  addiu      $t8, $t8, %lo(D_8006C580)
    /* 1B6C8 8001AAC8 3C048004 */  lui        $a0, %hi(D_8003980C)
    /* 1B6CC 8001AACC 254BFFFD */  addiu      $t3, $t2, -0x3
    /* 1B6D0 8001AAD0 A42BC6C8 */  sh         $t3, %lo(D_8006C6C8)($at)
    /* 1B6D4 8001AAD4 2484980C */  addiu      $a0, $a0, %lo(D_8003980C)
    /* 1B6D8 8001AAD8 24050018 */  addiu      $a1, $zero, 0x18
    /* 1B6DC 8001AADC 24060007 */  addiu      $a2, $zero, 0x7
    /* 1B6E0 8001AAE0 05A10004 */  bgez       $t5, .L8001AAF4
    /* 1B6E4 8001AAE4 31AF0007 */   andi      $t7, $t5, 0x7
    /* 1B6E8 8001AAE8 11E00002 */  beqz       $t7, .L8001AAF4
    /* 1B6EC 8001AAEC 00000000 */   nop
    /* 1B6F0 8001AAF0 25EFFFF8 */  addiu      $t7, $t7, -0x8
  .L8001AAF4:
    /* 1B6F4 8001AAF4 000F7080 */  sll        $t6, $t7, 2
    /* 1B6F8 8001AAF8 01CF7021 */  addu       $t6, $t6, $t7
    /* 1B6FC 8001AAFC 000E70C0 */  sll        $t6, $t6, 3
    /* 1B700 8001AB00 0C002929 */  jal        func_8000A4A4
    /* 1B704 8001AB04 01D83821 */   addu      $a3, $t6, $t8
    /* 1B708 8001AB08 3C038007 */  lui        $v1, %hi(D_8006C6CC)
    /* 1B70C 8001AB0C 2463C6CC */  addiu      $v1, $v1, %lo(D_8006C6CC)
    /* 1B710 8001AB10 94620000 */  lhu        $v0, 0x0($v1)
    /* 1B714 8001AB14 3C058007 */  lui        $a1, %hi(D_8006C6CE)
    /* 1B718 8001AB18 1040001A */  beqz       $v0, .L8001AB84
    /* 1B71C 8001AB1C 2459FFFF */   addiu     $t9, $v0, -0x1
    /* 1B720 8001AB20 A4790000 */  sh         $t9, 0x0($v1)
    /* 1B724 8001AB24 94A5C6CE */  lhu        $a1, %lo(D_8006C6CE)($a1)
    /* 1B728 8001AB28 3C048004 */  lui        $a0, %hi(D_80039814)
    /* 1B72C 8001AB2C 24849814 */  addiu      $a0, $a0, %lo(D_80039814)
    /* 1B730 8001AB30 00054080 */  sll        $t0, $a1, 2
    /* 1B734 8001AB34 0C002929 */  jal        func_8000A4A4
    /* 1B738 8001AB38 01002825 */   or        $a1, $t0, $zero
    /* 1B73C 8001AB3C 3C0B8007 */  lui        $t3, %hi(D_8006C6C8 + 0x2)
    /* 1B740 8001AB40 956BC6CA */  lhu        $t3, %lo(D_8006C6C8 + 0x2)($t3)
    /* 1B744 8001AB44 3C098007 */  lui        $t1, %hi(D_8006C6CE)
    /* 1B748 8001AB48 9529C6CE */  lhu        $t1, %lo(D_8006C6CE)($t1)
    /* 1B74C 8001AB4C 000B6080 */  sll        $t4, $t3, 2
    /* 1B750 8001AB50 3C0D8007 */  lui        $t5, %hi(D_8006C580)
    /* 1B754 8001AB54 018B6021 */  addu       $t4, $t4, $t3
    /* 1B758 8001AB58 3C018007 */  lui        $at, %hi(D_8006C6CE)
    /* 1B75C 8001AB5C 000C60C0 */  sll        $t4, $t4, 3
    /* 1B760 8001AB60 25ADC580 */  addiu      $t5, $t5, %lo(D_8006C580)
    /* 1B764 8001AB64 3C048004 */  lui        $a0, %hi(D_80039818)
    /* 1B768 8001AB68 252AFFFD */  addiu      $t2, $t1, -0x3
    /* 1B76C 8001AB6C A42AC6CE */  sh         $t2, %lo(D_8006C6CE)($at)
    /* 1B770 8001AB70 24849818 */  addiu      $a0, $a0, %lo(D_80039818)
    /* 1B774 8001AB74 018D3821 */  addu       $a3, $t4, $t5
    /* 1B778 8001AB78 24050018 */  addiu      $a1, $zero, 0x18
    /* 1B77C 8001AB7C 0C002929 */  jal        func_8000A4A4
    /* 1B780 8001AB80 24060007 */   addiu     $a2, $zero, 0x7
  .L8001AB84:
    /* 1B784 8001AB84 3C048004 */  lui        $a0, %hi(D_80039820)
    /* 1B788 8001AB88 240F00FF */  addiu      $t7, $zero, 0xFF
    /* 1B78C 8001AB8C AFAF0010 */  sw         $t7, 0x10($sp)
    /* 1B790 8001AB90 24849820 */  addiu      $a0, $a0, %lo(D_80039820)
    /* 1B794 8001AB94 240500E6 */  addiu      $a1, $zero, 0xE6
    /* 1B798 8001AB98 240600E6 */  addiu      $a2, $zero, 0xE6
    /* 1B79C 8001AB9C 0C002929 */  jal        func_8000A4A4
    /* 1B7A0 8001ABA0 240700E6 */   addiu     $a3, $zero, 0xE6
    /* 1B7A4 8001ABA4 3C048004 */  lui        $a0, %hi(D_80039828)
    /* 1B7A8 8001ABA8 24849828 */  addiu      $a0, $a0, %lo(D_80039828)
    /* 1B7AC 8001ABAC 0C002929 */  jal        func_8000A4A4
    /* 1B7B0 8001ABB0 00002825 */   or        $a1, $zero, $zero
    /* 1B7B4 8001ABB4 3C048004 */  lui        $a0, %hi(D_8003982C)
    /* 1B7B8 8001ABB8 2484982C */  addiu      $a0, $a0, %lo(D_8003982C)
    /* 1B7BC 8001ABBC 0C002929 */  jal        func_8000A4A4
    /* 1B7C0 8001ABC0 00002825 */   or        $a1, $zero, $zero
  .L8001ABC4:
    /* 1B7C4 8001ABC4 8FBF001C */  lw         $ra, 0x1C($sp)
  .L8001ABC8:
    /* 1B7C8 8001ABC8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 1B7CC 8001ABCC 03E00008 */  jr         $ra
    /* 1B7D0 8001ABD0 00000000 */   nop
    /* 1B7D4 8001ABD4 00000000 */  nop
    /* 1B7D8 8001ABD8 00000000 */  nop
    /* 1B7DC 8001ABDC 00000000 */  nop
