.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001ABE0
    /* 1B7E0 8001ABE0 3C0E8003 */  lui        $t6, %hi(D_80035618)
    /* 1B7E4 8001ABE4 8DCE5618 */  lw         $t6, %lo(D_80035618)($t6)
    /* 1B7E8 8001ABE8 44844000 */  mtc1       $a0, $ft2
    /* 1B7EC 8001ABEC 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 1B7F0 8001ABF0 448E2000 */  mtc1       $t6, $ft0
    /* 1B7F4 8001ABF4 468042A0 */  cvt.s.w    $ft3, $ft2
    /* 1B7F8 8001ABF8 04810005 */  bgez       $a0, .L8001AC10
    /* 1B7FC 8001ABFC 468021A0 */   cvt.s.w   $ft1, $ft0
    /* 1B800 8001AC00 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 1B804 8001AC04 44818000 */  mtc1       $at, $ft4
    /* 1B808 8001AC08 00000000 */  nop
    /* 1B80C 8001AC0C 46105280 */  add.s      $ft3, $ft3, $ft4
  .L8001AC10:
    /* 1B810 8001AC10 460A3483 */  div.s      $ft5, $ft1, $ft3
    /* 1B814 8001AC14 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* 1B818 8001AC18 44812000 */  mtc1       $at, $ft0
    /* 1B81C 8001AC1C 24050001 */  addiu      $a1, $zero, 0x1
    /* 1B820 8001AC20 46049300 */  add.s      $fa0, $ft5, $ft0
    /* 1B824 8001AC24 444FF800 */  cfc1       $t7, $31
    /* 1B828 8001AC28 44C5F800 */  ctc1       $a1, $31
    /* 1B82C 8001AC2C 00000000 */  nop
    /* 1B830 8001AC30 46006224 */  cvt.w.s    $ft2, $fa0
    /* 1B834 8001AC34 4445F800 */  cfc1       $a1, $31
    /* 1B838 8001AC38 00000000 */  nop
    /* 1B83C 8001AC3C 30A10004 */  andi       $at, $a1, 0x4
    /* 1B840 8001AC40 30A50078 */  andi       $a1, $a1, 0x78
    /* 1B844 8001AC44 10A00013 */  beqz       $a1, .L8001AC94
    /* 1B848 8001AC48 3C014F00 */   lui       $at, (0x4F000000 >> 16)
    /* 1B84C 8001AC4C 44814000 */  mtc1       $at, $ft2
    /* 1B850 8001AC50 24050001 */  addiu      $a1, $zero, 0x1
    /* 1B854 8001AC54 46086201 */  sub.s      $ft2, $fa0, $ft2
    /* 1B858 8001AC58 44C5F800 */  ctc1       $a1, $31
    /* 1B85C 8001AC5C 00000000 */  nop
    /* 1B860 8001AC60 46004224 */  cvt.w.s    $ft2, $ft2
    /* 1B864 8001AC64 4445F800 */  cfc1       $a1, $31
    /* 1B868 8001AC68 00000000 */  nop
    /* 1B86C 8001AC6C 30A10004 */  andi       $at, $a1, 0x4
    /* 1B870 8001AC70 30A50078 */  andi       $a1, $a1, 0x78
    /* 1B874 8001AC74 14A00005 */  bnez       $a1, .L8001AC8C
    /* 1B878 8001AC78 00000000 */   nop
    /* 1B87C 8001AC7C 44054000 */  mfc1       $a1, $ft2
    /* 1B880 8001AC80 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 1B884 8001AC84 10000007 */  b          .L8001ACA4
    /* 1B888 8001AC88 00A12825 */   or        $a1, $a1, $at
  .L8001AC8C:
    /* 1B88C 8001AC8C 10000005 */  b          .L8001ACA4
    /* 1B890 8001AC90 2405FFFF */   addiu     $a1, $zero, -0x1
  .L8001AC94:
    /* 1B894 8001AC94 44054000 */  mfc1       $a1, $ft2
    /* 1B898 8001AC98 00000000 */  nop
    /* 1B89C 8001AC9C 04A0FFFB */  bltz       $a1, .L8001AC8C
    /* 1B8A0 8001ACA0 00000000 */   nop
  .L8001ACA4:
    /* 1B8A4 8001ACA4 44CFF800 */  ctc1       $t7, $31
    /* 1B8A8 8001ACA8 2CA10084 */  sltiu      $at, $a1, 0x84
    /* 1B8AC 8001ACAC 10200003 */  beqz       $at, .L8001ACBC
    /* 1B8B0 8001ACB0 00000000 */   nop
    /* 1B8B4 8001ACB4 10000020 */  b          .L8001AD38
    /* 1B8B8 8001ACB8 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001ACBC:
    /* 1B8BC 8001ACBC 24010042 */  addiu      $at, $zero, 0x42
    /* 1B8C0 8001ACC0 00A1001B */  divu       $zero, $a1, $at
    /* 1B8C4 8001ACC4 00003012 */  mflo       $a2
    /* 1B8C8 8001ACC8 30D800FF */  andi       $t8, $a2, 0xFF
    /* 1B8CC 8001ACCC 03003025 */  or         $a2, $t8, $zero
    /* 1B8D0 8001ACD0 28C10011 */  slti       $at, $a2, 0x11
    /* 1B8D4 8001ACD4 14200002 */  bnez       $at, .L8001ACE0
    /* 1B8D8 8001ACD8 00000000 */   nop
    /* 1B8DC 8001ACDC 24060010 */  addiu      $a2, $zero, 0x10
  .L8001ACE0:
    /* 1B8E0 8001ACE0 24B9FFFF */  addiu      $t9, $a1, -0x1
    /* 1B8E4 8001ACE4 3C08A450 */  lui        $t0, %hi(D_A4500010)
    /* 1B8E8 8001ACE8 AD190010 */  sw         $t9, %lo(D_A4500010)($t0)
    /* 1B8EC 8001ACEC 24C9FFFF */  addiu      $t1, $a2, -0x1
    /* 1B8F0 8001ACF0 3C0AA450 */  lui        $t2, %hi(D_A4500014)
    /* 1B8F4 8001ACF4 AD490014 */  sw         $t1, %lo(D_A4500014)($t2)
    /* 1B8F8 8001ACF8 240B0001 */  addiu      $t3, $zero, 0x1
    /* 1B8FC 8001ACFC 3C0CA450 */  lui        $t4, %hi(D_A4500008)
    /* 1B900 8001AD00 AD8B0008 */  sw         $t3, %lo(D_A4500008)($t4)
    /* 1B904 8001AD04 3C0D8003 */  lui        $t5, %hi(D_80035618)
    /* 1B908 8001AD08 8DAD5618 */  lw         $t5, %lo(D_80035618)($t5)
    /* 1B90C 8001AD0C 01A5001A */  div        $zero, $t5, $a1
    /* 1B910 8001AD10 00001012 */  mflo       $v0
    /* 1B914 8001AD14 14A00002 */  bnez       $a1, .L8001AD20
    /* 1B918 8001AD18 00000000 */   nop
    /* 1B91C 8001AD1C 0007000D */  break      7
  .L8001AD20:
    /* 1B920 8001AD20 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1B924 8001AD24 14A10004 */  bne        $a1, $at, .L8001AD38
    /* 1B928 8001AD28 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 1B92C 8001AD2C 15A10002 */  bne        $t5, $at, .L8001AD38
    /* 1B930 8001AD30 00000000 */   nop
    /* 1B934 8001AD34 0006000D */  break      6
  .L8001AD38:
    /* 1B938 8001AD38 03E00008 */  jr         $ra
    /* 1B93C 8001AD3C 27BD0010 */   addiu     $sp, $sp, 0x10

glabel func_8001AD40
    /* 1B940 8001AD40 8C820000 */  lw         $v0, 0x0($a0)
    /* 1B944 8001AD44 50400004 */  beql       $v0, $zero, .L8001AD58
    /* 1B948 8001AD48 8C820004 */   lw        $v0, 0x4($a0)
    /* 1B94C 8001AD4C 8C8E0004 */  lw         $t6, 0x4($a0)
    /* 1B950 8001AD50 AC4E0004 */  sw         $t6, 0x4($v0)
    /* 1B954 8001AD54 8C820004 */  lw         $v0, 0x4($a0)
  .L8001AD58:
    /* 1B958 8001AD58 10400003 */  beqz       $v0, .L8001AD68
    /* 1B95C 8001AD5C 00000000 */   nop
    /* 1B960 8001AD60 8C8F0000 */  lw         $t7, 0x0($a0)
    /* 1B964 8001AD64 AC4F0000 */  sw         $t7, 0x0($v0)
  .L8001AD68:
    /* 1B968 8001AD68 03E00008 */  jr         $ra
    /* 1B96C 8001AD6C 00000000 */   nop

glabel func_8001AD70
    /* 1B970 8001AD70 8CAE0000 */  lw         $t6, 0x0($a1)
    /* 1B974 8001AD74 AC850004 */  sw         $a1, 0x4($a0)
    /* 1B978 8001AD78 AC8E0000 */  sw         $t6, 0x0($a0)
    /* 1B97C 8001AD7C 8CA20000 */  lw         $v0, 0x0($a1)
    /* 1B980 8001AD80 10400002 */  beqz       $v0, .L8001AD8C
    /* 1B984 8001AD84 00000000 */   nop
    /* 1B988 8001AD88 AC440004 */  sw         $a0, 0x4($v0)
  .L8001AD8C:
    /* 1B98C 8001AD8C 03E00008 */  jr         $ra
    /* 1B990 8001AD90 ACA40000 */   sw        $a0, 0x0($a1)

glabel func_8001AD94
    /* 1B994 8001AD94 3C0E8003 */  lui        $t6, %hi(D_80034DD0)
    /* 1B998 8001AD98 8DCE4DD0 */  lw         $t6, %lo(D_80034DD0)($t6)
    /* 1B99C 8001AD9C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1B9A0 8001ADA0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1B9A4 8001ADA4 51C00006 */  beql       $t6, $zero, .L8001ADC0
    /* 1B9A8 8001ADA8 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 1B9AC 8001ADAC 0C008C14 */  jal        func_80023050
    /* 1B9B0 8001ADB0 00000000 */   nop
    /* 1B9B4 8001ADB4 3C018003 */  lui        $at, %hi(D_80034DD0)
    /* 1B9B8 8001ADB8 AC204DD0 */  sw         $zero, %lo(D_80034DD0)($at)
    /* 1B9BC 8001ADBC 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8001ADC0:
    /* 1B9C0 8001ADC0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1B9C4 8001ADC4 03E00008 */  jr         $ra
    /* 1B9C8 8001ADC8 00000000 */   nop

glabel func_8001ADCC
    /* 1B9CC 8001ADCC 3C028003 */  lui        $v0, %hi(D_80034DD0)
    /* 1B9D0 8001ADD0 24424DD0 */  addiu      $v0, $v0, %lo(D_80034DD0)
    /* 1B9D4 8001ADD4 8C4E0000 */  lw         $t6, 0x0($v0)
    /* 1B9D8 8001ADD8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1B9DC 8001ADDC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1B9E0 8001ADE0 55C00004 */  bnel       $t6, $zero, .L8001ADF4
    /* 1B9E4 8001ADE4 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 1B9E8 8001ADE8 0C007034 */  jal        func_8001C0D0
    /* 1B9EC 8001ADEC AC440000 */   sw        $a0, 0x0($v0)
    /* 1B9F0 8001ADF0 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8001ADF4:
    /* 1B9F4 8001ADF4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1B9F8 8001ADF8 03E00008 */  jr         $ra
    /* 1B9FC 8001ADFC 00000000 */   nop

glabel func_8001AE00
    /* 1BA00 8001AE00 8FAE0010 */  lw         $t6, 0x10($sp)
    /* 1BA04 8001AE04 AFA40000 */  sw         $a0, 0x0($sp)
    /* 1BA08 8001AE08 AFA50004 */  sw         $a1, 0x4($sp)
    /* 1BA0C 8001AE0C 00EE0019 */  multu      $a3, $t6
    /* 1BA10 8001AE10 8CD90008 */  lw         $t9, 0x8($a2)
    /* 1BA14 8001AE14 8CD80000 */  lw         $t8, 0x0($a2)
    /* 1BA18 8001AE18 8CC40004 */  lw         $a0, 0x4($a2)
    /* 1BA1C 8001AE1C 2401FFF0 */  addiu      $at, $zero, -0x10
    /* 1BA20 8001AE20 03194021 */  addu       $t0, $t8, $t9
    /* 1BA24 8001AE24 00001825 */  or         $v1, $zero, $zero
    /* 1BA28 8001AE28 00001012 */  mflo       $v0
    /* 1BA2C 8001AE2C 2442000F */  addiu      $v0, $v0, 0xF
    /* 1BA30 8001AE30 00417824 */  and        $t7, $v0, $at
    /* 1BA34 8001AE34 008F4821 */  addu       $t1, $a0, $t7
    /* 1BA38 8001AE38 0109082B */  sltu       $at, $t0, $t1
    /* 1BA3C 8001AE3C 14200003 */  bnez       $at, .L8001AE4C
    /* 1BA40 8001AE40 008F5021 */   addu      $t2, $a0, $t7
    /* 1BA44 8001AE44 00801825 */  or         $v1, $a0, $zero
    /* 1BA48 8001AE48 ACCA0004 */  sw         $t2, 0x4($a2)
  .L8001AE4C:
    /* 1BA4C 8001AE4C 03E00008 */  jr         $ra
    /* 1BA50 8001AE50 00601025 */   or        $v0, $v1, $zero
    /* 1BA54 8001AE54 00000000 */  nop
    /* 1BA58 8001AE58 00000000 */  nop
    /* 1BA5C 8001AE5C 00000000 */  nop
