.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001BA70
    /* 1C670 8001BA70 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 1C674 8001BA74 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1C678 8001BA78 AFA40028 */  sw         $a0, 0x28($sp)
    /* 1C67C 8001BA7C AFA5002C */  sw         $a1, 0x2C($sp)
    /* 1C680 8001BA80 AFA60030 */  sw         $a2, 0x30($sp)
    /* 1C684 8001BA84 AFB10018 */  sw         $s1, 0x18($sp)
    /* 1C688 8001BA88 0C008E6C */  jal        func_800239B0
    /* 1C68C 8001BA8C AFB00014 */   sw        $s0, 0x14($sp)
    /* 1C690 8001BA90 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 1C694 8001BA94 00408025 */  or         $s0, $v0, $zero
    /* 1C698 8001BA98 8DCF0008 */  lw         $t7, 0x8($t6)
    /* 1C69C 8001BA9C 15E00012 */  bnez       $t7, .L8001BAE8
    /* 1C6A0 8001BAA0 00000000 */   nop
  .L8001BAA4:
    /* 1C6A4 8001BAA4 8FB80030 */  lw         $t8, 0x30($sp)
    /* 1C6A8 8001BAA8 17000005 */  bnez       $t8, .L8001BAC0
    /* 1C6AC 8001BAAC 00000000 */   nop
    /* 1C6B0 8001BAB0 0C008E74 */  jal        func_800239D0
    /* 1C6B4 8001BAB4 02002025 */   or        $a0, $s0, $zero
    /* 1C6B8 8001BAB8 10000036 */  b          .L8001BB94
    /* 1C6BC 8001BABC 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001BAC0:
    /* 1C6C0 8001BAC0 3C088003 */  lui        $t0, %hi(D_800363B0)
    /* 1C6C4 8001BAC4 8D0863B0 */  lw         $t0, %lo(D_800363B0)($t0)
    /* 1C6C8 8001BAC8 24190008 */  addiu      $t9, $zero, 0x8
    /* 1C6CC 8001BACC A5190010 */  sh         $t9, 0x10($t0)
    /* 1C6D0 8001BAD0 0C008DB3 */  jal        func_800236CC
    /* 1C6D4 8001BAD4 8FA40028 */   lw        $a0, 0x28($sp)
    /* 1C6D8 8001BAD8 8FA90028 */  lw         $t1, 0x28($sp)
    /* 1C6DC 8001BADC 8D2A0008 */  lw         $t2, 0x8($t1)
    /* 1C6E0 8001BAE0 1140FFF0 */  beqz       $t2, .L8001BAA4
    /* 1C6E4 8001BAE4 00000000 */   nop
  .L8001BAE8:
    /* 1C6E8 8001BAE8 8FAB002C */  lw         $t3, 0x2C($sp)
    /* 1C6EC 8001BAEC 11600008 */  beqz       $t3, .L8001BB10
    /* 1C6F0 8001BAF0 00000000 */   nop
    /* 1C6F4 8001BAF4 8FAC0028 */  lw         $t4, 0x28($sp)
    /* 1C6F8 8001BAF8 8D8E000C */  lw         $t6, 0xC($t4)
    /* 1C6FC 8001BAFC 8D8D0014 */  lw         $t5, 0x14($t4)
    /* 1C700 8001BB00 000E7880 */  sll        $t7, $t6, 2
    /* 1C704 8001BB04 01AFC021 */  addu       $t8, $t5, $t7
    /* 1C708 8001BB08 8F190000 */  lw         $t9, 0x0($t8)
    /* 1C70C 8001BB0C AD790000 */  sw         $t9, 0x0($t3)
  .L8001BB10:
    /* 1C710 8001BB10 8FA80028 */  lw         $t0, 0x28($sp)
    /* 1C714 8001BB14 8D09000C */  lw         $t1, 0xC($t0)
    /* 1C718 8001BB18 8D0C0010 */  lw         $t4, 0x10($t0)
    /* 1C71C 8001BB1C 252A0001 */  addiu      $t2, $t1, 0x1
    /* 1C720 8001BB20 014C001A */  div        $zero, $t2, $t4
    /* 1C724 8001BB24 00007010 */  mfhi       $t6
    /* 1C728 8001BB28 AD0E000C */  sw         $t6, 0xC($t0)
    /* 1C72C 8001BB2C 8FAD0028 */  lw         $t5, 0x28($sp)
    /* 1C730 8001BB30 15800002 */  bnez       $t4, .L8001BB3C
    /* 1C734 8001BB34 00000000 */   nop
    /* 1C738 8001BB38 0007000D */  break      7
  .L8001BB3C:
    /* 1C73C 8001BB3C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1C740 8001BB40 15810004 */  bne        $t4, $at, .L8001BB54
    /* 1C744 8001BB44 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 1C748 8001BB48 15410002 */  bne        $t2, $at, .L8001BB54
    /* 1C74C 8001BB4C 00000000 */   nop
    /* 1C750 8001BB50 0006000D */  break      6
  .L8001BB54:
    /* 1C754 8001BB54 8DAF0008 */  lw         $t7, 0x8($t5)
    /* 1C758 8001BB58 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 1C75C 8001BB5C ADB80008 */  sw         $t8, 0x8($t5)
    /* 1C760 8001BB60 8FB90028 */  lw         $t9, 0x28($sp)
    /* 1C764 8001BB64 8F2B0004 */  lw         $t3, 0x4($t9)
    /* 1C768 8001BB68 8D690000 */  lw         $t1, 0x0($t3)
    /* 1C76C 8001BB6C 11200006 */  beqz       $t1, .L8001BB88
    /* 1C770 8001BB70 00000000 */   nop
    /* 1C774 8001BB74 0C008E05 */  jal        func_80023814
    /* 1C778 8001BB78 27240004 */   addiu     $a0, $t9, 0x4
    /* 1C77C 8001BB7C 00408825 */  or         $s1, $v0, $zero
    /* 1C780 8001BB80 0C006BF8 */  jal        func_8001AFE0
    /* 1C784 8001BB84 02202025 */   or        $a0, $s1, $zero
  .L8001BB88:
    /* 1C788 8001BB88 0C008E74 */  jal        func_800239D0
    /* 1C78C 8001BB8C 02002025 */   or        $a0, $s0, $zero
    /* 1C790 8001BB90 00001025 */  or         $v0, $zero, $zero
  .L8001BB94:
    /* 1C794 8001BB94 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 1C798 8001BB98 8FB00014 */  lw         $s0, 0x14($sp)
    /* 1C79C 8001BB9C 8FB10018 */  lw         $s1, 0x18($sp)
    /* 1C7A0 8001BBA0 03E00008 */  jr         $ra
    /* 1C7A4 8001BBA4 27BD0028 */   addiu     $sp, $sp, 0x28
    /* 1C7A8 8001BBA8 00000000 */  nop
    /* 1C7AC 8001BBAC 00000000 */  nop
