.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001BCE0
    /* 1C8E0 8001BCE0 3C0EA450 */  lui        $t6, %hi(D_A4500004)
    /* 1C8E4 8001BCE4 03E00008 */  jr         $ra
    /* 1C8E8 8001BCE8 8DC20004 */   lw        $v0, %lo(D_A4500004)($t6)
    /* 1C8EC 8001BCEC 00000000 */  nop
