.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001BCF0
    /* 1C8F0 8001BCF0 03E00008 */  jr         $ra
    /* 1C8F4 8001BCF4 00000000 */   nop

glabel func_8001BCF8
    /* 1C8F8 8001BCF8 8C8E0044 */  lw         $t6, 0x44($a0)
    /* 1C8FC 8001BCFC 44852000 */  mtc1       $a1, $ft0
    /* 1C900 8001BD00 3C018004 */  lui        $at, %hi(D_80039860)
    /* 1C904 8001BD04 448E4000 */  mtc1       $t6, $ft2
    /* 1C908 8001BD08 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 1C90C 8001BD0C D4249860 */  ldc1       $ft0, %lo(D_80039860)($at)
    /* 1C910 8001BD10 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
    /* 1C914 8001BD14 44813800 */  mtc1       $at, $ft1f
    /* 1C918 8001BD18 2401FFF0 */  addiu      $at, $zero, -0x10
    /* 1C91C 8001BD1C 468042A0 */  cvt.s.w    $ft3, $ft2
    /* 1C920 8001BD20 460A3402 */  mul.s      $ft4, $ft1, $ft3
    /* 1C924 8001BD24 44803000 */  mtc1       $zero, $ft1
    /* 1C928 8001BD28 460084A1 */  cvt.d.s    $ft5, $ft4
    /* 1C92C 8001BD2C 46249203 */  div.d      $ft2, $ft5, $ft0
    /* 1C930 8001BD30 46264280 */  add.d      $ft3, $ft2, $ft1
    /* 1C934 8001BD34 46205020 */  cvt.s.d    $fv0, $ft3
    /* 1C938 8001BD38 4600040D */  trunc.w.s  $ft4, $fv0
    /* 1C93C 8001BD3C 44028000 */  mfc1       $v0, $ft4
    /* 1C940 8001BD40 00000000 */  nop
    /* 1C944 8001BD44 0041C024 */  and        $t8, $v0, $at
    /* 1C948 8001BD48 03E00008 */  jr         $ra
    /* 1C94C 8001BD4C 03001025 */   or        $v0, $t8, $zero

glabel func_8001BD50
    /* 1C950 8001BD50 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1C954 8001BD54 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1C958 8001BD58 AFA40018 */  sw         $a0, 0x18($sp)
    /* 1C95C 8001BD5C AFA5001C */  sw         $a1, 0x1C($sp)
    /* 1C960 8001BD60 0C006B50 */  jal        func_8001AD40
    /* 1C964 8001BD64 00A02025 */   or        $a0, $a1, $zero
    /* 1C968 8001BD68 8FA50018 */  lw         $a1, 0x18($sp)
    /* 1C96C 8001BD6C 8FA4001C */  lw         $a0, 0x1C($sp)
    /* 1C970 8001BD70 0C006B5C */  jal        func_8001AD70
    /* 1C974 8001BD74 24A50014 */   addiu     $a1, $a1, 0x14
    /* 1C978 8001BD78 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1C97C 8001BD7C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1C980 8001BD80 03E00008 */  jr         $ra
    /* 1C984 8001BD84 00000000 */   nop

glabel func_8001BD88
    /* 1C988 8001BD88 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 1C98C 8001BD8C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1C990 8001BD90 AFB20020 */  sw         $s2, 0x20($sp)
    /* 1C994 8001BD94 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 1C998 8001BD98 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1C99C 8001BD9C 8C900014 */  lw         $s0, 0x14($a0)
    /* 1C9A0 8001BDA0 00808825 */  or         $s1, $a0, $zero
    /* 1C9A4 8001BDA4 24920004 */  addiu      $s2, $a0, 0x4
    /* 1C9A8 8001BDA8 5200000A */  beql       $s0, $zero, .L8001BDD4
    /* 1C9AC 8001BDAC 8FBF0024 */   lw        $ra, 0x24($sp)
  .L8001BDB0:
    /* 1C9B0 8001BDB0 0C006B50 */  jal        func_8001AD40
    /* 1C9B4 8001BDB4 02002025 */   or        $a0, $s0, $zero
    /* 1C9B8 8001BDB8 02002025 */  or         $a0, $s0, $zero
    /* 1C9BC 8001BDBC 0C006B5C */  jal        func_8001AD70
    /* 1C9C0 8001BDC0 02402825 */   or        $a1, $s2, $zero
    /* 1C9C4 8001BDC4 8E300014 */  lw         $s0, 0x14($s1)
    /* 1C9C8 8001BDC8 1600FFF9 */  bnez       $s0, .L8001BDB0
    /* 1C9CC 8001BDCC 00000000 */   nop
    /* 1C9D0 8001BDD0 8FBF0024 */  lw         $ra, 0x24($sp)
  .L8001BDD4:
    /* 1C9D4 8001BDD4 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1C9D8 8001BDD8 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 1C9DC 8001BDDC 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1C9E0 8001BDE0 03E00008 */  jr         $ra
    /* 1C9E4 8001BDE4 27BD0028 */   addiu     $sp, $sp, 0x28

glabel func_8001BDE8
    /* 1C9E8 8001BDE8 3C028003 */  lui        $v0, %hi(D_80034DD0)
    /* 1C9EC 8001BDEC 8C424DD0 */  lw         $v0, %lo(D_80034DD0)($v0)
    /* 1C9F0 8001BDF0 8C4E002C */  lw         $t6, 0x2C($v0)
    /* 1C9F4 8001BDF4 AC8E0000 */  sw         $t6, 0x0($a0)
    /* 1C9F8 8001BDF8 03E00008 */  jr         $ra
    /* 1C9FC 8001BDFC AC44002C */   sw        $a0, 0x2C($v0)

glabel func_8001BE00
    /* 1CA00 8001BE00 3C028003 */  lui        $v0, %hi(D_80034DD0)
    /* 1CA04 8001BE04 8C424DD0 */  lw         $v0, %lo(D_80034DD0)($v0)
    /* 1CA08 8001BE08 00001825 */  or         $v1, $zero, $zero
    /* 1CA0C 8001BE0C 8C44002C */  lw         $a0, 0x2C($v0)
    /* 1CA10 8001BE10 10800005 */  beqz       $a0, .L8001BE28
    /* 1CA14 8001BE14 00000000 */   nop
    /* 1CA18 8001BE18 8C8E0000 */  lw         $t6, 0x0($a0)
    /* 1CA1C 8001BE1C 00801825 */  or         $v1, $a0, $zero
    /* 1CA20 8001BE20 AC4E002C */  sw         $t6, 0x2C($v0)
    /* 1CA24 8001BE24 AC800000 */  sw         $zero, 0x0($a0)
  .L8001BE28:
    /* 1CA28 8001BE28 03E00008 */  jr         $ra
    /* 1CA2C 8001BE2C 00601025 */   or        $v0, $v1, $zero

glabel func_8001BE30
    /* 1CA30 8001BE30 03E00008 */  jr         $ra
    /* 1CA34 8001BE34 00000000 */   nop

glabel func_8001BE38
    /* 1CA38 8001BE38 27BDFF48 */  addiu      $sp, $sp, -0xB8
    /* 1CA3C 8001BE3C AFB10030 */  sw         $s1, 0x30($sp)
    /* 1CA40 8001BE40 3C118003 */  lui        $s1, %hi(D_80034DD0)
    /* 1CA44 8001BE44 8E314DD0 */  lw         $s1, %lo(D_80034DD0)($s1)
    /* 1CA48 8001BE48 AFBF004C */  sw         $ra, 0x4C($sp)
    /* 1CA4C 8001BE4C AFB70048 */  sw         $s7, 0x48($sp)
    /* 1CA50 8001BE50 AFB60044 */  sw         $s6, 0x44($sp)
    /* 1CA54 8001BE54 AFB50040 */  sw         $s5, 0x40($sp)
    /* 1CA58 8001BE58 AFB4003C */  sw         $s4, 0x3C($sp)
    /* 1CA5C 8001BE5C AFB30038 */  sw         $s3, 0x38($sp)
    /* 1CA60 8001BE60 AFB20034 */  sw         $s2, 0x34($sp)
    /* 1CA64 8001BE64 AFB0002C */  sw         $s0, 0x2C($sp)
    /* 1CA68 8001BE68 F7B60020 */  sdc1       $fs1, 0x20($sp)
    /* 1CA6C 8001BE6C F7B40018 */  sdc1       $fs0, 0x18($sp)
    /* 1CA70 8001BE70 AFA400B8 */  sw         $a0, 0xB8($sp)
    /* 1CA74 8001BE74 AFA500BC */  sw         $a1, 0xBC($sp)
    /* 1CA78 8001BE78 A7A000AA */  sh         $zero, 0xAA($sp)
    /* 1CA7C 8001BE7C 8E2F0000 */  lw         $t7, 0x0($s1)
    /* 1CA80 8001BE80 00E09825 */  or         $s3, $a3, $zero
    /* 1CA84 8001BE84 0080A025 */  or         $s4, $a0, $zero
    /* 1CA88 8001BE88 15E00004 */  bnez       $t7, .L8001BE9C
    /* 1CA8C 8001BE8C 00C0A825 */   or        $s5, $a2, $zero
    /* 1CA90 8001BE90 ACA00000 */  sw         $zero, 0x0($a1)
    /* 1CA94 8001BE94 10000081 */  b          .L8001C09C
    /* 1CA98 8001BE98 00801025 */   or        $v0, $a0, $zero
  .L8001BE9C:
    /* 1CA9C 8001BE9C AFA000B4 */  sw         $zero, 0xB4($sp)
    /* 1CAA0 8001BEA0 8E220000 */  lw         $v0, 0x0($s1)
    /* 1CAA4 8001BEA4 3C037FFF */  lui        $v1, (0x7FFFFFFF >> 16)
    /* 1CAA8 8001BEA8 3463FFFF */  ori        $v1, $v1, (0x7FFFFFFF & 0xFFFF)
    /* 1CAAC 8001BEAC 1040000E */  beqz       $v0, .L8001BEE8
    /* 1CAB0 8001BEB0 2412FFF0 */   addiu     $s2, $zero, -0x10
    /* 1CAB4 8001BEB4 8E240020 */  lw         $a0, 0x20($s1)
    /* 1CAB8 8001BEB8 8C590010 */  lw         $t9, 0x10($v0)
  .L8001BEBC:
    /* 1CABC 8001BEBC 03244023 */  subu       $t0, $t9, $a0
    /* 1CAC0 8001BEC0 0103082A */  slt        $at, $t0, $v1
    /* 1CAC4 8001BEC4 50200006 */  beql       $at, $zero, .L8001BEE0
    /* 1CAC8 8001BEC8 8C420000 */   lw        $v0, 0x0($v0)
    /* 1CACC 8001BECC AFA200B4 */  sw         $v0, 0xB4($sp)
    /* 1CAD0 8001BED0 8C490010 */  lw         $t1, 0x10($v0)
    /* 1CAD4 8001BED4 8E240020 */  lw         $a0, 0x20($s1)
    /* 1CAD8 8001BED8 01241823 */  subu       $v1, $t1, $a0
    /* 1CADC 8001BEDC 8C420000 */  lw         $v0, 0x0($v0)
  .L8001BEE0:
    /* 1CAE0 8001BEE0 5440FFF6 */  bnel       $v0, $zero, .L8001BEBC
    /* 1CAE4 8001BEE4 8C590010 */   lw        $t9, 0x10($v0)
  .L8001BEE8:
    /* 1CAE8 8001BEE8 8FAA00B4 */  lw         $t2, 0xB4($sp)
    /* 1CAEC 8001BEEC 8E240020 */  lw         $a0, 0x20($s1)
    /* 1CAF0 8001BEF0 8D420010 */  lw         $v0, 0x10($t2)
    /* 1CAF4 8001BEF4 00445823 */  subu       $t3, $v0, $a0
    /* 1CAF8 8001BEF8 0173082A */  slt        $at, $t3, $s3
    /* 1CAFC 8001BEFC 10200038 */  beqz       $at, .L8001BFE0
    /* 1CB00 8001BF00 AE22001C */   sw        $v0, 0x1C($s1)
    /* 1CB04 8001BF04 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
    /* 1CB08 8001BF08 4481B800 */  mtc1       $at, $fs1f
    /* 1CB0C 8001BF0C 3C018004 */  lui        $at, %hi(D_80039868)
    /* 1CB10 8001BF10 4480B000 */  mtc1       $zero, $fs1
    /* 1CB14 8001BF14 D4349868 */  ldc1       $fs0, %lo(D_80039868)($at)
  .L8001BF18:
    /* 1CB18 8001BF18 8E2C001C */  lw         $t4, 0x1C($s1)
    /* 1CB1C 8001BF1C 3C107FFF */  lui        $s0, (0x7FFFFFFF >> 16)
    /* 1CB20 8001BF20 3610FFFF */  ori        $s0, $s0, (0x7FFFFFFF & 0xFFFF)
    /* 1CB24 8001BF24 01926824 */  and        $t5, $t4, $s2
    /* 1CB28 8001BF28 AE2D001C */  sw         $t5, 0x1C($s1)
    /* 1CB2C 8001BF2C 8FA400B4 */  lw         $a0, 0xB4($sp)
    /* 1CB30 8001BF30 8C990008 */  lw         $t9, 0x8($a0)
    /* 1CB34 8001BF34 0320F809 */  jalr       $t9
    /* 1CB38 8001BF38 00000000 */   nop
    /* 1CB3C 8001BF3C 8E380044 */  lw         $t8, 0x44($s1)
    /* 1CB40 8001BF40 44822000 */  mtc1       $v0, $ft0
    /* 1CB44 8001BF44 8FA800B4 */  lw         $t0, 0xB4($sp)
    /* 1CB48 8001BF48 44984000 */  mtc1       $t8, $ft2
    /* 1CB4C 8001BF4C 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 1CB50 8001BF50 8D090010 */  lw         $t1, 0x10($t0)
    /* 1CB54 8001BF54 468042A0 */  cvt.s.w    $ft3, $ft2
    /* 1CB58 8001BF58 460A3402 */  mul.s      $ft4, $ft1, $ft3
    /* 1CB5C 8001BF5C 460084A1 */  cvt.d.s    $ft5, $ft4
    /* 1CB60 8001BF60 46349103 */  div.d      $ft0, $ft5, $fs0
    /* 1CB64 8001BF64 46362200 */  add.d      $ft2, $ft0, $fs1
    /* 1CB68 8001BF68 46204020 */  cvt.s.d    $fv0, $ft2
    /* 1CB6C 8001BF6C 4600018D */  trunc.w.s  $ft1, $fv0
    /* 1CB70 8001BF70 44023000 */  mfc1       $v0, $ft1
    /* 1CB74 8001BF74 00000000 */  nop
    /* 1CB78 8001BF78 01225021 */  addu       $t2, $t1, $v0
    /* 1CB7C 8001BF7C AD0A0010 */  sw         $t2, 0x10($t0)
    /* 1CB80 8001BF80 AFA000B4 */  sw         $zero, 0xB4($sp)
    /* 1CB84 8001BF84 8E230000 */  lw         $v1, 0x0($s1)
    /* 1CB88 8001BF88 5060000F */  beql       $v1, $zero, .L8001BFC8
    /* 1CB8C 8001BF8C 8FAF00B4 */   lw        $t7, 0xB4($sp)
    /* 1CB90 8001BF90 8E240020 */  lw         $a0, 0x20($s1)
    /* 1CB94 8001BF94 8C6B0010 */  lw         $t3, 0x10($v1)
  .L8001BF98:
    /* 1CB98 8001BF98 01646023 */  subu       $t4, $t3, $a0
    /* 1CB9C 8001BF9C 0190082A */  slt        $at, $t4, $s0
    /* 1CBA0 8001BFA0 50200006 */  beql       $at, $zero, .L8001BFBC
    /* 1CBA4 8001BFA4 8C630000 */   lw        $v1, 0x0($v1)
    /* 1CBA8 8001BFA8 AFA300B4 */  sw         $v1, 0xB4($sp)
    /* 1CBAC 8001BFAC 8C6D0010 */  lw         $t5, 0x10($v1)
    /* 1CBB0 8001BFB0 8E240020 */  lw         $a0, 0x20($s1)
    /* 1CBB4 8001BFB4 01A48023 */  subu       $s0, $t5, $a0
    /* 1CBB8 8001BFB8 8C630000 */  lw         $v1, 0x0($v1)
  .L8001BFBC:
    /* 1CBBC 8001BFBC 5460FFF6 */  bnel       $v1, $zero, .L8001BF98
    /* 1CBC0 8001BFC0 8C6B0010 */   lw        $t3, 0x10($v1)
    /* 1CBC4 8001BFC4 8FAF00B4 */  lw         $t7, 0xB4($sp)
  .L8001BFC8:
    /* 1CBC8 8001BFC8 8E240020 */  lw         $a0, 0x20($s1)
    /* 1CBCC 8001BFCC 8DE20010 */  lw         $v0, 0x10($t7)
    /* 1CBD0 8001BFD0 0044C823 */  subu       $t9, $v0, $a0
    /* 1CBD4 8001BFD4 0333082A */  slt        $at, $t9, $s3
    /* 1CBD8 8001BFD8 1420FFCF */  bnez       $at, .L8001BF18
    /* 1CBDC 8001BFDC AE22001C */   sw        $v0, 0x1C($s1)
  .L8001BFE0:
    /* 1CBE0 8001BFE0 8E38001C */  lw         $t8, 0x1C($s1)
    /* 1CBE4 8001BFE4 2412FFF0 */  addiu      $s2, $zero, -0x10
    /* 1CBE8 8001BFE8 27B700AA */  addiu      $s7, $sp, 0xAA
    /* 1CBEC 8001BFEC 03127024 */  and        $t6, $t8, $s2
    /* 1CBF0 8001BFF0 1A600022 */  blez       $s3, .L8001C07C
    /* 1CBF4 8001BFF4 AE2E001C */   sw        $t6, 0x1C($s1)
    /* 1CBF8 8001BFF8 3C160700 */  lui        $s6, (0x7000000 >> 16)
  .L8001BFFC:
    /* 1CBFC 8001BFFC 8E220048 */  lw         $v0, 0x48($s1)
    /* 1CC00 8001C000 02608025 */  or         $s0, $s3, $zero
    /* 1CC04 8001C004 0053082A */  slt        $at, $v0, $s3
    /* 1CC08 8001C008 10200003 */  beqz       $at, .L8001C018
    /* 1CC0C 8001C00C 00000000 */   nop
    /* 1CC10 8001C010 10000001 */  b          .L8001C018
    /* 1CC14 8001C014 00408025 */   or        $s0, $v0, $zero
  .L8001C018:
    /* 1CC18 8001C018 AE960000 */  sw         $s6, 0x0($s4)
    /* 1CC1C 8001C01C AE800004 */  sw         $zero, 0x4($s4)
    /* 1CC20 8001C020 8E320038 */  lw         $s2, 0x38($s1)
    /* 1CC24 8001C024 24050006 */  addiu      $a1, $zero, 0x6
    /* 1CC28 8001C028 02A03025 */  or         $a2, $s5, $zero
    /* 1CC2C 8001C02C 8E590008 */  lw         $t9, 0x8($s2)
    /* 1CC30 8001C030 02402025 */  or         $a0, $s2, $zero
    /* 1CC34 8001C034 0320F809 */  jalr       $t9
    /* 1CC38 8001C038 00000000 */   nop
    /* 1CC3C 8001C03C 8E270020 */  lw         $a3, 0x20($s1)
    /* 1CC40 8001C040 26890008 */  addiu      $t1, $s4, 0x8
    /* 1CC44 8001C044 AFA90010 */  sw         $t1, 0x10($sp)
    /* 1CC48 8001C048 8E590004 */  lw         $t9, 0x4($s2)
    /* 1CC4C 8001C04C 02402025 */  or         $a0, $s2, $zero
    /* 1CC50 8001C050 02E02825 */  or         $a1, $s7, $zero
    /* 1CC54 8001C054 0320F809 */  jalr       $t9
    /* 1CC58 8001C058 02003025 */   or        $a2, $s0, $zero
    /* 1CC5C 8001C05C 8E2B0020 */  lw         $t3, 0x20($s1)
    /* 1CC60 8001C060 02709823 */  subu       $s3, $s3, $s0
    /* 1CC64 8001C064 00104080 */  sll        $t0, $s0, 2
    /* 1CC68 8001C068 01706021 */  addu       $t4, $t3, $s0
    /* 1CC6C 8001C06C 0040A025 */  or         $s4, $v0, $zero
    /* 1CC70 8001C070 02A8A821 */  addu       $s5, $s5, $t0
    /* 1CC74 8001C074 1E60FFE1 */  bgtz       $s3, .L8001BFFC
    /* 1CC78 8001C078 AE2C0020 */   sw        $t4, 0x20($s1)
  .L8001C07C:
    /* 1CC7C 8001C07C 8FAD00B8 */  lw         $t5, 0xB8($sp)
    /* 1CC80 8001C080 8FAE00BC */  lw         $t6, 0xBC($sp)
    /* 1CC84 8001C084 02202025 */  or         $a0, $s1, $zero
    /* 1CC88 8001C088 028D7823 */  subu       $t7, $s4, $t5
    /* 1CC8C 8001C08C 000FC0C3 */  sra        $t8, $t7, 3
    /* 1CC90 8001C090 0C006F62 */  jal        func_8001BD88
    /* 1CC94 8001C094 ADD80000 */   sw        $t8, 0x0($t6)
    /* 1CC98 8001C098 02801025 */  or         $v0, $s4, $zero
  .L8001C09C:
    /* 1CC9C 8001C09C 8FBF004C */  lw         $ra, 0x4C($sp)
    /* 1CCA0 8001C0A0 D7B40018 */  ldc1       $fs0, 0x18($sp)
    /* 1CCA4 8001C0A4 D7B60020 */  ldc1       $fs1, 0x20($sp)
    /* 1CCA8 8001C0A8 8FB0002C */  lw         $s0, 0x2C($sp)
    /* 1CCAC 8001C0AC 8FB10030 */  lw         $s1, 0x30($sp)
    /* 1CCB0 8001C0B0 8FB20034 */  lw         $s2, 0x34($sp)
    /* 1CCB4 8001C0B4 8FB30038 */  lw         $s3, 0x38($sp)
    /* 1CCB8 8001C0B8 8FB4003C */  lw         $s4, 0x3C($sp)
    /* 1CCBC 8001C0BC 8FB50040 */  lw         $s5, 0x40($sp)
    /* 1CCC0 8001C0C0 8FB60044 */  lw         $s6, 0x44($sp)
    /* 1CCC4 8001C0C4 8FB70048 */  lw         $s7, 0x48($sp)
    /* 1CCC8 8001C0C8 03E00008 */  jr         $ra
    /* 1CCCC 8001C0CC 27BD00B8 */   addiu     $sp, $sp, 0xB8

glabel func_8001C0D0
    /* 1CCD0 8001C0D0 27BDFF88 */  addiu      $sp, $sp, -0x78
    /* 1CCD4 8001C0D4 AFBF0044 */  sw         $ra, 0x44($sp)
    /* 1CCD8 8001C0D8 AFBE0040 */  sw         $fp, 0x40($sp)
    /* 1CCDC 8001C0DC AFB7003C */  sw         $s7, 0x3C($sp)
    /* 1CCE0 8001C0E0 AFB60038 */  sw         $s6, 0x38($sp)
    /* 1CCE4 8001C0E4 AFB50034 */  sw         $s5, 0x34($sp)
    /* 1CCE8 8001C0E8 AFB40030 */  sw         $s4, 0x30($sp)
    /* 1CCEC 8001C0EC AFB3002C */  sw         $s3, 0x2C($sp)
    /* 1CCF0 8001C0F0 AFB20028 */  sw         $s2, 0x28($sp)
    /* 1CCF4 8001C0F4 AFB10024 */  sw         $s1, 0x24($sp)
    /* 1CCF8 8001C0F8 AFB00020 */  sw         $s0, 0x20($sp)
    /* 1CCFC 8001C0FC 8CB70014 */  lw         $s7, 0x14($a1)
    /* 1CD00 8001C100 AC800000 */  sw         $zero, 0x0($a0)
    /* 1CD04 8001C104 8CAE0004 */  lw         $t6, 0x4($a1)
    /* 1CD08 8001C108 AC800020 */  sw         $zero, 0x20($a0)
    /* 1CD0C 8001C10C AC80001C */  sw         $zero, 0x1C($a0)
    /* 1CD10 8001C110 AC8E003C */  sw         $t6, 0x3C($a0)
    /* 1CD14 8001C114 8CAF0018 */  lw         $t7, 0x18($a1)
    /* 1CD18 8001C118 241800A0 */  addiu      $t8, $zero, 0xA0
    /* 1CD1C 8001C11C AC980048 */  sw         $t8, 0x48($a0)
    /* 1CD20 8001C120 AC8F0044 */  sw         $t7, 0x44($a0)
    /* 1CD24 8001C124 8CB90010 */  lw         $t9, 0x10($a1)
    /* 1CD28 8001C128 0080B025 */  or         $s6, $a0, $zero
    /* 1CD2C 8001C12C 00A0F025 */  or         $fp, $a1, $zero
    /* 1CD30 8001C130 2408001C */  addiu      $t0, $zero, 0x1C
    /* 1CD34 8001C134 AC990024 */  sw         $t9, 0x24($a0)
    /* 1CD38 8001C138 AFA80010 */  sw         $t0, 0x10($sp)
    /* 1CD3C 8001C13C 00002025 */  or         $a0, $zero, $zero
    /* 1CD40 8001C140 00002825 */  or         $a1, $zero, $zero
    /* 1CD44 8001C144 24070001 */  addiu      $a3, $zero, 0x1
    /* 1CD48 8001C148 0C006B80 */  jal        func_8001AE00
    /* 1CD4C 8001C14C 02E03025 */   or        $a2, $s7, $zero
    /* 1CD50 8001C150 AFA2005C */  sw         $v0, 0x5C($sp)
    /* 1CD54 8001C154 0C009010 */  jal        func_80024040
    /* 1CD58 8001C158 00402025 */   or        $a0, $v0, $zero
    /* 1CD5C 8001C15C 8FA9005C */  lw         $t1, 0x5C($sp)
    /* 1CD60 8001C160 240A004C */  addiu      $t2, $zero, 0x4C
    /* 1CD64 8001C164 00002025 */  or         $a0, $zero, $zero
    /* 1CD68 8001C168 AEC90038 */  sw         $t1, 0x38($s6)
    /* 1CD6C 8001C16C AFAA0010 */  sw         $t2, 0x10($sp)
    /* 1CD70 8001C170 00002825 */  or         $a1, $zero, $zero
    /* 1CD74 8001C174 02E03025 */  or         $a2, $s7, $zero
    /* 1CD78 8001C178 0C006B80 */  jal        func_8001AE00
    /* 1CD7C 8001C17C 24070001 */   addiu     $a3, $zero, 0x1
    /* 1CD80 8001C180 240B0001 */  addiu      $t3, $zero, 0x1
    /* 1CD84 8001C184 AEC20034 */  sw         $v0, 0x34($s6)
    /* 1CD88 8001C188 AECB0040 */  sw         $t3, 0x40($s6)
    /* 1CD8C 8001C18C 8FC70004 */  lw         $a3, 0x4($fp)
    /* 1CD90 8001C190 240C0004 */  addiu      $t4, $zero, 0x4
    /* 1CD94 8001C194 AFAC0010 */  sw         $t4, 0x10($sp)
    /* 1CD98 8001C198 00002025 */  or         $a0, $zero, $zero
    /* 1CD9C 8001C19C 00002825 */  or         $a1, $zero, $zero
    /* 1CDA0 8001C1A0 0C006B80 */  jal        func_8001AE00
    /* 1CDA4 8001C1A4 02E03025 */   or        $a2, $s7, $zero
    /* 1CDA8 8001C1A8 8EC40034 */  lw         $a0, 0x34($s6)
    /* 1CDAC 8001C1AC 00402825 */  or         $a1, $v0, $zero
    /* 1CDB0 8001C1B0 0C009036 */  jal        func_800240D8
    /* 1CDB4 8001C1B4 8FC60004 */   lw        $a2, 0x4($fp)
    /* 1CDB8 8001C1B8 240D0020 */  addiu      $t5, $zero, 0x20
    /* 1CDBC 8001C1BC AFAD0010 */  sw         $t5, 0x10($sp)
    /* 1CDC0 8001C1C0 00002025 */  or         $a0, $zero, $zero
    /* 1CDC4 8001C1C4 00002825 */  or         $a1, $zero, $zero
    /* 1CDC8 8001C1C8 02E03025 */  or         $a2, $s7, $zero
    /* 1CDCC 8001C1CC 0C006B80 */  jal        func_8001AE00
    /* 1CDD0 8001C1D0 24070001 */   addiu     $a3, $zero, 0x1
    /* 1CDD4 8001C1D4 AEC20030 */  sw         $v0, 0x30($s6)
    /* 1CDD8 8001C1D8 8FC70004 */  lw         $a3, 0x4($fp)
    /* 1CDDC 8001C1DC 240E0004 */  addiu      $t6, $zero, 0x4
    /* 1CDE0 8001C1E0 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 1CDE4 8001C1E4 00002025 */  or         $a0, $zero, $zero
    /* 1CDE8 8001C1E8 00002825 */  or         $a1, $zero, $zero
    /* 1CDEC 8001C1EC 0C006B80 */  jal        func_8001AE00
    /* 1CDF0 8001C1F0 02E03025 */   or        $a2, $s7, $zero
    /* 1CDF4 8001C1F4 8EC40030 */  lw         $a0, 0x30($s6)
    /* 1CDF8 8001C1F8 00402825 */  or         $a1, $v0, $zero
    /* 1CDFC 8001C1FC 0C009021 */  jal        func_80024084
    /* 1CE00 8001C200 8FC60004 */   lw        $a2, 0x4($fp)
    /* 1CE04 8001C204 93CF001C */  lbu        $t7, 0x1C($fp)
    /* 1CE08 8001C208 02C02025 */  or         $a0, $s6, $zero
    /* 1CE0C 8001C20C 03C03025 */  or         $a2, $fp, $zero
    /* 1CE10 8001C210 11E00006 */  beqz       $t7, .L8001C22C
    /* 1CE14 8001C214 24050002 */   addiu     $a1, $zero, 0x2
    /* 1CE18 8001C218 00002825 */  or         $a1, $zero, $zero
    /* 1CE1C 8001C21C 0C0091F8 */  jal        func_800247E0
    /* 1CE20 8001C220 02E03825 */   or        $a3, $s7, $zero
    /* 1CE24 8001C224 10000005 */  b          .L8001C23C
    /* 1CE28 8001C228 AEC00004 */   sw        $zero, 0x4($s6)
  .L8001C22C:
    /* 1CE2C 8001C22C 8EC40030 */  lw         $a0, 0x30($s6)
    /* 1CE30 8001C230 0C009220 */  jal        func_80024880
    /* 1CE34 8001C234 8EC60034 */   lw        $a2, 0x34($s6)
    /* 1CE38 8001C238 AEC00004 */  sw         $zero, 0x4($s6)
  .L8001C23C:
    /* 1CE3C 8001C23C AEC00008 */  sw         $zero, 0x8($s6)
    /* 1CE40 8001C240 AEC00014 */  sw         $zero, 0x14($s6)
    /* 1CE44 8001C244 AEC00018 */  sw         $zero, 0x18($s6)
    /* 1CE48 8001C248 AEC0000C */  sw         $zero, 0xC($s6)
    /* 1CE4C 8001C24C AEC00010 */  sw         $zero, 0x10($s6)
    /* 1CE50 8001C250 8FC70004 */  lw         $a3, 0x4($fp)
    /* 1CE54 8001C254 241800DC */  addiu      $t8, $zero, 0xDC
    /* 1CE58 8001C258 AFB80010 */  sw         $t8, 0x10($sp)
    /* 1CE5C 8001C25C 00002025 */  or         $a0, $zero, $zero
    /* 1CE60 8001C260 00002825 */  or         $a1, $zero, $zero
    /* 1CE64 8001C264 0C006B80 */  jal        func_8001AE00
    /* 1CE68 8001C268 02E03025 */   or        $a2, $s7, $zero
    /* 1CE6C 8001C26C 8FD90004 */  lw         $t9, 0x4($fp)
    /* 1CE70 8001C270 0000A025 */  or         $s4, $zero, $zero
    /* 1CE74 8001C274 00408025 */  or         $s0, $v0, $zero
    /* 1CE78 8001C278 1B20002F */  blez       $t9, .L8001C338
    /* 1CE7C 8001C27C 26C50004 */   addiu     $a1, $s6, 0x4
    /* 1CE80 8001C280 2451008C */  addiu      $s1, $v0, 0x8C
    /* 1CE84 8001C284 24520058 */  addiu      $s2, $v0, 0x58
    /* 1CE88 8001C288 24530010 */  addiu      $s3, $v0, 0x10
    /* 1CE8C 8001C28C AFA50048 */  sw         $a1, 0x48($sp)
  .L8001C290:
    /* 1CE90 8001C290 8FA50048 */  lw         $a1, 0x48($sp)
    /* 1CE94 8001C294 0200A825 */  or         $s5, $s0, $zero
    /* 1CE98 8001C298 0C006B5C */  jal        func_8001AD70
    /* 1CE9C 8001C29C 02002025 */   or        $a0, $s0, $zero
    /* 1CEA0 8001C2A0 AE000008 */  sw         $zero, 0x8($s0)
    /* 1CEA4 8001C2A4 8EC50024 */  lw         $a1, 0x24($s6)
    /* 1CEA8 8001C2A8 02602025 */  or         $a0, $s3, $zero
    /* 1CEAC 8001C2AC 0C00906D */  jal        func_800241B4
    /* 1CEB0 8001C2B0 02E03025 */   or        $a2, $s7, $zero
    /* 1CEB4 8001C2B4 02602025 */  or         $a0, $s3, $zero
    /* 1CEB8 8001C2B8 24050001 */  addiu      $a1, $zero, 0x1
    /* 1CEBC 8001C2BC 0C009274 */  jal        func_800249D0
    /* 1CEC0 8001C2C0 00003025 */   or        $a2, $zero, $zero
    /* 1CEC4 8001C2C4 02402025 */  or         $a0, $s2, $zero
    /* 1CEC8 8001C2C8 0C00904B */  jal        func_8002412C
    /* 1CECC 8001C2CC 02E02825 */   or        $a1, $s7, $zero
    /* 1CED0 8001C2D0 02402025 */  or         $a0, $s2, $zero
    /* 1CED4 8001C2D4 24050001 */  addiu      $a1, $zero, 0x1
    /* 1CED8 8001C2D8 0C009548 */  jal        func_80025520
    /* 1CEDC 8001C2DC 02603025 */   or        $a2, $s3, $zero
    /* 1CEE0 8001C2E0 02202025 */  or         $a0, $s1, $zero
    /* 1CEE4 8001C2E4 0C009097 */  jal        func_8002425C
    /* 1CEE8 8001C2E8 02E02825 */   or        $a1, $s7, $zero
    /* 1CEEC 8001C2EC 02202025 */  or         $a0, $s1, $zero
    /* 1CEF0 8001C2F0 24050001 */  addiu      $a1, $zero, 0x1
    /* 1CEF4 8001C2F4 0C00964D */  jal        func_80025934
    /* 1CEF8 8001C2F8 02403025 */   or        $a2, $s2, $zero
    /* 1CEFC 8001C2FC 8EC40034 */  lw         $a0, 0x34($s6)
    /* 1CF00 8001C300 24050002 */  addiu      $a1, $zero, 0x2
    /* 1CF04 8001C304 0C009920 */  jal        func_80026480
    /* 1CF08 8001C308 02203025 */   or        $a2, $s1, $zero
    /* 1CF0C 8001C30C 26A8008C */  addiu      $t0, $s5, 0x8C
    /* 1CF10 8001C310 AEA8000C */  sw         $t0, 0xC($s5)
    /* 1CF14 8001C314 8FC90004 */  lw         $t1, 0x4($fp)
    /* 1CF18 8001C318 26940001 */  addiu      $s4, $s4, 0x1
    /* 1CF1C 8001C31C 261000DC */  addiu      $s0, $s0, 0xDC
    /* 1CF20 8001C320 0289082A */  slt        $at, $s4, $t1
    /* 1CF24 8001C324 263100DC */  addiu      $s1, $s1, 0xDC
    /* 1CF28 8001C328 265200DC */  addiu      $s2, $s2, 0xDC
    /* 1CF2C 8001C32C 1420FFD8 */  bnez       $at, .L8001C290
    /* 1CF30 8001C330 267300DC */   addiu     $s3, $s3, 0xDC
    /* 1CF34 8001C334 0000A025 */  or         $s4, $zero, $zero
  .L8001C338:
    /* 1CF38 8001C338 8FA4005C */  lw         $a0, 0x5C($sp)
    /* 1CF3C 8001C33C 24050001 */  addiu      $a1, $zero, 0x1
    /* 1CF40 8001C340 0C009964 */  jal        func_80026590
    /* 1CF44 8001C344 8EC60030 */   lw        $a2, 0x30($s6)
    /* 1CF48 8001C348 8FC70008 */  lw         $a3, 0x8($fp)
    /* 1CF4C 8001C34C 240A001C */  addiu      $t2, $zero, 0x1C
    /* 1CF50 8001C350 AFAA0010 */  sw         $t2, 0x10($sp)
    /* 1CF54 8001C354 00002025 */  or         $a0, $zero, $zero
    /* 1CF58 8001C358 00002825 */  or         $a1, $zero, $zero
    /* 1CF5C 8001C35C 0C006B80 */  jal        func_8001AE00
    /* 1CF60 8001C360 02E03025 */   or        $a2, $s7, $zero
    /* 1CF64 8001C364 AEC0002C */  sw         $zero, 0x2C($s6)
    /* 1CF68 8001C368 8FCB0008 */  lw         $t3, 0x8($fp)
    /* 1CF6C 8001C36C 00401825 */  or         $v1, $v0, $zero
    /* 1CF70 8001C370 5960000B */  blezl      $t3, .L8001C3A0
    /* 1CF74 8001C374 AED70028 */   sw        $s7, 0x28($s6)
    /* 1CF78 8001C378 8ECC002C */  lw         $t4, 0x2C($s6)
  .L8001C37C:
    /* 1CF7C 8001C37C 26940001 */  addiu      $s4, $s4, 0x1
    /* 1CF80 8001C380 AC6C0000 */  sw         $t4, 0x0($v1)
    /* 1CF84 8001C384 AEC3002C */  sw         $v1, 0x2C($s6)
    /* 1CF88 8001C388 8FCD0008 */  lw         $t5, 0x8($fp)
    /* 1CF8C 8001C38C 2463001C */  addiu      $v1, $v1, 0x1C
    /* 1CF90 8001C390 028D082A */  slt        $at, $s4, $t5
    /* 1CF94 8001C394 5420FFF9 */  bnel       $at, $zero, .L8001C37C
    /* 1CF98 8001C398 8ECC002C */   lw        $t4, 0x2C($s6)
    /* 1CF9C 8001C39C AED70028 */  sw         $s7, 0x28($s6)
  .L8001C3A0:
    /* 1CFA0 8001C3A0 8FBF0044 */  lw         $ra, 0x44($sp)
    /* 1CFA4 8001C3A4 8FBE0040 */  lw         $fp, 0x40($sp)
    /* 1CFA8 8001C3A8 8FB7003C */  lw         $s7, 0x3C($sp)
    /* 1CFAC 8001C3AC 8FB60038 */  lw         $s6, 0x38($sp)
    /* 1CFB0 8001C3B0 8FB50034 */  lw         $s5, 0x34($sp)
    /* 1CFB4 8001C3B4 8FB40030 */  lw         $s4, 0x30($sp)
    /* 1CFB8 8001C3B8 8FB3002C */  lw         $s3, 0x2C($sp)
    /* 1CFBC 8001C3BC 8FB20028 */  lw         $s2, 0x28($sp)
    /* 1CFC0 8001C3C0 8FB10024 */  lw         $s1, 0x24($sp)
    /* 1CFC4 8001C3C4 8FB00020 */  lw         $s0, 0x20($sp)
    /* 1CFC8 8001C3C8 03E00008 */  jr         $ra
    /* 1CFCC 8001C3CC 27BD0078 */   addiu     $sp, $sp, 0x78

glabel func_8001C3D0
    /* 1CFD0 8001C3D0 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 1CFD4 8001C3D4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1CFD8 8001C3D8 AFA40038 */  sw         $a0, 0x38($sp)
    /* 1CFDC 8001C3DC AFA5003C */  sw         $a1, 0x3C($sp)
    /* 1CFE0 8001C3E0 AFA60040 */  sw         $a2, 0x40($sp)
    /* 1CFE4 8001C3E4 AFB20020 */  sw         $s2, 0x20($sp)
    /* 1CFE8 8001C3E8 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 1CFEC 8001C3EC 0C008E6C */  jal        func_800239B0
    /* 1CFF0 8001C3F0 AFB00018 */   sw        $s0, 0x18($sp)
    /* 1CFF4 8001C3F4 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 1CFF8 8001C3F8 00408025 */  or         $s0, $v0, $zero
    /* 1CFFC 8001C3FC 8DCF0008 */  lw         $t7, 0x8($t6)
    /* 1D000 8001C400 8DD80010 */  lw         $t8, 0x10($t6)
    /* 1D004 8001C404 01F8082A */  slt        $at, $t7, $t8
    /* 1D008 8001C408 14200018 */  bnez       $at, .L8001C46C
    /* 1D00C 8001C40C 00000000 */   nop
  .L8001C410:
    /* 1D010 8001C410 8FB90040 */  lw         $t9, 0x40($sp)
    /* 1D014 8001C414 24010001 */  addiu      $at, $zero, 0x1
    /* 1D018 8001C418 1721000A */  bne        $t9, $at, .L8001C444
    /* 1D01C 8001C41C 00000000 */   nop
    /* 1D020 8001C420 3C098003 */  lui        $t1, %hi(D_800363B0)
    /* 1D024 8001C424 8D2963B0 */  lw         $t1, %lo(D_800363B0)($t1)
    /* 1D028 8001C428 24080008 */  addiu      $t0, $zero, 0x8
    /* 1D02C 8001C42C A5280010 */  sh         $t0, 0x10($t1)
    /* 1D030 8001C430 8FA40038 */  lw         $a0, 0x38($sp)
    /* 1D034 8001C434 0C008DB3 */  jal        func_800236CC
    /* 1D038 8001C438 24840004 */   addiu     $a0, $a0, 0x4
    /* 1D03C 8001C43C 10000005 */  b          .L8001C454
    /* 1D040 8001C440 00000000 */   nop
  .L8001C444:
    /* 1D044 8001C444 0C008E74 */  jal        func_800239D0
    /* 1D048 8001C448 02002025 */   or        $a0, $s0, $zero
    /* 1D04C 8001C44C 1000002D */  b          .L8001C504
    /* 1D050 8001C450 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001C454:
    /* 1D054 8001C454 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 1D058 8001C458 8D4B0008 */  lw         $t3, 0x8($t2)
    /* 1D05C 8001C45C 8D4C0010 */  lw         $t4, 0x10($t2)
    /* 1D060 8001C460 016C082A */  slt        $at, $t3, $t4
    /* 1D064 8001C464 1020FFEA */  beqz       $at, .L8001C410
    /* 1D068 8001C468 00000000 */   nop
  .L8001C46C:
    /* 1D06C 8001C46C 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 1D070 8001C470 8FA8003C */  lw         $t0, 0x3C($sp)
    /* 1D074 8001C474 8DAE000C */  lw         $t6, 0xC($t5)
    /* 1D078 8001C478 8DAF0008 */  lw         $t7, 0x8($t5)
    /* 1D07C 8001C47C 8DB90010 */  lw         $t9, 0x10($t5)
    /* 1D080 8001C480 8DA90014 */  lw         $t1, 0x14($t5)
    /* 1D084 8001C484 01CFC021 */  addu       $t8, $t6, $t7
    /* 1D088 8001C488 0319001A */  div        $zero, $t8, $t9
    /* 1D08C 8001C48C 00008810 */  mfhi       $s1
    /* 1D090 8001C490 00115080 */  sll        $t2, $s1, 2
    /* 1D094 8001C494 012A5821 */  addu       $t3, $t1, $t2
    /* 1D098 8001C498 AD680000 */  sw         $t0, 0x0($t3)
    /* 1D09C 8001C49C 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 1D0A0 8001C4A0 17200002 */  bnez       $t9, .L8001C4AC
    /* 1D0A4 8001C4A4 00000000 */   nop
    /* 1D0A8 8001C4A8 0007000D */  break      7
  .L8001C4AC:
    /* 1D0AC 8001C4AC 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1D0B0 8001C4B0 17210004 */  bne        $t9, $at, .L8001C4C4
    /* 1D0B4 8001C4B4 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 1D0B8 8001C4B8 17010002 */  bne        $t8, $at, .L8001C4C4
    /* 1D0BC 8001C4BC 00000000 */   nop
    /* 1D0C0 8001C4C0 0006000D */  break      6
  .L8001C4C4:
    /* 1D0C4 8001C4C4 8D8E0008 */  lw         $t6, 0x8($t4)
    /* 1D0C8 8001C4C8 25CF0001 */  addiu      $t7, $t6, 0x1
    /* 1D0CC 8001C4CC AD8F0008 */  sw         $t7, 0x8($t4)
    /* 1D0D0 8001C4D0 8FB80038 */  lw         $t8, 0x38($sp)
    /* 1D0D4 8001C4D4 8F190000 */  lw         $t9, 0x0($t8)
    /* 1D0D8 8001C4D8 8F2D0000 */  lw         $t5, 0x0($t9)
    /* 1D0DC 8001C4DC 11A00006 */  beqz       $t5, .L8001C4F8
    /* 1D0E0 8001C4E0 00000000 */   nop
    /* 1D0E4 8001C4E4 0C008E05 */  jal        func_80023814
    /* 1D0E8 8001C4E8 03002025 */   or        $a0, $t8, $zero
    /* 1D0EC 8001C4EC 00409025 */  or         $s2, $v0, $zero
    /* 1D0F0 8001C4F0 0C006BF8 */  jal        func_8001AFE0
    /* 1D0F4 8001C4F4 02402025 */   or        $a0, $s2, $zero
  .L8001C4F8:
    /* 1D0F8 8001C4F8 0C008E74 */  jal        func_800239D0
    /* 1D0FC 8001C4FC 02002025 */   or        $a0, $s0, $zero
    /* 1D100 8001C500 00001025 */  or         $v0, $zero, $zero
  .L8001C504:
    /* 1D104 8001C504 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 1D108 8001C508 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1D10C 8001C50C 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 1D110 8001C510 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1D114 8001C514 03E00008 */  jr         $ra
    /* 1D118 8001C518 27BD0038 */   addiu     $sp, $sp, 0x38
    /* 1D11C 8001C51C 00000000 */  nop
