.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001D0C0
    /* 1DCC0 8001D0C0 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 1DCC4 8001D0C4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1DCC8 8001D0C8 AFA40020 */  sw         $a0, 0x20($sp)
    /* 1DCCC 8001D0CC 0C009AE4 */  jal        func_80026B90
    /* 1DCD0 8001D0D0 AFA0001C */   sw        $zero, 0x1C($sp)
    /* 1DCD4 8001D0D4 8FA40020 */  lw         $a0, 0x20($sp)
    /* 1DCD8 8001D0D8 0C009E5B */  jal        func_8002796C
    /* 1DCDC 8001D0DC 27A50018 */   addiu     $a1, $sp, 0x18
    /* 1DCE0 8001D0E0 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 1DCE4 8001D0E4 8FAE001C */  lw         $t6, 0x1C($sp)
    /* 1DCE8 8001D0E8 15C00008 */  bnez       $t6, .L8001D10C
    /* 1DCEC 8001D0EC 00000000 */   nop
    /* 1DCF0 8001D0F0 97AF0018 */  lhu        $t7, 0x18($sp)
    /* 1DCF4 8001D0F4 31F88000 */  andi       $t8, $t7, 0x8000
    /* 1DCF8 8001D0F8 13000004 */  beqz       $t8, .L8001D10C
    /* 1DCFC 8001D0FC 00000000 */   nop
    /* 1DD00 8001D100 24190001 */  addiu      $t9, $zero, 0x1
    /* 1DD04 8001D104 10000002 */  b          .L8001D110
    /* 1DD08 8001D108 AFB9001C */   sw        $t9, 0x1C($sp)
  .L8001D10C:
    /* 1DD0C 8001D10C AFA0001C */  sw         $zero, 0x1C($sp)
  .L8001D110:
    /* 1DD10 8001D110 0C009AF5 */  jal        func_80026BD4
    /* 1DD14 8001D114 00000000 */   nop
    /* 1DD18 8001D118 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1DD1C 8001D11C 8FA2001C */  lw         $v0, 0x1C($sp)
    /* 1DD20 8001D120 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 1DD24 8001D124 03E00008 */  jr         $ra
    /* 1DD28 8001D128 00000000 */   nop
    /* 1DD2C 8001D12C 00000000 */  nop
