.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001D5A0
    /* 1E1A0 8001D5A0 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 1E1A4 8001D5A4 AFA50044 */  sw         $a1, 0x44($sp)
    /* 1E1A8 8001D5A8 93AE0047 */  lbu        $t6, 0x47($sp)
    /* 1E1AC 8001D5AC AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1E1B0 8001D5B0 AFA40040 */  sw         $a0, 0x40($sp)
    /* 1E1B4 8001D5B4 29C10041 */  slti       $at, $t6, 0x41
    /* 1E1B8 8001D5B8 AFA60048 */  sw         $a2, 0x48($sp)
    /* 1E1BC 8001D5BC AFA7004C */  sw         $a3, 0x4C($sp)
    /* 1E1C0 8001D5C0 14200003 */  bnez       $at, .L8001D5D0
    /* 1E1C4 8001D5C4 AFA0003C */   sw        $zero, 0x3C($sp)
    /* 1E1C8 8001D5C8 10000040 */  b          .L8001D6CC
    /* 1E1CC 8001D5CC 2402FFFF */   addiu     $v0, $zero, -0x1
  .L8001D5D0:
    /* 1E1D0 8001D5D0 8FAF004C */  lw         $t7, 0x4C($sp)
    /* 1E1D4 8001D5D4 19E0003C */  blez       $t7, .L8001D6C8
    /* 1E1D8 8001D5D8 00000000 */   nop
  .L8001D5DC:
    /* 1E1DC 8001D5DC 8FA40040 */  lw         $a0, 0x40($sp)
    /* 1E1E0 8001D5E0 93A50047 */  lbu        $a1, 0x47($sp)
    /* 1E1E4 8001D5E4 0C009EE4 */  jal        func_80027B90
    /* 1E1E8 8001D5E8 8FA60048 */   lw        $a2, 0x48($sp)
    /* 1E1EC 8001D5EC AFA2003C */  sw         $v0, 0x3C($sp)
    /* 1E1F0 8001D5F0 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 1E1F4 8001D5F4 13000003 */  beqz       $t8, .L8001D604
    /* 1E1F8 8001D5F8 00000000 */   nop
    /* 1E1FC 8001D5FC 10000033 */  b          .L8001D6CC
    /* 1E200 8001D600 03001025 */   or        $v0, $t8, $zero
  .L8001D604:
    /* 1E204 8001D604 8FB9004C */  lw         $t9, 0x4C($sp)
    /* 1E208 8001D608 93A90047 */  lbu        $t1, 0x47($sp)
    /* 1E20C 8001D60C 8FAB0048 */  lw         $t3, 0x48($sp)
    /* 1E210 8001D610 3C068003 */  lui        $a2, %hi(D_80035610)
    /* 1E214 8001D614 3C078003 */  lui        $a3, %hi(D_80035614)
    /* 1E218 8001D618 2728FFF8 */  addiu      $t0, $t9, -0x8
    /* 1E21C 8001D61C 252A0001 */  addiu      $t2, $t1, 0x1
    /* 1E220 8001D620 256C0008 */  addiu      $t4, $t3, 0x8
    /* 1E224 8001D624 AFA8004C */  sw         $t0, 0x4C($sp)
    /* 1E228 8001D628 A3AA0047 */  sb         $t2, 0x47($sp)
    /* 1E22C 8001D62C AFAC0048 */  sw         $t4, 0x48($sp)
    /* 1E230 8001D630 8CE75614 */  lw         $a3, %lo(D_80035614)($a3)
    /* 1E234 8001D634 8CC65610 */  lw         $a2, %lo(D_80035610)($a2)
    /* 1E238 8001D638 24040000 */  addiu      $a0, $zero, 0x0
    /* 1E23C 8001D63C 0C0074C2 */  jal        func_8001D308
    /* 1E240 8001D640 24052EE0 */   addiu     $a1, $zero, 0x2EE0
    /* 1E244 8001D644 AFA20028 */  sw         $v0, 0x28($sp)
    /* 1E248 8001D648 AFA3002C */  sw         $v1, 0x2C($sp)
    /* 1E24C 8001D64C 3C07000F */  lui        $a3, (0xF4240 >> 16)
    /* 1E250 8001D650 34E74240 */  ori        $a3, $a3, (0xF4240 & 0xFFFF)
    /* 1E254 8001D654 8FA5002C */  lw         $a1, 0x2C($sp)
    /* 1E258 8001D658 8FA40028 */  lw         $a0, 0x28($sp)
    /* 1E25C 8001D65C 0C007482 */  jal        func_8001D208
    /* 1E260 8001D660 24060000 */   addiu     $a2, $zero, 0x0
    /* 1E264 8001D664 3C0D8007 */  lui        $t5, %hi(D_8006CA28)
    /* 1E268 8001D668 3C188007 */  lui        $t8, %hi(D_8006CA40)
    /* 1E26C 8001D66C 2718CA40 */  addiu      $t8, $t8, %lo(D_8006CA40)
    /* 1E270 8001D670 25ADCA28 */  addiu      $t5, $t5, %lo(D_8006CA28)
    /* 1E274 8001D674 AFA20030 */  sw         $v0, 0x30($sp)
    /* 1E278 8001D678 AFA30034 */  sw         $v1, 0x34($sp)
    /* 1E27C 8001D67C 3C048007 */  lui        $a0, %hi(D_8006CA08)
    /* 1E280 8001D680 240E0000 */  addiu      $t6, $zero, 0x0
    /* 1E284 8001D684 240F0000 */  addiu      $t7, $zero, 0x0
    /* 1E288 8001D688 AFAF0014 */  sw         $t7, 0x14($sp)
    /* 1E28C 8001D68C AFAE0010 */  sw         $t6, 0x10($sp)
    /* 1E290 8001D690 2484CA08 */  addiu      $a0, $a0, %lo(D_8006CA08)
    /* 1E294 8001D694 8FA70034 */  lw         $a3, 0x34($sp)
    /* 1E298 8001D698 8FA60030 */  lw         $a2, 0x30($sp)
    /* 1E29C 8001D69C AFAD0018 */  sw         $t5, 0x18($sp)
    /* 1E2A0 8001D6A0 0C009D74 */  jal        func_800275D0
    /* 1E2A4 8001D6A4 AFB8001C */   sw        $t8, 0x1C($sp)
    /* 1E2A8 8001D6A8 3C048007 */  lui        $a0, %hi(D_8006CA28)
    /* 1E2AC 8001D6AC 2484CA28 */  addiu      $a0, $a0, %lo(D_8006CA28)
    /* 1E2B0 8001D6B0 00002825 */  or         $a1, $zero, $zero
    /* 1E2B4 8001D6B4 0C006E9C */  jal        func_8001BA70
    /* 1E2B8 8001D6B8 24060001 */   addiu     $a2, $zero, 0x1
    /* 1E2BC 8001D6BC 8FB9004C */  lw         $t9, 0x4C($sp)
    /* 1E2C0 8001D6C0 1F20FFC6 */  bgtz       $t9, .L8001D5DC
    /* 1E2C4 8001D6C4 00000000 */   nop
  .L8001D6C8:
    /* 1E2C8 8001D6C8 8FA2003C */  lw         $v0, 0x3C($sp)
  .L8001D6CC:
    /* 1E2CC 8001D6CC 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 1E2D0 8001D6D0 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 1E2D4 8001D6D4 03E00008 */  jr         $ra
    /* 1E2D8 8001D6D8 00000000 */   nop
    /* 1E2DC 8001D6DC 00000000 */  nop
