.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001D950
    /* 1E550 8001D950 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1E554 8001D954 AFA40018 */  sw         $a0, 0x18($sp)
    /* 1E558 8001D958 00802825 */  or         $a1, $a0, $zero
    /* 1E55C 8001D95C 24A44000 */  addiu      $a0, $a1, 0x4000
    /* 1E560 8001D960 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1E564 8001D964 308EFFFF */  andi       $t6, $a0, 0xFFFF
    /* 1E568 8001D968 0C007660 */  jal        func_8001D980
    /* 1E56C 8001D96C 01C02025 */   or        $a0, $t6, $zero
    /* 1E570 8001D970 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1E574 8001D974 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1E578 8001D978 03E00008 */  jr         $ra
    /* 1E57C 8001D97C 00000000 */   nop

glabel func_8001D980
    /* 1E580 8001D980 308EFFFF */  andi       $t6, $a0, 0xFFFF
    /* 1E584 8001D984 000E7902 */  srl        $t7, $t6, 4
    /* 1E588 8001D988 31F8FFFF */  andi       $t8, $t7, 0xFFFF
    /* 1E58C 8001D98C 33190400 */  andi       $t9, $t8, 0x400
    /* 1E590 8001D990 AFA40000 */  sw         $a0, 0x0($sp)
    /* 1E594 8001D994 13200008 */  beqz       $t9, .L8001D9B8
    /* 1E598 8001D998 03001025 */   or        $v0, $t8, $zero
    /* 1E59C 8001D99C 330803FF */  andi       $t0, $t8, 0x3FF
    /* 1E5A0 8001D9A0 00084840 */  sll        $t1, $t0, 1
    /* 1E5A4 8001D9A4 00095023 */  negu       $t2, $t1
    /* 1E5A8 8001D9A8 3C038003 */  lui        $v1, %hi(D_8003560E)
    /* 1E5AC 8001D9AC 006A1821 */  addu       $v1, $v1, $t2
    /* 1E5B0 8001D9B0 10000006 */  b          .L8001D9CC
    /* 1E5B4 8001D9B4 8463560E */   lh        $v1, %lo(D_8003560E)($v1)
  .L8001D9B8:
    /* 1E5B8 8001D9B8 304B03FF */  andi       $t3, $v0, 0x3FF
    /* 1E5BC 8001D9BC 000B6040 */  sll        $t4, $t3, 1
    /* 1E5C0 8001D9C0 3C038003 */  lui        $v1, %hi(D_80034E10)
    /* 1E5C4 8001D9C4 006C1821 */  addu       $v1, $v1, $t4
    /* 1E5C8 8001D9C8 84634E10 */  lh         $v1, %lo(D_80034E10)($v1)
  .L8001D9CC:
    /* 1E5CC 8001D9CC 304D0800 */  andi       $t5, $v0, 0x800
    /* 1E5D0 8001D9D0 11A00005 */  beqz       $t5, .L8001D9E8
    /* 1E5D4 8001D9D4 00601025 */   or        $v0, $v1, $zero
    /* 1E5D8 8001D9D8 00031023 */  negu       $v0, $v1
    /* 1E5DC 8001D9DC 00027400 */  sll        $t6, $v0, 16
    /* 1E5E0 8001D9E0 03E00008 */  jr         $ra
    /* 1E5E4 8001D9E4 000E1403 */   sra       $v0, $t6, 16
  .L8001D9E8:
    /* 1E5E8 8001D9E8 03E00008 */  jr         $ra
    /* 1E5EC 8001D9EC 00000000 */   nop

glabel func_8001D9F0
    /* 1E5F0 8001D9F0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1E5F4 8001D9F4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 1E5F8 8001D9F8 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 1E5FC 8001D9FC AFA60020 */  sw         $a2, 0x20($sp)
    /* 1E600 8001DA00 AFA70024 */  sw         $a3, 0x24($sp)
    /* 1E604 8001DA04 0C009FE4 */  jal        func_80027F90
    /* 1E608 8001DA08 AFA40018 */   sw        $a0, 0x18($sp)
    /* 1E60C 8001DA0C C7A40020 */  lwc1       $ft0, 0x20($sp)
    /* 1E610 8001DA10 C7A6001C */  lwc1       $ft1, 0x1C($sp)
    /* 1E614 8001DA14 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 1E618 8001DA18 44814000 */  mtc1       $at, $ft2
    /* 1E61C 8001DA1C 46062001 */  sub.s      $fv0, $ft0, $ft1
    /* 1E620 8001DA20 8FA20018 */  lw         $v0, 0x18($sp)
    /* 1E624 8001DA24 C7AE0028 */  lwc1       $fa1, 0x28($sp)
    /* 1E628 8001DA28 C7B00030 */  lwc1       $ft4, 0x30($sp)
    /* 1E62C 8001DA2C 46004283 */  div.s      $ft3, $ft2, $fv0
    /* 1E630 8001DA30 C7B2002C */  lwc1       $ft5, 0x2C($sp)
    /* 1E634 8001DA34 44813000 */  mtc1       $at, $ft1
    /* 1E638 8001DA38 3C01C000 */  lui        $at, (0xC0000000 >> 16)
    /* 1E63C 8001DA3C 46128301 */  sub.s      $fa0, $ft4, $ft5
    /* 1E640 8001DA40 00001825 */  or         $v1, $zero, $zero
    /* 1E644 8001DA44 24040004 */  addiu      $a0, $zero, 0x4
    /* 1E648 8001DA48 E44A0000 */  swc1       $ft3, 0x0($v0)
    /* 1E64C 8001DA4C C7A40024 */  lwc1       $ft0, 0x24($sp)
    /* 1E650 8001DA50 44815000 */  mtc1       $at, $ft3
    /* 1E654 8001DA54 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 1E658 8001DA58 46047081 */  sub.s      $fv1, $fa1, $ft0
    /* 1E65C 8001DA5C 460C5103 */  div.s      $ft0, $ft3, $fa0
    /* 1E660 8001DA60 46023203 */  div.s      $ft2, $ft1, $fv1
    /* 1E664 8001DA64 E4440028 */  swc1       $ft0, 0x28($v0)
    /* 1E668 8001DA68 E4480014 */  swc1       $ft2, 0x14($v0)
    /* 1E66C 8001DA6C C7A8001C */  lwc1       $ft2, 0x1C($sp)
    /* 1E670 8001DA70 C7A60020 */  lwc1       $ft1, 0x20($sp)
    /* 1E674 8001DA74 46083280 */  add.s      $ft3, $ft1, $ft2
    /* 1E678 8001DA78 46005107 */  neg.s      $ft0, $ft3
    /* 1E67C 8001DA7C 46002183 */  div.s      $ft1, $ft0, $fv0
    /* 1E680 8001DA80 E4460030 */  swc1       $ft1, 0x30($v0)
    /* 1E684 8001DA84 C7A80024 */  lwc1       $ft2, 0x24($sp)
    /* 1E688 8001DA88 46087280 */  add.s      $ft3, $fa1, $ft2
    /* 1E68C 8001DA8C 46128200 */  add.s      $ft2, $ft4, $ft5
    /* 1E690 8001DA90 46005107 */  neg.s      $ft0, $ft3
    /* 1E694 8001DA94 46004287 */  neg.s      $ft3, $ft2
    /* 1E698 8001DA98 46022183 */  div.s      $ft1, $ft0, $fv1
    /* 1E69C 8001DA9C 460C5103 */  div.s      $ft0, $ft3, $fa0
    /* 1E6A0 8001DAA0 E4460034 */  swc1       $ft1, 0x34($v0)
    /* 1E6A4 8001DAA4 44813000 */  mtc1       $at, $ft1
    /* 1E6A8 8001DAA8 00000000 */  nop
    /* 1E6AC 8001DAAC E446003C */  swc1       $ft1, 0x3C($v0)
    /* 1E6B0 8001DAB0 E4440038 */  swc1       $ft0, 0x38($v0)
    /* 1E6B4 8001DAB4 C7A00034 */  lwc1       $fv0, 0x34($sp)
    /* 1E6B8 8001DAB8 C4480000 */  lwc1       $ft2, 0x0($v0)
    /* 1E6BC 8001DABC 24630001 */  addiu      $v1, $v1, 0x1
    /* 1E6C0 8001DAC0 C4520004 */  lwc1       $ft5, 0x4($v0)
    /* 1E6C4 8001DAC4 46004302 */  mul.s      $fa0, $ft2, $fv0
    /* 1E6C8 8001DAC8 C44E0008 */  lwc1       $fa1, 0x8($v0)
    /* 1E6CC 8001DACC 10640010 */  beq        $v1, $a0, .L8001DB10
    /* 1E6D0 8001DAD0 C450000C */   lwc1      $ft4, 0xC($v0)
  .L8001DAD4:
    /* 1E6D4 8001DAD4 46009282 */  mul.s      $ft3, $ft5, $fv0
    /* 1E6D8 8001DAD8 C4480010 */  lwc1       $ft2, 0x10($v0)
    /* 1E6DC 8001DADC C4520014 */  lwc1       $ft5, 0x14($v0)
    /* 1E6E0 8001DAE0 46007182 */  mul.s      $ft1, $fa1, $fv0
    /* 1E6E4 8001DAE4 C44E0018 */  lwc1       $fa1, 0x18($v0)
    /* 1E6E8 8001DAE8 24630001 */  addiu      $v1, $v1, 0x1
    /* 1E6EC 8001DAEC 46008102 */  mul.s      $ft0, $ft4, $fv0
    /* 1E6F0 8001DAF0 C450001C */  lwc1       $ft4, 0x1C($v0)
    /* 1E6F4 8001DAF4 E44C0000 */  swc1       $fa0, 0x0($v0)
    /* 1E6F8 8001DAF8 46004302 */  mul.s      $fa0, $ft2, $fv0
    /* 1E6FC 8001DAFC E44A0004 */  swc1       $ft3, 0x4($v0)
    /* 1E700 8001DB00 E4460008 */  swc1       $ft1, 0x8($v0)
    /* 1E704 8001DB04 24420010 */  addiu      $v0, $v0, 0x10
    /* 1E708 8001DB08 1464FFF2 */  bne        $v1, $a0, .L8001DAD4
    /* 1E70C 8001DB0C E444FFFC */   swc1      $ft0, -0x4($v0)
  .L8001DB10:
    /* 1E710 8001DB10 46009282 */  mul.s      $ft3, $ft5, $fv0
    /* 1E714 8001DB14 24420010 */  addiu      $v0, $v0, 0x10
    /* 1E718 8001DB18 E44CFFF0 */  swc1       $fa0, -0x10($v0)
    /* 1E71C 8001DB1C 46007182 */  mul.s      $ft1, $fa1, $fv0
    /* 1E720 8001DB20 00000000 */  nop
    /* 1E724 8001DB24 46008102 */  mul.s      $ft0, $ft4, $fv0
    /* 1E728 8001DB28 E44AFFF4 */  swc1       $ft3, -0xC($v0)
    /* 1E72C 8001DB2C E446FFF8 */  swc1       $ft1, -0x8($v0)
    /* 1E730 8001DB30 E444FFFC */  swc1       $ft0, -0x4($v0)
    /* 1E734 8001DB34 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1E738 8001DB38 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 1E73C 8001DB3C 03E00008 */  jr         $ra
    /* 1E740 8001DB40 00000000 */   nop

glabel func_8001DB44
    /* 1E744 8001DB44 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 1E748 8001DB48 44856000 */  mtc1       $a1, $fa0
    /* 1E74C 8001DB4C 44867000 */  mtc1       $a2, $fa1
    /* 1E750 8001DB50 44878000 */  mtc1       $a3, $ft4
    /* 1E754 8001DB54 C7A40078 */  lwc1       $ft0, 0x78($sp)
    /* 1E758 8001DB58 C7A6007C */  lwc1       $ft1, 0x7C($sp)
    /* 1E75C 8001DB5C C7A80080 */  lwc1       $ft2, 0x80($sp)
    /* 1E760 8001DB60 C7AA0084 */  lwc1       $ft3, 0x84($sp)
    /* 1E764 8001DB64 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1E768 8001DB68 AFA40068 */  sw         $a0, 0x68($sp)
    /* 1E76C 8001DB6C 44056000 */  mfc1       $a1, $fa0
    /* 1E770 8001DB70 44067000 */  mfc1       $a2, $fa1
    /* 1E774 8001DB74 44078000 */  mfc1       $a3, $ft4
    /* 1E778 8001DB78 27A40028 */  addiu      $a0, $sp, 0x28
    /* 1E77C 8001DB7C E7A40010 */  swc1       $ft0, 0x10($sp)
    /* 1E780 8001DB80 E7A60014 */  swc1       $ft1, 0x14($sp)
    /* 1E784 8001DB84 E7A80018 */  swc1       $ft2, 0x18($sp)
    /* 1E788 8001DB88 0C00767C */  jal        func_8001D9F0
    /* 1E78C 8001DB8C E7AA001C */   swc1      $ft3, 0x1C($sp)
    /* 1E790 8001DB90 27A40028 */  addiu      $a0, $sp, 0x28
    /* 1E794 8001DB94 0C009FA4 */  jal        func_80027E90
    /* 1E798 8001DB98 8FA50068 */   lw        $a1, 0x68($sp)
    /* 1E79C 8001DB9C 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 1E7A0 8001DBA0 27BD0068 */  addiu      $sp, $sp, 0x68
    /* 1E7A4 8001DBA4 03E00008 */  jr         $ra
    /* 1E7A8 8001DBA8 00000000 */   nop
    /* 1E7AC 8001DBAC 00000000 */  nop
