.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001E9C0
    /* 1F5C0 8001E9C0 3C0E8003 */  lui        $t6, %hi(D_80036350)
    /* 1F5C4 8001E9C4 8DCE6350 */  lw         $t6, %lo(D_80036350)($t6)
    /* 1F5C8 8001E9C8 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 1F5CC 8001E9CC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1F5D0 8001E9D0 15C00059 */  bnez       $t6, .L8001EB38
    /* 1F5D4 8001E9D4 AFA40030 */   sw        $a0, 0x30($sp)
    /* 1F5D8 8001E9D8 0C00A0E8 */  jal        func_800283A0
    /* 1F5DC 8001E9DC 00000000 */   nop
    /* 1F5E0 8001E9E0 3C048007 */  lui        $a0, %hi(D_8006DC20)
    /* 1F5E4 8001E9E4 3C058007 */  lui        $a1, %hi(D_8006DC38)
    /* 1F5E8 8001E9E8 24A5DC38 */  addiu      $a1, $a1, %lo(D_8006DC38)
    /* 1F5EC 8001E9EC 2484DC20 */  addiu      $a0, $a0, %lo(D_8006DC20)
    /* 1F5F0 8001E9F0 0C006B98 */  jal        func_8001AE60
    /* 1F5F4 8001E9F4 24060005 */   addiu     $a2, $zero, 0x5
    /* 1F5F8 8001E9F8 3C018007 */  lui        $at, %hi(D_8006DC50)
    /* 1F5FC 8001E9FC 240F000D */  addiu      $t7, $zero, 0xD
    /* 1F600 8001EA00 A42FDC50 */  sh         $t7, %lo(D_8006DC50)($at)
    /* 1F604 8001EA04 A020DC52 */  sb         $zero, %lo(D_8006DC52)($at)
    /* 1F608 8001EA08 AC20DC54 */  sw         $zero, %lo(D_8006DC54)($at)
    /* 1F60C 8001EA0C 3C018007 */  lui        $at, %hi(D_8006DC68)
    /* 1F610 8001EA10 2418000E */  addiu      $t8, $zero, 0xE
    /* 1F614 8001EA14 3C058007 */  lui        $a1, %hi(D_8006DC20)
    /* 1F618 8001EA18 3C068007 */  lui        $a2, %hi(D_8006DC50)
    /* 1F61C 8001EA1C A438DC68 */  sh         $t8, %lo(D_8006DC68)($at)
    /* 1F620 8001EA20 A020DC6A */  sb         $zero, %lo(D_8006DC6A)($at)
    /* 1F624 8001EA24 AC20DC6C */  sw         $zero, %lo(D_8006DC6C)($at)
    /* 1F628 8001EA28 24C6DC50 */  addiu      $a2, $a2, %lo(D_8006DC50)
    /* 1F62C 8001EA2C 24A5DC20 */  addiu      $a1, $a1, %lo(D_8006DC20)
    /* 1F630 8001EA30 0C007324 */  jal        func_8001CC90
    /* 1F634 8001EA34 24040007 */   addiu     $a0, $zero, 0x7
    /* 1F638 8001EA38 3C058007 */  lui        $a1, %hi(D_8006DC20)
    /* 1F63C 8001EA3C 3C068007 */  lui        $a2, %hi(D_8006DC68)
    /* 1F640 8001EA40 24C6DC68 */  addiu      $a2, $a2, %lo(D_8006DC68)
    /* 1F644 8001EA44 24A5DC20 */  addiu      $a1, $a1, %lo(D_8006DC20)
    /* 1F648 8001EA48 0C007324 */  jal        func_8001CC90
    /* 1F64C 8001EA4C 24040003 */   addiu     $a0, $zero, 0x3
    /* 1F650 8001EA50 2419FFFF */  addiu      $t9, $zero, -0x1
    /* 1F654 8001EA54 AFB90028 */  sw         $t9, 0x28($sp)
    /* 1F658 8001EA58 0C00A1E8 */  jal        func_800287A0
    /* 1F65C 8001EA5C 00002025 */   or        $a0, $zero, $zero
    /* 1F660 8001EA60 AFA20024 */  sw         $v0, 0x24($sp)
    /* 1F664 8001EA64 8FA80024 */  lw         $t0, 0x24($sp)
    /* 1F668 8001EA68 8FA90030 */  lw         $t1, 0x30($sp)
    /* 1F66C 8001EA6C 0109082A */  slt        $at, $t0, $t1
    /* 1F670 8001EA70 10200005 */  beqz       $at, .L8001EA88
    /* 1F674 8001EA74 00000000 */   nop
    /* 1F678 8001EA78 AFA80028 */  sw         $t0, 0x28($sp)
    /* 1F67C 8001EA7C 00002025 */  or         $a0, $zero, $zero
    /* 1F680 8001EA80 0C007BF4 */  jal        func_8001EFD0
    /* 1F684 8001EA84 01202825 */   or        $a1, $t1, $zero
  .L8001EA88:
    /* 1F688 8001EA88 0C008E6C */  jal        func_800239B0
    /* 1F68C 8001EA8C 00000000 */   nop
    /* 1F690 8001EA90 3C018003 */  lui        $at, %hi(D_80036350)
    /* 1F694 8001EA94 3C0C8007 */  lui        $t4, %hi(D_8006DC20)
    /* 1F698 8001EA98 3C0B8007 */  lui        $t3, %hi(D_8006CA70)
    /* 1F69C 8001EA9C 258CDC20 */  addiu      $t4, $t4, %lo(D_8006DC20)
    /* 1F6A0 8001EAA0 240A0001 */  addiu      $t2, $zero, 0x1
    /* 1F6A4 8001EAA4 256BCA70 */  addiu      $t3, $t3, %lo(D_8006CA70)
    /* 1F6A8 8001EAA8 AC2A6350 */  sw         $t2, %lo(D_80036350)($at)
    /* 1F6AC 8001EAAC AC2B6354 */  sw         $t3, %lo(D_80036354)($at)
    /* 1F6B0 8001EAB0 AC2C6358 */  sw         $t4, %lo(D_80036358)($at)
    /* 1F6B4 8001EAB4 AC2C635C */  sw         $t4, %lo(D_8003635C)($at)
    /* 1F6B8 8001EAB8 3C0D8007 */  lui        $t5, %hi(D_8006CC20)
    /* 1F6BC 8001EABC 8FAF0030 */  lw         $t7, 0x30($sp)
    /* 1F6C0 8001EAC0 3C018003 */  lui        $at, %hi(D_80036360)
    /* 1F6C4 8001EAC4 25ADCC20 */  addiu      $t5, $t5, %lo(D_8006CC20)
    /* 1F6C8 8001EAC8 25AE1000 */  addiu      $t6, $t5, 0x1000
    /* 1F6CC 8001EACC 3C068002 */  lui        $a2, %hi(func_8001EB48)
    /* 1F6D0 8001EAD0 3C078003 */  lui        $a3, %hi(D_80036350)
    /* 1F6D4 8001EAD4 AFA2002C */  sw         $v0, 0x2C($sp)
    /* 1F6D8 8001EAD8 AC206360 */  sw         $zero, %lo(D_80036360)($at)
    /* 1F6DC 8001EADC AC206364 */  sw         $zero, %lo(D_80036364)($at)
    /* 1F6E0 8001EAE0 AC206368 */  sw         $zero, %lo(D_80036368)($at)
    /* 1F6E4 8001EAE4 24E76350 */  addiu      $a3, $a3, %lo(D_80036350)
    /* 1F6E8 8001EAE8 24C6EB48 */  addiu      $a2, $a2, %lo(func_8001EB48)
    /* 1F6EC 8001EAEC AFAE0010 */  sw         $t6, 0x10($sp)
    /* 1F6F0 8001EAF0 01602025 */  or         $a0, $t3, $zero
    /* 1F6F4 8001EAF4 00002825 */  or         $a1, $zero, $zero
    /* 1F6F8 8001EAF8 0C006BA4 */  jal        func_8001AE90
    /* 1F6FC 8001EAFC AFAF0014 */   sw        $t7, 0x14($sp)
    /* 1F700 8001EB00 0C00A1F0 */  jal        func_800287C0
    /* 1F704 8001EB04 00000000 */   nop
    /* 1F708 8001EB08 3C048007 */  lui        $a0, %hi(D_8006CA70)
    /* 1F70C 8001EB0C 0C006BF8 */  jal        func_8001AFE0
    /* 1F710 8001EB10 2484CA70 */   addiu     $a0, $a0, %lo(D_8006CA70)
    /* 1F714 8001EB14 0C008E74 */  jal        func_800239D0
    /* 1F718 8001EB18 8FA4002C */   lw        $a0, 0x2C($sp)
    /* 1F71C 8001EB1C 8FB80028 */  lw         $t8, 0x28($sp)
    /* 1F720 8001EB20 2401FFFF */  addiu      $at, $zero, -0x1
    /* 1F724 8001EB24 13010004 */  beq        $t8, $at, .L8001EB38
    /* 1F728 8001EB28 00000000 */   nop
    /* 1F72C 8001EB2C 00002025 */  or         $a0, $zero, $zero
    /* 1F730 8001EB30 0C007BF4 */  jal        func_8001EFD0
    /* 1F734 8001EB34 03002825 */   or        $a1, $t8, $zero
  .L8001EB38:
    /* 1F738 8001EB38 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 1F73C 8001EB3C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 1F740 8001EB40 03E00008 */  jr         $ra
    /* 1F744 8001EB44 00000000 */   nop

glabel func_8001EB48
    /* 1F748 8001EB48 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 1F74C 8001EB4C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1F750 8001EB50 AFA40038 */  sw         $a0, 0x38($sp)
    /* 1F754 8001EB54 AFB00018 */  sw         $s0, 0x18($sp)
    /* 1F758 8001EB58 AFA0002C */  sw         $zero, 0x2C($sp)
    /* 1F75C 8001EB5C 0C00A240 */  jal        func_80028900
    /* 1F760 8001EB60 AFA00028 */   sw        $zero, 0x28($sp)
    /* 1F764 8001EB64 AFA20034 */  sw         $v0, 0x34($sp)
    /* 1F768 8001EB68 8FAE0034 */  lw         $t6, 0x34($sp)
    /* 1F76C 8001EB6C 3C018007 */  lui        $at, %hi(D_8006DC80)
    /* 1F770 8001EB70 95CF0002 */  lhu        $t7, 0x2($t6)
    /* 1F774 8001EB74 15E00004 */  bnez       $t7, .L8001EB88
    /* 1F778 8001EB78 A42FDC80 */   sh        $t7, %lo(D_8006DC80)($at)
    /* 1F77C 8001EB7C 24180001 */  addiu      $t8, $zero, 0x1
    /* 1F780 8001EB80 3C018007 */  lui        $at, %hi(D_8006DC80)
    /* 1F784 8001EB84 A438DC80 */  sh         $t8, %lo(D_8006DC80)($at)
  .L8001EB88:
    /* 1F788 8001EB88 8FB90038 */  lw         $t9, 0x38($sp)
    /* 1F78C 8001EB8C AFB90030 */  sw         $t9, 0x30($sp)
  .L8001EB90:
    /* 1F790 8001EB90 8FA80030 */  lw         $t0, 0x30($sp)
    /* 1F794 8001EB94 27A5002C */  addiu      $a1, $sp, 0x2C
    /* 1F798 8001EB98 24060001 */  addiu      $a2, $zero, 0x1
    /* 1F79C 8001EB9C 0C006E9C */  jal        func_8001BA70
    /* 1F7A0 8001EBA0 8D04000C */   lw        $a0, 0xC($t0)
    /* 1F7A4 8001EBA4 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 1F7A8 8001EBA8 2401000D */  addiu      $at, $zero, 0xD
    /* 1F7AC 8001EBAC 95300000 */  lhu        $s0, 0x0($t1)
    /* 1F7B0 8001EBB0 12010005 */  beq        $s0, $at, .L8001EBC8
    /* 1F7B4 8001EBB4 2401000E */   addiu     $at, $zero, 0xE
    /* 1F7B8 8001EBB8 12010047 */  beq        $s0, $at, .L8001ECD8
    /* 1F7BC 8001EBBC 00000000 */   nop
    /* 1F7C0 8001EBC0 1000FFF3 */  b          .L8001EB90
    /* 1F7C4 8001EBC4 00000000 */   nop
  .L8001EBC8:
    /* 1F7C8 8001EBC8 0C00A244 */  jal        func_80028910
    /* 1F7CC 8001EBCC 00000000 */   nop
    /* 1F7D0 8001EBD0 3C0A8007 */  lui        $t2, %hi(D_8006DC80)
    /* 1F7D4 8001EBD4 954ADC80 */  lhu        $t2, %lo(D_8006DC80)($t2)
    /* 1F7D8 8001EBD8 3C018007 */  lui        $at, %hi(D_8006DC80)
    /* 1F7DC 8001EBDC 254BFFFF */  addiu      $t3, $t2, -0x1
    /* 1F7E0 8001EBE0 316CFFFF */  andi       $t4, $t3, 0xFFFF
    /* 1F7E4 8001EBE4 15800010 */  bnez       $t4, .L8001EC28
    /* 1F7E8 8001EBE8 A42BDC80 */   sh        $t3, %lo(D_8006DC80)($at)
    /* 1F7EC 8001EBEC 0C00A240 */  jal        func_80028900
    /* 1F7F0 8001EBF0 00000000 */   nop
    /* 1F7F4 8001EBF4 AFA20034 */  sw         $v0, 0x34($sp)
    /* 1F7F8 8001EBF8 8FAD0034 */  lw         $t5, 0x34($sp)
    /* 1F7FC 8001EBFC 8DAE0010 */  lw         $t6, 0x10($t5)
    /* 1F800 8001EC00 11C00005 */  beqz       $t6, .L8001EC18
    /* 1F804 8001EC04 00000000 */   nop
    /* 1F808 8001EC08 01C02025 */  or         $a0, $t6, $zero
    /* 1F80C 8001EC0C 8DA50014 */  lw         $a1, 0x14($t5)
    /* 1F810 8001EC10 0C0070F4 */  jal        func_8001C3D0
    /* 1F814 8001EC14 00003025 */   or        $a2, $zero, $zero
  .L8001EC18:
    /* 1F818 8001EC18 8FAF0034 */  lw         $t7, 0x34($sp)
    /* 1F81C 8001EC1C 3C018007 */  lui        $at, %hi(D_8006DC80)
    /* 1F820 8001EC20 95F80002 */  lhu        $t8, 0x2($t7)
    /* 1F824 8001EC24 A438DC80 */  sh         $t8, %lo(D_8006DC80)($at)
  .L8001EC28:
    /* 1F828 8001EC28 3C198007 */  lui        $t9, %hi(D_8006EF8C)
    /* 1F82C 8001EC2C 8F39EF8C */  lw         $t9, %lo(D_8006EF8C)($t9)
    /* 1F830 8001EC30 8FA90028 */  lw         $t1, 0x28($sp)
    /* 1F834 8001EC34 3C018007 */  lui        $at, %hi(D_8006EF8C)
    /* 1F838 8001EC38 27280001 */  addiu      $t0, $t9, 0x1
    /* 1F83C 8001EC3C 1120000C */  beqz       $t1, .L8001EC70
    /* 1F840 8001EC40 AC28EF8C */   sw        $t0, %lo(D_8006EF8C)($at)
    /* 1F844 8001EC44 0C007D50 */  jal        func_8001F540
    /* 1F848 8001EC48 00000000 */   nop
    /* 1F84C 8001EC4C AFA20024 */  sw         $v0, 0x24($sp)
    /* 1F850 8001EC50 8FAA0024 */  lw         $t2, 0x24($sp)
    /* 1F854 8001EC54 240C0000 */  addiu      $t4, $zero, 0x0
    /* 1F858 8001EC58 3C018007 */  lui        $at, %hi(D_8006EF80)
    /* 1F85C 8001EC5C AC2CEF80 */  sw         $t4, %lo(D_8006EF80)($at)
    /* 1F860 8001EC60 3C018007 */  lui        $at, %hi(D_8006EF84)
    /* 1F864 8001EC64 01406825 */  or         $t5, $t2, $zero
    /* 1F868 8001EC68 AC2DEF84 */  sw         $t5, %lo(D_8006EF84)($at)
    /* 1F86C 8001EC6C AFA00028 */  sw         $zero, 0x28($sp)
  .L8001EC70:
    /* 1F870 8001EC70 3C0B8007 */  lui        $t3, %hi(D_8006EF88)
    /* 1F874 8001EC74 8D6BEF88 */  lw         $t3, %lo(D_8006EF88)($t3)
    /* 1F878 8001EC78 0C007D50 */  jal        func_8001F540
    /* 1F87C 8001EC7C AFAB0024 */   sw        $t3, 0x24($sp)
    /* 1F880 8001EC80 3C018007 */  lui        $at, %hi(D_8006EF88)
    /* 1F884 8001EC84 AC22EF88 */  sw         $v0, %lo(D_8006EF88)($at)
    /* 1F888 8001EC88 3C0E8007 */  lui        $t6, %hi(D_8006EF88)
    /* 1F88C 8001EC8C 8DCEEF88 */  lw         $t6, %lo(D_8006EF88)($t6)
    /* 1F890 8001EC90 8FAF0024 */  lw         $t7, 0x24($sp)
    /* 1F894 8001EC94 3C0B8007 */  lui        $t3, %hi(D_8006EF84)
    /* 1F898 8001EC98 8D6BEF84 */  lw         $t3, %lo(D_8006EF84)($t3)
    /* 1F89C 8001EC9C 01CFC023 */  subu       $t8, $t6, $t7
    /* 1F8A0 8001ECA0 03004825 */  or         $t1, $t8, $zero
    /* 1F8A4 8001ECA4 3C0A8007 */  lui        $t2, %hi(D_8006EF80)
    /* 1F8A8 8001ECA8 012B6821 */  addu       $t5, $t1, $t3
    /* 1F8AC 8001ECAC 8D4AEF80 */  lw         $t2, %lo(D_8006EF80)($t2)
    /* 1F8B0 8001ECB0 24080000 */  addiu      $t0, $zero, 0x0
    /* 1F8B4 8001ECB4 01AB082B */  sltu       $at, $t5, $t3
    /* 1F8B8 8001ECB8 00286021 */  addu       $t4, $at, $t0
    /* 1F8BC 8001ECBC 3C018007 */  lui        $at, %hi(D_8006EF80)
    /* 1F8C0 8001ECC0 018A6021 */  addu       $t4, $t4, $t2
    /* 1F8C4 8001ECC4 AC2CEF80 */  sw         $t4, %lo(D_8006EF80)($at)
    /* 1F8C8 8001ECC8 3C018007 */  lui        $at, %hi(D_8006EF84)
    /* 1F8CC 8001ECCC AFB80024 */  sw         $t8, 0x24($sp)
    /* 1F8D0 8001ECD0 1000FFAF */  b          .L8001EB90
    /* 1F8D4 8001ECD4 AC2DEF84 */   sw        $t5, %lo(D_8006EF84)($at)
  .L8001ECD8:
    /* 1F8D8 8001ECD8 0C00A10B */  jal        func_8002842C
    /* 1F8DC 8001ECDC 00000000 */   nop
    /* 1F8E0 8001ECE0 1000FFAB */  b          .L8001EB90
    /* 1F8E4 8001ECE4 00000000 */   nop
    /* 1F8E8 8001ECE8 00000000 */  nop
    /* 1F8EC 8001ECEC 00000000 */  nop
    /* 1F8F0 8001ECF0 00000000 */  nop
    /* 1F8F4 8001ECF4 00000000 */  nop
    /* 1F8F8 8001ECF8 00000000 */  nop
    /* 1F8FC 8001ECFC 00000000 */  nop
    /* 1F900 8001ED00 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 1F904 8001ED04 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1F908 8001ED08 27BD0038 */  addiu      $sp, $sp, 0x38
    /* 1F90C 8001ED0C 03E00008 */  jr         $ra
    /* 1F910 8001ED10 00000000 */   nop
    /* 1F914 8001ED14 00000000 */  nop
    /* 1F918 8001ED18 00000000 */  nop
    /* 1F91C 8001ED1C 00000000 */  nop
    /* 1F920 8001ED20 00000000 */  nop
    /* 1F924 8001ED24 00000000 */  nop
    /* 1F928 8001ED28 00000000 */  nop
    /* 1F92C 8001ED2C 00000000 */  nop
    /* 1F930 8001ED30 00000000 */  nop
    /* 1F934 8001ED34 00000000 */  nop
    /* 1F938 8001ED38 00000000 */  nop
    /* 1F93C 8001ED3C 00000000 */  nop
    /* 1F940 8001ED40 00000000 */  nop
    /* 1F944 8001ED44 00000000 */  nop
    /* 1F948 8001ED48 00000000 */  nop
    /* 1F94C 8001ED4C 00000000 */  nop
    /* 1F950 8001ED50 00000000 */  nop
    /* 1F954 8001ED54 00000000 */  nop
    /* 1F958 8001ED58 00000000 */  nop
    /* 1F95C 8001ED5C 00000000 */  nop
    /* 1F960 8001ED60 00000000 */  nop
    /* 1F964 8001ED64 00000000 */  nop
    /* 1F968 8001ED68 00000000 */  nop
    /* 1F96C 8001ED6C 00000000 */  nop
    /* 1F970 8001ED70 00000000 */  nop
    /* 1F974 8001ED74 00000000 */  nop
    /* 1F978 8001ED78 00000000 */  nop
    /* 1F97C 8001ED7C 00000000 */  nop
