.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001EFD0
    /* 1FBD0 8001EFD0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 1FBD4 8001EFD4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 1FBD8 8001EFD8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 1FBDC 8001EFDC AFA5002C */  sw         $a1, 0x2C($sp)
    /* 1FBE0 8001EFE0 0C008E6C */  jal        func_800239B0
    /* 1FBE4 8001EFE4 AFB00018 */   sw        $s0, 0x18($sp)
    /* 1FBE8 8001EFE8 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 1FBEC 8001EFEC 00408025 */  or         $s0, $v0, $zero
    /* 1FBF0 8001EFF0 15C00004 */  bnez       $t6, .L8001F004
    /* 1FBF4 8001EFF4 00000000 */   nop
    /* 1FBF8 8001EFF8 3C0F8003 */  lui        $t7, %hi(D_800363B0)
    /* 1FBFC 8001EFFC 8DEF63B0 */  lw         $t7, %lo(D_800363B0)($t7)
    /* 1FC00 8001F000 AFAF0028 */  sw         $t7, 0x28($sp)
  .L8001F004:
    /* 1FC04 8001F004 8FB80028 */  lw         $t8, 0x28($sp)
    /* 1FC08 8001F008 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 1FC0C 8001F00C 8F190004 */  lw         $t9, 0x4($t8)
    /* 1FC10 8001F010 13280020 */  beq        $t9, $t0, .L8001F094
    /* 1FC14 8001F014 00000000 */   nop
    /* 1FC18 8001F018 AF080004 */  sw         $t0, 0x4($t8)
    /* 1FC1C 8001F01C 3C0A8003 */  lui        $t2, %hi(D_800363B0)
    /* 1FC20 8001F020 8D4A63B0 */  lw         $t2, %lo(D_800363B0)($t2)
    /* 1FC24 8001F024 8FA90028 */  lw         $t1, 0x28($sp)
    /* 1FC28 8001F028 112A000C */  beq        $t1, $t2, .L8001F05C
    /* 1FC2C 8001F02C 00000000 */   nop
    /* 1FC30 8001F030 952B0010 */  lhu        $t3, 0x10($t1)
    /* 1FC34 8001F034 24010001 */  addiu      $at, $zero, 0x1
    /* 1FC38 8001F038 11610008 */  beq        $t3, $at, .L8001F05C
    /* 1FC3C 8001F03C 00000000 */   nop
    /* 1FC40 8001F040 8D240008 */  lw         $a0, 0x8($t1)
    /* 1FC44 8001F044 0C008C18 */  jal        func_80023060
    /* 1FC48 8001F048 01202825 */   or        $a1, $t1, $zero
    /* 1FC4C 8001F04C 8FAC0028 */  lw         $t4, 0x28($sp)
    /* 1FC50 8001F050 8D840008 */  lw         $a0, 0x8($t4)
    /* 1FC54 8001F054 0C008DF3 */  jal        func_800237CC
    /* 1FC58 8001F058 01802825 */   or        $a1, $t4, $zero
  .L8001F05C:
    /* 1FC5C 8001F05C 3C0D8003 */  lui        $t5, %hi(D_800363B0)
    /* 1FC60 8001F060 3C0F8003 */  lui        $t7, %hi(D_800363A8)
    /* 1FC64 8001F064 8DEF63A8 */  lw         $t7, %lo(D_800363A8)($t7)
    /* 1FC68 8001F068 8DAD63B0 */  lw         $t5, %lo(D_800363B0)($t5)
    /* 1FC6C 8001F06C 8DF90004 */  lw         $t9, 0x4($t7)
    /* 1FC70 8001F070 8DAE0004 */  lw         $t6, 0x4($t5)
    /* 1FC74 8001F074 01D9082A */  slt        $at, $t6, $t9
    /* 1FC78 8001F078 10200006 */  beqz       $at, .L8001F094
    /* 1FC7C 8001F07C 00000000 */   nop
    /* 1FC80 8001F080 24080002 */  addiu      $t0, $zero, 0x2
    /* 1FC84 8001F084 3C048003 */  lui        $a0, %hi(D_800363A8)
    /* 1FC88 8001F088 A5A80010 */  sh         $t0, 0x10($t5)
    /* 1FC8C 8001F08C 0C008DB3 */  jal        func_800236CC
    /* 1FC90 8001F090 248463A8 */   addiu     $a0, $a0, %lo(D_800363A8)
  .L8001F094:
    /* 1FC94 8001F094 0C008E74 */  jal        func_800239D0
    /* 1FC98 8001F098 02002025 */   or        $a0, $s0, $zero
    /* 1FC9C 8001F09C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 1FCA0 8001F0A0 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1FCA4 8001F0A4 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 1FCA8 8001F0A8 03E00008 */  jr         $ra
    /* 1FCAC 8001F0AC 00000000 */   nop

glabel func_8001F0B0
    /* 1FCB0 8001F0B0 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 1FCB4 8001F0B4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1FCB8 8001F0B8 AFA40038 */  sw         $a0, 0x38($sp)
    /* 1FCBC 8001F0BC AFB20020 */  sw         $s2, 0x20($sp)
    /* 1FCC0 8001F0C0 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 1FCC4 8001F0C4 0C008E6C */  jal        func_800239B0
    /* 1FCC8 8001F0C8 AFB00018 */   sw        $s0, 0x18($sp)
    /* 1FCCC 8001F0CC 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 1FCD0 8001F0D0 00408025 */  or         $s0, $v0, $zero
    /* 1FCD4 8001F0D4 15C00003 */  bnez       $t6, .L8001F0E4
    /* 1FCD8 8001F0D8 00000000 */   nop
    /* 1FCDC 8001F0DC 10000003 */  b          .L8001F0EC
    /* 1FCE0 8001F0E0 24110004 */   addiu     $s1, $zero, 0x4
  .L8001F0E4:
    /* 1FCE4 8001F0E4 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 1FCE8 8001F0E8 95F10010 */  lhu        $s1, 0x10($t7)
  .L8001F0EC:
    /* 1FCEC 8001F0EC 02209025 */  or         $s2, $s1, $zero
    /* 1FCF0 8001F0F0 24010002 */  addiu      $at, $zero, 0x2
    /* 1FCF4 8001F0F4 1241000F */  beq        $s2, $at, .L8001F134
    /* 1FCF8 8001F0F8 24010004 */   addiu     $at, $zero, 0x4
    /* 1FCFC 8001F0FC 12410005 */  beq        $s2, $at, .L8001F114
    /* 1FD00 8001F100 24010008 */   addiu     $at, $zero, 0x8
    /* 1FD04 8001F104 1241000B */  beq        $s2, $at, .L8001F134
    /* 1FD08 8001F108 00000000 */   nop
    /* 1FD0C 8001F10C 10000010 */  b          .L8001F150
    /* 1FD10 8001F110 00000000 */   nop
  .L8001F114:
    /* 1FD14 8001F114 3C198003 */  lui        $t9, %hi(D_800363B0)
    /* 1FD18 8001F118 8F3963B0 */  lw         $t9, %lo(D_800363B0)($t9)
    /* 1FD1C 8001F11C 24180001 */  addiu      $t8, $zero, 0x1
    /* 1FD20 8001F120 00002025 */  or         $a0, $zero, $zero
    /* 1FD24 8001F124 0C008DB3 */  jal        func_800236CC
    /* 1FD28 8001F128 A7380010 */   sh        $t8, 0x10($t9)
    /* 1FD2C 8001F12C 10000008 */  b          .L8001F150
    /* 1FD30 8001F130 00000000 */   nop
  .L8001F134:
    /* 1FD34 8001F134 8FA90038 */  lw         $t1, 0x38($sp)
    /* 1FD38 8001F138 24080001 */  addiu      $t0, $zero, 0x1
    /* 1FD3C 8001F13C A5280010 */  sh         $t0, 0x10($t1)
    /* 1FD40 8001F140 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 1FD44 8001F144 8D440008 */  lw         $a0, 0x8($t2)
    /* 1FD48 8001F148 0C008C18 */  jal        func_80023060
    /* 1FD4C 8001F14C 01402825 */   or        $a1, $t2, $zero
  .L8001F150:
    /* 1FD50 8001F150 0C008E74 */  jal        func_800239D0
    /* 1FD54 8001F154 02002025 */   or        $a0, $s0, $zero
    /* 1FD58 8001F158 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 1FD5C 8001F15C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1FD60 8001F160 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 1FD64 8001F164 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1FD68 8001F168 03E00008 */  jr         $ra
    /* 1FD6C 8001F16C 27BD0038 */   addiu     $sp, $sp, 0x38

glabel func_8001F170
    /* 1FD70 8001F170 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 1FD74 8001F174 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 1FD78 8001F178 AFA40038 */  sw         $a0, 0x38($sp)
    /* 1FD7C 8001F17C AFB20020 */  sw         $s2, 0x20($sp)
    /* 1FD80 8001F180 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 1FD84 8001F184 0C008E6C */  jal        func_800239B0
    /* 1FD88 8001F188 AFB00018 */   sw        $s0, 0x18($sp)
    /* 1FD8C 8001F18C 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 1FD90 8001F190 00408025 */  or         $s0, $v0, $zero
    /* 1FD94 8001F194 15C00005 */  bnez       $t6, .L8001F1AC
    /* 1FD98 8001F198 00000000 */   nop
    /* 1FD9C 8001F19C 3C0F8003 */  lui        $t7, %hi(D_800363B0)
    /* 1FDA0 8001F1A0 8DEF63B0 */  lw         $t7, %lo(D_800363B0)($t7)
    /* 1FDA4 8001F1A4 10000009 */  b          .L8001F1CC
    /* 1FDA8 8001F1A8 AFAF0038 */   sw        $t7, 0x38($sp)
  .L8001F1AC:
    /* 1FDAC 8001F1AC 8FB80038 */  lw         $t8, 0x38($sp)
    /* 1FDB0 8001F1B0 24010001 */  addiu      $at, $zero, 0x1
    /* 1FDB4 8001F1B4 97190010 */  lhu        $t9, 0x10($t8)
    /* 1FDB8 8001F1B8 13210004 */  beq        $t9, $at, .L8001F1CC
    /* 1FDBC 8001F1BC 00000000 */   nop
    /* 1FDC0 8001F1C0 8F040008 */  lw         $a0, 0x8($t8)
    /* 1FDC4 8001F1C4 0C008C18 */  jal        func_80023060
    /* 1FDC8 8001F1C8 03002825 */   or        $a1, $t8, $zero
  .L8001F1CC:
    /* 1FDCC 8001F1CC 3C088003 */  lui        $t0, %hi(D_800363AC)
    /* 1FDD0 8001F1D0 8D0863AC */  lw         $t0, %lo(D_800363AC)($t0)
    /* 1FDD4 8001F1D4 8FA90038 */  lw         $t1, 0x38($sp)
    /* 1FDD8 8001F1D8 15090005 */  bne        $t0, $t1, .L8001F1F0
    /* 1FDDC 8001F1DC 00000000 */   nop
    /* 1FDE0 8001F1E0 8D0A000C */  lw         $t2, 0xC($t0)
    /* 1FDE4 8001F1E4 3C018003 */  lui        $at, %hi(D_800363AC)
    /* 1FDE8 8001F1E8 10000010 */  b          .L8001F22C
    /* 1FDEC 8001F1EC AC2A63AC */   sw        $t2, %lo(D_800363AC)($at)
  .L8001F1F0:
    /* 1FDF0 8001F1F0 3C118003 */  lui        $s1, %hi(D_800363AC)
    /* 1FDF4 8001F1F4 8E3163AC */  lw         $s1, %lo(D_800363AC)($s1)
    /* 1FDF8 8001F1F8 8E32000C */  lw         $s2, 0xC($s1)
    /* 1FDFC 8001F1FC 1240000B */  beqz       $s2, .L8001F22C
    /* 1FE00 8001F200 00000000 */   nop
  .L8001F204:
    /* 1FE04 8001F204 8FAB0038 */  lw         $t3, 0x38($sp)
    /* 1FE08 8001F208 164B0004 */  bne        $s2, $t3, .L8001F21C
    /* 1FE0C 8001F20C 00000000 */   nop
    /* 1FE10 8001F210 8D6C000C */  lw         $t4, 0xC($t3)
    /* 1FE14 8001F214 10000005 */  b          .L8001F22C
    /* 1FE18 8001F218 AE2C000C */   sw        $t4, 0xC($s1)
  .L8001F21C:
    /* 1FE1C 8001F21C 02408825 */  or         $s1, $s2, $zero
    /* 1FE20 8001F220 8E32000C */  lw         $s2, 0xC($s1)
    /* 1FE24 8001F224 1640FFF7 */  bnez       $s2, .L8001F204
    /* 1FE28 8001F228 00000000 */   nop
  .L8001F22C:
    /* 1FE2C 8001F22C 3C0E8003 */  lui        $t6, %hi(D_800363B0)
    /* 1FE30 8001F230 8DCE63B0 */  lw         $t6, %lo(D_800363B0)($t6)
    /* 1FE34 8001F234 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 1FE38 8001F238 15AE0003 */  bne        $t5, $t6, .L8001F248
    /* 1FE3C 8001F23C 00000000 */   nop
    /* 1FE40 8001F240 0C008E09 */  jal        func_80023824
    /* 1FE44 8001F244 00000000 */   nop
  .L8001F248:
    /* 1FE48 8001F248 0C008E74 */  jal        func_800239D0
    /* 1FE4C 8001F24C 02002025 */   or        $a0, $s0, $zero
    /* 1FE50 8001F250 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 1FE54 8001F254 8FB00018 */  lw         $s0, 0x18($sp)
    /* 1FE58 8001F258 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 1FE5C 8001F25C 8FB20020 */  lw         $s2, 0x20($sp)
    /* 1FE60 8001F260 03E00008 */  jr         $ra
    /* 1FE64 8001F264 27BD0038 */   addiu     $sp, $sp, 0x38
    /* 1FE68 8001F268 00000000 */  nop
    /* 1FE6C 8001F26C 00000000 */  nop
