.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001F4D0
    /* 200D0 8001F4D0 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 200D4 8001F4D4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 200D8 8001F4D8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 200DC 8001F4DC 0C008E6C */  jal        func_800239B0
    /* 200E0 8001F4E0 AFB00018 */   sw        $s0, 0x18($sp)
    /* 200E4 8001F4E4 93AE002B */  lbu        $t6, 0x2B($sp)
    /* 200E8 8001F4E8 00408025 */  or         $s0, $v0, $zero
    /* 200EC 8001F4EC 11C00007 */  beqz       $t6, .L8001F50C
    /* 200F0 8001F4F0 00000000 */   nop
    /* 200F4 8001F4F4 3C0F8003 */  lui        $t7, %hi(D_80036734)
    /* 200F8 8001F4F8 8DEF6734 */  lw         $t7, %lo(D_80036734)($t7)
    /* 200FC 8001F4FC 95F80000 */  lhu        $t8, 0x0($t7)
    /* 20100 8001F500 37190020 */  ori        $t9, $t8, 0x20
    /* 20104 8001F504 10000007 */  b          .L8001F524
    /* 20108 8001F508 A5F90000 */   sh        $t9, 0x0($t7)
  .L8001F50C:
    /* 2010C 8001F50C 3C088003 */  lui        $t0, %hi(D_80036734)
    /* 20110 8001F510 8D086734 */  lw         $t0, %lo(D_80036734)($t0)
    /* 20114 8001F514 2401FFDF */  addiu      $at, $zero, -0x21
    /* 20118 8001F518 95090000 */  lhu        $t1, 0x0($t0)
    /* 2011C 8001F51C 01215024 */  and        $t2, $t1, $at
    /* 20120 8001F520 A50A0000 */  sh         $t2, 0x0($t0)
  .L8001F524:
    /* 20124 8001F524 0C008E74 */  jal        func_800239D0
    /* 20128 8001F528 02002025 */   or        $a0, $s0, $zero
    /* 2012C 8001F52C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 20130 8001F530 8FB00018 */  lw         $s0, 0x18($sp)
    /* 20134 8001F534 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 20138 8001F538 03E00008 */  jr         $ra
    /* 2013C 8001F53C 00000000 */   nop

/* Handwritten function */
glabel func_8001F540
    /* 20140 8001F540 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 20144 8001F544 03E00008 */  jr         $ra
    /* 20148 8001F548 00000000 */   nop
    /* 2014C 8001F54C 00000000 */  nop
