.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8001F820
    /* 20420 8001F820 00057400 */  sll        $t6, $a1, 16
    /* 20424 8001F824 000E7C03 */  sra        $t7, $t6, 16
    /* 20428 8001F828 AFA50004 */  sw         $a1, 0x4($sp)
    /* 2042C 8001F82C 03E00008 */  jr         $ra
    /* 20430 8001F830 AC8F003C */   sw        $t7, 0x3C($a0)
    /* 20434 8001F834 00000000 */  nop
    /* 20438 8001F838 00000000 */  nop
    /* 2043C 8001F83C 00000000 */  nop
