.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_80022F90
    /* 23B90 80022F90 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 23B94 80022F94 AFA5006C */  sw         $a1, 0x6C($sp)
    /* 23B98 80022F98 00802825 */  or         $a1, $a0, $zero
    /* 23B9C 80022F9C AFBF0024 */  sw         $ra, 0x24($sp)
    /* 23BA0 80022FA0 AFA40068 */  sw         $a0, 0x68($sp)
    /* 23BA4 80022FA4 AFA60070 */  sw         $a2, 0x70($sp)
    /* 23BA8 80022FA8 AFA70074 */  sw         $a3, 0x74($sp)
    /* 23BAC 80022FAC 0C00A012 */  jal        func_80028048
    /* 23BB0 80022FB0 27A40028 */   addiu     $a0, $sp, 0x28
    /* 23BB4 80022FB4 8FAE0078 */  lw         $t6, 0x78($sp)
    /* 23BB8 80022FB8 8FAF007C */  lw         $t7, 0x7C($sp)
    /* 23BBC 80022FBC 8FB80080 */  lw         $t8, 0x80($sp)
    /* 23BC0 80022FC0 27A40028 */  addiu      $a0, $sp, 0x28
    /* 23BC4 80022FC4 8FA5006C */  lw         $a1, 0x6C($sp)
    /* 23BC8 80022FC8 8FA60070 */  lw         $a2, 0x70($sp)
    /* 23BCC 80022FCC 8FA70074 */  lw         $a3, 0x74($sp)
    /* 23BD0 80022FD0 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 23BD4 80022FD4 AFAF0014 */  sw         $t7, 0x14($sp)
    /* 23BD8 80022FD8 0C008B60 */  jal        func_80022D80
    /* 23BDC 80022FDC AFB80018 */   sw        $t8, 0x18($sp)
    /* 23BE0 80022FE0 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 23BE4 80022FE4 27BD0068 */  addiu      $sp, $sp, 0x68
    /* 23BE8 80022FE8 03E00008 */  jr         $ra
    /* 23BEC 80022FEC 00000000 */   nop

glabel func_80022FF0
    /* 23BF0 80022FF0 27BDFF28 */  addiu      $sp, $sp, -0xD8
    /* 23BF4 80022FF4 AFA500DC */  sw         $a1, 0xDC($sp)
    /* 23BF8 80022FF8 00802825 */  or         $a1, $a0, $zero
    /* 23BFC 80022FFC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 23C00 80023000 AFA400D8 */  sw         $a0, 0xD8($sp)
    /* 23C04 80023004 AFA600E0 */  sw         $a2, 0xE0($sp)
    /* 23C08 80023008 0C00A012 */  jal        func_80028048
    /* 23C0C 8002300C 27A40098 */   addiu     $a0, $sp, 0x98
    /* 23C10 80023010 27A40058 */  addiu      $a0, $sp, 0x58
    /* 23C14 80023014 0C00A012 */  jal        func_80028048
    /* 23C18 80023018 8FA500DC */   lw        $a1, 0xDC($sp)
    /* 23C1C 8002301C 27A40098 */  addiu      $a0, $sp, 0x98
    /* 23C20 80023020 27A50058 */  addiu      $a1, $sp, 0x58
    /* 23C24 80023024 0C008B88 */  jal        func_80022E20
    /* 23C28 80023028 27A60018 */   addiu     $a2, $sp, 0x18
    /* 23C2C 8002302C 27A40018 */  addiu      $a0, $sp, 0x18
    /* 23C30 80023030 0C009FA4 */  jal        func_80027E90
    /* 23C34 80023034 8FA500E0 */   lw        $a1, 0xE0($sp)
    /* 23C38 80023038 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 23C3C 8002303C 27BD00D8 */  addiu      $sp, $sp, 0xD8
    /* 23C40 80023040 03E00008 */  jr         $ra
    /* 23C44 80023044 00000000 */   nop
    /* 23C48 80023048 00000000 */  nop
    /* 23C4C 8002304C 00000000 */  nop
