.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

/* Handwritten function */
glabel func_800239B0
    /* 245B0 800239B0 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 245B4 800239B4 2401FFFE */  addiu      $at, $zero, -0x2
    /* 245B8 800239B8 01014824 */  and        $t1, $t0, $at
    /* 245BC 800239BC 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 245C0 800239C0 31020001 */  andi       $v0, $t0, 0x1
    /* 245C4 800239C4 00000000 */  nop
    /* 245C8 800239C8 03E00008 */  jr         $ra
    /* 245CC 800239CC 00000000 */   nop

/* Handwritten function */
glabel func_800239D0
    /* 245D0 800239D0 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 245D4 800239D4 01044025 */  or         $t0, $t0, $a0
    /* 245D8 800239D8 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 245DC 800239DC 00000000 */  nop
    /* 245E0 800239E0 00000000 */  nop
    /* 245E4 800239E4 03E00008 */  jr         $ra
    /* 245E8 800239E8 00000000 */   nop
    /* 245EC 800239EC 00000000 */  nop
