.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_80027E90
    /* 28A90 80027E90 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* 28A94 80027E94 44810000 */  mtc1       $at, $fv0
    /* 28A98 80027E98 00A01025 */  or         $v0, $a1, $zero
    /* 28A9C 80027E9C 24A30020 */  addiu      $v1, $a1, 0x20
    /* 28AA0 80027EA0 00003025 */  or         $a2, $zero, $zero
    /* 28AA4 80027EA4 00803825 */  or         $a3, $a0, $zero
    /* 28AA8 80027EA8 240C0004 */  addiu      $t4, $zero, 0x4
    /* 28AAC 80027EAC 240B0002 */  addiu      $t3, $zero, 0x2
    /* 28AB0 80027EB0 3C0AFFFF */  lui        $t2, (0xFFFF0000 >> 16)
  .L80027EB4:
    /* 28AB4 80027EB4 00002025 */  or         $a0, $zero, $zero
    /* 28AB8 80027EB8 00E04025 */  or         $t0, $a3, $zero
    /* 28ABC 80027EBC C50E0004 */  lwc1       $fa1, 0x4($t0)
    /* 28AC0 80027EC0 24840001 */  addiu      $a0, $a0, 0x1
    /* 28AC4 80027EC4 C5120000 */  lwc1       $ft5, 0x0($t0)
    /* 28AC8 80027EC8 46007402 */  mul.s      $ft4, $fa1, $fv0
    /* 28ACC 80027ECC 108B0019 */  beq        $a0, $t3, .L80027F34
    /* 28AD0 80027ED0 00000000 */   nop
  .L80027ED4:
    /* 28AD4 80027ED4 46009382 */  mul.s      $fa1, $ft5, $fv0
    /* 28AD8 80027ED8 24840001 */  addiu      $a0, $a0, 0x1
    /* 28ADC 80027EDC 24420004 */  addiu      $v0, $v0, 0x4
    /* 28AE0 80027EE0 24630004 */  addiu      $v1, $v1, 0x4
    /* 28AE4 80027EE4 25080008 */  addiu      $t0, $t0, 0x8
    /* 28AE8 80027EE8 4600830D */  trunc.w.s  $fa0, $ft4
    /* 28AEC 80027EEC 4600738D */  trunc.w.s  $fa1, $fa1
    /* 28AF0 80027EF0 44096000 */  mfc1       $t1, $fa0
    /* 28AF4 80027EF4 44057000 */  mfc1       $a1, $fa1
    /* 28AF8 80027EF8 0009CC03 */  sra        $t9, $t1, 16
    /* 28AFC 80027EFC 332DFFFF */  andi       $t5, $t9, 0xFFFF
    /* 28B00 80027F00 00AAC024 */  and        $t8, $a1, $t2
    /* 28B04 80027F04 030D7025 */  or         $t6, $t8, $t5
    /* 28B08 80027F08 00057C00 */  sll        $t7, $a1, 16
    /* 28B0C 80027F0C 01EAC824 */  and        $t9, $t7, $t2
    /* 28B10 80027F10 AC4EFFFC */  sw         $t6, -0x4($v0)
    /* 28B14 80027F14 3138FFFF */  andi       $t8, $t1, 0xFFFF
    /* 28B18 80027F18 03386825 */  or         $t5, $t9, $t8
    /* 28B1C 80027F1C AC6DFFFC */  sw         $t5, -0x4($v1)
    /* 28B20 80027F20 C50E0004 */  lwc1       $fa1, 0x4($t0)
    /* 28B24 80027F24 C5120000 */  lwc1       $ft5, 0x0($t0)
    /* 28B28 80027F28 46007402 */  mul.s      $ft4, $fa1, $fv0
    /* 28B2C 80027F2C 148BFFE9 */  bne        $a0, $t3, .L80027ED4
    /* 28B30 80027F30 00000000 */   nop
  .L80027F34:
    /* 28B34 80027F34 46009382 */  mul.s      $fa1, $ft5, $fv0
    /* 28B38 80027F38 25080008 */  addiu      $t0, $t0, 0x8
    /* 28B3C 80027F3C 24420004 */  addiu      $v0, $v0, 0x4
    /* 28B40 80027F40 24630004 */  addiu      $v1, $v1, 0x4
    /* 28B44 80027F44 4600830D */  trunc.w.s  $fa0, $ft4
    /* 28B48 80027F48 4600738D */  trunc.w.s  $fa1, $fa1
    /* 28B4C 80027F4C 44096000 */  mfc1       $t1, $fa0
    /* 28B50 80027F50 44057000 */  mfc1       $a1, $fa1
    /* 28B54 80027F54 0009CC03 */  sra        $t9, $t1, 16
    /* 28B58 80027F58 332DFFFF */  andi       $t5, $t9, 0xFFFF
    /* 28B5C 80027F5C 00AAC024 */  and        $t8, $a1, $t2
    /* 28B60 80027F60 030D7025 */  or         $t6, $t8, $t5
    /* 28B64 80027F64 00057C00 */  sll        $t7, $a1, 16
    /* 28B68 80027F68 01EAC824 */  and        $t9, $t7, $t2
    /* 28B6C 80027F6C 3138FFFF */  andi       $t8, $t1, 0xFFFF
    /* 28B70 80027F70 AC4EFFFC */  sw         $t6, -0x4($v0)
    /* 28B74 80027F74 03386825 */  or         $t5, $t9, $t8
    /* 28B78 80027F78 AC6DFFFC */  sw         $t5, -0x4($v1)
    /* 28B7C 80027F7C 24C60001 */  addiu      $a2, $a2, 0x1
    /* 28B80 80027F80 14CCFFCC */  bne        $a2, $t4, .L80027EB4
    /* 28B84 80027F84 24E70010 */   addiu     $a3, $a3, 0x10
    /* 28B88 80027F88 03E00008 */  jr         $ra
    /* 28B8C 80027F8C 00000000 */   nop

glabel func_80027F90
    /* 28B90 80027F90 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 28B94 80027F94 00801825 */  or         $v1, $a0, $zero
    /* 28B98 80027F98 44810000 */  mtc1       $at, $fv0
    /* 28B9C 80027F9C 44801000 */  mtc1       $zero, $fv1
    /* 28BA0 80027FA0 24040001 */  addiu      $a0, $zero, 0x1
    /* 28BA4 80027FA4 00001025 */  or         $v0, $zero, $zero
    /* 28BA8 80027FA8 24070004 */  addiu      $a3, $zero, 0x4
    /* 28BAC 80027FAC 24060003 */  addiu      $a2, $zero, 0x3
    /* 28BB0 80027FB0 24050002 */  addiu      $a1, $zero, 0x2
  .L80027FB4:
    /* 28BB4 80027FB4 54400004 */  bnel       $v0, $zero, .L80027FC8
    /* 28BB8 80027FB8 E4620000 */   swc1      $fv1, 0x0($v1)
    /* 28BBC 80027FBC 10000002 */  b          .L80027FC8
    /* 28BC0 80027FC0 E4600000 */   swc1      $fv0, 0x0($v1)
    /* 28BC4 80027FC4 E4620000 */  swc1       $fv1, 0x0($v1)
  .L80027FC8:
    /* 28BC8 80027FC8 54440004 */  bnel       $v0, $a0, .L80027FDC
    /* 28BCC 80027FCC E4620004 */   swc1      $fv1, 0x4($v1)
    /* 28BD0 80027FD0 10000002 */  b          .L80027FDC
    /* 28BD4 80027FD4 E4600004 */   swc1      $fv0, 0x4($v1)
    /* 28BD8 80027FD8 E4620004 */  swc1       $fv1, 0x4($v1)
  .L80027FDC:
    /* 28BDC 80027FDC 54450004 */  bnel       $v0, $a1, .L80027FF0
    /* 28BE0 80027FE0 E4620008 */   swc1      $fv1, 0x8($v1)
    /* 28BE4 80027FE4 10000002 */  b          .L80027FF0
    /* 28BE8 80027FE8 E4600008 */   swc1      $fv0, 0x8($v1)
    /* 28BEC 80027FEC E4620008 */  swc1       $fv1, 0x8($v1)
  .L80027FF0:
    /* 28BF0 80027FF0 54460004 */  bnel       $v0, $a2, .L80028004
    /* 28BF4 80027FF4 E462000C */   swc1      $fv1, 0xC($v1)
    /* 28BF8 80027FF8 10000002 */  b          .L80028004
    /* 28BFC 80027FFC E460000C */   swc1      $fv0, 0xC($v1)
    /* 28C00 80028000 E462000C */  swc1       $fv1, 0xC($v1)
  .L80028004:
    /* 28C04 80028004 24420001 */  addiu      $v0, $v0, 0x1
    /* 28C08 80028008 1447FFEA */  bne        $v0, $a3, .L80027FB4
    /* 28C0C 8002800C 24630010 */   addiu     $v1, $v1, 0x10
    /* 28C10 80028010 03E00008 */  jr         $ra
    /* 28C14 80028014 00000000 */   nop

glabel func_80028018
    /* 28C18 80028018 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 28C1C 8002801C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 28C20 80028020 AFA40058 */  sw         $a0, 0x58($sp)
    /* 28C24 80028024 0C009FE4 */  jal        func_80027F90
    /* 28C28 80028028 27A40018 */   addiu     $a0, $sp, 0x18
    /* 28C2C 8002802C 27A40018 */  addiu      $a0, $sp, 0x18
    /* 28C30 80028030 0C009FA4 */  jal        func_80027E90
    /* 28C34 80028034 8FA50058 */   lw        $a1, 0x58($sp)
    /* 28C38 80028038 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 28C3C 8002803C 27BD0058 */  addiu      $sp, $sp, 0x58
    /* 28C40 80028040 03E00008 */  jr         $ra
    /* 28C44 80028044 00000000 */   nop

glabel func_80028048
    /* 28C48 80028048 3C014780 */  lui        $at, (0x47800000 >> 16)
    /* 28C4C 8002804C 44810000 */  mtc1       $at, $fv0
    /* 28C50 80028050 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 28C54 80028054 00A01025 */  or         $v0, $a1, $zero
    /* 28C58 80028058 24A30020 */  addiu      $v1, $a1, 0x20
    /* 28C5C 8002805C 00003025 */  or         $a2, $zero, $zero
    /* 28C60 80028060 00804025 */  or         $t0, $a0, $zero
    /* 28C64 80028064 240C0004 */  addiu      $t4, $zero, 0x4
    /* 28C68 80028068 240B0002 */  addiu      $t3, $zero, 0x2
    /* 28C6C 8002806C 3C0AFFFF */  lui        $t2, (0xFFFF0000 >> 16)
  .L80028070:
    /* 28C70 80028070 00002025 */  or         $a0, $zero, $zero
    /* 28C74 80028074 01004825 */  or         $t1, $t0, $zero
  .L80028078:
    /* 28C78 80028078 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 28C7C 8002807C 8C590000 */  lw         $t9, 0x0($v0)
    /* 28C80 80028080 24840001 */  addiu      $a0, $a0, 0x1
    /* 28C84 80028084 000E7C02 */  srl        $t7, $t6, 16
    /* 28C88 80028088 31F8FFFF */  andi       $t8, $t7, 0xFFFF
    /* 28C8C 8002808C 032A6824 */  and        $t5, $t9, $t2
    /* 28C90 80028090 030D7025 */  or         $t6, $t8, $t5
    /* 28C94 80028094 AFAE0004 */  sw         $t6, 0x4($sp)
    /* 28C98 80028098 8C6F0000 */  lw         $t7, 0x0($v1)
    /* 28C9C 8002809C 8C580000 */  lw         $t8, 0x0($v0)
    /* 28CA0 800280A0 8FA50004 */  lw         $a1, 0x4($sp)
    /* 28CA4 800280A4 31F9FFFF */  andi       $t9, $t7, 0xFFFF
    /* 28CA8 800280A8 00186C00 */  sll        $t5, $t8, 16
    /* 28CAC 800280AC 44859000 */  mtc1       $a1, $ft5
    /* 28CB0 800280B0 01AA7024 */  and        $t6, $t5, $t2
    /* 28CB4 800280B4 032E3825 */  or         $a3, $t9, $t6
    /* 28CB8 800280B8 468094A0 */  cvt.s.w    $ft5, $ft5
    /* 28CBC 800280BC 44878000 */  mtc1       $a3, $ft4
    /* 28CC0 800280C0 AFA70000 */  sw         $a3, 0x0($sp)
    /* 28CC4 800280C4 24420004 */  addiu      $v0, $v0, 0x4
    /* 28CC8 800280C8 24630004 */  addiu      $v1, $v1, 0x4
    /* 28CCC 800280CC 46808420 */  cvt.s.w    $ft4, $ft4
    /* 28CD0 800280D0 25290008 */  addiu      $t1, $t1, 0x8
    /* 28CD4 800280D4 46009483 */  div.s      $ft5, $ft5, $fv0
    /* 28CD8 800280D8 46008403 */  div.s      $ft4, $ft4, $fv0
    /* 28CDC 800280DC E532FFF8 */  swc1       $ft5, -0x8($t1)
    /* 28CE0 800280E0 148BFFE5 */  bne        $a0, $t3, .L80028078
    /* 28CE4 800280E4 E530FFFC */   swc1      $ft4, -0x4($t1)
    /* 28CE8 800280E8 24C60001 */  addiu      $a2, $a2, 0x1
    /* 28CEC 800280EC 14CCFFE0 */  bne        $a2, $t4, .L80028070
    /* 28CF0 800280F0 25080010 */   addiu     $t0, $t0, 0x10
    /* 28CF4 800280F4 03E00008 */  jr         $ra
    /* 28CF8 800280F8 27BD0010 */   addiu     $sp, $sp, 0x10
    /* 28CFC 800280FC 00000000 */  nop
