.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_800281B0
    /* 28DB0 800281B0 4442F800 */  cfc1       $v0, $31
    /* 28DB4 800281B4 44C4F800 */  ctc1       $a0, $31
    /* 28DB8 800281B8 03E00008 */  jr         $ra
    /* 28DBC 800281BC 00000000 */   nop

glabel func_800281C0
    /* 28DC0 800281C0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 28DC4 800281C4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 28DC8 800281C8 AFA40018 */  sw         $a0, 0x18($sp)
    /* 28DCC 800281CC 0C00B53C */  jal        func_8002D4F0
    /* 28DD0 800281D0 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 28DD4 800281D4 10400003 */  beqz       $v0, .L800281E4
    /* 28DD8 800281D8 00000000 */   nop
    /* 28DDC 800281DC 10000008 */  b          .L80028200
    /* 28DE0 800281E0 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800281E4:
    /* 28DE4 800281E4 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 28DE8 800281E8 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 28DEC 800281EC 8FB9001C */  lw         $t9, 0x1C($sp)
    /* 28DF0 800281F0 01C17825 */  or         $t7, $t6, $at
    /* 28DF4 800281F4 8DF80000 */  lw         $t8, %lo(D_A0000000)($t7)
    /* 28DF8 800281F8 00001025 */  or         $v0, $zero, $zero
    /* 28DFC 800281FC AF380000 */  sw         $t8, 0x0($t9)
  .L80028200:
    /* 28E00 80028200 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 28E04 80028204 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 28E08 80028208 03E00008 */  jr         $ra
    /* 28E0C 8002820C 00000000 */   nop

glabel func_80028210
    /* 28E10 80028210 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 28E14 80028214 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 28E18 80028218 AFA40018 */  sw         $a0, 0x18($sp)
    /* 28E1C 8002821C 0C00B53C */  jal        func_8002D4F0
    /* 28E20 80028220 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 28E24 80028224 10400003 */  beqz       $v0, .L80028234
    /* 28E28 80028228 00000000 */   nop
    /* 28E2C 8002822C 10000007 */  b          .L8002824C
    /* 28E30 80028230 2402FFFF */   addiu     $v0, $zero, -0x1
  .L80028234:
    /* 28E34 80028234 8FAF0018 */  lw         $t7, 0x18($sp)
    /* 28E38 80028238 8FAE001C */  lw         $t6, 0x1C($sp)
    /* 28E3C 8002823C 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 28E40 80028240 01E1C025 */  or         $t8, $t7, $at
    /* 28E44 80028244 00001025 */  or         $v0, $zero, $zero
    /* 28E48 80028248 AF0E0000 */  sw         $t6, %lo(D_A0000000)($t8)
  .L8002824C:
    /* 28E4C 8002824C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 28E50 80028250 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 28E54 80028254 03E00008 */  jr         $ra
    /* 28E58 80028258 00000000 */   nop
    /* 28E5C 8002825C 00000000 */  nop
