.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002B000
    /* 2BC00 8002B000 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 2BC04 8002B004 AFB30020 */  sw         $s3, 0x20($sp)
    /* 2BC08 8002B008 00059C00 */  sll        $s3, $a1, 16
    /* 2BC0C 8002B00C AFB2001C */  sw         $s2, 0x1C($sp)
    /* 2BC10 8002B010 00809025 */  or         $s2, $a0, $zero
    /* 2BC14 8002B014 00137403 */  sra        $t6, $s3, 16
    /* 2BC18 8002B018 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2BC1C 8002B01C 01C09825 */  or         $s3, $t6, $zero
    /* 2BC20 8002B020 AFB10018 */  sw         $s1, 0x18($sp)
    /* 2BC24 8002B024 AFB00014 */  sw         $s0, 0x14($sp)
    /* 2BC28 8002B028 AFA50044 */  sw         $a1, 0x44($sp)
    /* 2BC2C 8002B02C 0C008E7C */  jal        func_800239F0
    /* 2BC30 8002B030 24040001 */   addiu     $a0, $zero, 0x1
    /* 2BC34 8002B034 AFA2002C */  sw         $v0, 0x2C($sp)
    /* 2BC38 8002B038 8E500008 */  lw         $s0, 0x8($s2)
    /* 2BC3C 8002B03C 12000012 */  beqz       $s0, .L8002B088
    /* 2BC40 8002B040 00000000 */   nop
  .L8002B044:
    /* 2BC44 8002B044 860F000C */  lh         $t7, 0xC($s0)
    /* 2BC48 8002B048 8E110000 */  lw         $s1, 0x0($s0)
    /* 2BC4C 8002B04C 166F000C */  bne        $s3, $t7, .L8002B080
    /* 2BC50 8002B050 00000000 */   nop
    /* 2BC54 8002B054 12200005 */  beqz       $s1, .L8002B06C
    /* 2BC58 8002B058 00000000 */   nop
    /* 2BC5C 8002B05C 8E380008 */  lw         $t8, 0x8($s1)
    /* 2BC60 8002B060 8E190008 */  lw         $t9, 0x8($s0)
    /* 2BC64 8002B064 03194021 */  addu       $t0, $t8, $t9
    /* 2BC68 8002B068 AE280008 */  sw         $t0, 0x8($s1)
  .L8002B06C:
    /* 2BC6C 8002B06C 0C006B50 */  jal        func_8001AD40
    /* 2BC70 8002B070 02002025 */   or        $a0, $s0, $zero
    /* 2BC74 8002B074 02002025 */  or         $a0, $s0, $zero
    /* 2BC78 8002B078 0C006B5C */  jal        func_8001AD70
    /* 2BC7C 8002B07C 02402825 */   or        $a1, $s2, $zero
  .L8002B080:
    /* 2BC80 8002B080 1620FFF0 */  bnez       $s1, .L8002B044
    /* 2BC84 8002B084 02208025 */   or        $s0, $s1, $zero
  .L8002B088:
    /* 2BC88 8002B088 0C008E7C */  jal        func_800239F0
    /* 2BC8C 8002B08C 8FA4002C */   lw        $a0, 0x2C($sp)
    /* 2BC90 8002B090 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2BC94 8002B094 8FB00014 */  lw         $s0, 0x14($sp)
    /* 2BC98 8002B098 8FB10018 */  lw         $s1, 0x18($sp)
    /* 2BC9C 8002B09C 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 2BCA0 8002B0A0 8FB30020 */  lw         $s3, 0x20($sp)
    /* 2BCA4 8002B0A4 03E00008 */  jr         $ra
    /* 2BCA8 8002B0A8 27BD0040 */   addiu     $sp, $sp, 0x40

glabel func_8002B0AC
    /* 2BCAC 8002B0AC 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 2BCB0 8002B0B0 AFB20020 */  sw         $s2, 0x20($sp)
    /* 2BCB4 8002B0B4 00809025 */  or         $s2, $a0, $zero
    /* 2BCB8 8002B0B8 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2BCBC 8002B0BC AFB1001C */  sw         $s1, 0x1C($sp)
    /* 2BCC0 8002B0C0 AFB00018 */  sw         $s0, 0x18($sp)
    /* 2BCC4 8002B0C4 0C008E7C */  jal        func_800239F0
    /* 2BCC8 8002B0C8 24040001 */   addiu     $a0, $zero, 0x1
    /* 2BCCC 8002B0CC AFA2002C */  sw         $v0, 0x2C($sp)
    /* 2BCD0 8002B0D0 8E500008 */  lw         $s0, 0x8($s2)
    /* 2BCD4 8002B0D4 12000009 */  beqz       $s0, .L8002B0FC
    /* 2BCD8 8002B0D8 00000000 */   nop
  .L8002B0DC:
    /* 2BCDC 8002B0DC 8E110000 */  lw         $s1, 0x0($s0)
    /* 2BCE0 8002B0E0 0C006B50 */  jal        func_8001AD40
    /* 2BCE4 8002B0E4 02002025 */   or        $a0, $s0, $zero
    /* 2BCE8 8002B0E8 02002025 */  or         $a0, $s0, $zero
    /* 2BCEC 8002B0EC 0C006B5C */  jal        func_8001AD70
    /* 2BCF0 8002B0F0 02402825 */   or        $a1, $s2, $zero
    /* 2BCF4 8002B0F4 1620FFF9 */  bnez       $s1, .L8002B0DC
    /* 2BCF8 8002B0F8 02208025 */   or        $s0, $s1, $zero
  .L8002B0FC:
    /* 2BCFC 8002B0FC 0C008E7C */  jal        func_800239F0
    /* 2BD00 8002B100 8FA4002C */   lw        $a0, 0x2C($sp)
    /* 2BD04 8002B104 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2BD08 8002B108 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2BD0C 8002B10C 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 2BD10 8002B110 8FB20020 */  lw         $s2, 0x20($sp)
    /* 2BD14 8002B114 03E00008 */  jr         $ra
    /* 2BD18 8002B118 27BD0038 */   addiu     $sp, $sp, 0x38

glabel func_8002B11C
    /* 2BD1C 8002B11C 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 2BD20 8002B120 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2BD24 8002B124 AFA40030 */  sw         $a0, 0x30($sp)
    /* 2BD28 8002B128 AFA50034 */  sw         $a1, 0x34($sp)
    /* 2BD2C 8002B12C AFA00020 */  sw         $zero, 0x20($sp)
    /* 2BD30 8002B130 24040001 */  addiu      $a0, $zero, 0x1
    /* 2BD34 8002B134 0C008E7C */  jal        func_800239F0
    /* 2BD38 8002B138 AFA60038 */   sw        $a2, 0x38($sp)
    /* 2BD3C 8002B13C 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 2BD40 8002B140 8FA70038 */  lw         $a3, 0x38($sp)
    /* 2BD44 8002B144 00402825 */  or         $a1, $v0, $zero
    /* 2BD48 8002B148 8DC80000 */  lw         $t0, 0x0($t6)
    /* 2BD4C 8002B14C 15000005 */  bnez       $t0, .L8002B164
    /* 2BD50 8002B150 01002025 */   or        $a0, $t0, $zero
    /* 2BD54 8002B154 0C008E7C */  jal        func_800239F0
    /* 2BD58 8002B158 00402025 */   or        $a0, $v0, $zero
    /* 2BD5C 8002B15C 10000035 */  b          .L8002B234
    /* 2BD60 8002B160 8FBF0014 */   lw        $ra, 0x14($sp)
  .L8002B164:
    /* 2BD64 8002B164 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 2BD68 8002B168 AFA70038 */  sw         $a3, 0x38($sp)
    /* 2BD6C 8002B16C 0C006B50 */  jal        func_8001AD40
    /* 2BD70 8002B170 AFA8002C */   sw        $t0, 0x2C($sp)
    /* 2BD74 8002B174 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 2BD78 8002B178 8FA40034 */  lw         $a0, 0x34($sp)
    /* 2BD7C 8002B17C 24060010 */  addiu      $a2, $zero, 0x10
    /* 2BD80 8002B180 0C00B51C */  jal        func_8002D470
    /* 2BD84 8002B184 2505000C */   addiu     $a1, $t0, 0xC
    /* 2BD88 8002B188 8FA70038 */  lw         $a3, 0x38($sp)
    /* 2BD8C 8002B18C 3C017FFF */  lui        $at, (0x7FFFFFFF >> 16)
    /* 2BD90 8002B190 3421FFFF */  ori        $at, $at, (0x7FFFFFFF & 0xFFFF)
    /* 2BD94 8002B194 14E10003 */  bne        $a3, $at, .L8002B1A4
    /* 2BD98 8002B198 8FA8002C */   lw        $t0, 0x2C($sp)
    /* 2BD9C 8002B19C 240FFFFF */  addiu      $t7, $zero, -0x1
    /* 2BDA0 8002B1A0 AFAF0020 */  sw         $t7, 0x20($sp)
  .L8002B1A4:
    /* 2BDA4 8002B1A4 8FA20030 */  lw         $v0, 0x30($sp)
    /* 2BDA8 8002B1A8 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 2BDAC 8002B1AC 8FB80020 */  lw         $t8, 0x20($sp)
    /* 2BDB0 8002B1B0 1041001D */  beq        $v0, $at, .L8002B228
    /* 2BDB4 8002B1B4 24450008 */   addiu     $a1, $v0, 0x8
  .L8002B1B8:
    /* 2BDB8 8002B1B8 8CA20000 */  lw         $v0, 0x0($a1)
    /* 2BDBC 8002B1BC 5440000B */  bnel       $v0, $zero, .L8002B1EC
    /* 2BDC0 8002B1C0 8C430008 */   lw        $v1, 0x8($v0)
    /* 2BDC4 8002B1C4 53000004 */  beql       $t8, $zero, .L8002B1D8
    /* 2BDC8 8002B1C8 AD070008 */   sw        $a3, 0x8($t0)
    /* 2BDCC 8002B1CC 10000002 */  b          .L8002B1D8
    /* 2BDD0 8002B1D0 AD000008 */   sw        $zero, 0x8($t0)
    /* 2BDD4 8002B1D4 AD070008 */  sw         $a3, 0x8($t0)
  .L8002B1D8:
    /* 2BDD8 8002B1D8 0C006B5C */  jal        func_8001AD70
    /* 2BDDC 8002B1DC 01002025 */   or        $a0, $t0, $zero
    /* 2BDE0 8002B1E0 10000011 */  b          .L8002B228
    /* 2BDE4 8002B1E4 00000000 */   nop
    /* 2BDE8 8002B1E8 8C430008 */  lw         $v1, 0x8($v0)
  .L8002B1EC:
    /* 2BDEC 8002B1EC 00403025 */  or         $a2, $v0, $zero
    /* 2BDF0 8002B1F0 00E3082A */  slt        $at, $a3, $v1
    /* 2BDF4 8002B1F4 5020000A */  beql       $at, $zero, .L8002B220
    /* 2BDF8 8002B1F8 00402825 */   or        $a1, $v0, $zero
    /* 2BDFC 8002B1FC AD070008 */  sw         $a3, 0x8($t0)
    /* 2BE00 8002B200 8CD90008 */  lw         $t9, 0x8($a2)
    /* 2BE04 8002B204 01002025 */  or         $a0, $t0, $zero
    /* 2BE08 8002B208 03274823 */  subu       $t1, $t9, $a3
    /* 2BE0C 8002B20C 0C006B5C */  jal        func_8001AD70
    /* 2BE10 8002B210 ACC90008 */   sw        $t1, 0x8($a2)
    /* 2BE14 8002B214 10000004 */  b          .L8002B228
    /* 2BE18 8002B218 00000000 */   nop
    /* 2BE1C 8002B21C 00402825 */  or         $a1, $v0, $zero
  .L8002B220:
    /* 2BE20 8002B220 1440FFE5 */  bnez       $v0, .L8002B1B8
    /* 2BE24 8002B224 00E33823 */   subu      $a3, $a3, $v1
  .L8002B228:
    /* 2BE28 8002B228 0C008E7C */  jal        func_800239F0
    /* 2BE2C 8002B22C 8FA4001C */   lw        $a0, 0x1C($sp)
    /* 2BE30 8002B230 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002B234:
    /* 2BE34 8002B234 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 2BE38 8002B238 03E00008 */  jr         $ra
    /* 2BE3C 8002B23C 00000000 */   nop

glabel func_8002B240
    /* 2BE40 8002B240 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 2BE44 8002B244 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2BE48 8002B248 AFA40030 */  sw         $a0, 0x30($sp)
    /* 2BE4C 8002B24C AFB00018 */  sw         $s0, 0x18($sp)
    /* 2BE50 8002B250 AFA50034 */  sw         $a1, 0x34($sp)
    /* 2BE54 8002B254 0C008E7C */  jal        func_800239F0
    /* 2BE58 8002B258 24040001 */   addiu     $a0, $zero, 0x1
    /* 2BE5C 8002B25C 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 2BE60 8002B260 AFA20024 */  sw         $v0, 0x24($sp)
    /* 2BE64 8002B264 8FB80034 */  lw         $t8, 0x34($sp)
    /* 2BE68 8002B268 8DD00008 */  lw         $s0, 0x8($t6)
    /* 2BE6C 8002B26C 00001825 */  or         $v1, $zero, $zero
    /* 2BE70 8002B270 5200000D */  beql       $s0, $zero, .L8002B2A8
    /* 2BE74 8002B274 240FFFFF */   addiu     $t7, $zero, -0x1
    /* 2BE78 8002B278 0C006B50 */  jal        func_8001AD40
    /* 2BE7C 8002B27C 02002025 */   or        $a0, $s0, $zero
    /* 2BE80 8002B280 2604000C */  addiu      $a0, $s0, 0xC
    /* 2BE84 8002B284 8FA50034 */  lw         $a1, 0x34($sp)
    /* 2BE88 8002B288 0C00B51C */  jal        func_8002D470
    /* 2BE8C 8002B28C 24060010 */   addiu     $a2, $zero, 0x10
    /* 2BE90 8002B290 02002025 */  or         $a0, $s0, $zero
    /* 2BE94 8002B294 0C006B5C */  jal        func_8001AD70
    /* 2BE98 8002B298 8FA50030 */   lw        $a1, 0x30($sp)
    /* 2BE9C 8002B29C 10000003 */  b          .L8002B2AC
    /* 2BEA0 8002B2A0 8E030008 */   lw        $v1, 0x8($s0)
    /* 2BEA4 8002B2A4 240FFFFF */  addiu      $t7, $zero, -0x1
  .L8002B2A8:
    /* 2BEA8 8002B2A8 A70F0000 */  sh         $t7, 0x0($t8)
  .L8002B2AC:
    /* 2BEAC 8002B2AC 8FA40024 */  lw         $a0, 0x24($sp)
    /* 2BEB0 8002B2B0 0C008E7C */  jal        func_800239F0
    /* 2BEB4 8002B2B4 AFA30028 */   sw        $v1, 0x28($sp)
    /* 2BEB8 8002B2B8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2BEBC 8002B2BC 8FA20028 */  lw         $v0, 0x28($sp)
    /* 2BEC0 8002B2C0 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2BEC4 8002B2C4 03E00008 */  jr         $ra
    /* 2BEC8 8002B2C8 27BD0030 */   addiu     $sp, $sp, 0x30

glabel func_8002B2CC
    /* 2BECC 8002B2CC 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 2BED0 8002B2D0 AFB30020 */  sw         $s3, 0x20($sp)
    /* 2BED4 8002B2D4 AFB2001C */  sw         $s2, 0x1C($sp)
    /* 2BED8 8002B2D8 AFB00014 */  sw         $s0, 0x14($sp)
    /* 2BEDC 8002B2DC AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2BEE0 8002B2E0 AFB10018 */  sw         $s1, 0x18($sp)
    /* 2BEE4 8002B2E4 00809025 */  or         $s2, $a0, $zero
    /* 2BEE8 8002B2E8 00C09825 */  or         $s3, $a2, $zero
    /* 2BEEC 8002B2EC AC800010 */  sw         $zero, 0x10($a0)
    /* 2BEF0 8002B2F0 AC800008 */  sw         $zero, 0x8($a0)
    /* 2BEF4 8002B2F4 AC80000C */  sw         $zero, 0xC($a0)
    /* 2BEF8 8002B2F8 AC800000 */  sw         $zero, 0x0($a0)
    /* 2BEFC 8002B2FC AC800004 */  sw         $zero, 0x4($a0)
    /* 2BF00 8002B300 18C00008 */  blez       $a2, .L8002B324
    /* 2BF04 8002B304 00008025 */   or        $s0, $zero, $zero
    /* 2BF08 8002B308 00A08825 */  or         $s1, $a1, $zero
  .L8002B30C:
    /* 2BF0C 8002B30C 02202025 */  or         $a0, $s1, $zero
    /* 2BF10 8002B310 0C006B5C */  jal        func_8001AD70
    /* 2BF14 8002B314 02402825 */   or        $a1, $s2, $zero
    /* 2BF18 8002B318 26100001 */  addiu      $s0, $s0, 0x1
    /* 2BF1C 8002B31C 1613FFFB */  bne        $s0, $s3, .L8002B30C
    /* 2BF20 8002B320 2631001C */   addiu     $s1, $s1, 0x1C
  .L8002B324:
    /* 2BF24 8002B324 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2BF28 8002B328 8FB00014 */  lw         $s0, 0x14($sp)
    /* 2BF2C 8002B32C 8FB10018 */  lw         $s1, 0x18($sp)
    /* 2BF30 8002B330 8FB2001C */  lw         $s2, 0x1C($sp)
    /* 2BF34 8002B334 8FB30020 */  lw         $s3, 0x20($sp)
    /* 2BF38 8002B338 03E00008 */  jr         $ra
    /* 2BF3C 8002B33C 27BD0028 */   addiu     $sp, $sp, 0x28

glabel func_8002B340
    /* 2BF40 8002B340 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2BF44 8002B344 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2BF48 8002B348 00803025 */  or         $a2, $a0, $zero
    /* 2BF4C 8002B34C AFA60018 */  sw         $a2, 0x18($sp)
    /* 2BF50 8002B350 24040001 */  addiu      $a0, $zero, 0x1
    /* 2BF54 8002B354 0C008E7C */  jal        func_800239F0
    /* 2BF58 8002B358 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 2BF5C 8002B35C 8FA60018 */  lw         $a2, 0x18($sp)
    /* 2BF60 8002B360 8FA5001C */  lw         $a1, 0x1C($sp)
    /* 2BF64 8002B364 00402025 */  or         $a0, $v0, $zero
    /* 2BF68 8002B368 8CCE0020 */  lw         $t6, 0x20($a2)
    /* 2BF6C 8002B36C ACAE0010 */  sw         $t6, 0x10($a1)
    /* 2BF70 8002B370 8CCF0000 */  lw         $t7, 0x0($a2)
    /* 2BF74 8002B374 ACAF0000 */  sw         $t7, 0x0($a1)
    /* 2BF78 8002B378 0C008E7C */  jal        func_800239F0
    /* 2BF7C 8002B37C ACC50000 */   sw        $a1, 0x0($a2)
    /* 2BF80 8002B380 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2BF84 8002B384 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2BF88 8002B388 03E00008 */  jr         $ra
    /* 2BF8C 8002B38C 00000000 */   nop

glabel func_8002B390
    /* 2BF90 8002B390 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2BF94 8002B394 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2BF98 8002B398 AFA40018 */  sw         $a0, 0x18($sp)
    /* 2BF9C 8002B39C 8CAE0008 */  lw         $t6, 0x8($a1)
    /* 2BFA0 8002B3A0 51C00016 */  beql       $t6, $zero, .L8002B3FC
    /* 2BFA4 8002B3A4 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 2BFA8 8002B3A8 0C006F80 */  jal        func_8001BE00
    /* 2BFAC 8002B3AC AFA5001C */   sw        $a1, 0x1C($sp)
    /* 2BFB0 8002B3B0 8FA7001C */  lw         $a3, 0x1C($sp)
    /* 2BFB4 8002B3B4 10400010 */  beqz       $v0, .L8002B3F8
    /* 2BFB8 8002B3B8 00403025 */   or        $a2, $v0, $zero
    /* 2BFBC 8002B3BC 8FAF0018 */  lw         $t7, 0x18($sp)
    /* 2BFC0 8002B3C0 8CF90008 */  lw         $t9, 0x8($a3)
    /* 2BFC4 8002B3C4 240A000F */  addiu      $t2, $zero, 0xF
    /* 2BFC8 8002B3C8 8DF8001C */  lw         $t8, 0x1C($t7)
    /* 2BFCC 8002B3CC 8F2800D8 */  lw         $t0, 0xD8($t9)
    /* 2BFD0 8002B3D0 A44A0008 */  sh         $t2, 0x8($v0)
    /* 2BFD4 8002B3D4 AC400000 */  sw         $zero, 0x0($v0)
    /* 2BFD8 8002B3D8 03084821 */  addu       $t1, $t8, $t0
    /* 2BFDC 8002B3DC AC490004 */  sw         $t1, 0x4($v0)
    /* 2BFE0 8002B3E0 8CEB0008 */  lw         $t3, 0x8($a3)
    /* 2BFE4 8002B3E4 24050003 */  addiu      $a1, $zero, 0x3
    /* 2BFE8 8002B3E8 8D64000C */  lw         $a0, 0xC($t3)
    /* 2BFEC 8002B3EC 8C990008 */  lw         $t9, 0x8($a0)
    /* 2BFF0 8002B3F0 0320F809 */  jalr       $t9
    /* 2BFF4 8002B3F4 00000000 */   nop
  .L8002B3F8:
    /* 2BFF8 8002B3F8 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002B3FC:
    /* 2BFFC 8002B3FC 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2C000 8002B400 03E00008 */  jr         $ra
    /* 2C004 8002B404 00000000 */   nop
    /* 2C008 8002B408 00000000 */  nop
    /* 2C00C 8002B40C 00000000 */  nop
