.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002B410
    /* 2C010 8002B410 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2C014 8002B414 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2C018 8002B418 8CA60008 */  lw         $a2, 0x8($a1)
    /* 2C01C 8002B41C 00804025 */  or         $t0, $a0, $zero
    /* 2C020 8002B420 00A03825 */  or         $a3, $a1, $zero
    /* 2C024 8002B424 50C00023 */  beql       $a2, $zero, .L8002B4B4
    /* 2C028 8002B428 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 2C02C 8002B42C 8CCE00D8 */  lw         $t6, 0xD8($a2)
    /* 2C030 8002B430 51C0001A */  beql       $t6, $zero, .L8002B49C
    /* 2C034 8002B434 01002025 */   or        $a0, $t0, $zero
    /* 2C038 8002B438 AFA5001C */  sw         $a1, 0x1C($sp)
    /* 2C03C 8002B43C 0C006F80 */  jal        func_8001BE00
    /* 2C040 8002B440 AFA40018 */   sw        $a0, 0x18($sp)
    /* 2C044 8002B444 8FA7001C */  lw         $a3, 0x1C($sp)
    /* 2C048 8002B448 8FA80018 */  lw         $t0, 0x18($sp)
    /* 2C04C 8002B44C 10400018 */  beqz       $v0, .L8002B4B0
    /* 2C050 8002B450 00403025 */   or        $a2, $v0, $zero
    /* 2C054 8002B454 8CF80008 */  lw         $t8, 0x8($a3)
    /* 2C058 8002B458 8D0F001C */  lw         $t7, 0x1C($t0)
    /* 2C05C 8002B45C 24050003 */  addiu      $a1, $zero, 0x3
    /* 2C060 8002B460 8F1900D8 */  lw         $t9, 0xD8($t8)
    /* 2C064 8002B464 A4400008 */  sh         $zero, 0x8($v0)
    /* 2C068 8002B468 01F94821 */  addu       $t1, $t7, $t9
    /* 2C06C 8002B46C AC490004 */  sw         $t1, 0x4($v0)
    /* 2C070 8002B470 8CEA0008 */  lw         $t2, 0x8($a3)
    /* 2C074 8002B474 AC4A000C */  sw         $t2, 0xC($v0)
    /* 2C078 8002B478 8CEB0008 */  lw         $t3, 0x8($a3)
    /* 2C07C 8002B47C 8D64000C */  lw         $a0, 0xC($t3)
    /* 2C080 8002B480 AFA7001C */  sw         $a3, 0x1C($sp)
    /* 2C084 8002B484 8C990008 */  lw         $t9, 0x8($a0)
    /* 2C088 8002B488 0320F809 */  jalr       $t9
    /* 2C08C 8002B48C 00000000 */   nop
    /* 2C090 8002B490 10000006 */  b          .L8002B4AC
    /* 2C094 8002B494 8FA7001C */   lw        $a3, 0x1C($sp)
    /* 2C098 8002B498 01002025 */  or         $a0, $t0, $zero
  .L8002B49C:
    /* 2C09C 8002B49C 00C02825 */  or         $a1, $a2, $zero
    /* 2C0A0 8002B4A0 0C006F54 */  jal        func_8001BD50
    /* 2C0A4 8002B4A4 AFA7001C */   sw        $a3, 0x1C($sp)
    /* 2C0A8 8002B4A8 8FA7001C */  lw         $a3, 0x1C($sp)
  .L8002B4AC:
    /* 2C0AC 8002B4AC ACE00008 */  sw         $zero, 0x8($a3)
  .L8002B4B0:
    /* 2C0B0 8002B4B0 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002B4B4:
    /* 2C0B4 8002B4B4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2C0B8 8002B4B8 03E00008 */  jr         $ra
    /* 2C0BC 8002B4BC 00000000 */   nop

glabel func_8002B4C0
    /* 2C0C0 8002B4C0 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 2C0C4 8002B4C4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2C0C8 8002B4C8 AFA50024 */  sw         $a1, 0x24($sp)
    /* 2C0CC 8002B4CC AFA60028 */  sw         $a2, 0x28($sp)
    /* 2C0D0 8002B4D0 AFA7002C */  sw         $a3, 0x2C($sp)
    /* 2C0D4 8002B4D4 8CAF0008 */  lw         $t7, 0x8($a1)
    /* 2C0D8 8002B4D8 51E0001D */  beql       $t7, $zero, .L8002B550
    /* 2C0DC 8002B4DC 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 2C0E0 8002B4E0 0C006F80 */  jal        func_8001BE00
    /* 2C0E4 8002B4E4 AFA40020 */   sw        $a0, 0x20($sp)
    /* 2C0E8 8002B4E8 10400018 */  beqz       $v0, .L8002B54C
    /* 2C0EC 8002B4EC 8FA40020 */   lw        $a0, 0x20($sp)
    /* 2C0F0 8002B4F0 8FB90024 */  lw         $t9, 0x24($sp)
    /* 2C0F4 8002B4F4 8C98001C */  lw         $t8, 0x1C($a0)
    /* 2C0F8 8002B4F8 240B000B */  addiu      $t3, $zero, 0xB
    /* 2C0FC 8002B4FC 8F280008 */  lw         $t0, 0x8($t9)
    /* 2C100 8002B500 8D0900D8 */  lw         $t1, 0xD8($t0)
    /* 2C104 8002B504 A44B0008 */  sh         $t3, 0x8($v0)
    /* 2C108 8002B508 03095021 */  addu       $t2, $t8, $t1
    /* 2C10C 8002B50C AC4A0004 */  sw         $t2, 0x4($v0)
    /* 2C110 8002B510 87AC002A */  lh         $t4, 0x2A($sp)
    /* 2C114 8002B514 AC4C000C */  sw         $t4, 0xC($v0)
    /* 2C118 8002B518 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 2C11C 8002B51C 0C006F3E */  jal        func_8001BCF8
    /* 2C120 8002B520 8FA5002C */   lw        $a1, 0x2C($sp)
    /* 2C124 8002B524 8FA6001C */  lw         $a2, 0x1C($sp)
    /* 2C128 8002B528 24050003 */  addiu      $a1, $zero, 0x3
    /* 2C12C 8002B52C ACC20010 */  sw         $v0, 0x10($a2)
    /* 2C130 8002B530 ACC00000 */  sw         $zero, 0x0($a2)
    /* 2C134 8002B534 8FAD0024 */  lw         $t5, 0x24($sp)
    /* 2C138 8002B538 8DAE0008 */  lw         $t6, 0x8($t5)
    /* 2C13C 8002B53C 8DC4000C */  lw         $a0, 0xC($t6)
    /* 2C140 8002B540 8C990008 */  lw         $t9, 0x8($a0)
    /* 2C144 8002B544 0320F809 */  jalr       $t9
    /* 2C148 8002B548 00000000 */   nop
  .L8002B54C:
    /* 2C14C 8002B54C 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002B550:
    /* 2C150 8002B550 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 2C154 8002B554 03E00008 */  jr         $ra
    /* 2C158 8002B558 00000000 */   nop
    /* 2C15C 8002B55C 00000000 */  nop
