.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002B820
    /* 2C420 8002B820 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 2C424 8002B824 44811000 */  mtc1       $at, $fv1
    /* 2C428 8002B828 04800004 */  bltz       $a0, .L8002B83C
    /* 2C42C 8002B82C 3C018004 */   lui       $at, %hi(D_80039FF4)
    /* 2C430 8002B830 3C018004 */  lui        $at, %hi(D_80039FF0)
    /* 2C434 8002B834 10000003 */  b          .L8002B844
    /* 2C438 8002B838 C4209FF0 */   lwc1      $fv0, %lo(D_80039FF0)($at)
  .L8002B83C:
    /* 2C43C 8002B83C C4209FF4 */  lwc1       $fv0, %lo(D_80039FF4)($at)
    /* 2C440 8002B840 00042023 */  negu       $a0, $a0
  .L8002B844:
    /* 2C444 8002B844 10800008 */  beqz       $a0, .L8002B868
  .L8002B848:
    /* 2C448 8002B848 308E0001 */   andi      $t6, $a0, 0x1
    /* 2C44C 8002B84C 11C00003 */  beqz       $t6, .L8002B85C
    /* 2C450 8002B850 00047843 */   sra       $t7, $a0, 1
    /* 2C454 8002B854 46001082 */  mul.s      $fv1, $fv1, $fv0
    /* 2C458 8002B858 00000000 */  nop
  .L8002B85C:
    /* 2C45C 8002B85C 46000002 */  mul.s      $fv0, $fv0, $fv0
    /* 2C460 8002B860 15E0FFF9 */  bnez       $t7, .L8002B848
    /* 2C464 8002B864 01E02025 */   or        $a0, $t7, $zero
  .L8002B868:
    /* 2C468 8002B868 03E00008 */  jr         $ra
    /* 2C46C 8002B86C 46001006 */   mov.s     $fv0, $fv1

glabel func_8002B870
    /* 2C470 8002B870 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 2C474 8002B874 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2C478 8002B878 AFA50024 */  sw         $a1, 0x24($sp)
    /* 2C47C 8002B87C AFA60028 */  sw         $a2, 0x28($sp)
    /* 2C480 8002B880 AFA7002C */  sw         $a3, 0x2C($sp)
    /* 2C484 8002B884 8CAE0008 */  lw         $t6, 0x8($a1)
    /* 2C488 8002B888 51C0002F */  beql       $t6, $zero, .L8002B948
    /* 2C48C 8002B88C 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 2C490 8002B890 AFA40020 */  sw         $a0, 0x20($sp)
    /* 2C494 8002B894 0C006F80 */  jal        func_8001BE00
    /* 2C498 8002B898 AFA50024 */   sw        $a1, 0x24($sp)
    /* 2C49C 8002B89C 8FA40020 */  lw         $a0, 0x20($sp)
    /* 2C4A0 8002B8A0 8FA70024 */  lw         $a3, 0x24($sp)
    /* 2C4A4 8002B8A4 10400027 */  beqz       $v0, .L8002B944
    /* 2C4A8 8002B8A8 00403025 */   or        $a2, $v0, $zero
    /* 2C4AC 8002B8AC 93A3003B */  lbu        $v1, 0x3B($sp)
    /* 2C4B0 8002B8B0 04610004 */  bgez       $v1, .L8002B8C4
    /* 2C4B4 8002B8B4 00601025 */   or        $v0, $v1, $zero
    /* 2C4B8 8002B8B8 00021823 */  negu       $v1, $v0
    /* 2C4BC 8002B8BC 306F00FF */  andi       $t7, $v1, 0xFF
    /* 2C4C0 8002B8C0 01E01825 */  or         $v1, $t7, $zero
  .L8002B8C4:
    /* 2C4C4 8002B8C4 8CF90008 */  lw         $t9, 0x8($a3)
    /* 2C4C8 8002B8C8 8C98001C */  lw         $t8, 0x1C($a0)
    /* 2C4CC 8002B8CC 240A000D */  addiu      $t2, $zero, 0xD
    /* 2C4D0 8002B8D0 8F2800D8 */  lw         $t0, 0xD8($t9)
    /* 2C4D4 8002B8D4 ACC00000 */  sw         $zero, 0x0($a2)
    /* 2C4D8 8002B8D8 A4CA0008 */  sh         $t2, 0x8($a2)
    /* 2C4DC 8002B8DC 03084821 */  addu       $t1, $t8, $t0
    /* 2C4E0 8002B8E0 ACC90004 */  sw         $t1, 0x4($a2)
    /* 2C4E4 8002B8E4 84EB001A */  lh         $t3, 0x1A($a3)
    /* 2C4E8 8002B8E8 A4CB000A */  sh         $t3, 0xA($a2)
    /* 2C4EC 8002B8EC 93AC0037 */  lbu        $t4, 0x37($sp)
    /* 2C4F0 8002B8F0 A0CC0012 */  sb         $t4, 0x12($a2)
    /* 2C4F4 8002B8F4 87AD0032 */  lh         $t5, 0x32($sp)
    /* 2C4F8 8002B8F8 A0C30013 */  sb         $v1, 0x13($a2)
    /* 2C4FC 8002B8FC A4CD0010 */  sh         $t5, 0x10($a2)
    /* 2C500 8002B900 C7A4002C */  lwc1       $ft0, 0x2C($sp)
    /* 2C504 8002B904 E4C4000C */  swc1       $ft0, 0xC($a2)
    /* 2C508 8002B908 AFA70024 */  sw         $a3, 0x24($sp)
    /* 2C50C 8002B90C AFA6001C */  sw         $a2, 0x1C($sp)
    /* 2C510 8002B910 0C006F3E */  jal        func_8001BCF8
    /* 2C514 8002B914 8FA5003C */   lw        $a1, 0x3C($sp)
    /* 2C518 8002B918 8FA6001C */  lw         $a2, 0x1C($sp)
    /* 2C51C 8002B91C 8FA70024 */  lw         $a3, 0x24($sp)
    /* 2C520 8002B920 24050003 */  addiu      $a1, $zero, 0x3
    /* 2C524 8002B924 ACC20014 */  sw         $v0, 0x14($a2)
    /* 2C528 8002B928 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 2C52C 8002B92C ACCE0018 */  sw         $t6, 0x18($a2)
    /* 2C530 8002B930 8CEF0008 */  lw         $t7, 0x8($a3)
    /* 2C534 8002B934 8DE4000C */  lw         $a0, 0xC($t7)
    /* 2C538 8002B938 8C990008 */  lw         $t9, 0x8($a0)
    /* 2C53C 8002B93C 0320F809 */  jalr       $t9
    /* 2C540 8002B940 00000000 */   nop
  .L8002B944:
    /* 2C544 8002B944 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002B948:
    /* 2C548 8002B948 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 2C54C 8002B94C 03E00008 */  jr         $ra
    /* 2C550 8002B950 00000000 */   nop
    /* 2C554 8002B954 00000000 */  nop
    /* 2C558 8002B958 00000000 */  nop
    /* 2C55C 8002B95C 00000000 */  nop
