.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002BB20
    /* 2C720 8002BB20 3C0E8007 */  lui        $t6, %hi(D_8006F094)
    /* 2C724 8002BB24 8DCEF094 */  lw         $t6, %lo(D_8006F094)($t6)
    /* 2C728 8002BB28 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 2C72C 8002BB2C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2C730 8002BB30 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 2C734 8002BB34 AFA0003C */  sw         $zero, 0x3C($sp)
    /* 2C738 8002BB38 AFAF0030 */  sw         $t7, 0x30($sp)
    /* 2C73C 8002BB3C 95D8001A */  lhu        $t8, 0x1A($t6)
    /* 2C740 8002BB40 3C0AA460 */  lui        $t2, %hi(D_A4600010)
    /* 2C744 8002BB44 0018C8C0 */  sll        $t9, $t8, 3
    /* 2C748 8002BB48 0338C821 */  addu       $t9, $t9, $t8
    /* 2C74C 8002BB4C 0019C880 */  sll        $t9, $t9, 2
    /* 2C750 8002BB50 01F94021 */  addu       $t0, $t7, $t9
    /* 2C754 8002BB54 25090018 */  addiu      $t1, $t0, 0x18
    /* 2C758 8002BB58 AFA9002C */  sw         $t1, 0x2C($sp)
    /* 2C75C 8002BB5C 8D4B0010 */  lw         $t3, %lo(D_A4600010)($t2)
    /* 2C760 8002BB60 AFAB0038 */  sw         $t3, 0x38($sp)
    /* 2C764 8002BB64 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 2C768 8002BB68 318D0001 */  andi       $t5, $t4, 0x1
    /* 2C76C 8002BB6C 11A0000C */  beqz       $t5, .L8002BBA0
    /* 2C770 8002BB70 00000000 */   nop
    /* 2C774 8002BB74 3C0E8003 */  lui        $t6, %hi(D_80035620)
    /* 2C778 8002BB78 8DCE5620 */  lw         $t6, %lo(D_80035620)($t6)
    /* 2C77C 8002BB7C 2401F7FF */  addiu      $at, $zero, -0x801
    /* 2C780 8002BB80 240F001D */  addiu      $t7, $zero, 0x1D
    /* 2C784 8002BB84 01C1C024 */  and        $t8, $t6, $at
    /* 2C788 8002BB88 3C018003 */  lui        $at, %hi(D_80035620)
    /* 2C78C 8002BB8C AC385620 */  sw         $t8, %lo(D_80035620)($at)
    /* 2C790 8002BB90 0C00B0AB */  jal        func_8002C2AC
    /* 2C794 8002BB94 AD0F0018 */   sw        $t7, 0x18($t0)
    /* 2C798 8002BB98 10000186 */  b          .L8002C1B4
    /* 2C79C 8002BB9C 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BBA0:
    /* 2C7A0 8002BBA0 3C19A460 */  lui        $t9, %hi(D_A4600010)
    /* 2C7A4 8002BBA4 8F290010 */  lw         $t1, %lo(D_A4600010)($t9)
    /* 2C7A8 8002BBA8 AFA90038 */  sw         $t1, 0x38($sp)
    /* 2C7AC 8002BBAC 8FAA0038 */  lw         $t2, 0x38($sp)
    /* 2C7B0 8002BBB0 314B0003 */  andi       $t3, $t2, 0x3
    /* 2C7B4 8002BBB4 11600008 */  beqz       $t3, .L8002BBD8
    /* 2C7B8 8002BBB8 00000000 */   nop
  .L8002BBBC:
    /* 2C7BC 8002BBBC 3C0CA460 */  lui        $t4, %hi(D_A4600010)
    /* 2C7C0 8002BBC0 8D8D0010 */  lw         $t5, %lo(D_A4600010)($t4)
    /* 2C7C4 8002BBC4 AFAD0038 */  sw         $t5, 0x38($sp)
    /* 2C7C8 8002BBC8 8FAE0038 */  lw         $t6, 0x38($sp)
    /* 2C7CC 8002BBCC 31D80003 */  andi       $t8, $t6, 0x3
    /* 2C7D0 8002BBD0 1700FFFA */  bnez       $t8, .L8002BBBC
    /* 2C7D4 8002BBD4 00000000 */   nop
  .L8002BBD8:
    /* 2C7D8 8002BBD8 3C0FA500 */  lui        $t7, %hi(D_A5000508)
    /* 2C7DC 8002BBDC 8DE80508 */  lw         $t0, %lo(D_A5000508)($t7)
    /* 2C7E0 8002BBE0 3C010200 */  lui        $at, (0x2000000 >> 16)
    /* 2C7E4 8002BBE4 AFA8003C */  sw         $t0, 0x3C($sp)
    /* 2C7E8 8002BBE8 8FB9003C */  lw         $t9, 0x3C($sp)
    /* 2C7EC 8002BBEC 03214824 */  and        $t1, $t9, $at
    /* 2C7F0 8002BBF0 11200019 */  beqz       $t1, .L8002BC58
    /* 2C7F4 8002BBF4 00000000 */   nop
    /* 2C7F8 8002BBF8 3C0AA460 */  lui        $t2, %hi(D_A4600010)
    /* 2C7FC 8002BBFC 8D4B0010 */  lw         $t3, %lo(D_A4600010)($t2)
    /* 2C800 8002BC00 AFAB0038 */  sw         $t3, 0x38($sp)
    /* 2C804 8002BC04 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 2C808 8002BC08 318D0003 */  andi       $t5, $t4, 0x3
    /* 2C80C 8002BC0C 11A00008 */  beqz       $t5, .L8002BC30
    /* 2C810 8002BC10 00000000 */   nop
  .L8002BC14:
    /* 2C814 8002BC14 3C0EA460 */  lui        $t6, %hi(D_A4600010)
    /* 2C818 8002BC18 8DD80010 */  lw         $t8, %lo(D_A4600010)($t6)
    /* 2C81C 8002BC1C AFB80038 */  sw         $t8, 0x38($sp)
    /* 2C820 8002BC20 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 2C824 8002BC24 31E80003 */  andi       $t0, $t7, 0x3
    /* 2C828 8002BC28 1500FFFA */  bnez       $t0, .L8002BC14
    /* 2C82C 8002BC2C 00000000 */   nop
  .L8002BC30:
    /* 2C830 8002BC30 8FB90030 */  lw         $t9, 0x30($sp)
    /* 2C834 8002BC34 3C010100 */  lui        $at, (0x1000000 >> 16)
    /* 2C838 8002BC38 3C0BA500 */  lui        $t3, %hi(D_A5000510)
    /* 2C83C 8002BC3C 8F290010 */  lw         $t1, 0x10($t9)
    /* 2C840 8002BC40 00001025 */  or         $v0, $zero, $zero
    /* 2C844 8002BC44 01215025 */  or         $t2, $t1, $at
    /* 2C848 8002BC48 AD6A0510 */  sw         $t2, %lo(D_A5000510)($t3)
    /* 2C84C 8002BC4C 8FAC002C */  lw         $t4, 0x2C($sp)
    /* 2C850 8002BC50 10000158 */  b          .L8002C1B4
    /* 2C854 8002BC54 AD800000 */   sw        $zero, 0x0($t4)
  .L8002BC58:
    /* 2C858 8002BC58 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 2C85C 8002BC5C 24010002 */  addiu      $at, $zero, 0x2
    /* 2C860 8002BC60 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 2C864 8002BC64 15C10003 */  bne        $t6, $at, .L8002BC74
    /* 2C868 8002BC68 00000000 */   nop
    /* 2C86C 8002BC6C 10000151 */  b          .L8002C1B4
    /* 2C870 8002BC70 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BC74:
    /* 2C874 8002BC74 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 2C878 8002BC78 3C010800 */  lui        $at, (0x8000000 >> 16)
    /* 2C87C 8002BC7C 03017824 */  and        $t7, $t8, $at
    /* 2C880 8002BC80 11E00022 */  beqz       $t7, .L8002BD0C
    /* 2C884 8002BC84 00000000 */   nop
    /* 2C888 8002BC88 3C08A460 */  lui        $t0, %hi(D_A4600010)
    /* 2C88C 8002BC8C 8D190010 */  lw         $t9, %lo(D_A4600010)($t0)
    /* 2C890 8002BC90 AFB90038 */  sw         $t9, 0x38($sp)
    /* 2C894 8002BC94 8FA90038 */  lw         $t1, 0x38($sp)
    /* 2C898 8002BC98 312A0003 */  andi       $t2, $t1, 0x3
    /* 2C89C 8002BC9C 11400008 */  beqz       $t2, .L8002BCC0
    /* 2C8A0 8002BCA0 00000000 */   nop
  .L8002BCA4:
    /* 2C8A4 8002BCA4 3C0BA460 */  lui        $t3, %hi(D_A4600010)
    /* 2C8A8 8002BCA8 8D6C0010 */  lw         $t4, %lo(D_A4600010)($t3)
    /* 2C8AC 8002BCAC AFAC0038 */  sw         $t4, 0x38($sp)
    /* 2C8B0 8002BCB0 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 2C8B4 8002BCB4 31AE0003 */  andi       $t6, $t5, 0x3
    /* 2C8B8 8002BCB8 15C0FFFA */  bnez       $t6, .L8002BCA4
    /* 2C8BC 8002BCBC 00000000 */   nop
  .L8002BCC0:
    /* 2C8C0 8002BCC0 3C18A500 */  lui        $t8, %hi(D_A5000508)
    /* 2C8C4 8002BCC4 8F0F0508 */  lw         $t7, %lo(D_A5000508)($t8)
    /* 2C8C8 8002BCC8 8FB9002C */  lw         $t9, 0x2C($sp)
    /* 2C8CC 8002BCCC 24080016 */  addiu      $t0, $zero, 0x16
    /* 2C8D0 8002BCD0 AFAF003C */  sw         $t7, 0x3C($sp)
    /* 2C8D4 8002BCD4 0C00B0AB */  jal        func_8002C2AC
    /* 2C8D8 8002BCD8 AF280000 */   sw        $t0, 0x0($t9)
    /* 2C8DC 8002BCDC 24090002 */  addiu      $t1, $zero, 0x2
    /* 2C8E0 8002BCE0 3C0AA460 */  lui        $t2, %hi(D_A4600010)
    /* 2C8E4 8002BCE4 AD490010 */  sw         $t1, %lo(D_A4600010)($t2)
    /* 2C8E8 8002BCE8 3C0B8003 */  lui        $t3, %hi(D_80035620)
    /* 2C8EC 8002BCEC 8D6B5620 */  lw         $t3, %lo(D_80035620)($t3)
    /* 2C8F0 8002BCF0 3C010010 */  lui        $at, (0x100401 >> 16)
    /* 2C8F4 8002BCF4 34210401 */  ori        $at, $at, (0x100401 & 0xFFFF)
    /* 2C8F8 8002BCF8 01616025 */  or         $t4, $t3, $at
    /* 2C8FC 8002BCFC 3C018003 */  lui        $at, %hi(D_80035620)
    /* 2C900 8002BD00 AC2C5620 */  sw         $t4, %lo(D_80035620)($at)
    /* 2C904 8002BD04 1000012B */  b          .L8002C1B4
    /* 2C908 8002BD08 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BD0C:
    /* 2C90C 8002BD0C 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 2C910 8002BD10 24010001 */  addiu      $at, $zero, 0x1
    /* 2C914 8002BD14 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 2C918 8002BD18 15C1003B */  bne        $t6, $at, .L8002BE08
    /* 2C91C 8002BD1C 00000000 */   nop
    /* 2C920 8002BD20 8FB8003C */  lw         $t8, 0x3C($sp)
    /* 2C924 8002BD24 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 2C928 8002BD28 03017824 */  and        $t7, $t8, $at
    /* 2C92C 8002BD2C 15E00021 */  bnez       $t7, .L8002BDB4
    /* 2C930 8002BD30 00000000 */   nop
    /* 2C934 8002BD34 95A90004 */  lhu        $t1, 0x4($t5)
    /* 2C938 8002BD38 8DA80008 */  lw         $t0, 0x8($t5)
    /* 2C93C 8002BD3C 00095080 */  sll        $t2, $t1, 2
    /* 2C940 8002BD40 01495021 */  addu       $t2, $t2, $t1
    /* 2C944 8002BD44 000A5080 */  sll        $t2, $t2, 2
    /* 2C948 8002BD48 01495021 */  addu       $t2, $t2, $t1
    /* 2C94C 8002BD4C 000A5080 */  sll        $t2, $t2, 2
    /* 2C950 8002BD50 01495021 */  addu       $t2, $t2, $t1
    /* 2C954 8002BD54 25190001 */  addiu      $t9, $t0, 0x1
    /* 2C958 8002BD58 132A0007 */  beq        $t9, $t2, .L8002BD78
    /* 2C95C 8002BD5C 00000000 */   nop
    /* 2C960 8002BD60 8FAC002C */  lw         $t4, 0x2C($sp)
    /* 2C964 8002BD64 240B0018 */  addiu      $t3, $zero, 0x18
    /* 2C968 8002BD68 0C00B071 */  jal        func_8002C1C4
    /* 2C96C 8002BD6C AD8B0000 */   sw        $t3, 0x0($t4)
    /* 2C970 8002BD70 10000110 */  b          .L8002C1B4
    /* 2C974 8002BD74 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BD78:
    /* 2C978 8002BD78 240E0002 */  addiu      $t6, $zero, 0x2
    /* 2C97C 8002BD7C 3C18A460 */  lui        $t8, %hi(D_A4600010)
    /* 2C980 8002BD80 AF0E0010 */  sw         $t6, %lo(D_A4600010)($t8)
    /* 2C984 8002BD84 3C0F8003 */  lui        $t7, %hi(D_80035620)
    /* 2C988 8002BD88 8DEF5620 */  lw         $t7, %lo(D_80035620)($t7)
    /* 2C98C 8002BD8C 3C010010 */  lui        $at, (0x100401 >> 16)
    /* 2C990 8002BD90 34210401 */  ori        $at, $at, (0x100401 & 0xFFFF)
    /* 2C994 8002BD94 01E14025 */  or         $t0, $t7, $at
    /* 2C998 8002BD98 8FAD002C */  lw         $t5, 0x2C($sp)
    /* 2C99C 8002BD9C 3C018003 */  lui        $at, %hi(D_80035620)
    /* 2C9A0 8002BDA0 AC285620 */  sw         $t0, %lo(D_80035620)($at)
    /* 2C9A4 8002BDA4 0C00B0AB */  jal        func_8002C2AC
    /* 2C9A8 8002BDA8 ADA00000 */   sw        $zero, 0x0($t5)
    /* 2C9AC 8002BDAC 10000101 */  b          .L8002C1B4
    /* 2C9B0 8002BDB0 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BDB4:
    /* 2C9B4 8002BDB4 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 2C9B8 8002BDB8 3C048007 */  lui        $a0, %hi(D_8006F094)
    /* 2C9BC 8002BDBC 3C060500 */  lui        $a2, (0x5000400 >> 16)
    /* 2C9C0 8002BDC0 8D390004 */  lw         $t9, 0x4($t1)
    /* 2C9C4 8002BDC4 8D2A000C */  lw         $t2, 0xC($t1)
    /* 2C9C8 8002BDC8 34C60400 */  ori        $a2, $a2, (0x5000400 & 0xFFFF)
    /* 2C9CC 8002BDCC 24050001 */  addiu      $a1, $zero, 0x1
    /* 2C9D0 8002BDD0 032A5821 */  addu       $t3, $t9, $t2
    /* 2C9D4 8002BDD4 AD2B0004 */  sw         $t3, 0x4($t1)
    /* 2C9D8 8002BDD8 8FAC0030 */  lw         $t4, 0x30($sp)
    /* 2C9DC 8002BDDC 8D8E0008 */  lw         $t6, 0x8($t4)
    /* 2C9E0 8002BDE0 25D80001 */  addiu      $t8, $t6, 0x1
    /* 2C9E4 8002BDE4 AD980008 */  sw         $t8, 0x8($t4)
    /* 2C9E8 8002BDE8 8FAF002C */  lw         $t7, 0x2C($sp)
    /* 2C9EC 8002BDEC 8C84F094 */  lw         $a0, %lo(D_8006F094)($a0)
    /* 2C9F0 8002BDF0 8DE8000C */  lw         $t0, 0xC($t7)
    /* 2C9F4 8002BDF4 8DE70004 */  lw         $a3, 0x4($t7)
    /* 2C9F8 8002BDF8 0C00A400 */  jal        func_80029000
    /* 2C9FC 8002BDFC AFA80010 */   sw        $t0, 0x10($sp)
    /* 2CA00 8002BE00 100000EC */  b          .L8002C1B4
    /* 2CA04 8002BE04 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BE08:
    /* 2CA08 8002BE08 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 2CA0C 8002BE0C 8DB90000 */  lw         $t9, 0x0($t5)
    /* 2CA10 8002BE10 172000E3 */  bnez       $t9, .L8002C1A0
    /* 2CA14 8002BE14 00000000 */   nop
    /* 2CA18 8002BE18 95AA0004 */  lhu        $t2, 0x4($t5)
    /* 2CA1C 8002BE1C 24010003 */  addiu      $at, $zero, 0x3
    /* 2CA20 8002BE20 15410017 */  bne        $t2, $at, .L8002BE80
    /* 2CA24 8002BE24 00000000 */   nop
    /* 2CA28 8002BE28 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 2CA2C 8002BE2C 8DAB0008 */  lw         $t3, 0x8($t5)
    /* 2CA30 8002BE30 8D2E0010 */  lw         $t6, 0x10($t1)
    /* 2CA34 8002BE34 25D80011 */  addiu      $t8, $t6, 0x11
    /* 2CA38 8002BE38 030B082A */  slt        $at, $t8, $t3
    /* 2CA3C 8002BE3C 10200005 */  beqz       $at, .L8002BE54
    /* 2CA40 8002BE40 00000000 */   nop
    /* 2CA44 8002BE44 0C00B071 */  jal        func_8002C1C4
    /* 2CA48 8002BE48 AD200000 */   sw        $zero, 0x0($t1)
    /* 2CA4C 8002BE4C 100000D9 */  b          .L8002C1B4
    /* 2CA50 8002BE50 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BE54:
    /* 2CA54 8002BE54 8FAC003C */  lw         $t4, 0x3C($sp)
    /* 2CA58 8002BE58 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 2CA5C 8002BE5C 01817824 */  and        $t7, $t4, $at
    /* 2CA60 8002BE60 15E0000C */  bnez       $t7, .L8002BE94
    /* 2CA64 8002BE64 00000000 */   nop
    /* 2CA68 8002BE68 8FB9002C */  lw         $t9, 0x2C($sp)
    /* 2CA6C 8002BE6C 24080017 */  addiu      $t0, $zero, 0x17
    /* 2CA70 8002BE70 0C00B071 */  jal        func_8002C1C4
    /* 2CA74 8002BE74 AF280000 */   sw        $t0, 0x0($t9)
    /* 2CA78 8002BE78 100000CE */  b          .L8002C1B4
    /* 2CA7C 8002BE7C 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BE80:
    /* 2CA80 8002BE80 8FAA002C */  lw         $t2, 0x2C($sp)
    /* 2CA84 8002BE84 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 2CA88 8002BE88 8D4E000C */  lw         $t6, 0xC($t2)
    /* 2CA8C 8002BE8C 01AE5821 */  addu       $t3, $t5, $t6
    /* 2CA90 8002BE90 AD4B0004 */  sw         $t3, 0x4($t2)
  .L8002BE94:
    /* 2CA94 8002BE94 3C18A500 */  lui        $t8, %hi(D_A5000510)
    /* 2CA98 8002BE98 8F090510 */  lw         $t1, %lo(D_A5000510)($t8)
    /* 2CA9C 8002BE9C 3C010020 */  lui        $at, (0x200000 >> 16)
    /* 2CAA0 8002BEA0 AFA90034 */  sw         $t1, 0x34($sp)
    /* 2CAA4 8002BEA4 8FAC0034 */  lw         $t4, 0x34($sp)
    /* 2CAA8 8002BEA8 01817824 */  and        $t7, $t4, $at
    /* 2CAAC 8002BEAC 11E00004 */  beqz       $t7, .L8002BEC0
    /* 2CAB0 8002BEB0 3C010040 */   lui       $at, (0x400000 >> 16)
    /* 2CAB4 8002BEB4 01814024 */  and        $t0, $t4, $at
    /* 2CAB8 8002BEB8 15000006 */  bnez       $t0, .L8002BED4
    /* 2CABC 8002BEBC 00000000 */   nop
  .L8002BEC0:
    /* 2CAC0 8002BEC0 8FB90034 */  lw         $t9, 0x34($sp)
    /* 2CAC4 8002BEC4 3C010200 */  lui        $at, (0x2000000 >> 16)
    /* 2CAC8 8002BEC8 03216824 */  and        $t5, $t9, $at
    /* 2CACC 8002BECC 11A00022 */  beqz       $t5, .L8002BF58
    /* 2CAD0 8002BED0 00000000 */   nop
  .L8002BED4:
    /* 2CAD4 8002BED4 8FAE002C */  lw         $t6, 0x2C($sp)
    /* 2CAD8 8002BED8 8DCB0010 */  lw         $t3, 0x10($t6)
    /* 2CADC 8002BEDC 2D610004 */  sltiu      $at, $t3, 0x4
    /* 2CAE0 8002BEE0 14200010 */  bnez       $at, .L8002BF24
    /* 2CAE4 8002BEE4 00000000 */   nop
    /* 2CAE8 8002BEE8 8FAA0030 */  lw         $t2, 0x30($sp)
    /* 2CAEC 8002BEEC 24010003 */  addiu      $at, $zero, 0x3
    /* 2CAF0 8002BEF0 95580004 */  lhu        $t8, 0x4($t2)
    /* 2CAF4 8002BEF4 17010005 */  bne        $t8, $at, .L8002BF0C
    /* 2CAF8 8002BEF8 00000000 */   nop
    /* 2CAFC 8002BEFC 8D490008 */  lw         $t1, 0x8($t2)
    /* 2CB00 8002BF00 29210053 */  slti       $at, $t1, 0x53
    /* 2CB04 8002BF04 14200010 */  bnez       $at, .L8002BF48
    /* 2CB08 8002BF08 00000000 */   nop
  .L8002BF0C:
    /* 2CB0C 8002BF0C 8FAC002C */  lw         $t4, 0x2C($sp)
    /* 2CB10 8002BF10 240F0017 */  addiu      $t7, $zero, 0x17
    /* 2CB14 8002BF14 0C00B071 */  jal        func_8002C1C4
    /* 2CB18 8002BF18 AD8F0000 */   sw        $t7, 0x0($t4)
    /* 2CB1C 8002BF1C 100000A5 */  b          .L8002C1B4
    /* 2CB20 8002BF20 24020001 */   addiu     $v0, $zero, 0x1
  .L8002BF24:
    /* 2CB24 8002BF24 8FA8002C */  lw         $t0, 0x2C($sp)
    /* 2CB28 8002BF28 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 2CB2C 8002BF2C 8D190010 */  lw         $t9, 0x10($t0)
    /* 2CB30 8002BF30 AFB90028 */  sw         $t9, 0x28($sp)
    /* 2CB34 8002BF34 8DAE0008 */  lw         $t6, 0x8($t5)
    /* 2CB38 8002BF38 0019C080 */  sll        $t8, $t9, 2
    /* 2CB3C 8002BF3C 01185021 */  addu       $t2, $t0, $t8
    /* 2CB40 8002BF40 25CB0001 */  addiu      $t3, $t6, 0x1
    /* 2CB44 8002BF44 AD4B0014 */  sw         $t3, 0x14($t2)
  .L8002BF48:
    /* 2CB48 8002BF48 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 2CB4C 8002BF4C 8D2F0010 */  lw         $t7, 0x10($t1)
    /* 2CB50 8002BF50 25EC0001 */  addiu      $t4, $t7, 0x1
    /* 2CB54 8002BF54 AD2C0010 */  sw         $t4, 0x10($t1)
  .L8002BF58:
    /* 2CB58 8002BF58 8FAD003C */  lw         $t5, 0x3C($sp)
    /* 2CB5C 8002BF5C 3C011000 */  lui        $at, (0x10000000 >> 16)
    /* 2CB60 8002BF60 01A17024 */  and        $t6, $t5, $at
    /* 2CB64 8002BF64 11C0003B */  beqz       $t6, .L8002C054
    /* 2CB68 8002BF68 00000000 */   nop
    /* 2CB6C 8002BF6C 8FB90030 */  lw         $t9, 0x30($sp)
    /* 2CB70 8002BF70 24010057 */  addiu      $at, $zero, 0x57
    /* 2CB74 8002BF74 8F280008 */  lw         $t0, 0x8($t9)
    /* 2CB78 8002BF78 11010005 */  beq        $t0, $at, .L8002BF90
    /* 2CB7C 8002BF7C 00000000 */   nop
    /* 2CB80 8002BF80 8FAB002C */  lw         $t3, 0x2C($sp)
    /* 2CB84 8002BF84 24180018 */  addiu      $t8, $zero, 0x18
    /* 2CB88 8002BF88 0C00B071 */  jal        func_8002C1C4
    /* 2CB8C 8002BF8C AD780000 */   sw        $t8, 0x0($t3)
  .L8002BF90:
    /* 2CB90 8002BF90 8FAA0030 */  lw         $t2, 0x30($sp)
    /* 2CB94 8002BF94 24010002 */  addiu      $at, $zero, 0x2
    /* 2CB98 8002BF98 954F0004 */  lhu        $t7, 0x4($t2)
    /* 2CB9C 8002BF9C 15E10012 */  bne        $t7, $at, .L8002BFE8
    /* 2CBA0 8002BFA0 00000000 */   nop
    /* 2CBA4 8002BFA4 954C0006 */  lhu        $t4, 0x6($t2)
    /* 2CBA8 8002BFA8 1580000F */  bnez       $t4, .L8002BFE8
    /* 2CBAC 8002BFAC 00000000 */   nop
    /* 2CBB0 8002BFB0 24090001 */  addiu      $t1, $zero, 0x1
    /* 2CBB4 8002BFB4 A5490006 */  sh         $t1, 0x6($t2)
    /* 2CBB8 8002BFB8 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 2CBBC 8002BFBC 240DFFFF */  addiu      $t5, $zero, -0x1
    /* 2CBC0 8002BFC0 240F0016 */  addiu      $t7, $zero, 0x16
    /* 2CBC4 8002BFC4 ADCD0008 */  sw         $t5, 0x8($t6)
    /* 2CBC8 8002BFC8 8FB90030 */  lw         $t9, 0x30($sp)
    /* 2CBCC 8002BFCC 8F280040 */  lw         $t0, 0x40($t9)
    /* 2CBD0 8002BFD0 8F380048 */  lw         $t8, 0x48($t9)
    /* 2CBD4 8002BFD4 01185823 */  subu       $t3, $t0, $t8
    /* 2CBD8 8002BFD8 AF2B0040 */  sw         $t3, 0x40($t9)
    /* 2CBDC 8002BFDC 8FAC002C */  lw         $t4, 0x2C($sp)
    /* 2CBE0 8002BFE0 10000010 */  b          .L8002C024
    /* 2CBE4 8002BFE4 AD8F0000 */   sw        $t7, 0x0($t4)
  .L8002BFE8:
    /* 2CBE8 8002BFE8 24090002 */  addiu      $t1, $zero, 0x2
    /* 2CBEC 8002BFEC 3C0AA460 */  lui        $t2, %hi(D_A4600010)
    /* 2CBF0 8002BFF0 AD490010 */  sw         $t1, %lo(D_A4600010)($t2)
    /* 2CBF4 8002BFF4 3C0D8003 */  lui        $t5, %hi(D_80035620)
    /* 2CBF8 8002BFF8 8DAD5620 */  lw         $t5, %lo(D_80035620)($t5)
    /* 2CBFC 8002BFFC 3C010010 */  lui        $at, (0x100401 >> 16)
    /* 2CC00 8002C000 34210401 */  ori        $at, $at, (0x100401 & 0xFFFF)
    /* 2CC04 8002C004 8FB80030 */  lw         $t8, 0x30($sp)
    /* 2CC08 8002C008 01A17025 */  or         $t6, $t5, $at
    /* 2CC0C 8002C00C 3C018003 */  lui        $at, %hi(D_80035620)
    /* 2CC10 8002C010 AC2E5620 */  sw         $t6, %lo(D_80035620)($at)
    /* 2CC14 8002C014 24080002 */  addiu      $t0, $zero, 0x2
    /* 2CC18 8002C018 AF080000 */  sw         $t0, 0x0($t8)
    /* 2CC1C 8002C01C 8FAB002C */  lw         $t3, 0x2C($sp)
    /* 2CC20 8002C020 AD600000 */  sw         $zero, 0x0($t3)
  .L8002C024:
    /* 2CC24 8002C024 8FB9002C */  lw         $t9, 0x2C($sp)
    /* 2CC28 8002C028 3C048007 */  lui        $a0, %hi(D_8006F094)
    /* 2CC2C 8002C02C 8C84F094 */  lw         $a0, %lo(D_8006F094)($a0)
    /* 2CC30 8002C030 8F2F000C */  lw         $t7, 0xC($t9)
    /* 2CC34 8002C034 8F270008 */  lw         $a3, 0x8($t9)
    /* 2CC38 8002C038 00002825 */  or         $a1, $zero, $zero
    /* 2CC3C 8002C03C 000F6080 */  sll        $t4, $t7, 2
    /* 2CC40 8002C040 AFAC0010 */  sw         $t4, 0x10($sp)
    /* 2CC44 8002C044 0C00A400 */  jal        func_80029000
    /* 2CC48 8002C048 3C060500 */   lui       $a2, (0x5000000 >> 16)
    /* 2CC4C 8002C04C 10000059 */  b          .L8002C1B4
    /* 2CC50 8002C050 24020001 */   addiu     $v0, $zero, 0x1
  .L8002C054:
    /* 2CC54 8002C054 8FA90030 */  lw         $t1, 0x30($sp)
    /* 2CC58 8002C058 2401FFFF */  addiu      $at, $zero, -0x1
    /* 2CC5C 8002C05C 8D2A0008 */  lw         $t2, 0x8($t1)
    /* 2CC60 8002C060 15410020 */  bne        $t2, $at, .L8002C0E4
    /* 2CC64 8002C064 00000000 */   nop
    /* 2CC68 8002C068 952D0004 */  lhu        $t5, 0x4($t1)
    /* 2CC6C 8002C06C 24010002 */  addiu      $at, $zero, 0x2
    /* 2CC70 8002C070 15A1001C */  bne        $t5, $at, .L8002C0E4
    /* 2CC74 8002C074 00000000 */   nop
    /* 2CC78 8002C078 952E0006 */  lhu        $t6, 0x6($t1)
    /* 2CC7C 8002C07C 24010001 */  addiu      $at, $zero, 0x1
    /* 2CC80 8002C080 15C10018 */  bne        $t6, $at, .L8002C0E4
    /* 2CC84 8002C084 00000000 */   nop
    /* 2CC88 8002C088 25280018 */  addiu      $t0, $t1, 0x18
    /* 2CC8C 8002C08C AFA80024 */  sw         $t0, 0x24($sp)
    /* 2CC90 8002C090 8D380028 */  lw         $t8, 0x28($t1)
    /* 2CC94 8002C094 17000010 */  bnez       $t8, .L8002C0D8
    /* 2CC98 8002C098 00000000 */   nop
    /* 2CC9C 8002C09C 8D2B0020 */  lw         $t3, 0x20($t1)
    /* 2CCA0 8002C0A0 8D790000 */  lw         $t9, 0x0($t3)
    /* 2CCA4 8002C0A4 8D6F0004 */  lw         $t7, 0x4($t3)
    /* 2CCA8 8002C0A8 8D6A0008 */  lw         $t2, 0x8($t3)
    /* 2CCAC 8002C0AC 8D6E000C */  lw         $t6, 0xC($t3)
    /* 2CCB0 8002C0B0 032F6025 */  or         $t4, $t9, $t7
    /* 2CCB4 8002C0B4 018A6825 */  or         $t5, $t4, $t2
    /* 2CCB8 8002C0B8 01CD4025 */  or         $t0, $t6, $t5
    /* 2CCBC 8002C0BC 11000006 */  beqz       $t0, .L8002C0D8
    /* 2CCC0 8002C0C0 00000000 */   nop
    /* 2CCC4 8002C0C4 24180018 */  addiu      $t8, $zero, 0x18
    /* 2CCC8 8002C0C8 0C00B071 */  jal        func_8002C1C4
    /* 2CCCC 8002C0CC AD380018 */   sw        $t8, 0x18($t1)
    /* 2CCD0 8002C0D0 10000038 */  b          .L8002C1B4
    /* 2CCD4 8002C0D4 24020001 */   addiu     $v0, $zero, 0x1
  .L8002C0D8:
    /* 2CCD8 8002C0D8 8FB90024 */  lw         $t9, 0x24($sp)
    /* 2CCDC 8002C0DC 0C00B0AB */  jal        func_8002C2AC
    /* 2CCE0 8002C0E0 AF200000 */   sw        $zero, 0x0($t9)
  .L8002C0E4:
    /* 2CCE4 8002C0E4 8FAF0030 */  lw         $t7, 0x30($sp)
    /* 2CCE8 8002C0E8 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 2CCEC 8002C0EC 8DEC0008 */  lw         $t4, 0x8($t7)
    /* 2CCF0 8002C0F0 258A0001 */  addiu      $t2, $t4, 0x1
    /* 2CCF4 8002C0F4 ADEA0008 */  sw         $t2, 0x8($t7)
    /* 2CCF8 8002C0F8 8FAB003C */  lw         $t3, 0x3C($sp)
    /* 2CCFC 8002C0FC 01617024 */  and        $t6, $t3, $at
    /* 2CD00 8002C100 11C0001A */  beqz       $t6, .L8002C16C
    /* 2CD04 8002C104 00000000 */   nop
    /* 2CD08 8002C108 8FAD0030 */  lw         $t5, 0x30($sp)
    /* 2CD0C 8002C10C 8DA80008 */  lw         $t0, 0x8($t5)
    /* 2CD10 8002C110 29010055 */  slti       $at, $t0, 0x55
    /* 2CD14 8002C114 14200007 */  bnez       $at, .L8002C134
    /* 2CD18 8002C118 00000000 */   nop
    /* 2CD1C 8002C11C 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 2CD20 8002C120 24180018 */  addiu      $t8, $zero, 0x18
    /* 2CD24 8002C124 0C00B071 */  jal        func_8002C1C4
    /* 2CD28 8002C128 AD380000 */   sw        $t8, 0x0($t1)
    /* 2CD2C 8002C12C 10000021 */  b          .L8002C1B4
    /* 2CD30 8002C130 24020001 */   addiu     $v0, $zero, 0x1
  .L8002C134:
    /* 2CD34 8002C134 8FB9002C */  lw         $t9, 0x2C($sp)
    /* 2CD38 8002C138 3C048007 */  lui        $a0, %hi(D_8006F094)
    /* 2CD3C 8002C13C 3C060500 */  lui        $a2, (0x5000400 >> 16)
    /* 2CD40 8002C140 8F2C000C */  lw         $t4, 0xC($t9)
    /* 2CD44 8002C144 8F270004 */  lw         $a3, 0x4($t9)
    /* 2CD48 8002C148 34C60400 */  ori        $a2, $a2, (0x5000400 & 0xFFFF)
    /* 2CD4C 8002C14C 8C84F094 */  lw         $a0, %lo(D_8006F094)($a0)
    /* 2CD50 8002C150 00002825 */  or         $a1, $zero, $zero
    /* 2CD54 8002C154 0C00A400 */  jal        func_80029000
    /* 2CD58 8002C158 AFAC0010 */   sw        $t4, 0x10($sp)
    /* 2CD5C 8002C15C 8FAA002C */  lw         $t2, 0x2C($sp)
    /* 2CD60 8002C160 24020001 */  addiu      $v0, $zero, 0x1
    /* 2CD64 8002C164 10000013 */  b          .L8002C1B4
    /* 2CD68 8002C168 AD400000 */   sw        $zero, 0x0($t2)
  .L8002C16C:
    /* 2CD6C 8002C16C 8FAF0030 */  lw         $t7, 0x30($sp)
    /* 2CD70 8002C170 8DEB0008 */  lw         $t3, 0x8($t7)
    /* 2CD74 8002C174 29610055 */  slti       $at, $t3, 0x55
    /* 2CD78 8002C178 10200007 */  beqz       $at, .L8002C198
    /* 2CD7C 8002C17C 00000000 */   nop
    /* 2CD80 8002C180 8FAD002C */  lw         $t5, 0x2C($sp)
    /* 2CD84 8002C184 240E0018 */  addiu      $t6, $zero, 0x18
    /* 2CD88 8002C188 0C00B071 */  jal        func_8002C1C4
    /* 2CD8C 8002C18C ADAE0000 */   sw        $t6, 0x0($t5)
    /* 2CD90 8002C190 10000008 */  b          .L8002C1B4
    /* 2CD94 8002C194 24020001 */   addiu     $v0, $zero, 0x1
  .L8002C198:
    /* 2CD98 8002C198 10000006 */  b          .L8002C1B4
    /* 2CD9C 8002C19C 24020001 */   addiu     $v0, $zero, 0x1
  .L8002C1A0:
    /* 2CDA0 8002C1A0 8FB8002C */  lw         $t8, 0x2C($sp)
    /* 2CDA4 8002C1A4 24080004 */  addiu      $t0, $zero, 0x4
    /* 2CDA8 8002C1A8 0C00B071 */  jal        func_8002C1C4
    /* 2CDAC 8002C1AC AF080000 */   sw        $t0, 0x0($t8)
    /* 2CDB0 8002C1B0 24020001 */  addiu      $v0, $zero, 0x1
  .L8002C1B4:
    /* 2CDB4 8002C1B4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2CDB8 8002C1B8 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 2CDBC 8002C1BC 03E00008 */  jr         $ra
    /* 2CDC0 8002C1C0 00000000 */   nop

glabel func_8002C1C4
    /* 2CDC4 8002C1C4 3C0E8007 */  lui        $t6, %hi(D_8006F094)
    /* 2CDC8 8002C1C8 8DCEF094 */  lw         $t6, %lo(D_8006F094)($t6)
    /* 2CDCC 8002C1CC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 2CDD0 8002C1D0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2CDD4 8002C1D4 25CF0014 */  addiu      $t7, $t6, 0x14
    /* 2CDD8 8002C1D8 AFAF001C */  sw         $t7, 0x1C($sp)
    /* 2CDDC 8002C1DC 3C18A460 */  lui        $t8, %hi(D_A4600010)
    /* 2CDE0 8002C1E0 8F190010 */  lw         $t9, %lo(D_A4600010)($t8)
    /* 2CDE4 8002C1E4 AFB90018 */  sw         $t9, 0x18($sp)
    /* 2CDE8 8002C1E8 8FA80018 */  lw         $t0, 0x18($sp)
    /* 2CDEC 8002C1EC 31090003 */  andi       $t1, $t0, 0x3
    /* 2CDF0 8002C1F0 11200008 */  beqz       $t1, .L8002C214
    /* 2CDF4 8002C1F4 00000000 */   nop
  .L8002C1F8:
    /* 2CDF8 8002C1F8 3C0AA460 */  lui        $t2, %hi(D_A4600010)
    /* 2CDFC 8002C1FC 8D4B0010 */  lw         $t3, %lo(D_A4600010)($t2)
    /* 2CE00 8002C200 AFAB0018 */  sw         $t3, 0x18($sp)
    /* 2CE04 8002C204 8FAC0018 */  lw         $t4, 0x18($sp)
    /* 2CE08 8002C208 318D0003 */  andi       $t5, $t4, 0x3
    /* 2CE0C 8002C20C 15A0FFFA */  bnez       $t5, .L8002C1F8
    /* 2CE10 8002C210 00000000 */   nop
  .L8002C214:
    /* 2CE14 8002C214 8FAE001C */  lw         $t6, 0x1C($sp)
    /* 2CE18 8002C218 3C011000 */  lui        $at, (0x10000000 >> 16)
    /* 2CE1C 8002C21C 3C19A500 */  lui        $t9, %hi(D_A5000510)
    /* 2CE20 8002C220 8DCF0010 */  lw         $t7, 0x10($t6)
    /* 2CE24 8002C224 3C08A460 */  lui        $t0, %hi(D_A4600010)
    /* 2CE28 8002C228 01E1C025 */  or         $t8, $t7, $at
    /* 2CE2C 8002C22C AF380510 */  sw         $t8, %lo(D_A5000510)($t9)
    /* 2CE30 8002C230 8D090010 */  lw         $t1, %lo(D_A4600010)($t0)
    /* 2CE34 8002C234 AFA90018 */  sw         $t1, 0x18($sp)
    /* 2CE38 8002C238 8FAA0018 */  lw         $t2, 0x18($sp)
    /* 2CE3C 8002C23C 314B0003 */  andi       $t3, $t2, 0x3
    /* 2CE40 8002C240 11600008 */  beqz       $t3, .L8002C264
    /* 2CE44 8002C244 00000000 */   nop
  .L8002C248:
    /* 2CE48 8002C248 3C0CA460 */  lui        $t4, %hi(D_A4600010)
    /* 2CE4C 8002C24C 8D8D0010 */  lw         $t5, %lo(D_A4600010)($t4)
    /* 2CE50 8002C250 AFAD0018 */  sw         $t5, 0x18($sp)
    /* 2CE54 8002C254 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 2CE58 8002C258 31CF0003 */  andi       $t7, $t6, 0x3
    /* 2CE5C 8002C25C 15E0FFFA */  bnez       $t7, .L8002C248
    /* 2CE60 8002C260 00000000 */   nop
  .L8002C264:
    /* 2CE64 8002C264 8FB8001C */  lw         $t8, 0x1C($sp)
    /* 2CE68 8002C268 3C08A500 */  lui        $t0, %hi(D_A5000510)
    /* 2CE6C 8002C26C 8F190010 */  lw         $t9, 0x10($t8)
    /* 2CE70 8002C270 0C00B0AB */  jal        func_8002C2AC
    /* 2CE74 8002C274 AD190510 */   sw        $t9, %lo(D_A5000510)($t0)
    /* 2CE78 8002C278 24090002 */  addiu      $t1, $zero, 0x2
    /* 2CE7C 8002C27C 3C0AA460 */  lui        $t2, %hi(D_A4600010)
    /* 2CE80 8002C280 AD490010 */  sw         $t1, %lo(D_A4600010)($t2)
    /* 2CE84 8002C284 3C0B8003 */  lui        $t3, %hi(D_80035620)
    /* 2CE88 8002C288 8D6B5620 */  lw         $t3, %lo(D_80035620)($t3)
    /* 2CE8C 8002C28C 3C010010 */  lui        $at, (0x100401 >> 16)
    /* 2CE90 8002C290 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2CE94 8002C294 34210401 */  ori        $at, $at, (0x100401 & 0xFFFF)
    /* 2CE98 8002C298 01616025 */  or         $t4, $t3, $at
    /* 2CE9C 8002C29C 3C018003 */  lui        $at, %hi(D_80035620)
    /* 2CEA0 8002C2A0 AC2C5620 */  sw         $t4, %lo(D_80035620)($at)
    /* 2CEA4 8002C2A4 03E00008 */  jr         $ra
    /* 2CEA8 8002C2A8 27BD0020 */   addiu     $sp, $sp, 0x20

glabel func_8002C2AC
    /* 2CEAC 8002C2AC 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 2CEB0 8002C2B0 3C0E8007 */  lui        $t6, %hi(D_8006C940)
    /* 2CEB4 8002C2B4 25CEC940 */  addiu      $t6, $t6, %lo(D_8006C940)
    /* 2CEB8 8002C2B8 25CF0040 */  addiu      $t7, $t6, 0x40
    /* 2CEBC 8002C2BC AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2CEC0 8002C2C0 AFB00018 */  sw         $s0, 0x18($sp)
    /* 2CEC4 8002C2C4 AFAF002C */  sw         $t7, 0x2C($sp)
    /* 2CEC8 8002C2C8 8DD80040 */  lw         $t8, 0x40($t6)
    /* 2CECC 8002C2CC 1300002D */  beqz       $t8, .L8002C384
    /* 2CED0 8002C2D0 AFB80028 */   sw        $t8, 0x28($sp)
    /* 2CED4 8002C2D4 8F190008 */  lw         $t9, 0x8($t8)
    /* 2CED8 8002C2D8 8F080010 */  lw         $t0, 0x10($t8)
    /* 2CEDC 8002C2DC 0328082A */  slt        $at, $t9, $t0
    /* 2CEE0 8002C2E0 10200028 */  beqz       $at, .L8002C384
    /* 2CEE4 8002C2E4 00000000 */   nop
    /* 2CEE8 8002C2E8 8FA90028 */  lw         $t1, 0x28($sp)
    /* 2CEEC 8002C2EC 8FAE002C */  lw         $t6, 0x2C($sp)
    /* 2CEF0 8002C2F0 8D2A000C */  lw         $t2, 0xC($t1)
    /* 2CEF4 8002C2F4 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 2CEF8 8002C2F8 8D2D0010 */  lw         $t5, 0x10($t1)
    /* 2CEFC 8002C2FC 014B6021 */  addu       $t4, $t2, $t3
    /* 2CF00 8002C300 018D001A */  div        $zero, $t4, $t5
    /* 2CF04 8002C304 00007810 */  mfhi       $t7
    /* 2CF08 8002C308 AFAF0024 */  sw         $t7, 0x24($sp)
    /* 2CF0C 8002C30C 8D280014 */  lw         $t0, 0x14($t1)
    /* 2CF10 8002C310 8DD80004 */  lw         $t8, 0x4($t6)
    /* 2CF14 8002C314 000FC880 */  sll        $t9, $t7, 2
    /* 2CF18 8002C318 01195021 */  addu       $t2, $t0, $t9
    /* 2CF1C 8002C31C AD580000 */  sw         $t8, 0x0($t2)
    /* 2CF20 8002C320 8FAB0028 */  lw         $t3, 0x28($sp)
    /* 2CF24 8002C324 15A00002 */  bnez       $t5, .L8002C330
    /* 2CF28 8002C328 00000000 */   nop
    /* 2CF2C 8002C32C 0007000D */  break      7
  .L8002C330:
    /* 2CF30 8002C330 2401FFFF */  addiu      $at, $zero, -0x1
    /* 2CF34 8002C334 15A10004 */  bne        $t5, $at, .L8002C348
    /* 2CF38 8002C338 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 2CF3C 8002C33C 15810002 */  bne        $t4, $at, .L8002C348
    /* 2CF40 8002C340 00000000 */   nop
    /* 2CF44 8002C344 0006000D */  break      6
  .L8002C348:
    /* 2CF48 8002C348 8D6C0008 */  lw         $t4, 0x8($t3)
    /* 2CF4C 8002C34C 258D0001 */  addiu      $t5, $t4, 0x1
    /* 2CF50 8002C350 AD6D0008 */  sw         $t5, 0x8($t3)
    /* 2CF54 8002C354 8FAE0028 */  lw         $t6, 0x28($sp)
    /* 2CF58 8002C358 8DCF0000 */  lw         $t7, 0x0($t6)
    /* 2CF5C 8002C35C 8DE90000 */  lw         $t1, 0x0($t7)
    /* 2CF60 8002C360 11200008 */  beqz       $t1, .L8002C384
    /* 2CF64 8002C364 00000000 */   nop
    /* 2CF68 8002C368 0C008E05 */  jal        func_80023814
    /* 2CF6C 8002C36C 01C02025 */   or        $a0, $t6, $zero
    /* 2CF70 8002C370 00408025 */  or         $s0, $v0, $zero
    /* 2CF74 8002C374 3C048003 */  lui        $a0, %hi(D_800363A8)
    /* 2CF78 8002C378 248463A8 */  addiu      $a0, $a0, %lo(D_800363A8)
    /* 2CF7C 8002C37C 0C008DF3 */  jal        func_800237CC
    /* 2CF80 8002C380 02002825 */   or        $a1, $s0, $zero
  .L8002C384:
    /* 2CF84 8002C384 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2CF88 8002C388 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2CF8C 8002C38C 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 2CF90 8002C390 03E00008 */  jr         $ra
    /* 2CF94 8002C394 00000000 */   nop
    /* 2CF98 8002C398 00000000 */  nop
    /* 2CF9C 8002C39C 00000000 */  nop
