.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002C7D0
    /* 2D3D0 8002C7D0 3C0EA410 */  lui        $t6, %hi(D_A410000C)
    /* 2D3D4 8002C7D4 8DC4000C */  lw         $a0, %lo(D_A410000C)($t6)
    /* 2D3D8 8002C7D8 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2D3DC 8002C7DC 308F0100 */  andi       $t7, $a0, 0x100
    /* 2D3E0 8002C7E0 11E00003 */  beqz       $t7, .L8002C7F0
    /* 2D3E4 8002C7E4 00000000 */   nop
    /* 2D3E8 8002C7E8 10000002 */  b          .L8002C7F4
    /* 2D3EC 8002C7EC 24020001 */   addiu     $v0, $zero, 0x1
  .L8002C7F0:
    /* 2D3F0 8002C7F0 00001025 */  or         $v0, $zero, $zero
  .L8002C7F4:
    /* 2D3F4 8002C7F4 03E00008 */  jr         $ra
    /* 2D3F8 8002C7F8 27BD0008 */   addiu     $sp, $sp, 0x8
    /* 2D3FC 8002C7FC 00000000 */  nop
