.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002C820
    /* 2D420 8002C820 44853000 */  mtc1       $a1, $ft1
    /* 2D424 8002C824 C4840010 */  lwc1       $ft0, 0x10($a0)
    /* 2D428 8002C828 C4900014 */  lwc1       $ft4, 0x14($a0)
    /* 2D42C 8002C82C 46803220 */  cvt.s.w    $ft2, $ft1
    /* 2D430 8002C830 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 2D434 8002C834 44812800 */  mtc1       $at, $ft0f
    /* 2D438 8002C838 3C014010 */  lui        $at, (0x40100000 >> 16)
    /* 2D43C 8002C83C 46082282 */  mul.s      $ft3, $ft0, $ft2
    /* 2D440 8002C840 44802000 */  mtc1       $zero, $ft0
    /* 2D444 8002C844 460A8480 */  add.s      $ft5, $ft4, $ft3
    /* 2D448 8002C848 E4920014 */  swc1       $ft5, 0x14($a0)
    /* 2D44C 8002C84C C4860014 */  lwc1       $ft1, 0x14($a0)
    /* 2D450 8002C850 46003021 */  cvt.d.s    $fv0, $ft1
    /* 2D454 8002C854 44803000 */  mtc1       $zero, $ft1
    /* 2D458 8002C858 4620203C */  c.lt.d     $ft0, $fv0
    /* 2D45C 8002C85C 00000000 */  nop
    /* 2D460 8002C860 45020009 */  bc1fl      .L8002C888
    /* 2D464 8002C864 462004A0 */   cvt.s.d   $ft5, $fv0
    /* 2D468 8002C868 44814800 */  mtc1       $at, $ft2f
    /* 2D46C 8002C86C 44804000 */  mtc1       $zero, $ft2
    /* 2D470 8002C870 00000000 */  nop
    /* 2D474 8002C874 46280401 */  sub.d      $ft4, $fv0, $ft2
    /* 2D478 8002C878 462082A0 */  cvt.s.d    $ft3, $ft4
    /* 2D47C 8002C87C 10000003 */  b          .L8002C88C
    /* 2D480 8002C880 E48A0014 */   swc1      $ft3, 0x14($a0)
    /* 2D484 8002C884 462004A0 */  cvt.s.d    $ft5, $fv0
  .L8002C888:
    /* 2D488 8002C888 E4920014 */  swc1       $ft5, 0x14($a0)
  .L8002C88C:
    /* 2D48C 8002C88C C4820014 */  lwc1       $fv1, 0x14($a0)
    /* 2D490 8002C890 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 2D494 8002C894 44814800 */  mtc1       $at, $ft2f
    /* 2D498 8002C898 4606103C */  c.lt.s     $fv1, $ft1
    /* 2D49C 8002C89C 44804000 */  mtc1       $zero, $ft2
    /* 2D4A0 8002C8A0 45020003 */  bc1fl      .L8002C8B0
    /* 2D4A4 8002C8A4 46001121 */   cvt.d.s   $ft0, $fv1
    /* 2D4A8 8002C8A8 46001087 */  neg.s      $fv1, $fv1
    /* 2D4AC 8002C8AC 46001121 */  cvt.d.s    $ft0, $fv1
  .L8002C8B0:
    /* 2D4B0 8002C8B0 C48A001C */  lwc1       $ft3, 0x1C($a0)
    /* 2D4B4 8002C8B4 46282401 */  sub.d      $ft4, $ft0, $ft2
    /* 2D4B8 8002C8B8 462080A0 */  cvt.s.d    $fv1, $ft4
    /* 2D4BC 8002C8BC 46025002 */  mul.s      $fv0, $ft3, $fv1
    /* 2D4C0 8002C8C0 03E00008 */  jr         $ra
    /* 2D4C4 8002C8C4 00000000 */   nop

glabel func_8002C8C8
    /* 2D4C8 8002C8C8 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 2D4CC 8002C8CC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2D4D0 8002C8D0 30A2FFFF */  andi       $v0, $a1, 0xFFFF
    /* 2D4D4 8002C8D4 0006C040 */  sll        $t8, $a2, 1
    /* 2D4D8 8002C8D8 3319FFFF */  andi       $t9, $t8, 0xFFFF
    /* 2D4DC 8002C8DC 00027C00 */  sll        $t7, $v0, 16
    /* 2D4E0 8002C8E0 3C010800 */  lui        $at, (0x8000000 >> 16)
    /* 2D4E4 8002C8E4 3C0A0B00 */  lui        $t2, (0xB000020 >> 16)
    /* 2D4E8 8002C8E8 00417025 */  or         $t6, $v0, $at
    /* 2D4EC 8002C8EC 01F94825 */  or         $t1, $t7, $t9
    /* 2D4F0 8002C8F0 354A0020 */  ori        $t2, $t2, (0xB000020 & 0xFFFF)
    /* 2D4F4 8002C8F4 00804025 */  or         $t0, $a0, $zero
    /* 2D4F8 8002C8F8 ACE90004 */  sw         $t1, 0x4($a3)
    /* 2D4FC 8002C8FC ACEE0000 */  sw         $t6, 0x0($a3)
    /* 2D500 8002C900 ACEA0008 */  sw         $t2, 0x8($a3)
    /* 2D504 8002C904 AFA80028 */  sw         $t0, 0x28($sp)
    /* 2D508 8002C908 AFA70034 */  sw         $a3, 0x34($sp)
    /* 2D50C 8002C90C 0C006EEC */  jal        func_8001BBB0
    /* 2D510 8002C910 24840008 */   addiu     $a0, $a0, 0x8
    /* 2D514 8002C914 8FA70034 */  lw         $a3, 0x34($sp)
    /* 2D518 8002C918 8FA80028 */  lw         $t0, 0x28($sp)
    /* 2D51C 8002C91C 3C010E00 */  lui        $at, (0xE000000 >> 16)
    /* 2D520 8002C920 24E30010 */  addiu      $v1, $a3, 0x10
    /* 2D524 8002C924 246B0008 */  addiu      $t3, $v1, 0x8
    /* 2D528 8002C928 ACE2000C */  sw         $v0, 0xC($a3)
    /* 2D52C 8002C92C AFAB0024 */  sw         $t3, 0x24($sp)
    /* 2D530 8002C930 8D0C002C */  lw         $t4, 0x2C($t0)
    /* 2D534 8002C934 850F0002 */  lh         $t7, 0x2($t0)
    /* 2D538 8002C938 318D00FF */  andi       $t5, $t4, 0xFF
    /* 2D53C 8002C93C 000D7400 */  sll        $t6, $t5, 16
    /* 2D540 8002C940 01C1C025 */  or         $t8, $t6, $at
    /* 2D544 8002C944 31F9FFFF */  andi       $t9, $t7, 0xFFFF
    /* 2D548 8002C948 03194825 */  or         $t1, $t8, $t9
    /* 2D54C 8002C94C AC690000 */  sw         $t1, 0x0($v1)
    /* 2D550 8002C950 8D040028 */  lw         $a0, 0x28($t0)
    /* 2D554 8002C954 0C006EEC */  jal        func_8001BBB0
    /* 2D558 8002C958 AFA30018 */   sw        $v1, 0x18($sp)
    /* 2D55C 8002C95C 8FA50018 */  lw         $a1, 0x18($sp)
    /* 2D560 8002C960 8FA80028 */  lw         $t0, 0x28($sp)
    /* 2D564 8002C964 ACA20004 */  sw         $v0, 0x4($a1)
    /* 2D568 8002C968 AD00002C */  sw         $zero, 0x2C($t0)
    /* 2D56C 8002C96C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2D570 8002C970 8FA20024 */  lw         $v0, 0x24($sp)
    /* 2D574 8002C974 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 2D578 8002C978 03E00008 */  jr         $ra
    /* 2D57C 8002C97C 00000000 */   nop

glabel func_8002C980
    /* 2D580 8002C980 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 2D584 8002C984 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2D588 8002C988 AFB00018 */  sw         $s0, 0x18($sp)
    /* 2D58C 8002C98C 8C83001C */  lw         $v1, 0x1C($a0)
    /* 2D590 8002C990 8C820014 */  lw         $v0, 0x14($a0)
    /* 2D594 8002C994 8FA80070 */  lw         $t0, 0x70($sp)
    /* 2D598 8002C998 00037040 */  sll        $t6, $v1, 1
    /* 2D59C 8002C99C 00A2082B */  sltu       $at, $a1, $v0
    /* 2D5A0 8002C9A0 00805025 */  or         $t2, $a0, $zero
    /* 2D5A4 8002C9A4 00C06825 */  or         $t5, $a2, $zero
    /* 2D5A8 8002C9A8 00E05825 */  or         $t3, $a3, $zero
    /* 2D5AC 8002C9AC 10200002 */  beqz       $at, .L8002C9B8
    /* 2D5B0 8002C9B0 004E4821 */   addu      $t1, $v0, $t6
    /* 2D5B4 8002C9B4 00AE2821 */  addu       $a1, $a1, $t6
  .L8002C9B8:
    /* 2D5B8 8002C9B8 000B3040 */  sll        $a2, $t3, 1
    /* 2D5BC 8002C9BC 00C53821 */  addu       $a3, $a2, $a1
    /* 2D5C0 8002C9C0 0127082B */  sltu       $at, $t1, $a3
    /* 2D5C4 8002C9C4 1020003C */  beqz       $at, .L8002CAB8
    /* 2D5C8 8002C9C8 25100008 */   addiu     $s0, $t0, 0x8
    /* 2D5CC 8002C9CC 01255823 */  subu       $t3, $t1, $a1
    /* 2D5D0 8002C9D0 000BC043 */  sra        $t8, $t3, 1
    /* 2D5D4 8002C9D4 3C0F0800 */  lui        $t7, (0x8000000 >> 16)
    /* 2D5D8 8002C9D8 AD0F0000 */  sw         $t7, 0x0($t0)
    /* 2D5DC 8002C9DC 00185840 */  sll        $t3, $t8, 1
    /* 2D5E0 8002C9E0 3178FFFF */  andi       $t8, $t3, 0xFFFF
    /* 2D5E4 8002C9E4 000D7C00 */  sll        $t7, $t5, 16
    /* 2D5E8 8002C9E8 01F8C825 */  or         $t9, $t7, $t8
    /* 2D5EC 8002C9EC 25100008 */  addiu      $s0, $t0, 0x8
    /* 2D5F0 8002C9F0 AD190004 */  sw         $t9, 0x4($t0)
    /* 2D5F4 8002C9F4 02006025 */  or         $t4, $s0, $zero
    /* 2D5F8 8002C9F8 3C0E0600 */  lui        $t6, (0x6000000 >> 16)
    /* 2D5FC 8002C9FC AD8E0000 */  sw         $t6, 0x0($t4)
    /* 2D600 8002CA00 AFAD0068 */  sw         $t5, 0x68($sp)
    /* 2D604 8002CA04 AFAC0044 */  sw         $t4, 0x44($sp)
    /* 2D608 8002CA08 AFAB0024 */  sw         $t3, 0x24($sp)
    /* 2D60C 8002CA0C AFAA0060 */  sw         $t2, 0x60($sp)
    /* 2D610 8002CA10 AFA9004C */  sw         $t1, 0x4C($sp)
    /* 2D614 8002CA14 AFA70028 */  sw         $a3, 0x28($sp)
    /* 2D618 8002CA18 AFA6002C */  sw         $a2, 0x2C($sp)
    /* 2D61C 8002CA1C 26100008 */  addiu      $s0, $s0, 0x8
    /* 2D620 8002CA20 0C006EEC */  jal        func_8001BBB0
    /* 2D624 8002CA24 00A02025 */   or        $a0, $a1, $zero
    /* 2D628 8002CA28 8FAC0044 */  lw         $t4, 0x44($sp)
    /* 2D62C 8002CA2C 8FA70028 */  lw         $a3, 0x28($sp)
    /* 2D630 8002CA30 8FA9004C */  lw         $t1, 0x4C($sp)
    /* 2D634 8002CA34 8FAB0024 */  lw         $t3, 0x24($sp)
    /* 2D638 8002CA38 8FAD0068 */  lw         $t5, 0x68($sp)
    /* 2D63C 8002CA3C 8FAA0060 */  lw         $t2, 0x60($sp)
    /* 2D640 8002CA40 02001825 */  or         $v1, $s0, $zero
    /* 2D644 8002CA44 3C0F0800 */  lui        $t7, (0x8000000 >> 16)
    /* 2D648 8002CA48 AD820004 */  sw         $v0, 0x4($t4)
    /* 2D64C 8002CA4C AC6F0000 */  sw         $t7, 0x0($v1)
    /* 2D650 8002CA50 00E97823 */  subu       $t7, $a3, $t1
    /* 2D654 8002CA54 016DC821 */  addu       $t9, $t3, $t5
    /* 2D658 8002CA58 00197400 */  sll        $t6, $t9, 16
    /* 2D65C 8002CA5C 000FC043 */  sra        $t8, $t7, 1
    /* 2D660 8002CA60 0018C840 */  sll        $t9, $t8, 1
    /* 2D664 8002CA64 332FFFFF */  andi       $t7, $t9, 0xFFFF
    /* 2D668 8002CA68 01CFC025 */  or         $t8, $t6, $t7
    /* 2D66C 8002CA6C 26100008 */  addiu      $s0, $s0, 0x8
    /* 2D670 8002CA70 AC780004 */  sw         $t8, 0x4($v1)
    /* 2D674 8002CA74 02002825 */  or         $a1, $s0, $zero
    /* 2D678 8002CA78 3C190600 */  lui        $t9, (0x6000000 >> 16)
    /* 2D67C 8002CA7C ACB90000 */  sw         $t9, 0x0($a1)
    /* 2D680 8002CA80 8D440014 */  lw         $a0, 0x14($t2)
    /* 2D684 8002CA84 AFA5003C */  sw         $a1, 0x3C($sp)
    /* 2D688 8002CA88 0C006EEC */  jal        func_8001BBB0
    /* 2D68C 8002CA8C 26100008 */   addiu     $s0, $s0, 0x8
    /* 2D690 8002CA90 8FA5003C */  lw         $a1, 0x3C($sp)
    /* 2D694 8002CA94 8FA6002C */  lw         $a2, 0x2C($sp)
    /* 2D698 8002CA98 02001825 */  or         $v1, $s0, $zero
    /* 2D69C 8002CA9C 3C0E0800 */  lui        $t6, (0x8000000 >> 16)
    /* 2D6A0 8002CAA0 ACA20004 */  sw         $v0, 0x4($a1)
    /* 2D6A4 8002CAA4 30CFFFFF */  andi       $t7, $a2, 0xFFFF
    /* 2D6A8 8002CAA8 AC6F0004 */  sw         $t7, 0x4($v1)
    /* 2D6AC 8002CAAC AC6E0000 */  sw         $t6, 0x0($v1)
    /* 2D6B0 8002CAB0 10000010 */  b          .L8002CAF4
    /* 2D6B4 8002CAB4 26100008 */   addiu     $s0, $s0, 0x8
  .L8002CAB8:
    /* 2D6B8 8002CAB8 3C180800 */  lui        $t8, (0x8000000 >> 16)
    /* 2D6BC 8002CABC AD180000 */  sw         $t8, 0x0($t0)
    /* 2D6C0 8002CAC0 000D7400 */  sll        $t6, $t5, 16
    /* 2D6C4 8002CAC4 30CFFFFF */  andi       $t7, $a2, 0xFFFF
    /* 2D6C8 8002CAC8 01CFC025 */  or         $t8, $t6, $t7
    /* 2D6CC 8002CACC AD180004 */  sw         $t8, 0x4($t0)
    /* 2D6D0 8002CAD0 02001825 */  or         $v1, $s0, $zero
    /* 2D6D4 8002CAD4 3C190600 */  lui        $t9, (0x6000000 >> 16)
    /* 2D6D8 8002CAD8 AC790000 */  sw         $t9, 0x0($v1)
    /* 2D6DC 8002CADC AFA30030 */  sw         $v1, 0x30($sp)
    /* 2D6E0 8002CAE0 26100008 */  addiu      $s0, $s0, 0x8
    /* 2D6E4 8002CAE4 0C006EEC */  jal        func_8001BBB0
    /* 2D6E8 8002CAE8 00A02025 */   or        $a0, $a1, $zero
    /* 2D6EC 8002CAEC 8FA30030 */  lw         $v1, 0x30($sp)
    /* 2D6F0 8002CAF0 AC620004 */  sw         $v0, 0x4($v1)
  .L8002CAF4:
    /* 2D6F4 8002CAF4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2D6F8 8002CAF8 02001025 */  or         $v0, $s0, $zero
    /* 2D6FC 8002CAFC 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2D700 8002CB00 03E00008 */  jr         $ra
    /* 2D704 8002CB04 27BD0060 */   addiu     $sp, $sp, 0x60

glabel func_8002CB08
    /* 2D708 8002CB08 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 2D70C 8002CB0C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2D710 8002CB10 AFB00018 */  sw         $s0, 0x18($sp)
    /* 2D714 8002CB14 8C83001C */  lw         $v1, 0x1C($a0)
    /* 2D718 8002CB18 8C820014 */  lw         $v0, 0x14($a0)
    /* 2D71C 8002CB1C 8FA80070 */  lw         $t0, 0x70($sp)
    /* 2D720 8002CB20 00037040 */  sll        $t6, $v1, 1
    /* 2D724 8002CB24 00A2082B */  sltu       $at, $a1, $v0
    /* 2D728 8002CB28 00805025 */  or         $t2, $a0, $zero
    /* 2D72C 8002CB2C 00C06825 */  or         $t5, $a2, $zero
    /* 2D730 8002CB30 00E05825 */  or         $t3, $a3, $zero
    /* 2D734 8002CB34 10200002 */  beqz       $at, .L8002CB40
    /* 2D738 8002CB38 004E4821 */   addu      $t1, $v0, $t6
    /* 2D73C 8002CB3C 00AE2821 */  addu       $a1, $a1, $t6
  .L8002CB40:
    /* 2D740 8002CB40 000B3040 */  sll        $a2, $t3, 1
    /* 2D744 8002CB44 00C53821 */  addu       $a3, $a2, $a1
    /* 2D748 8002CB48 0127082B */  sltu       $at, $t1, $a3
    /* 2D74C 8002CB4C 10200037 */  beqz       $at, .L8002CC2C
    /* 2D750 8002CB50 25100008 */   addiu     $s0, $t0, 0x8
    /* 2D754 8002CB54 31AFFFFF */  andi       $t7, $t5, 0xFFFF
    /* 2D758 8002CB58 3C010800 */  lui        $at, (0x8000000 >> 16)
    /* 2D75C 8002CB5C 01255823 */  subu       $t3, $t1, $a1
    /* 2D760 8002CB60 000BC843 */  sra        $t9, $t3, 1
    /* 2D764 8002CB64 01E1C025 */  or         $t8, $t7, $at
    /* 2D768 8002CB68 00197040 */  sll        $t6, $t9, 1
    /* 2D76C 8002CB6C 31CFFFFF */  andi       $t7, $t6, 0xFFFF
    /* 2D770 8002CB70 AD180000 */  sw         $t8, 0x0($t0)
    /* 2D774 8002CB74 25100008 */  addiu      $s0, $t0, 0x8
    /* 2D778 8002CB78 AD0F0004 */  sw         $t7, 0x4($t0)
    /* 2D77C 8002CB7C 02006025 */  or         $t4, $s0, $zero
    /* 2D780 8002CB80 3C180400 */  lui        $t8, (0x4000000 >> 16)
    /* 2D784 8002CB84 AD980000 */  sw         $t8, 0x0($t4)
    /* 2D788 8002CB88 AFAD0068 */  sw         $t5, 0x68($sp)
    /* 2D78C 8002CB8C AFAC0044 */  sw         $t4, 0x44($sp)
    /* 2D790 8002CB90 AFAE0024 */  sw         $t6, 0x24($sp)
    /* 2D794 8002CB94 AFAA0060 */  sw         $t2, 0x60($sp)
    /* 2D798 8002CB98 AFA9004C */  sw         $t1, 0x4C($sp)
    /* 2D79C 8002CB9C AFA70028 */  sw         $a3, 0x28($sp)
    /* 2D7A0 8002CBA0 AFA6002C */  sw         $a2, 0x2C($sp)
    /* 2D7A4 8002CBA4 26100008 */  addiu      $s0, $s0, 0x8
    /* 2D7A8 8002CBA8 0C006EEC */  jal        func_8001BBB0
    /* 2D7AC 8002CBAC 00A02025 */   or        $a0, $a1, $zero
    /* 2D7B0 8002CBB0 8FAB0024 */  lw         $t3, 0x24($sp)
    /* 2D7B4 8002CBB4 8FAD0068 */  lw         $t5, 0x68($sp)
    /* 2D7B8 8002CBB8 8FA70028 */  lw         $a3, 0x28($sp)
    /* 2D7BC 8002CBBC 8FA9004C */  lw         $t1, 0x4C($sp)
    /* 2D7C0 8002CBC0 8FAC0044 */  lw         $t4, 0x44($sp)
    /* 2D7C4 8002CBC4 016DC821 */  addu       $t9, $t3, $t5
    /* 2D7C8 8002CBC8 332EFFFF */  andi       $t6, $t9, 0xFFFF
    /* 2D7CC 8002CBCC 3C010800 */  lui        $at, (0x8000000 >> 16)
    /* 2D7D0 8002CBD0 8FAA0060 */  lw         $t2, 0x60($sp)
    /* 2D7D4 8002CBD4 01C17825 */  or         $t7, $t6, $at
    /* 2D7D8 8002CBD8 00E9C023 */  subu       $t8, $a3, $t1
    /* 2D7DC 8002CBDC 0018C843 */  sra        $t9, $t8, 1
    /* 2D7E0 8002CBE0 02001825 */  or         $v1, $s0, $zero
    /* 2D7E4 8002CBE4 AD820004 */  sw         $v0, 0x4($t4)
    /* 2D7E8 8002CBE8 AC6F0000 */  sw         $t7, 0x0($v1)
    /* 2D7EC 8002CBEC 00197040 */  sll        $t6, $t9, 1
    /* 2D7F0 8002CBF0 31CFFFFF */  andi       $t7, $t6, 0xFFFF
    /* 2D7F4 8002CBF4 26100008 */  addiu      $s0, $s0, 0x8
    /* 2D7F8 8002CBF8 AC6F0004 */  sw         $t7, 0x4($v1)
    /* 2D7FC 8002CBFC 02002825 */  or         $a1, $s0, $zero
    /* 2D800 8002CC00 3C180400 */  lui        $t8, (0x4000000 >> 16)
    /* 2D804 8002CC04 ACB80000 */  sw         $t8, 0x0($a1)
    /* 2D808 8002CC08 8D440014 */  lw         $a0, 0x14($t2)
    /* 2D80C 8002CC0C AFA5003C */  sw         $a1, 0x3C($sp)
    /* 2D810 8002CC10 0C006EEC */  jal        func_8001BBB0
    /* 2D814 8002CC14 26100008 */   addiu     $s0, $s0, 0x8
    /* 2D818 8002CC18 8FA5003C */  lw         $a1, 0x3C($sp)
    /* 2D81C 8002CC1C 8FA6002C */  lw         $a2, 0x2C($sp)
    /* 2D820 8002CC20 ACA20004 */  sw         $v0, 0x4($a1)
    /* 2D824 8002CC24 10000012 */  b          .L8002CC70
    /* 2D828 8002CC28 30C7FFFF */   andi      $a3, $a2, 0xFFFF
  .L8002CC2C:
    /* 2D82C 8002CC2C 31B9FFFF */  andi       $t9, $t5, 0xFFFF
    /* 2D830 8002CC30 3C010800 */  lui        $at, (0x8000000 >> 16)
    /* 2D834 8002CC34 03217025 */  or         $t6, $t9, $at
    /* 2D838 8002CC38 30C7FFFF */  andi       $a3, $a2, 0xFFFF
    /* 2D83C 8002CC3C AD070004 */  sw         $a3, 0x4($t0)
    /* 2D840 8002CC40 AD0E0000 */  sw         $t6, 0x0($t0)
    /* 2D844 8002CC44 02001825 */  or         $v1, $s0, $zero
    /* 2D848 8002CC48 3C0F0400 */  lui        $t7, (0x4000000 >> 16)
    /* 2D84C 8002CC4C AC6F0000 */  sw         $t7, 0x0($v1)
    /* 2D850 8002CC50 AFA70028 */  sw         $a3, 0x28($sp)
    /* 2D854 8002CC54 AFA30034 */  sw         $v1, 0x34($sp)
    /* 2D858 8002CC58 26100008 */  addiu      $s0, $s0, 0x8
    /* 2D85C 8002CC5C 0C006EEC */  jal        func_8001BBB0
    /* 2D860 8002CC60 00A02025 */   or        $a0, $a1, $zero
    /* 2D864 8002CC64 8FA30034 */  lw         $v1, 0x34($sp)
    /* 2D868 8002CC68 8FA70028 */  lw         $a3, 0x28($sp)
    /* 2D86C 8002CC6C AC620004 */  sw         $v0, 0x4($v1)
  .L8002CC70:
    /* 2D870 8002CC70 02001825 */  or         $v1, $s0, $zero
    /* 2D874 8002CC74 3C180800 */  lui        $t8, (0x8000000 >> 16)
    /* 2D878 8002CC78 AC780000 */  sw         $t8, 0x0($v1)
    /* 2D87C 8002CC7C AC670004 */  sw         $a3, 0x4($v1)
    /* 2D880 8002CC80 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2D884 8002CC84 26020008 */  addiu      $v0, $s0, 0x8
    /* 2D888 8002CC88 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2D88C 8002CC8C 03E00008 */  jr         $ra
    /* 2D890 8002CC90 27BD0060 */   addiu     $sp, $sp, 0x60

glabel func_8002CC94
    /* 2D894 8002CC94 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 2D898 8002CC98 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 2D89C 8002CC9C AFB10020 */  sw         $s1, 0x20($sp)
    /* 2D8A0 8002CCA0 AFB0001C */  sw         $s0, 0x1C($sp)
    /* 2D8A4 8002CCA4 AFA60068 */  sw         $a2, 0x68($sp)
    /* 2D8A8 8002CCA8 8CAE0024 */  lw         $t6, 0x24($a1)
    /* 2D8AC 8002CCAC 00A08025 */  or         $s0, $a1, $zero
    /* 2D8B0 8002CCB0 00E08825 */  or         $s1, $a3, $zero
    /* 2D8B4 8002CCB4 11C0006E */  beqz       $t6, .L8002CE70
    /* 2D8B8 8002CCB8 00805025 */   or        $t2, $a0, $zero
    /* 2D8BC 8002CCBC 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 2D8C0 8002CCC0 8CB80000 */  lw         $t8, 0x0($a1)
    /* 2D8C4 8002CCC4 00A02025 */  or         $a0, $a1, $zero
    /* 2D8C8 8002CCC8 00E02825 */  or         $a1, $a3, $zero
    /* 2D8CC 8002CCCC 01F8C823 */  subu       $t9, $t7, $t8
    /* 2D8D0 8002CCD0 AFB90038 */  sw         $t9, 0x38($sp)
    /* 2D8D4 8002CCD4 0C00B208 */  jal        func_8002C820
    /* 2D8D8 8002CCD8 AFAA0060 */   sw        $t2, 0x60($sp)
    /* 2D8DC 8002CCDC 8FAC0038 */  lw         $t4, 0x38($sp)
    /* 2D8E0 8002CCE0 3C014700 */  lui        $at, (0x47000000 >> 16)
    /* 2D8E4 8002CCE4 44817000 */  mtc1       $at, $fa1
    /* 2D8E8 8002CCE8 448C3000 */  mtc1       $t4, $ft1
    /* 2D8EC 8002CCEC 3C013FF0 */  lui        $at, (0x3FF00000 >> 16)
    /* 2D8F0 8002CCF0 44812800 */  mtc1       $at, $ft0f
    /* 2D8F4 8002CCF4 46803220 */  cvt.s.w    $ft2, $ft1
    /* 2D8F8 8002CCF8 44802000 */  mtc1       $zero, $ft0
    /* 2D8FC 8002CCFC 8FA40060 */  lw         $a0, 0x60($sp)
    /* 2D900 8002CD00 24060280 */  addiu      $a2, $zero, 0x280
    /* 2D904 8002CD04 46080283 */  div.s      $ft3, $fv0, $ft2
    /* 2D908 8002CD08 460E5402 */  mul.s      $ft4, $ft3, $fa1
    /* 2D90C 8002CD0C 4600848D */  trunc.w.s  $ft5, $ft4
    /* 2D910 8002CD10 440E9000 */  mfc1       $t6, $ft5
    /* 2D914 8002CD14 00000000 */  nop
    /* 2D918 8002CD18 448E3000 */  mtc1       $t6, $ft1
    /* 2D91C 8002CD1C 00000000 */  nop
    /* 2D920 8002CD20 46803220 */  cvt.s.w    $ft2, $ft1
    /* 2D924 8002CD24 460E4283 */  div.s      $ft3, $ft2, $fa1
    /* 2D928 8002CD28 44914000 */  mtc1       $s1, $ft2
    /* 2D92C 8002CD2C 46005421 */  cvt.d.s    $ft4, $ft3
    /* 2D930 8002CD30 468042A0 */  cvt.s.w    $ft3, $ft2
    /* 2D934 8002CD34 46302481 */  sub.d      $ft5, $ft0, $ft4
    /* 2D938 8002CD38 462090A0 */  cvt.s.d    $fv1, $ft5
    /* 2D93C 8002CD3C 460A1102 */  mul.s      $ft0, $fv1, $ft3
    /* 2D940 8002CD40 E7A20044 */  swc1       $fv1, 0x44($sp)
    /* 2D944 8002CD44 8E020024 */  lw         $v0, 0x24($s0)
    /* 2D948 8002CD48 C4460020 */  lwc1       $ft1, 0x20($v0)
    /* 2D94C 8002CD4C 46043300 */  add.s      $fa0, $ft1, $ft0
    /* 2D950 8002CD50 4600640D */  trunc.w.s  $ft4, $fa0
    /* 2D954 8002CD54 44098000 */  mfc1       $t1, $ft4
    /* 2D958 8002CD58 00000000 */  nop
    /* 2D95C 8002CD5C 44899000 */  mtc1       $t1, $ft5
    /* 2D960 8002CD60 00000000 */  nop
    /* 2D964 8002CD64 46809220 */  cvt.s.w    $ft2, $ft5
    /* 2D968 8002CD68 46086281 */  sub.s      $ft3, $fa0, $ft2
    /* 2D96C 8002CD6C E44A0020 */  swc1       $ft3, 0x20($v0)
    /* 2D970 8002CD70 8E190018 */  lw         $t9, 0x18($s0)
    /* 2D974 8002CD74 8E180004 */  lw         $t8, 0x4($s0)
    /* 2D978 8002CD78 8C8F0018 */  lw         $t7, 0x18($a0)
    /* 2D97C 8002CD7C AFA9002C */  sw         $t1, 0x2C($sp)
    /* 2D980 8002CD80 03196023 */  subu       $t4, $t8, $t9
    /* 2D984 8002CD84 000C6823 */  negu       $t5, $t4
    /* 2D988 8002CD88 000D7040 */  sll        $t6, $t5, 1
    /* 2D98C 8002CD8C 01EE4021 */  addu       $t0, $t7, $t6
    /* 2D990 8002CD90 31030007 */  andi       $v1, $t0, 0x7
    /* 2D994 8002CD94 8FB90070 */  lw         $t9, 0x70($sp)
    /* 2D998 8002CD98 0003C043 */  sra        $t8, $v1, 1
    /* 2D99C 8002CD9C 00185840 */  sll        $t3, $t8, 1
    /* 2D9A0 8002CDA0 010B2823 */  subu       $a1, $t0, $t3
    /* 2D9A4 8002CDA4 AFAB0028 */  sw         $t3, 0x28($sp)
    /* 2D9A8 8002CDA8 03001825 */  or         $v1, $t8, $zero
    /* 2D9AC 8002CDAC 01383821 */  addu       $a3, $t1, $t8
    /* 2D9B0 8002CDB0 0C00B2C2 */  jal        func_8002CB08
    /* 2D9B4 8002CDB4 AFB90010 */   sw        $t9, 0x10($sp)
    /* 2D9B8 8002CDB8 8FAB0028 */  lw         $t3, 0x28($sp)
    /* 2D9BC 8002CDBC 3C010800 */  lui        $at, (0x8000000 >> 16)
    /* 2D9C0 8002CDC0 244E0008 */  addiu      $t6, $v0, 0x8
    /* 2D9C4 8002CDC4 256C0280 */  addiu      $t4, $t3, 0x280
    /* 2D9C8 8002CDC8 318DFFFF */  andi       $t5, $t4, 0xFFFF
    /* 2D9CC 8002CDCC 01A17825 */  or         $t7, $t5, $at
    /* 2D9D0 8002CDD0 AC4F0000 */  sw         $t7, 0x0($v0)
    /* 2D9D4 8002CDD4 8FB80068 */  lw         $t8, 0x68($sp)
    /* 2D9D8 8002CDD8 00116040 */  sll        $t4, $s1, 1
    /* 2D9DC 8002CDDC 318DFFFF */  andi       $t5, $t4, 0xFFFF
    /* 2D9E0 8002CDE0 0018CC00 */  sll        $t9, $t8, 16
    /* 2D9E4 8002CDE4 032D7825 */  or         $t7, $t9, $t5
    /* 2D9E8 8002CDE8 AC4F0004 */  sw         $t7, 0x4($v0)
    /* 2D9EC 8002CDEC 3C014700 */  lui        $at, (0x47000000 >> 16)
    /* 2D9F0 8002CDF0 44812000 */  mtc1       $at, $ft0
    /* 2D9F4 8002CDF4 C7A60044 */  lwc1       $ft1, 0x44($sp)
    /* 2D9F8 8002CDF8 AFAE0030 */  sw         $t6, 0x30($sp)
    /* 2D9FC 8002CDFC 8E0D0024 */  lw         $t5, 0x24($s0)
    /* 2DA00 8002CE00 46043402 */  mul.s      $ft4, $ft1, $ft0
    /* 2DA04 8002CE04 3C010500 */  lui        $at, (0x5000000 >> 16)
    /* 2DA08 8002CE08 8DAF0024 */  lw         $t7, 0x24($t5)
    /* 2DA0C 8002CE0C 24430010 */  addiu      $v1, $v0, 0x10
    /* 2DA10 8002CE10 31EE00FF */  andi       $t6, $t7, 0xFF
    /* 2DA14 8002CE14 000EC400 */  sll        $t8, $t6, 16
    /* 2DA18 8002CE18 4600848D */  trunc.w.s  $ft5, $ft4
    /* 2DA1C 8002CE1C 440C9000 */  mfc1       $t4, $ft5
    /* 2DA20 8002CE20 00000000 */  nop
    /* 2DA24 8002CE24 3199FFFF */  andi       $t9, $t4, 0xFFFF
    /* 2DA28 8002CE28 03016025 */  or         $t4, $t8, $at
    /* 2DA2C 8002CE2C 01996825 */  or         $t5, $t4, $t9
    /* 2DA30 8002CE30 AC4D0008 */  sw         $t5, 0x8($v0)
    /* 2DA34 8002CE34 8E0F0024 */  lw         $t7, 0x24($s0)
    /* 2DA38 8002CE38 8DE40014 */  lw         $a0, 0x14($t7)
    /* 2DA3C 8002CE3C 0C006EEC */  jal        func_8001BBB0
    /* 2DA40 8002CE40 AFA3005C */   sw        $v1, 0x5C($sp)
    /* 2DA44 8002CE44 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 2DA48 8002CE48 8FA9002C */  lw         $t1, 0x2C($sp)
    /* 2DA4C 8002CE4C 8FA3005C */  lw         $v1, 0x5C($sp)
    /* 2DA50 8002CE50 ADC20004 */  sw         $v0, 0x4($t6)
    /* 2DA54 8002CE54 8E180024 */  lw         $t8, 0x24($s0)
    /* 2DA58 8002CE58 AF000024 */  sw         $zero, 0x24($t8)
    /* 2DA5C 8002CE5C 8E0C0018 */  lw         $t4, 0x18($s0)
    /* 2DA60 8002CE60 0189C821 */  addu       $t9, $t4, $t1
    /* 2DA64 8002CE64 03316823 */  subu       $t5, $t9, $s1
    /* 2DA68 8002CE68 1000000D */  b          .L8002CEA0
    /* 2DA6C 8002CE6C AE0D0018 */   sw        $t5, 0x18($s0)
  .L8002CE70:
    /* 2DA70 8002CE70 8E0E0004 */  lw         $t6, 0x4($s0)
    /* 2DA74 8002CE74 8D4F0018 */  lw         $t7, 0x18($t2)
    /* 2DA78 8002CE78 8FB90070 */  lw         $t9, 0x70($sp)
    /* 2DA7C 8002CE7C 000EC023 */  negu       $t8, $t6
    /* 2DA80 8002CE80 00186040 */  sll        $t4, $t8, 1
    /* 2DA84 8002CE84 01402025 */  or         $a0, $t2, $zero
    /* 2DA88 8002CE88 8FA60068 */  lw         $a2, 0x68($sp)
    /* 2DA8C 8002CE8C 02203825 */  or         $a3, $s1, $zero
    /* 2DA90 8002CE90 01EC2821 */  addu       $a1, $t7, $t4
    /* 2DA94 8002CE94 0C00B2C2 */  jal        func_8002CB08
    /* 2DA98 8002CE98 AFB90010 */   sw        $t9, 0x10($sp)
    /* 2DA9C 8002CE9C 00401825 */  or         $v1, $v0, $zero
  .L8002CEA0:
    /* 2DAA0 8002CEA0 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 2DAA4 8002CEA4 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 2DAA8 8002CEA8 8FB10020 */  lw         $s1, 0x20($sp)
    /* 2DAAC 8002CEAC 27BD0060 */  addiu      $sp, $sp, 0x60
    /* 2DAB0 8002CEB0 03E00008 */  jr         $ra
    /* 2DAB4 8002CEB4 00601025 */   or        $v0, $v1, $zero

glabel func_8002CEB8
    /* 2DAB8 8002CEB8 24A3FFFE */  addiu      $v1, $a1, -0x2
    /* 2DABC 8002CEBC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2DAC0 8002CEC0 306E0007 */  andi       $t6, $v1, 0x7
    /* 2DAC4 8002CEC4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2DAC8 8002CEC8 2DC10008 */  sltiu      $at, $t6, 0x8
    /* 2DACC 8002CECC 00803825 */  or         $a3, $a0, $zero
    /* 2DAD0 8002CED0 1020008B */  beqz       $at, .L8002D100
    /* 2DAD4 8002CED4 8CC80000 */   lw        $t0, 0x0($a2)
    /* 2DAD8 8002CED8 000E7080 */  sll        $t6, $t6, 2
    /* 2DADC 8002CEDC 3C018004 */  lui        $at, %hi(jtbl_8003A000)
    /* 2DAE0 8002CEE0 002E0821 */  addu       $at, $at, $t6
    /* 2DAE4 8002CEE4 8C2EA000 */  lw         $t6, %lo(jtbl_8003A000)($at)
    /* 2DAE8 8002CEE8 01C00008 */  jr         $t6
    /* 2DAEC 8002CEEC 00000000 */   nop
    /* 2DAF0 8002CEF0 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 2DAF4 8002CEF4 01017824 */  and        $t7, $t0, $at
    /* 2DAF8 8002CEF8 8CF80020 */  lw         $t8, 0x20($a3)
    /* 2DAFC 8002CEFC 04610003 */  bgez       $v1, .L8002CF0C
    /* 2DB00 8002CF00 0003C8C3 */   sra       $t9, $v1, 3
    /* 2DB04 8002CF04 24610007 */  addiu      $at, $v1, 0x7
    /* 2DB08 8002CF08 0001C8C3 */  sra        $t9, $at, 3
  .L8002CF0C:
    /* 2DB0C 8002CF0C 00194880 */  sll        $t1, $t9, 2
    /* 2DB10 8002CF10 01394821 */  addu       $t1, $t1, $t9
    /* 2DB14 8002CF14 000948C0 */  sll        $t1, $t1, 3
    /* 2DB18 8002CF18 03095021 */  addu       $t2, $t8, $t1
    /* 2DB1C 8002CF1C 10000078 */  b          .L8002D100
    /* 2DB20 8002CF20 AD4F0000 */   sw        $t7, 0x0($t2)
    /* 2DB24 8002CF24 2401FFF8 */  addiu      $at, $zero, -0x8
    /* 2DB28 8002CF28 01015824 */  and        $t3, $t0, $at
    /* 2DB2C 8002CF2C 8CEC0020 */  lw         $t4, 0x20($a3)
    /* 2DB30 8002CF30 04610003 */  bgez       $v1, .L8002CF40
    /* 2DB34 8002CF34 000368C3 */   sra       $t5, $v1, 3
    /* 2DB38 8002CF38 24610007 */  addiu      $at, $v1, 0x7
    /* 2DB3C 8002CF3C 000168C3 */  sra        $t5, $at, 3
  .L8002CF40:
    /* 2DB40 8002CF40 000D7080 */  sll        $t6, $t5, 2
    /* 2DB44 8002CF44 01CD7021 */  addu       $t6, $t6, $t5
    /* 2DB48 8002CF48 000E70C0 */  sll        $t6, $t6, 3
    /* 2DB4C 8002CF4C 018EC821 */  addu       $t9, $t4, $t6
    /* 2DB50 8002CF50 1000006B */  b          .L8002D100
    /* 2DB54 8002CF54 AF2B0004 */   sw        $t3, 0x4($t9)
    /* 2DB58 8002CF58 8CF80020 */  lw         $t8, 0x20($a3)
    /* 2DB5C 8002CF5C 04610003 */  bgez       $v1, .L8002CF6C
    /* 2DB60 8002CF60 000348C3 */   sra       $t1, $v1, 3
    /* 2DB64 8002CF64 24610007 */  addiu      $at, $v1, 0x7
    /* 2DB68 8002CF68 000148C3 */  sra        $t1, $at, 3
  .L8002CF6C:
    /* 2DB6C 8002CF6C 00097880 */  sll        $t7, $t1, 2
    /* 2DB70 8002CF70 01E97821 */  addu       $t7, $t7, $t1
    /* 2DB74 8002CF74 000F78C0 */  sll        $t7, $t7, 3
    /* 2DB78 8002CF78 030F5021 */  addu       $t2, $t8, $t7
    /* 2DB7C 8002CF7C 10000060 */  b          .L8002D100
    /* 2DB80 8002CF80 A5480008 */   sh        $t0, 0x8($t2)
    /* 2DB84 8002CF84 8CED0020 */  lw         $t5, 0x20($a3)
    /* 2DB88 8002CF88 04610003 */  bgez       $v1, .L8002CF98
    /* 2DB8C 8002CF8C 000360C3 */   sra       $t4, $v1, 3
    /* 2DB90 8002CF90 24610007 */  addiu      $at, $v1, 0x7
    /* 2DB94 8002CF94 000160C3 */  sra        $t4, $at, 3
  .L8002CF98:
    /* 2DB98 8002CF98 000C7080 */  sll        $t6, $t4, 2
    /* 2DB9C 8002CF9C 01CC7021 */  addu       $t6, $t6, $t4
    /* 2DBA0 8002CFA0 000E70C0 */  sll        $t6, $t6, 3
    /* 2DBA4 8002CFA4 01AE5821 */  addu       $t3, $t5, $t6
    /* 2DBA8 8002CFA8 10000055 */  b          .L8002D100
    /* 2DBAC 8002CFAC A568000A */   sh        $t0, 0xA($t3)
    /* 2DBB0 8002CFB0 8CF90020 */  lw         $t9, 0x20($a3)
    /* 2DBB4 8002CFB4 04610003 */  bgez       $v1, .L8002CFC4
    /* 2DBB8 8002CFB8 000348C3 */   sra       $t1, $v1, 3
    /* 2DBBC 8002CFBC 24610007 */  addiu      $at, $v1, 0x7
    /* 2DBC0 8002CFC0 000148C3 */  sra        $t1, $at, 3
  .L8002CFC4:
    /* 2DBC4 8002CFC4 0009C080 */  sll        $t8, $t1, 2
    /* 2DBC8 8002CFC8 0309C021 */  addu       $t8, $t8, $t1
    /* 2DBCC 8002CFCC 0018C0C0 */  sll        $t8, $t8, 3
    /* 2DBD0 8002CFD0 03387821 */  addu       $t7, $t9, $t8
    /* 2DBD4 8002CFD4 1000004A */  b          .L8002D100
    /* 2DBD8 8002CFD8 A5E8000C */   sh        $t0, 0xC($t7)
    /* 2DBDC 8002CFDC 44882000 */  mtc1       $t0, $ft0
    /* 2DBE0 8002CFE0 3C01447A */  lui        $at, (0x447A0000 >> 16)
    /* 2DBE4 8002CFE4 44814000 */  mtc1       $at, $ft2
    /* 2DBE8 8002CFE8 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 2DBEC 8002CFEC 3C0A8003 */  lui        $t2, %hi(D_80034DD0)
    /* 2DBF0 8002CFF0 8D4A4DD0 */  lw         $t2, %lo(D_80034DD0)($t2)
    /* 2DBF4 8002CFF4 8CED0020 */  lw         $t5, 0x20($a3)
    /* 2DBF8 8002CFF8 8D4C0044 */  lw         $t4, 0x44($t2)
    /* 2DBFC 8002CFFC 46083283 */  div.s      $ft3, $ft1, $ft2
    /* 2DC00 8002D000 448C9000 */  mtc1       $t4, $ft5
    /* 2DC04 8002D004 00000000 */  nop
    /* 2DC08 8002D008 46809121 */  cvt.d.w    $ft0, $ft5
    /* 2DC0C 8002D00C 46005021 */  cvt.d.s    $fv0, $ft3
    /* 2DC10 8002D010 46200400 */  add.d      $ft4, $fv0, $fv0
    /* 2DC14 8002D014 46248183 */  div.d      $ft1, $ft4, $ft0
    /* 2DC18 8002D018 46203220 */  cvt.s.d    $ft2, $ft1
    /* 2DC1C 8002D01C 04610003 */  bgez       $v1, .L8002D02C
    /* 2DC20 8002D020 000370C3 */   sra       $t6, $v1, 3
    /* 2DC24 8002D024 24610007 */  addiu      $at, $v1, 0x7
    /* 2DC28 8002D028 000170C3 */  sra        $t6, $at, 3
  .L8002D02C:
    /* 2DC2C 8002D02C 000E5880 */  sll        $t3, $t6, 2
    /* 2DC30 8002D030 016E5821 */  addu       $t3, $t3, $t6
    /* 2DC34 8002D034 000B58C0 */  sll        $t3, $t3, 3
    /* 2DC38 8002D038 01AB4821 */  addu       $t1, $t5, $t3
    /* 2DC3C 8002D03C 10000030 */  b          .L8002D100
    /* 2DC40 8002D040 E5280010 */   swc1      $ft2, 0x10($t1)
    /* 2DC44 8002D044 8CF90020 */  lw         $t9, 0x20($a3)
    /* 2DC48 8002D048 04610003 */  bgez       $v1, .L8002D058
    /* 2DC4C 8002D04C 0003C0C3 */   sra       $t8, $v1, 3
    /* 2DC50 8002D050 24610007 */  addiu      $at, $v1, 0x7
    /* 2DC54 8002D054 0001C0C3 */  sra        $t8, $at, 3
  .L8002D058:
    /* 2DC58 8002D058 00187880 */  sll        $t7, $t8, 2
    /* 2DC5C 8002D05C 01F87821 */  addu       $t7, $t7, $t8
    /* 2DC60 8002D060 000F78C0 */  sll        $t7, $t7, 3
    /* 2DC64 8002D064 032F1021 */  addu       $v0, $t9, $t7
    /* 2DC68 8002D068 8C4A0004 */  lw         $t2, 0x4($v0)
    /* 2DC6C 8002D06C 8C4C0000 */  lw         $t4, 0x0($v0)
    /* 2DC70 8002D070 44882000 */  mtc1       $t0, $ft0
    /* 2DC74 8002D074 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* 2DC78 8002D078 014C7023 */  subu       $t6, $t2, $t4
    /* 2DC7C 8002D07C 448E5000 */  mtc1       $t6, $ft3
    /* 2DC80 8002D080 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 2DC84 8002D084 05C10005 */  bgez       $t6, .L8002D09C
    /* 2DC88 8002D088 468054A1 */   cvt.d.w   $ft5, $ft3
    /* 2DC8C 8002D08C 44818800 */  mtc1       $at, $ft4f
    /* 2DC90 8002D090 44808000 */  mtc1       $zero, $ft4
    /* 2DC94 8002D094 00000000 */  nop
    /* 2DC98 8002D098 46309480 */  add.d      $ft5, $ft5, $ft4
  .L8002D09C:
    /* 2DC9C 8002D09C 3C018004 */  lui        $at, %hi(D_8003A020)
    /* 2DCA0 8002D0A0 D42AA020 */  ldc1       $ft3, %lo(D_8003A020)($at)
    /* 2DCA4 8002D0A4 46003221 */  cvt.d.s    $ft2, $ft1
    /* 2DCA8 8002D0A8 462A4403 */  div.d      $ft4, $ft2, $ft3
    /* 2DCAC 8002D0AC 46309102 */  mul.d      $ft0, $ft5, $ft4
    /* 2DCB0 8002D0B0 462021A0 */  cvt.s.d    $ft1, $ft0
    /* 2DCB4 8002D0B4 10000012 */  b          .L8002D100
    /* 2DCB8 8002D0B8 E446001C */   swc1      $ft1, 0x1C($v0)
    /* 2DCBC 8002D0BC 04610003 */  bgez       $v1, .L8002D0CC
    /* 2DCC0 8002D0C0 000310C3 */   sra       $v0, $v1, 3
    /* 2DCC4 8002D0C4 24610007 */  addiu      $at, $v1, 0x7
    /* 2DCC8 8002D0C8 000110C3 */  sra        $v0, $at, 3
  .L8002D0CC:
    /* 2DCCC 8002D0CC 8CEB0020 */  lw         $t3, 0x20($a3)
    /* 2DCD0 8002D0D0 00026880 */  sll        $t5, $v0, 2
    /* 2DCD4 8002D0D4 01A26821 */  addu       $t5, $t5, $v0
    /* 2DCD8 8002D0D8 000D68C0 */  sll        $t5, $t5, 3
    /* 2DCDC 8002D0DC 016D4821 */  addu       $t1, $t3, $t5
    /* 2DCE0 8002D0E0 8D250020 */  lw         $a1, 0x20($t1)
    /* 2DCE4 8002D0E4 50A00007 */  beql       $a1, $zero, .L8002D104
    /* 2DCE8 8002D0E8 8FBF0014 */   lw        $ra, 0x14($sp)
    /* 2DCEC 8002D0EC A4A80000 */  sh         $t0, 0x0($a1)
    /* 2DCF0 8002D0F0 8CF80020 */  lw         $t8, 0x20($a3)
    /* 2DCF4 8002D0F4 030DC821 */  addu       $t9, $t8, $t5
    /* 2DCF8 8002D0F8 0C0090C0 */  jal        func_80024300
    /* 2DCFC 8002D0FC 8F240020 */   lw        $a0, 0x20($t9)
  .L8002D100:
    /* 2DD00 8002D100 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8002D104:
    /* 2DD04 8002D104 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2DD08 8002D108 00001025 */  or         $v0, $zero, $zero
    /* 2DD0C 8002D10C 03E00008 */  jr         $ra
    /* 2DD10 8002D110 00000000 */   nop

glabel func_8002D114
    /* 2DD14 8002D114 24010001 */  addiu      $at, $zero, 0x1
    /* 2DD18 8002D118 14A10002 */  bne        $a1, $at, .L8002D124
    /* 2DD1C 8002D11C 00000000 */   nop
    /* 2DD20 8002D120 AC860000 */  sw         $a2, 0x0($a0)
  .L8002D124:
    /* 2DD24 8002D124 03E00008 */  jr         $ra
    /* 2DD28 8002D128 00001025 */   or        $v0, $zero, $zero

glabel func_8002D12C
    /* 2DD2C 8002D12C 27BDFF58 */  addiu      $sp, $sp, -0xA8
    /* 2DD30 8002D130 AFB3002C */  sw         $s3, 0x2C($sp)
    /* 2DD34 8002D134 00809825 */  or         $s3, $a0, $zero
    /* 2DD38 8002D138 AFBF0044 */  sw         $ra, 0x44($sp)
    /* 2DD3C 8002D13C AFBE0040 */  sw         $fp, 0x40($sp)
    /* 2DD40 8002D140 AFB7003C */  sw         $s7, 0x3C($sp)
    /* 2DD44 8002D144 AFB60038 */  sw         $s6, 0x38($sp)
    /* 2DD48 8002D148 AFB50034 */  sw         $s5, 0x34($sp)
    /* 2DD4C 8002D14C AFB40030 */  sw         $s4, 0x30($sp)
    /* 2DD50 8002D150 AFB20028 */  sw         $s2, 0x28($sp)
    /* 2DD54 8002D154 AFB10024 */  sw         $s1, 0x24($sp)
    /* 2DD58 8002D158 AFB00020 */  sw         $s0, 0x20($sp)
    /* 2DD5C 8002D15C 8C840000 */  lw         $a0, 0x0($a0)
    /* 2DD60 8002D160 8FAE00B8 */  lw         $t6, 0xB8($sp)
    /* 2DD64 8002D164 AFA00080 */  sw         $zero, 0x80($sp)
    /* 2DD68 8002D168 00C0B025 */  or         $s6, $a2, $zero
    /* 2DD6C 8002D16C AFAE0010 */  sw         $t6, 0x10($sp)
    /* 2DD70 8002D170 8C990004 */  lw         $t9, 0x4($a0)
    /* 2DD74 8002D174 0320F809 */  jalr       $t9
    /* 2DD78 8002D178 00000000 */   nop
    /* 2DD7C 8002D17C 00168840 */  sll        $s1, $s6, 1
    /* 2DD80 8002D180 3C180C00 */  lui        $t8, (0xC00DA83 >> 16)
    /* 2DD84 8002D184 3C0A06C0 */  lui        $t2, (0x6C006C0 >> 16)
    /* 2DD88 8002D188 3C0B0C00 */  lui        $t3, (0xC005A82 >> 16)
    /* 2DD8C 8002D18C 3C0C0800 */  lui        $t4, (0x80006C0 >> 16)
    /* 2DD90 8002D190 3229FFFF */  andi       $t1, $s1, 0xFFFF
    /* 2DD94 8002D194 3C0F0800 */  lui        $t7, (0x8000000 >> 16)
    /* 2DD98 8002D198 354A06C0 */  ori        $t2, $t2, (0x6C006C0 & 0xFFFF)
    /* 2DD9C 8002D19C 3718DA83 */  ori        $t8, $t8, (0xC00DA83 & 0xFFFF)
    /* 2DDA0 8002D1A0 358C06C0 */  ori        $t4, $t4, (0x80006C0 & 0xFFFF)
    /* 2DDA4 8002D1A4 356B5A82 */  ori        $t3, $t3, (0xC005A82 & 0xFFFF)
    /* 2DDA8 8002D1A8 AC4F0000 */  sw         $t7, 0x0($v0)
    /* 2DDAC 8002D1AC AC490004 */  sw         $t1, 0x4($v0)
    /* 2DDB0 8002D1B0 AC580008 */  sw         $t8, 0x8($v0)
    /* 2DDB4 8002D1B4 AC4A000C */  sw         $t2, 0xC($v0)
    /* 2DDB8 8002D1B8 AC4B0010 */  sw         $t3, 0x10($v0)
    /* 2DDBC 8002D1BC AC4C0014 */  sw         $t4, 0x14($v0)
    /* 2DDC0 8002D1C0 8E650018 */  lw         $a1, 0x18($s3)
    /* 2DDC4 8002D1C4 244D0018 */  addiu      $t5, $v0, 0x18
    /* 2DDC8 8002D1C8 0000A825 */  or         $s5, $zero, $zero
    /* 2DDCC 8002D1CC 24120140 */  addiu      $s2, $zero, 0x140
    /* 2DDD0 8002D1D0 AFAD0010 */  sw         $t5, 0x10($sp)
    /* 2DDD4 8002D1D4 AFA90048 */  sw         $t1, 0x48($sp)
    /* 2DDD8 8002D1D8 AFB10050 */  sw         $s1, 0x50($sp)
    /* 2DDDC 8002D1DC 02602025 */  or         $a0, $s3, $zero
    /* 2DDE0 8002D1E0 240606C0 */  addiu      $a2, $zero, 0x6C0
    /* 2DDE4 8002D1E4 0C00B260 */  jal        func_8002C980
    /* 2DDE8 8002D1E8 02C03825 */   or        $a3, $s6, $zero
    /* 2DDEC 8002D1EC 8FA30080 */  lw         $v1, 0x80($sp)
    /* 2DDF0 8002D1F0 3C0E0200 */  lui        $t6, (0x2000800 >> 16)
    /* 2DDF4 8002D1F4 35CE0800 */  ori        $t6, $t6, (0x2000800 & 0xFFFF)
    /* 2DDF8 8002D1F8 AC4E0000 */  sw         $t6, 0x0($v0)
    /* 2DDFC 8002D1FC AC510004 */  sw         $s1, 0x4($v0)
    /* 2DE00 8002D200 92790024 */  lbu        $t9, 0x24($s3)
    /* 2DE04 8002D204 24500008 */  addiu      $s0, $v0, 0x8
    /* 2DE08 8002D208 0000B825 */  or         $s7, $zero, $zero
    /* 2DE0C 8002D20C 5B200077 */  blezl      $t9, .L8002D3EC
    /* 2DE10 8002D210 8E63001C */   lw        $v1, 0x1C($s3)
    /* 2DE14 8002D214 8E620018 */  lw         $v0, 0x18($s3)
  .L8002D218:
    /* 2DE18 8002D218 8E6F0020 */  lw         $t7, 0x20($s3)
    /* 2DE1C 8002D21C 0017C080 */  sll        $t8, $s7, 2
    /* 2DE20 8002D220 0317C021 */  addu       $t8, $t8, $s7
    /* 2DE24 8002D224 0018C0C0 */  sll        $t8, $t8, 3
    /* 2DE28 8002D228 01F88821 */  addu       $s1, $t7, $t8
    /* 2DE2C 8002D22C 8E2A0000 */  lw         $t2, 0x0($s1)
    /* 2DE30 8002D230 8E2D0004 */  lw         $t5, 0x4($s1)
    /* 2DE34 8002D234 02602025 */  or         $a0, $s3, $zero
    /* 2DE38 8002D238 000A5823 */  negu       $t3, $t2
    /* 2DE3C 8002D23C 000B6040 */  sll        $t4, $t3, 1
    /* 2DE40 8002D240 000D7023 */  negu       $t6, $t5
    /* 2DE44 8002D244 004CA021 */  addu       $s4, $v0, $t4
    /* 2DE48 8002D248 000EC840 */  sll        $t9, $t6, 1
    /* 2DE4C 8002D24C 16830009 */  bne        $s4, $v1, .L8002D274
    /* 2DE50 8002D250 0059F021 */   addu      $fp, $v0, $t9
    /* 2DE54 8002D254 02407825 */  or         $t7, $s2, $zero
    /* 2DE58 8002D258 00159400 */  sll        $s2, $s5, 16
    /* 2DE5C 8002D25C 000FAC00 */  sll        $s5, $t7, 16
    /* 2DE60 8002D260 00155403 */  sra        $t2, $s5, 16
    /* 2DE64 8002D264 0012C403 */  sra        $t8, $s2, 16
    /* 2DE68 8002D268 03009025 */  or         $s2, $t8, $zero
    /* 2DE6C 8002D26C 10000007 */  b          .L8002D28C
    /* 2DE70 8002D270 0140A825 */   or        $s5, $t2, $zero
  .L8002D274:
    /* 2DE74 8002D274 02802825 */  or         $a1, $s4, $zero
    /* 2DE78 8002D278 02A03025 */  or         $a2, $s5, $zero
    /* 2DE7C 8002D27C 02C03825 */  or         $a3, $s6, $zero
    /* 2DE80 8002D280 0C00B2C2 */  jal        func_8002CB08
    /* 2DE84 8002D284 AFB00010 */   sw        $s0, 0x10($sp)
    /* 2DE88 8002D288 00408025 */  or         $s0, $v0, $zero
  .L8002D28C:
    /* 2DE8C 8002D28C 02602025 */  or         $a0, $s3, $zero
    /* 2DE90 8002D290 02202825 */  or         $a1, $s1, $zero
    /* 2DE94 8002D294 02403025 */  or         $a2, $s2, $zero
    /* 2DE98 8002D298 02C03825 */  or         $a3, $s6, $zero
    /* 2DE9C 8002D29C 0C00B325 */  jal        func_8002CC94
    /* 2DEA0 8002D2A0 AFB00010 */   sw        $s0, 0x10($sp)
    /* 2DEA4 8002D2A4 86240008 */  lh         $a0, 0x8($s1)
    /* 2DEA8 8002D2A8 00408025 */  or         $s0, $v0, $zero
    /* 2DEAC 8002D2AC 3C010C00 */  lui        $at, (0xC000000 >> 16)
    /* 2DEB0 8002D2B0 10800014 */  beqz       $a0, .L8002D304
    /* 2DEB4 8002D2B4 308CFFFF */   andi      $t4, $a0, 0xFFFF
    /* 2DEB8 8002D2B8 0015CC00 */  sll        $t9, $s5, 16
    /* 2DEBC 8002D2BC 324FFFFF */  andi       $t7, $s2, 0xFFFF
    /* 2DEC0 8002D2C0 032FC025 */  or         $t8, $t9, $t7
    /* 2DEC4 8002D2C4 01816825 */  or         $t5, $t4, $at
    /* 2DEC8 8002D2C8 AC4D0000 */  sw         $t5, 0x0($v0)
    /* 2DECC 8002D2CC AC580004 */  sw         $t8, 0x4($v0)
    /* 2DED0 8002D2D0 8E2A0024 */  lw         $t2, 0x24($s1)
    /* 2DED4 8002D2D4 24500008 */  addiu      $s0, $v0, 0x8
    /* 2DED8 8002D2D8 5540000B */  bnel       $t2, $zero, .L8002D308
    /* 2DEDC 8002D2DC 8623000A */   lh        $v1, 0xA($s1)
    /* 2DEE0 8002D2E0 8E2B0020 */  lw         $t3, 0x20($s1)
    /* 2DEE4 8002D2E4 02602025 */  or         $a0, $s3, $zero
    /* 2DEE8 8002D2E8 03C02825 */  or         $a1, $fp, $zero
    /* 2DEEC 8002D2EC 15600005 */  bnez       $t3, .L8002D304
    /* 2DEF0 8002D2F0 02403025 */   or        $a2, $s2, $zero
    /* 2DEF4 8002D2F4 02C03825 */  or         $a3, $s6, $zero
    /* 2DEF8 8002D2F8 0C00B260 */  jal        func_8002C980
    /* 2DEFC 8002D2FC AFB00010 */   sw        $s0, 0x10($sp)
    /* 2DF00 8002D300 00408025 */  or         $s0, $v0, $zero
  .L8002D304:
    /* 2DF04 8002D304 8623000A */  lh         $v1, 0xA($s1)
  .L8002D308:
    /* 2DF08 8002D308 02001025 */  or         $v0, $s0, $zero
    /* 2DF0C 8002D30C 3C010C00 */  lui        $at, (0xC000000 >> 16)
    /* 2DF10 8002D310 1060000F */  beqz       $v1, .L8002D350
    /* 2DF14 8002D314 306DFFFF */   andi      $t5, $v1, 0xFFFF
    /* 2DF18 8002D318 00127C00 */  sll        $t7, $s2, 16
    /* 2DF1C 8002D31C 32B8FFFF */  andi       $t8, $s5, 0xFFFF
    /* 2DF20 8002D320 01F85025 */  or         $t2, $t7, $t8
    /* 2DF24 8002D324 01A17025 */  or         $t6, $t5, $at
    /* 2DF28 8002D328 AC4E0000 */  sw         $t6, 0x0($v0)
    /* 2DF2C 8002D32C AC4A0004 */  sw         $t2, 0x4($v0)
    /* 2DF30 8002D330 26100008 */  addiu      $s0, $s0, 0x8
    /* 2DF34 8002D334 AFB00010 */  sw         $s0, 0x10($sp)
    /* 2DF38 8002D338 02602025 */  or         $a0, $s3, $zero
    /* 2DF3C 8002D33C 02802825 */  or         $a1, $s4, $zero
    /* 2DF40 8002D340 02A03025 */  or         $a2, $s5, $zero
    /* 2DF44 8002D344 0C00B260 */  jal        func_8002C980
    /* 2DF48 8002D348 02C03825 */   or        $a3, $s6, $zero
    /* 2DF4C 8002D34C 00408025 */  or         $s0, $v0, $zero
  .L8002D350:
    /* 2DF50 8002D350 8E240020 */  lw         $a0, 0x20($s1)
    /* 2DF54 8002D354 02402825 */  or         $a1, $s2, $zero
    /* 2DF58 8002D358 02C03025 */  or         $a2, $s6, $zero
    /* 2DF5C 8002D35C 50800005 */  beql       $a0, $zero, .L8002D374
    /* 2DF60 8002D360 8E2B0024 */   lw        $t3, 0x24($s1)
    /* 2DF64 8002D364 0C00B232 */  jal        func_8002C8C8
    /* 2DF68 8002D368 02003825 */   or        $a3, $s0, $zero
    /* 2DF6C 8002D36C 00408025 */  or         $s0, $v0, $zero
    /* 2DF70 8002D370 8E2B0024 */  lw         $t3, 0x24($s1)
  .L8002D374:
    /* 2DF74 8002D374 02602025 */  or         $a0, $s3, $zero
    /* 2DF78 8002D378 03C02825 */  or         $a1, $fp, $zero
    /* 2DF7C 8002D37C 15600005 */  bnez       $t3, .L8002D394
    /* 2DF80 8002D380 02403025 */   or        $a2, $s2, $zero
    /* 2DF84 8002D384 02C03825 */  or         $a3, $s6, $zero
    /* 2DF88 8002D388 0C00B260 */  jal        func_8002C980
    /* 2DF8C 8002D38C AFB00010 */   sw        $s0, 0x10($sp)
    /* 2DF90 8002D390 00408025 */  or         $s0, $v0, $zero
  .L8002D394:
    /* 2DF94 8002D394 8623000C */  lh         $v1, 0xC($s1)
    /* 2DF98 8002D398 26F70001 */  addiu      $s7, $s7, 0x1
    /* 2DF9C 8002D39C 00176400 */  sll        $t4, $s7, 16
    /* 2DFA0 8002D3A0 1060000A */  beqz       $v1, .L8002D3CC
    /* 2DFA4 8002D3A4 000CBC03 */   sra       $s7, $t4, 16
    /* 2DFA8 8002D3A8 02001025 */  or         $v0, $s0, $zero
    /* 2DFAC 8002D3AC 306DFFFF */  andi       $t5, $v1, 0xFFFF
    /* 2DFB0 8002D3B0 3C010C00 */  lui        $at, (0xC000000 >> 16)
    /* 2DFB4 8002D3B4 00127C00 */  sll        $t7, $s2, 16
    /* 2DFB8 8002D3B8 35F80800 */  ori        $t8, $t7, 0x800
    /* 2DFBC 8002D3BC 01A17025 */  or         $t6, $t5, $at
    /* 2DFC0 8002D3C0 AC4E0000 */  sw         $t6, 0x0($v0)
    /* 2DFC4 8002D3C4 AC580004 */  sw         $t8, 0x4($v0)
    /* 2DFC8 8002D3C8 26100008 */  addiu      $s0, $s0, 0x8
  .L8002D3CC:
    /* 2DFCC 8002D3CC 926E0024 */  lbu        $t6, 0x24($s3)
    /* 2DFD0 8002D3D0 8E2A0004 */  lw         $t2, 0x4($s1)
    /* 2DFD4 8002D3D4 8E620018 */  lw         $v0, 0x18($s3)
    /* 2DFD8 8002D3D8 02EE082A */  slt        $at, $s7, $t6
    /* 2DFDC 8002D3DC 000A5840 */  sll        $t3, $t2, 1
    /* 2DFE0 8002D3E0 1420FF8D */  bnez       $at, .L8002D218
    /* 2DFE4 8002D3E4 004B1821 */   addu      $v1, $v0, $t3
    /* 2DFE8 8002D3E8 8E63001C */  lw         $v1, 0x1C($s3)
  .L8002D3EC:
    /* 2DFEC 8002D3EC 8E790018 */  lw         $t9, 0x18($s3)
    /* 2DFF0 8002D3F0 8FAF0050 */  lw         $t7, 0x50($sp)
    /* 2DFF4 8002D3F4 8E6B0014 */  lw         $t3, 0x14($s3)
    /* 2DFF8 8002D3F8 00035040 */  sll        $t2, $v1, 1
    /* 2DFFC 8002D3FC 032FC021 */  addu       $t8, $t9, $t7
    /* 2E000 8002D400 016A6021 */  addu       $t4, $t3, $t2
    /* 2E004 8002D404 0198082B */  sltu       $at, $t4, $t8
    /* 2E008 8002D408 10200003 */  beqz       $at, .L8002D418
    /* 2E00C 8002D40C AE780018 */   sw        $t8, 0x18($s3)
    /* 2E010 8002D410 030A6823 */  subu       $t5, $t8, $t2
    /* 2E014 8002D414 AE6D0018 */  sw         $t5, 0x18($s3)
  .L8002D418:
    /* 2E018 8002D418 3C0E0A00 */  lui        $t6, (0xA000800 >> 16)
    /* 2E01C 8002D41C 35CE0800 */  ori        $t6, $t6, (0xA000800 & 0xFFFF)
    /* 2E020 8002D420 02001825 */  or         $v1, $s0, $zero
    /* 2E024 8002D424 AC6E0000 */  sw         $t6, 0x0($v1)
    /* 2E028 8002D428 8FB90048 */  lw         $t9, 0x48($sp)
    /* 2E02C 8002D42C 3C0106C0 */  lui        $at, (0x6C00000 >> 16)
    /* 2E030 8002D430 26020008 */  addiu      $v0, $s0, 0x8
    /* 2E034 8002D434 03217825 */  or         $t7, $t9, $at
    /* 2E038 8002D438 AC6F0004 */  sw         $t7, 0x4($v1)
    /* 2E03C 8002D43C 8FBF0044 */  lw         $ra, 0x44($sp)
    /* 2E040 8002D440 8FBE0040 */  lw         $fp, 0x40($sp)
    /* 2E044 8002D444 8FB7003C */  lw         $s7, 0x3C($sp)
    /* 2E048 8002D448 8FB60038 */  lw         $s6, 0x38($sp)
    /* 2E04C 8002D44C 8FB50034 */  lw         $s5, 0x34($sp)
    /* 2E050 8002D450 8FB40030 */  lw         $s4, 0x30($sp)
    /* 2E054 8002D454 8FB3002C */  lw         $s3, 0x2C($sp)
    /* 2E058 8002D458 8FB20028 */  lw         $s2, 0x28($sp)
    /* 2E05C 8002D45C 8FB10024 */  lw         $s1, 0x24($sp)
    /* 2E060 8002D460 8FB00020 */  lw         $s0, 0x20($sp)
    /* 2E064 8002D464 03E00008 */  jr         $ra
    /* 2E068 8002D468 27BD00A8 */   addiu     $sp, $sp, 0xA8
    /* 2E06C 8002D46C 00000000 */  nop
