.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002D4F0
    /* 2E0F0 8002D4F0 3C0EA480 */  lui        $t6, %hi(D_A4800018)
    /* 2E0F4 8002D4F4 8DC40018 */  lw         $a0, %lo(D_A4800018)($t6)
    /* 2E0F8 8002D4F8 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2E0FC 8002D4FC 308F0003 */  andi       $t7, $a0, 0x3
    /* 2E100 8002D500 11E00003 */  beqz       $t7, .L8002D510
    /* 2E104 8002D504 00000000 */   nop
    /* 2E108 8002D508 10000002 */  b          .L8002D514
    /* 2E10C 8002D50C 24020001 */   addiu     $v0, $zero, 0x1
  .L8002D510:
    /* 2E110 8002D510 00001025 */  or         $v0, $zero, $zero
  .L8002D514:
    /* 2E114 8002D514 03E00008 */  jr         $ra
    /* 2E118 8002D518 27BD0008 */   addiu     $sp, $sp, 0x8
    /* 2E11C 8002D51C 00000000 */  nop
