.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002D520
    /* 2E120 8002D520 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 2E124 8002D524 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 2E128 8002D528 AFA40038 */  sw         $a0, 0x38($sp)
    /* 2E12C 8002D52C AFA5003C */  sw         $a1, 0x3C($sp)
    /* 2E130 8002D530 AFA00034 */  sw         $zero, 0x34($sp)
    /* 2E134 8002D534 0C009A5C */  jal        func_80026970
    /* 2E138 8002D538 00002025 */   or        $a0, $zero, $zero
    /* 2E13C 8002D53C 3C058007 */  lui        $a1, %hi(D_8006EEC0)
    /* 2E140 8002D540 24A5EEC0 */  addiu      $a1, $a1, %lo(D_8006EEC0)
    /* 2E144 8002D544 0C009B00 */  jal        func_80026C00
    /* 2E148 8002D548 24040001 */   addiu     $a0, $zero, 0x1
    /* 2E14C 8002D54C AFA20034 */  sw         $v0, 0x34($sp)
    /* 2E150 8002D550 8FA40038 */  lw         $a0, 0x38($sp)
    /* 2E154 8002D554 27A50030 */  addiu      $a1, $sp, 0x30
    /* 2E158 8002D558 0C006E9C */  jal        func_8001BA70
    /* 2E15C 8002D55C 24060001 */   addiu     $a2, $zero, 0x1
    /* 2E160 8002D560 3C058007 */  lui        $a1, %hi(D_8006EEC0)
    /* 2E164 8002D564 24A5EEC0 */  addiu      $a1, $a1, %lo(D_8006EEC0)
    /* 2E168 8002D568 0C009B00 */  jal        func_80026C00
    /* 2E16C 8002D56C 00002025 */   or        $a0, $zero, $zero
    /* 2E170 8002D570 AFA20034 */  sw         $v0, 0x34($sp)
    /* 2E174 8002D574 8FA40038 */  lw         $a0, 0x38($sp)
    /* 2E178 8002D578 27A50030 */  addiu      $a1, $sp, 0x30
    /* 2E17C 8002D57C 0C006E9C */  jal        func_8001BA70
    /* 2E180 8002D580 24060001 */   addiu     $a2, $zero, 0x1
    /* 2E184 8002D584 27A4002F */  addiu      $a0, $sp, 0x2F
    /* 2E188 8002D588 0C009A9B */  jal        func_80026A6C
    /* 2E18C 8002D58C 27A5001C */   addiu     $a1, $sp, 0x1C
    /* 2E190 8002D590 8FAE003C */  lw         $t6, 0x3C($sp)
    /* 2E194 8002D594 000E7880 */  sll        $t7, $t6, 2
    /* 2E198 8002D598 03AFC021 */  addu       $t8, $sp, $t7
    /* 2E19C 8002D59C 9318001E */  lbu        $t8, 0x1E($t8)
    /* 2E1A0 8002D5A0 33190001 */  andi       $t9, $t8, 0x1
    /* 2E1A4 8002D5A4 13200006 */  beqz       $t9, .L8002D5C0
    /* 2E1A8 8002D5A8 00000000 */   nop
    /* 2E1AC 8002D5AC 33080002 */  andi       $t0, $t8, 0x2
    /* 2E1B0 8002D5B0 11000003 */  beqz       $t0, .L8002D5C0
    /* 2E1B4 8002D5B4 00000000 */   nop
    /* 2E1B8 8002D5B8 10000018 */  b          .L8002D61C
    /* 2E1BC 8002D5BC 24020002 */   addiu     $v0, $zero, 0x2
  .L8002D5C0:
    /* 2E1C0 8002D5C0 8FA9003C */  lw         $t1, 0x3C($sp)
    /* 2E1C4 8002D5C4 27AB001C */  addiu      $t3, $sp, 0x1C
    /* 2E1C8 8002D5C8 00095080 */  sll        $t2, $t1, 2
    /* 2E1CC 8002D5CC 014B6021 */  addu       $t4, $t2, $t3
    /* 2E1D0 8002D5D0 918D0003 */  lbu        $t5, 0x3($t4)
    /* 2E1D4 8002D5D4 15A00005 */  bnez       $t5, .L8002D5EC
    /* 2E1D8 8002D5D8 00000000 */   nop
    /* 2E1DC 8002D5DC 918E0002 */  lbu        $t6, 0x2($t4)
    /* 2E1E0 8002D5E0 31CF0001 */  andi       $t7, $t6, 0x1
    /* 2E1E4 8002D5E4 15E00003 */  bnez       $t7, .L8002D5F4
    /* 2E1E8 8002D5E8 00000000 */   nop
  .L8002D5EC:
    /* 2E1EC 8002D5EC 1000000B */  b          .L8002D61C
    /* 2E1F0 8002D5F0 24020001 */   addiu     $v0, $zero, 0x1
  .L8002D5F4:
    /* 2E1F4 8002D5F4 8FB9003C */  lw         $t9, 0x3C($sp)
    /* 2E1F8 8002D5F8 0019C080 */  sll        $t8, $t9, 2
    /* 2E1FC 8002D5FC 03B84021 */  addu       $t0, $sp, $t8
    /* 2E200 8002D600 9108001E */  lbu        $t0, 0x1E($t0)
    /* 2E204 8002D604 31090004 */  andi       $t1, $t0, 0x4
    /* 2E208 8002D608 11200003 */  beqz       $t1, .L8002D618
    /* 2E20C 8002D60C 00000000 */   nop
    /* 2E210 8002D610 10000002 */  b          .L8002D61C
    /* 2E214 8002D614 24020004 */   addiu     $v0, $zero, 0x4
  .L8002D618:
    /* 2E218 8002D618 8FA20034 */  lw         $v0, 0x34($sp)
  .L8002D61C:
    /* 2E21C 8002D61C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 2E220 8002D620 27BD0038 */  addiu      $sp, $sp, 0x38
    /* 2E224 8002D624 03E00008 */  jr         $ra
    /* 2E228 8002D628 00000000 */   nop
    /* 2E22C 8002D62C 00000000 */  nop
