.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002D6A0
    /* 2E2A0 8002D6A0 3C0EA460 */  lui        $t6, %hi(D_A4600010)
    /* 2E2A4 8002D6A4 8DC70010 */  lw         $a3, %lo(D_A4600010)($t6)
    /* 2E2A8 8002D6A8 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2E2AC 8002D6AC 30EF0003 */  andi       $t7, $a3, 0x3
    /* 2E2B0 8002D6B0 11E00006 */  beqz       $t7, .L8002D6CC
    /* 2E2B4 8002D6B4 00000000 */   nop
  .L8002D6B8:
    /* 2E2B8 8002D6B8 3C18A460 */  lui        $t8, %hi(D_A4600010)
    /* 2E2BC 8002D6BC 8F070010 */  lw         $a3, %lo(D_A4600010)($t8)
    /* 2E2C0 8002D6C0 30F90003 */  andi       $t9, $a3, 0x3
    /* 2E2C4 8002D6C4 1720FFFC */  bnez       $t9, .L8002D6B8
    /* 2E2C8 8002D6C8 00000000 */   nop
  .L8002D6CC:
    /* 2E2CC 8002D6CC 8C88000C */  lw         $t0, 0xC($a0)
    /* 2E2D0 8002D6D0 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 2E2D4 8002D6D4 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 2E2D8 8002D6D8 01054825 */  or         $t1, $t0, $a1
    /* 2E2DC 8002D6DC 01215025 */  or         $t2, $t1, $at
    /* 2E2E0 8002D6E0 AD460000 */  sw         $a2, %lo(D_A0000000)($t2)
    /* 2E2E4 8002D6E4 03E00008 */  jr         $ra
    /* 2E2E8 8002D6E8 00001025 */   or        $v0, $zero, $zero
    /* 2E2EC 8002D6EC 00000000 */  nop
