.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002D6F0
    /* 2E2F0 8002D6F0 3C0EA460 */  lui        $t6, %hi(D_A4600010)
    /* 2E2F4 8002D6F4 8DC70010 */  lw         $a3, %lo(D_A4600010)($t6)
    /* 2E2F8 8002D6F8 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2E2FC 8002D6FC 30EF0003 */  andi       $t7, $a3, 0x3
    /* 2E300 8002D700 11E00006 */  beqz       $t7, .L8002D71C
    /* 2E304 8002D704 00000000 */   nop
  .L8002D708:
    /* 2E308 8002D708 3C18A460 */  lui        $t8, %hi(D_A4600010)
    /* 2E30C 8002D70C 8F070010 */  lw         $a3, %lo(D_A4600010)($t8)
    /* 2E310 8002D710 30F90003 */  andi       $t9, $a3, 0x3
    /* 2E314 8002D714 1720FFFC */  bnez       $t9, .L8002D708
    /* 2E318 8002D718 00000000 */   nop
  .L8002D71C:
    /* 2E31C 8002D71C 8C88000C */  lw         $t0, 0xC($a0)
    /* 2E320 8002D720 3C01A000 */  lui        $at, %hi(D_A0000000)
    /* 2E324 8002D724 00001025 */  or         $v0, $zero, $zero
    /* 2E328 8002D728 01054825 */  or         $t1, $t0, $a1
    /* 2E32C 8002D72C 01215025 */  or         $t2, $t1, $at
    /* 2E330 8002D730 8D4B0000 */  lw         $t3, %lo(D_A0000000)($t2)
    /* 2E334 8002D734 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 2E338 8002D738 03E00008 */  jr         $ra
    /* 2E33C 8002D73C ACCB0000 */   sw        $t3, 0x0($a2)

glabel func_8002D740
    /* 2E340 8002D740 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 2E344 8002D744 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2E348 8002D748 AFA40028 */  sw         $a0, 0x28($sp)
    /* 2E34C 8002D74C 0C008E6C */  jal        func_800239B0
    /* 2E350 8002D750 AFB00018 */   sw        $s0, 0x18($sp)
    /* 2E354 8002D754 3C0E8003 */  lui        $t6, %hi(D_80035620)
    /* 2E358 8002D758 8DCE5620 */  lw         $t6, %lo(D_80035620)($t6)
    /* 2E35C 8002D75C 8FAF0028 */  lw         $t7, 0x28($sp)
    /* 2E360 8002D760 00408025 */  or         $s0, $v0, $zero
    /* 2E364 8002D764 3C018003 */  lui        $at, %hi(D_80035620)
    /* 2E368 8002D768 01CFC025 */  or         $t8, $t6, $t7
    /* 2E36C 8002D76C AC385620 */  sw         $t8, %lo(D_80035620)($at)
    /* 2E370 8002D770 0C008E74 */  jal        func_800239D0
    /* 2E374 8002D774 02002025 */   or        $a0, $s0, $zero
    /* 2E378 8002D778 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2E37C 8002D77C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2E380 8002D780 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 2E384 8002D784 03E00008 */  jr         $ra
    /* 2E388 8002D788 00000000 */   nop
    /* 2E38C 8002D78C 00000000 */  nop
