.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8002D790
    /* 2E390 8002D790 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 2E394 8002D794 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 2E398 8002D798 0C008E6C */  jal        func_800239B0
    /* 2E39C 8002D79C AFB00018 */   sw        $s0, 0x18($sp)
    /* 2E3A0 8002D7A0 3C0F8003 */  lui        $t7, %hi(D_800363B0)
    /* 2E3A4 8002D7A4 8DEF63B0 */  lw         $t7, %lo(D_800363B0)($t7)
    /* 2E3A8 8002D7A8 240E0002 */  addiu      $t6, $zero, 0x2
    /* 2E3AC 8002D7AC 3C048003 */  lui        $a0, %hi(D_800363A8)
    /* 2E3B0 8002D7B0 00408025 */  or         $s0, $v0, $zero
    /* 2E3B4 8002D7B4 248463A8 */  addiu      $a0, $a0, %lo(D_800363A8)
    /* 2E3B8 8002D7B8 0C008DB3 */  jal        func_800236CC
    /* 2E3BC 8002D7BC A5EE0010 */   sh        $t6, 0x10($t7)
    /* 2E3C0 8002D7C0 0C008E74 */  jal        func_800239D0
    /* 2E3C4 8002D7C4 02002025 */   or        $a0, $s0, $zero
    /* 2E3C8 8002D7C8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 2E3CC 8002D7CC 8FB00018 */  lw         $s0, 0x18($sp)
    /* 2E3D0 8002D7D0 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 2E3D4 8002D7D4 03E00008 */  jr         $ra
    /* 2E3D8 8002D7D8 00000000 */   nop
    /* 2E3DC 8002D7DC 00000000 */  nop
