.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_800047D0
    /* 53D0 800047D0 AFA40000 */  sw         $a0, 0x0($sp)
    /* 53D4 800047D4 03E00008 */  jr         $ra
    /* 53D8 800047D8 AFA50004 */   sw        $a1, 0x4($sp)

glabel func_800047DC
    /* 53DC 800047DC AFA40000 */  sw         $a0, 0x0($sp)
    /* 53E0 800047E0 AFA50004 */  sw         $a1, 0x4($sp)
    /* 53E4 800047E4 03E00008 */  jr         $ra
    /* 53E8 800047E8 AFA60008 */   sw        $a2, 0x8($sp)
    /* 53EC 800047EC 00000000 */  nop
