.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8000DC30
    /* E830 8000DC30 00801025 */  or         $v0, $a0, $zero
    /* E834 8000DC34 00A01825 */  or         $v1, $a1, $zero
    /* E838 8000DC38 24060006 */  addiu      $a2, $zero, 0x6
  .L8000DC3C:
    /* E83C 8000DC3C 24050009 */  addiu      $a1, $zero, 0x9
  .L8000DC40:
    /* E840 8000DC40 2407001F */  addiu      $a3, $zero, 0x1F
  .L8000DC44:
    /* E844 8000DC44 2408001F */  addiu      $t0, $zero, 0x1F
  .L8000DC48:
    /* E848 8000DC48 844E0000 */  lh         $t6, 0x0($v0)
    /* E84C 8000DC4C 01002025 */  or         $a0, $t0, $zero
    /* E850 8000DC50 24630002 */  addiu      $v1, $v1, 0x2
    /* E854 8000DC54 24420002 */  addiu      $v0, $v0, 0x2
    /* E858 8000DC58 A46EFFFE */  sh         $t6, -0x2($v1)
    /* E85C 8000DC5C 1500FFFA */  bnez       $t0, .L8000DC48
    /* E860 8000DC60 2508FFFF */   addiu     $t0, $t0, -0x1
    /* E864 8000DC64 00E02025 */  or         $a0, $a3, $zero
    /* E868 8000DC68 24420240 */  addiu      $v0, $v0, 0x240
    /* E86C 8000DC6C 14E0FFF5 */  bnez       $a3, .L8000DC44
    /* E870 8000DC70 24E7FFFF */   addiu     $a3, $a3, -0x1
    /* E874 8000DC74 00A02025 */  or         $a0, $a1, $zero
    /* E878 8000DC78 2442B040 */  addiu      $v0, $v0, -0x4FC0
    /* E87C 8000DC7C 14A0FFF0 */  bnez       $a1, .L8000DC40
    /* E880 8000DC80 24A5FFFF */   addiu     $a1, $a1, -0x1
    /* E884 8000DC84 00C02025 */  or         $a0, $a2, $zero
    /* E888 8000DC88 24424D80 */  addiu      $v0, $v0, 0x4D80
    /* E88C 8000DC8C 14C0FFEB */  bnez       $a2, .L8000DC3C
    /* E890 8000DC90 24C6FFFF */   addiu     $a2, $a2, -0x1
    /* E894 8000DC94 03E00008 */  jr         $ra
    /* E898 8000DC98 00000000 */   nop

glabel func_8000DC9C
    /* E89C 8000DC9C 00801025 */  or         $v0, $a0, $zero
    /* E8A0 8000DCA0 00A01825 */  or         $v1, $a1, $zero
    /* E8A4 8000DCA4 340695FF */  ori        $a2, $zero, 0x95FF
  .L8000DCA8:
    /* E8A8 8000DCA8 8C4E0000 */  lw         $t6, 0x0($v0)
    /* E8AC 8000DCAC 00C02025 */  or         $a0, $a2, $zero
    /* E8B0 8000DCB0 24630004 */  addiu      $v1, $v1, 0x4
    /* E8B4 8000DCB4 24420004 */  addiu      $v0, $v0, 0x4
    /* E8B8 8000DCB8 AC6EFFFC */  sw         $t6, -0x4($v1)
    /* E8BC 8000DCBC 14C0FFFA */  bnez       $a2, .L8000DCA8
    /* E8C0 8000DCC0 24C6FFFF */   addiu     $a2, $a2, -0x1
    /* E8C4 8000DCC4 03E00008 */  jr         $ra
    /* E8C8 8000DCC8 00000000 */   nop

glabel func_8000DCCC
    /* E8CC 8000DCCC 3C028006 */  lui        $v0, %hi(D_8005BAEC)
    /* E8D0 8000DCD0 8C42BAEC */  lw         $v0, %lo(D_8005BAEC)($v0)
    /* E8D4 8000DCD4 3C038006 */  lui        $v1, %hi(D_8005BAF0)
    /* E8D8 8000DCD8 8C63BAF0 */  lw         $v1, %lo(D_8005BAF0)($v1)
    /* E8DC 8000DCDC 00420019 */  multu      $v0, $v0
    /* E8E0 8000DCE0 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* E8E4 8000DCE4 AFA70064 */  sw         $a3, 0x64($sp)
    /* E8E8 8000DCE8 3C078006 */  lui        $a3, %hi(D_80059CD2)
    /* E8EC 8000DCEC 84E79CD2 */  lh         $a3, %lo(D_80059CD2)($a3)
    /* E8F0 8000DCF0 3C088006 */  lui        $t0, %hi(D_80059CD4)
    /* E8F4 8000DCF4 85089CD4 */  lh         $t0, %lo(D_80059CD4)($t0)
    /* E8F8 8000DCF8 AFA60060 */  sw         $a2, 0x60($sp)
    /* E8FC 8000DCFC 3C068006 */  lui        $a2, %hi(D_80059CD0)
    /* E900 8000DD00 84C69CD0 */  lh         $a2, %lo(D_80059CD0)($a2)
    /* E904 8000DD04 00007012 */  mflo       $t6
    /* E908 8000DD08 AFA5005C */  sw         $a1, 0x5C($sp)
    /* E90C 8000DD0C 00065840 */  sll        $t3, $a2, 1
    /* E910 8000DD10 00630019 */  multu      $v1, $v1
    /* E914 8000DD14 AFB10018 */  sw         $s1, 0x18($sp)
    /* E918 8000DD18 AFB00014 */  sw         $s0, 0x14($sp)
    /* E91C 8000DD1C AFBF001C */  sw         $ra, 0x1C($sp)
    /* E920 8000DD20 AFA40058 */  sw         $a0, 0x58($sp)
    /* E924 8000DD24 AFA70054 */  sw         $a3, 0x54($sp)
    /* E928 8000DD28 AFA80050 */  sw         $t0, 0x50($sp)
    /* E92C 8000DD2C 00007812 */  mflo       $t7
    /* E930 8000DD30 01CF4821 */  addu       $t1, $t6, $t7
    /* E934 8000DD34 05210003 */  bgez       $t1, .L8000DD44
    /* E938 8000DD38 0009C083 */   sra       $t8, $t1, 2
    /* E93C 8000DD3C 25210003 */  addiu      $at, $t1, 0x3
    /* E940 8000DD40 0001C083 */  sra        $t8, $at, 2
  .L8000DD44:
    /* E944 8000DD44 00E70019 */  multu      $a3, $a3
    /* E948 8000DD48 24010510 */  addiu      $at, $zero, 0x510
    /* E94C 8000DD4C 0000C812 */  mflo       $t9
    /* E950 8000DD50 00000000 */  nop
    /* E954 8000DD54 00000000 */  nop
    /* E958 8000DD58 01080019 */  multu      $t0, $t0
    /* E95C 8000DD5C 00005012 */  mflo       $t2
    /* E960 8000DD60 032A2821 */  addu       $a1, $t9, $t2
    /* E964 8000DD64 03056023 */  subu       $t4, $t8, $a1
    /* E968 8000DD68 016C0019 */  multu      $t3, $t4
    /* E96C 8000DD6C 00006812 */  mflo       $t5
    /* E970 8000DD70 00000000 */  nop
    /* E974 8000DD74 00000000 */  nop
    /* E978 8000DD78 00C50019 */  multu      $a2, $a1
    /* E97C 8000DD7C 00007012 */  mflo       $t6
    /* E980 8000DD80 01AE8821 */  addu       $s1, $t5, $t6
    /* E984 8000DD84 00000000 */  nop
    /* E988 8000DD88 0221001A */  div        $zero, $s1, $at
    /* E98C 8000DD8C 00008812 */  mflo       $s1
    /* E990 8000DD90 3230FFFF */  andi       $s0, $s1, 0xFFFF
    /* E994 8000DD94 0C007654 */  jal        func_8001D950
    /* E998 8000DD98 3204FFFF */   andi      $a0, $s0, 0xFFFF
    /* E99C 8000DD9C A7A20036 */  sh         $v0, 0x36($sp)
    /* E9A0 8000DDA0 0C007660 */  jal        func_8001D980
    /* E9A4 8000DDA4 3204FFFF */   andi      $a0, $s0, 0xFFFF
    /* E9A8 8000DDA8 44824000 */  mtc1       $v0, $ft2
    /* E9AC 8000DDAC 8FA80050 */  lw         $t0, 0x50($sp)
    /* E9B0 8000DDB0 3C0140E0 */  lui        $at, (0x40E00000 >> 16)
    /* E9B4 8000DDB4 468042A0 */  cvt.s.w    $ft3, $ft2
    /* E9B8 8000DDB8 44882000 */  mtc1       $t0, $ft0
    /* E9BC 8000DDBC 44817800 */  mtc1       $at, $fa1f
    /* E9C0 8000DDC0 44807000 */  mtc1       $zero, $fa1
    /* E9C4 8000DDC4 87B80036 */  lh         $t8, 0x36($sp)
    /* E9C8 8000DDC8 46802021 */  cvt.d.w    $fv0, $ft0
    /* E9CC 8000DDCC 8FA70054 */  lw         $a3, 0x54($sp)
    /* E9D0 8000DDD0 44984000 */  mtc1       $t8, $ft2
    /* E9D4 8000DDD4 3204FFFF */  andi       $a0, $s0, 0xFFFF
    /* E9D8 8000DDD8 460054A1 */  cvt.d.s    $ft5, $ft3
    /* E9DC 8000DDDC 468042A0 */  cvt.s.w    $ft3, $ft2
    /* E9E0 8000DDE0 44873000 */  mtc1       $a3, $ft1
    /* E9E4 8000DDE4 F7A00028 */  sdc1       $fv0, 0x28($sp)
    /* E9E8 8000DDE8 462E9103 */  div.d      $ft0, $ft5, $fa1
    /* E9EC 8000DDEC 468030A1 */  cvt.d.w    $fv1, $ft1
    /* E9F0 8000DDF0 460054A1 */  cvt.d.s    $ft5, $ft3
    /* E9F4 8000DDF4 F7A20020 */  sdc1       $fv1, 0x20($sp)
    /* E9F8 8000DDF8 46202182 */  mul.d      $ft1, $ft0, $fv0
    /* E9FC 8000DDFC 462E9103 */  div.d      $ft0, $ft5, $fa1
    /* EA00 8000DE00 46222202 */  mul.d      $ft2, $ft0, $fv1
    /* EA04 8000DE04 46283280 */  add.d      $ft3, $ft1, $ft2
    /* EA08 8000DE08 4620548D */  trunc.w.d  $ft5, $ft3
    /* EA0C 8000DE0C 0C007660 */  jal        func_8001D980
    /* EA10 8000DE10 E7B20040 */   swc1      $ft5, 0x40($sp)
    /* EA14 8000DE14 A7A20036 */  sh         $v0, 0x36($sp)
    /* EA18 8000DE18 0C007654 */  jal        func_8001D950
    /* EA1C 8000DE1C 3204FFFF */   andi      $a0, $s0, 0xFFFF
    /* EA20 8000DE20 3C0140E0 */  lui        $at, (0x40E00000 >> 16)
    /* EA24 8000DE24 44817800 */  mtc1       $at, $fa1f
    /* EA28 8000DE28 34018000 */  ori        $at, $zero, 0x8000
    /* EA2C 8000DE2C 44807000 */  mtc1       $zero, $fa1
    /* EA30 8000DE30 0221082A */  slt        $at, $s1, $at
    /* EA34 8000DE34 D7A00028 */  ldc1       $fv0, 0x28($sp)
    /* EA38 8000DE38 14200002 */  bnez       $at, .L8000DE44
    /* EA3C 8000DE3C D7A20020 */   ldc1      $fv1, 0x20($sp)
    /* EA40 8000DE40 24117FFF */  addiu      $s1, $zero, 0x7FFF
  .L8000DE44:
    /* EA44 8000DE44 44912000 */  mtc1       $s1, $ft0
    /* EA48 8000DE48 3C018003 */  lui        $at, %hi(D_80037620)
    /* EA4C 8000DE4C D4307620 */  ldc1       $ft4, %lo(D_80037620)($at)
    /* EA50 8000DE50 468021A0 */  cvt.s.w    $ft1, $ft0
    /* EA54 8000DE54 8FAA0040 */  lw         $t2, 0x40($sp)
    /* EA58 8000DE58 87AD0036 */  lh         $t5, 0x36($sp)
    /* EA5C 8000DE5C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* EA60 8000DE60 448A2000 */  mtc1       $t2, $ft0
    /* EA64 8000DE64 3C018006 */  lui        $at, %hi(D_80059CD2)
    /* EA68 8000DE68 46003221 */  cvt.d.s    $ft2, $ft1
    /* EA6C 8000DE6C 468021A0 */  cvt.s.w    $ft1, $ft0
    /* EA70 8000DE70 8FB10018 */  lw         $s1, 0x18($sp)
    /* EA74 8000DE74 8FB00014 */  lw         $s0, 0x14($sp)
    /* EA78 8000DE78 27BD0058 */  addiu      $sp, $sp, 0x58
    /* EA7C 8000DE7C 46288281 */  sub.d      $ft3, $ft4, $ft2
    /* EA80 8000DE80 46305483 */  div.d      $ft5, $ft3, $ft4
    /* EA84 8000DE84 46209320 */  cvt.s.d    $fa0, $ft5
    /* EA88 8000DE88 44829000 */  mtc1       $v0, $ft5
    /* EA8C 8000DE8C 460C3202 */  mul.s      $ft2, $ft1, $fa0
    /* EA90 8000DE90 46809120 */  cvt.s.w    $ft0, $ft5
    /* EA94 8000DE94 448D9000 */  mtc1       $t5, $ft5
    /* EA98 8000DE98 4600428D */  trunc.w.s  $ft3, $ft2
    /* EA9C 8000DE9C 460021A1 */  cvt.d.s    $ft1, $ft0
    /* EAA0 8000DEA0 46809120 */  cvt.s.w    $ft0, $ft5
    /* EAA4 8000DEA4 440C5000 */  mfc1       $t4, $ft3
    /* EAA8 8000DEA8 00000000 */  nop
    /* EAAC 8000DEAC A42C9CD2 */  sh         $t4, %lo(D_80059CD2)($at)
    /* EAB0 8000DEB0 462E3203 */  div.d      $ft2, $ft1, $fa1
    /* EAB4 8000DEB4 3C018006 */  lui        $at, %hi(D_80059CD4)
    /* EAB8 8000DEB8 460021A1 */  cvt.d.s    $ft1, $ft0
    /* EABC 8000DEBC 46204282 */  mul.d      $ft3, $ft2, $fv0
    /* EAC0 8000DEC0 462E3203 */  div.d      $ft2, $ft1, $fa1
    /* EAC4 8000DEC4 46204487 */  neg.d      $ft5, $ft2
    /* EAC8 8000DEC8 46229102 */  mul.d      $ft0, $ft5, $fv1
    /* EACC 8000DECC 46245180 */  add.d      $ft1, $ft3, $ft0
    /* EAD0 8000DED0 4620320D */  trunc.w.d  $ft2, $ft1
    /* EAD4 8000DED4 440F4000 */  mfc1       $t7, $ft2
    /* EAD8 8000DED8 00000000 */  nop
    /* EADC 8000DEDC 448F9000 */  mtc1       $t7, $ft5
    /* EAE0 8000DEE0 00000000 */  nop
    /* EAE4 8000DEE4 468092A0 */  cvt.s.w    $ft3, $ft5
    /* EAE8 8000DEE8 460C5102 */  mul.s      $ft0, $ft3, $fa0
    /* EAEC 8000DEEC 4600218D */  trunc.w.s  $ft1, $ft0
    /* EAF0 8000DEF0 44193000 */  mfc1       $t9, $ft1
    /* EAF4 8000DEF4 03E00008 */  jr         $ra
    /* EAF8 8000DEF8 A4399CD4 */   sh        $t9, %lo(D_80059CD4)($at)

glabel func_8000DEFC
    /* EAFC 8000DEFC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* EB00 8000DF00 AFA40020 */  sw         $a0, 0x20($sp)
    /* EB04 8000DF04 3C048006 */  lui        $a0, %hi(D_80059CD0)
    /* EB08 8000DF08 84849CD0 */  lh         $a0, %lo(D_80059CD0)($a0)
    /* EB0C 8000DF0C AFBF0014 */  sw         $ra, 0x14($sp)
    /* EB10 8000DF10 AFA50024 */  sw         $a1, 0x24($sp)
    /* EB14 8000DF14 00047140 */  sll        $t6, $a0, 5
    /* EB18 8000DF18 AFA60028 */  sw         $a2, 0x28($sp)
    /* EB1C 8000DF1C AFA7002C */  sw         $a3, 0x2C($sp)
    /* EB20 8000DF20 0C007654 */  jal        func_8001D950
    /* EB24 8000DF24 31C4FFFF */   andi      $a0, $t6, 0xFFFF
    /* EB28 8000DF28 3C048006 */  lui        $a0, %hi(D_80059CD0)
    /* EB2C 8000DF2C 84849CD0 */  lh         $a0, %lo(D_80059CD0)($a0)
    /* EB30 8000DF30 A7A2001E */  sh         $v0, 0x1E($sp)
    /* EB34 8000DF34 0004C100 */  sll        $t8, $a0, 4
    /* EB38 8000DF38 0C007660 */  jal        func_8001D980
    /* EB3C 8000DF3C 3304FFFF */   andi      $a0, $t8, 0xFFFF
    /* EB40 8000DF40 3C038006 */  lui        $v1, %hi(D_80059CD0)
    /* EB44 8000DF44 84639CD0 */  lh         $v1, %lo(D_80059CD0)($v1)
    /* EB48 8000DF48 3C0140E0 */  lui        $at, (0x40E00000 >> 16)
    /* EB4C 8000DF4C 44810800 */  mtc1       $at, $fv0f
    /* EB50 8000DF50 2401000A */  addiu      $at, $zero, 0xA
    /* EB54 8000DF54 0061001A */  div        $zero, $v1, $at
    /* EB58 8000DF58 44822000 */  mtc1       $v0, $ft0
    /* EB5C 8000DF5C 44800000 */  mtc1       $zero, $fv0
    /* EB60 8000DF60 00004012 */  mflo       $t0
    /* EB64 8000DF64 468021A0 */  cvt.s.w    $ft1, $ft0
    /* EB68 8000DF68 44888000 */  mtc1       $t0, $ft4
    /* EB6C 8000DF6C 87AA001E */  lh         $t2, 0x1E($sp)
    /* EB70 8000DF70 3C058006 */  lui        $a1, %hi(D_80059CD2)
    /* EB74 8000DF74 24A59CD2 */  addiu      $a1, $a1, %lo(D_80059CD2)
    /* EB78 8000DF78 468084A1 */  cvt.d.w    $ft5, $ft4
    /* EB7C 8000DF7C 448A8000 */  mtc1       $t2, $ft4
    /* EB80 8000DF80 84A90000 */  lh         $t1, 0x0($a1)
    /* EB84 8000DF84 00032100 */  sll        $a0, $v1, 4
    /* EB88 8000DF88 46003221 */  cvt.d.s    $ft2, $ft1
    /* EB8C 8000DF8C 44893000 */  mtc1       $t1, $ft1
    /* EB90 8000DF90 46204283 */  div.d      $ft3, $ft2, $fv0
    /* EB94 8000DF94 308DFFFF */  andi       $t5, $a0, 0xFFFF
    /* EB98 8000DF98 01A02025 */  or         $a0, $t5, $zero
    /* EB9C 8000DF9C 46803221 */  cvt.d.w    $ft2, $ft1
    /* EBA0 8000DFA0 46325102 */  mul.d      $ft0, $ft3, $ft5
    /* EBA4 8000DFA4 468082A0 */  cvt.s.w    $ft3, $ft4
    /* EBA8 8000DFA8 460054A1 */  cvt.d.s    $ft5, $ft3
    /* EBAC 8000DFAC 46209183 */  div.d      $ft1, $ft5, $fv0
    /* EBB0 8000DFB0 46264402 */  mul.d      $ft4, $ft2, $ft1
    /* EBB4 8000DFB4 46302280 */  add.d      $ft3, $ft0, $ft4
    /* EBB8 8000DFB8 4620548D */  trunc.w.d  $ft5, $ft3
    /* EBBC 8000DFBC 440C9000 */  mfc1       $t4, $ft5
    /* EBC0 8000DFC0 0C007654 */  jal        func_8001D950
    /* EBC4 8000DFC4 A4AC0000 */   sh        $t4, 0x0($a1)
    /* EBC8 8000DFC8 3C038006 */  lui        $v1, %hi(D_80059CD0)
    /* EBCC 8000DFCC 84639CD0 */  lh         $v1, %lo(D_80059CD0)($v1)
    /* EBD0 8000DFD0 3C0140E0 */  lui        $at, (0x40E00000 >> 16)
    /* EBD4 8000DFD4 44810800 */  mtc1       $at, $fv0f
    /* EBD8 8000DFD8 2401000A */  addiu      $at, $zero, 0xA
    /* EBDC 8000DFDC 0061001A */  div        $zero, $v1, $at
    /* EBE0 8000DFE0 44822000 */  mtc1       $v0, $ft0
    /* EBE4 8000DFE4 44800000 */  mtc1       $zero, $fv0
    /* EBE8 8000DFE8 00007012 */  mflo       $t6
    /* EBEC 8000DFEC 46802420 */  cvt.s.w    $ft4, $ft0
    /* EBF0 8000DFF0 448E4000 */  mtc1       $t6, $ft2
    /* EBF4 8000DFF4 3C048006 */  lui        $a0, %hi(D_80059CD4)
    /* EBF8 8000DFF8 24849CD4 */  addiu      $a0, $a0, %lo(D_80059CD4)
    /* EBFC 8000DFFC 848F0000 */  lh         $t7, 0x0($a0)
    /* EC00 8000E000 468041A1 */  cvt.d.w    $ft1, $ft2
    /* EC04 8000E004 8FBF0014 */  lw         $ra, 0x14($sp)
    /* EC08 8000E008 448F2000 */  mtc1       $t7, $ft0
    /* EC0C 8000E00C 00034023 */  negu       $t0, $v1
    /* EC10 8000E010 460082A1 */  cvt.d.s    $ft3, $ft4
    /* EC14 8000E014 46802421 */  cvt.d.w    $ft4, $ft0
    /* EC18 8000E018 00084840 */  sll        $t1, $t0, 1
    /* EC1C 8000E01C 3C018006 */  lui        $at, %hi(D_80059CD6)
    /* EC20 8000E020 27BD0020 */  addiu      $sp, $sp, 0x20
    /* EC24 8000E024 46205483 */  div.d      $ft5, $ft3, $fv0
    /* EC28 8000E028 46323202 */  mul.d      $ft2, $ft1, $ft5
    /* EC2C 8000E02C 46288280 */  add.d      $ft3, $ft4, $ft2
    /* EC30 8000E030 4620518D */  trunc.w.d  $ft1, $ft3
    /* EC34 8000E034 44193000 */  mfc1       $t9, $ft1
    /* EC38 8000E038 00000000 */  nop
    /* EC3C 8000E03C A4990000 */  sh         $t9, 0x0($a0)
    /* EC40 8000E040 03E00008 */  jr         $ra
    /* EC44 8000E044 A4299CD6 */   sh        $t1, %lo(D_80059CD6)($at)

glabel func_8000E048
    /* EC48 8000E048 AFA40000 */  sw         $a0, 0x0($sp)
    /* EC4C 8000E04C 00047400 */  sll        $t6, $a0, 16
    /* EC50 8000E050 000E2403 */  sra        $a0, $t6, 16
    /* EC54 8000E054 00077400 */  sll        $t6, $a3, 16
    /* EC58 8000E058 0005C400 */  sll        $t8, $a1, 16
    /* EC5C 8000E05C 00066400 */  sll        $t4, $a2, 16
    /* EC60 8000E060 000C6C03 */  sra        $t5, $t4, 16
    /* EC64 8000E064 0018CC03 */  sra        $t9, $t8, 16
    /* EC68 8000E068 000E7C03 */  sra        $t7, $t6, 16
    /* EC6C 8000E06C AFA50004 */  sw         $a1, 0x4($sp)
    /* EC70 8000E070 AFA60008 */  sw         $a2, 0x8($sp)
    /* EC74 8000E074 AFA7000C */  sw         $a3, 0xC($sp)
    /* EC78 8000E078 28810005 */  slti       $at, $a0, 0x5
    /* EC7C 8000E07C 01E03825 */  or         $a3, $t7, $zero
    /* EC80 8000E080 01A03025 */  or         $a2, $t5, $zero
    /* EC84 8000E084 1420006A */  bnez       $at, .L8000E230
    /* EC88 8000E088 03202825 */   or        $a1, $t9, $zero
    /* EC8C 8000E08C 2B210004 */  slti       $at, $t9, 0x4
    /* EC90 8000E090 1420002D */  bnez       $at, .L8000E148
    /* EC94 8000E094 00861021 */   addu      $v0, $a0, $a2
    /* EC98 8000E098 008D1021 */  addu       $v0, $a0, $t5
    /* EC9C 8000E09C 2442FFFC */  addiu      $v0, $v0, -0x4
    /* ECA0 8000E0A0 00420019 */  multu      $v0, $v0
    /* ECA4 8000E0A4 032F1821 */  addu       $v1, $t9, $t7
    /* ECA8 8000E0A8 2463FFFF */  addiu      $v1, $v1, -0x1
    /* ECAC 8000E0AC 3C098006 */  lui        $t1, %hi(D_80059CD0)
    /* ECB0 8000E0B0 85299CD0 */  lh         $t1, %lo(D_80059CD0)($t1)
    /* ECB4 8000E0B4 240D0019 */  addiu      $t5, $zero, 0x19
    /* ECB8 8000E0B8 3C018003 */  lui        $at, %hi(D_80037628)
    /* ECBC 8000E0BC 00096040 */  sll        $t4, $t1, 1
    /* ECC0 8000E0C0 D42C7628 */  ldc1       $fa0, %lo(D_80037628)($at)
    /* ECC4 8000E0C4 3C0B8006 */  lui        $t3, %hi(D_80059CD4)
    /* ECC8 8000E0C8 0000C012 */  mflo       $t8
    /* ECCC 8000E0CC 256B9CD4 */  addiu      $t3, $t3, %lo(D_80059CD4)
    /* ECD0 8000E0D0 3C014440 */  lui        $at, (0x44400000 >> 16)
    /* ECD4 8000E0D4 00630019 */  multu      $v1, $v1
    /* ECD8 8000E0D8 0000C812 */  mflo       $t9
    /* ECDC 8000E0DC 03195021 */  addu       $t2, $t8, $t9
    /* ECE0 8000E0E0 01AA7023 */  subu       $t6, $t5, $t2
    /* ECE4 8000E0E4 018E0019 */  multu      $t4, $t6
    /* ECE8 8000E0E8 85790000 */  lh         $t9, 0x0($t3)
    /* ECEC 8000E0EC 272D0300 */  addiu      $t5, $t9, 0x300
    /* ECF0 8000E0F0 448D9000 */  mtc1       $t5, $ft5
    /* ECF4 8000E0F4 00007812 */  mflo       $t7
    /* ECF8 8000E0F8 00000000 */  nop
    /* ECFC 8000E0FC 00000000 */  nop
    /* ED00 8000E100 012A0019 */  multu      $t1, $t2
    /* ED04 8000E104 0000C012 */  mflo       $t8
    /* ED08 8000E108 01F84021 */  addu       $t0, $t7, $t8
    /* ED0C 8000E10C 44882000 */  mtc1       $t0, $ft0
    /* ED10 8000E110 00000000 */  nop
    /* ED14 8000E114 468021A0 */  cvt.s.w    $ft1, $ft0
    /* ED18 8000E118 46809120 */  cvt.s.w    $ft0, $ft5
    /* ED1C 8000E11C 46003221 */  cvt.d.s    $ft2, $ft1
    /* ED20 8000E120 46286281 */  sub.d      $ft3, $fa0, $ft2
    /* ED24 8000E124 44814000 */  mtc1       $at, $ft2
    /* ED28 8000E128 462C5403 */  div.d      $ft4, $ft3, $fa0
    /* ED2C 8000E12C 46208020 */  cvt.s.d    $fv0, $ft4
    /* ED30 8000E130 46002182 */  mul.s      $ft1, $ft0, $fv0
    /* ED34 8000E134 46083281 */  sub.s      $ft3, $ft1, $ft2
    /* ED38 8000E138 4600540D */  trunc.w.s  $ft4, $ft3
    /* ED3C 8000E13C 440E8000 */  mfc1       $t6, $ft4
    /* ED40 8000E140 1000002C */  b          .L8000E1F4
    /* ED44 8000E144 A56E0000 */   sh        $t6, 0x0($t3)
  .L8000E148:
    /* ED48 8000E148 2442FFFC */  addiu      $v0, $v0, -0x4
    /* ED4C 8000E14C 00420019 */  multu      $v0, $v0
    /* ED50 8000E150 00A71821 */  addu       $v1, $a1, $a3
    /* ED54 8000E154 2463FFF9 */  addiu      $v1, $v1, -0x7
    /* ED58 8000E158 3C098006 */  lui        $t1, %hi(D_80059CD0)
    /* ED5C 8000E15C 85299CD0 */  lh         $t1, %lo(D_80059CD0)($t1)
    /* ED60 8000E160 240D0019 */  addiu      $t5, $zero, 0x19
    /* ED64 8000E164 3C018003 */  lui        $at, %hi(D_80037630)
    /* ED68 8000E168 0009C840 */  sll        $t9, $t1, 1
    /* ED6C 8000E16C D42C7630 */  ldc1       $fa0, %lo(D_80037630)($at)
    /* ED70 8000E170 3C0B8006 */  lui        $t3, %hi(D_80059CD4)
    /* ED74 8000E174 00007812 */  mflo       $t7
    /* ED78 8000E178 256B9CD4 */  addiu      $t3, $t3, %lo(D_80059CD4)
    /* ED7C 8000E17C 3C014440 */  lui        $at, (0x44400000 >> 16)
    /* ED80 8000E180 00630019 */  multu      $v1, $v1
    /* ED84 8000E184 0000C012 */  mflo       $t8
    /* ED88 8000E188 01F85021 */  addu       $t2, $t7, $t8
    /* ED8C 8000E18C 01AA6023 */  subu       $t4, $t5, $t2
    /* ED90 8000E190 032C0019 */  multu      $t9, $t4
    /* ED94 8000E194 85780000 */  lh         $t8, 0x0($t3)
    /* ED98 8000E198 270DFD00 */  addiu      $t5, $t8, -0x300
    /* ED9C 8000E19C 448D8000 */  mtc1       $t5, $ft4
    /* EDA0 8000E1A0 00007012 */  mflo       $t6
    /* EDA4 8000E1A4 00000000 */  nop
    /* EDA8 8000E1A8 00000000 */  nop
    /* EDAC 8000E1AC 012A0019 */  multu      $t1, $t2
    /* EDB0 8000E1B0 00007812 */  mflo       $t7
    /* EDB4 8000E1B4 01CF4021 */  addu       $t0, $t6, $t7
    /* EDB8 8000E1B8 44889000 */  mtc1       $t0, $ft5
    /* EDBC 8000E1BC 00000000 */  nop
    /* EDC0 8000E1C0 46809120 */  cvt.s.w    $ft0, $ft5
    /* EDC4 8000E1C4 468084A0 */  cvt.s.w    $ft5, $ft4
    /* EDC8 8000E1C8 460021A1 */  cvt.d.s    $ft1, $ft0
    /* EDCC 8000E1CC 46266201 */  sub.d      $ft2, $fa0, $ft1
    /* EDD0 8000E1D0 44813000 */  mtc1       $at, $ft1
    /* EDD4 8000E1D4 462C4283 */  div.d      $ft3, $ft2, $fa0
    /* EDD8 8000E1D8 46205020 */  cvt.s.d    $fv0, $ft3
    /* EDDC 8000E1DC 46009102 */  mul.s      $ft0, $ft5, $fv0
    /* EDE0 8000E1E0 46062200 */  add.s      $ft2, $ft0, $ft1
    /* EDE4 8000E1E4 4600428D */  trunc.w.s  $ft3, $ft2
    /* EDE8 8000E1E8 440C5000 */  mfc1       $t4, $ft3
    /* EDEC 8000E1EC 00000000 */  nop
    /* EDF0 8000E1F0 A56C0000 */  sh         $t4, 0x0($t3)
  .L8000E1F4:
    /* EDF4 8000E1F4 3C028006 */  lui        $v0, %hi(D_80059CD2)
    /* EDF8 8000E1F8 24429CD2 */  addiu      $v0, $v0, %lo(D_80059CD2)
    /* EDFC 8000E1FC 844E0000 */  lh         $t6, 0x0($v0)
    /* EE00 8000E200 3C014490 */  lui        $at, (0x44900000 >> 16)
    /* EE04 8000E204 44813000 */  mtc1       $at, $ft1
    /* EE08 8000E208 25CFFB80 */  addiu      $t7, $t6, -0x480
    /* EE0C 8000E20C 448F8000 */  mtc1       $t7, $ft4
    /* EE10 8000E210 00000000 */  nop
    /* EE14 8000E214 468084A0 */  cvt.s.w    $ft5, $ft4
    /* EE18 8000E218 46009102 */  mul.s      $ft0, $ft5, $fv0
    /* EE1C 8000E21C 46062200 */  add.s      $ft2, $ft0, $ft1
    /* EE20 8000E220 4600428D */  trunc.w.s  $ft3, $ft2
    /* EE24 8000E224 440D5000 */  mfc1       $t5, $ft3
    /* EE28 8000E228 03E00008 */  jr         $ra
    /* EE2C 8000E22C A44D0000 */   sh        $t5, 0x0($v0)
  .L8000E230:
    /* EE30 8000E230 28A10004 */  slti       $at, $a1, 0x4
    /* EE34 8000E234 1420002C */  bnez       $at, .L8000E2E8
    /* EE38 8000E238 00861021 */   addu      $v0, $a0, $a2
    /* EE3C 8000E23C 2442FFFA */  addiu      $v0, $v0, -0x6
    /* EE40 8000E240 00420019 */  multu      $v0, $v0
    /* EE44 8000E244 00A71821 */  addu       $v1, $a1, $a3
    /* EE48 8000E248 2463FFFF */  addiu      $v1, $v1, -0x1
    /* EE4C 8000E24C 3C098006 */  lui        $t1, %hi(D_80059CD0)
    /* EE50 8000E250 85299CD0 */  lh         $t1, %lo(D_80059CD0)($t1)
    /* EE54 8000E254 240F0019 */  addiu      $t7, $zero, 0x19
    /* EE58 8000E258 3C018003 */  lui        $at, %hi(D_80037638)
    /* EE5C 8000E25C 00097040 */  sll        $t6, $t1, 1
    /* EE60 8000E260 D42C7638 */  ldc1       $fa0, %lo(D_80037638)($at)
    /* EE64 8000E264 3C0B8006 */  lui        $t3, %hi(D_80059CD4)
    /* EE68 8000E268 0000C812 */  mflo       $t9
    /* EE6C 8000E26C 256B9CD4 */  addiu      $t3, $t3, %lo(D_80059CD4)
    /* EE70 8000E270 3C014440 */  lui        $at, (0x44400000 >> 16)
    /* EE74 8000E274 00630019 */  multu      $v1, $v1
    /* EE78 8000E278 00006012 */  mflo       $t4
    /* EE7C 8000E27C 032C5021 */  addu       $t2, $t9, $t4
    /* EE80 8000E280 01EAC023 */  subu       $t8, $t7, $t2
    /* EE84 8000E284 01D80019 */  multu      $t6, $t8
    /* EE88 8000E288 856C0000 */  lh         $t4, 0x0($t3)
    /* EE8C 8000E28C 258F0300 */  addiu      $t7, $t4, 0x300
    /* EE90 8000E290 448F5000 */  mtc1       $t7, $ft3
    /* EE94 8000E294 00006812 */  mflo       $t5
    /* EE98 8000E298 00000000 */  nop
    /* EE9C 8000E29C 00000000 */  nop
    /* EEA0 8000E2A0 012A0019 */  multu      $t1, $t2
    /* EEA4 8000E2A4 0000C812 */  mflo       $t9
    /* EEA8 8000E2A8 01B94021 */  addu       $t0, $t5, $t9
    /* EEAC 8000E2AC 44888000 */  mtc1       $t0, $ft4
    /* EEB0 8000E2B0 00000000 */  nop
    /* EEB4 8000E2B4 468084A0 */  cvt.s.w    $ft5, $ft4
    /* EEB8 8000E2B8 46805420 */  cvt.s.w    $ft4, $ft3
    /* EEBC 8000E2BC 46009121 */  cvt.d.s    $ft0, $ft5
    /* EEC0 8000E2C0 46246181 */  sub.d      $ft1, $fa0, $ft0
    /* EEC4 8000E2C4 44812000 */  mtc1       $at, $ft0
    /* EEC8 8000E2C8 462C3203 */  div.d      $ft2, $ft1, $fa0
    /* EECC 8000E2CC 46204020 */  cvt.s.d    $fv0, $ft2
    /* EED0 8000E2D0 46008482 */  mul.s      $ft5, $ft4, $fv0
    /* EED4 8000E2D4 46049181 */  sub.s      $ft1, $ft5, $ft0
    /* EED8 8000E2D8 4600320D */  trunc.w.s  $ft2, $ft1
    /* EEDC 8000E2DC 44184000 */  mfc1       $t8, $ft2
    /* EEE0 8000E2E0 1000002D */  b          .L8000E398
    /* EEE4 8000E2E4 A5780000 */   sh        $t8, 0x0($t3)
  .L8000E2E8:
    /* EEE8 8000E2E8 00861021 */  addu       $v0, $a0, $a2
    /* EEEC 8000E2EC 2442FFFA */  addiu      $v0, $v0, -0x6
    /* EEF0 8000E2F0 00420019 */  multu      $v0, $v0
    /* EEF4 8000E2F4 00A71821 */  addu       $v1, $a1, $a3
    /* EEF8 8000E2F8 2463FFF9 */  addiu      $v1, $v1, -0x7
    /* EEFC 8000E2FC 3C098006 */  lui        $t1, %hi(D_80059CD0)
    /* EF00 8000E300 85299CD0 */  lh         $t1, %lo(D_80059CD0)($t1)
    /* EF04 8000E304 240F0019 */  addiu      $t7, $zero, 0x19
    /* EF08 8000E308 3C018003 */  lui        $at, %hi(D_80037640)
    /* EF0C 8000E30C 00096040 */  sll        $t4, $t1, 1
    /* EF10 8000E310 D42C7640 */  ldc1       $fa0, %lo(D_80037640)($at)
    /* EF14 8000E314 3C0B8006 */  lui        $t3, %hi(D_80059CD4)
    /* EF18 8000E318 00006812 */  mflo       $t5
    /* EF1C 8000E31C 256B9CD4 */  addiu      $t3, $t3, %lo(D_80059CD4)
    /* EF20 8000E320 3C014440 */  lui        $at, (0x44400000 >> 16)
    /* EF24 8000E324 00630019 */  multu      $v1, $v1
    /* EF28 8000E328 0000C812 */  mflo       $t9
    /* EF2C 8000E32C 01B95021 */  addu       $t2, $t5, $t9
    /* EF30 8000E330 01EA7023 */  subu       $t6, $t7, $t2
    /* EF34 8000E334 018E0019 */  multu      $t4, $t6
    /* EF38 8000E338 85790000 */  lh         $t9, 0x0($t3)
    /* EF3C 8000E33C 272FFD00 */  addiu      $t7, $t9, -0x300
    /* EF40 8000E340 448F4000 */  mtc1       $t7, $ft2
    /* EF44 8000E344 0000C012 */  mflo       $t8
    /* EF48 8000E348 00000000 */  nop
    /* EF4C 8000E34C 00000000 */  nop
    /* EF50 8000E350 012A0019 */  multu      $t1, $t2
    /* EF54 8000E354 00006812 */  mflo       $t5
    /* EF58 8000E358 030D4021 */  addu       $t0, $t8, $t5
    /* EF5C 8000E35C 44885000 */  mtc1       $t0, $ft3
    /* EF60 8000E360 00000000 */  nop
    /* EF64 8000E364 46805420 */  cvt.s.w    $ft4, $ft3
    /* EF68 8000E368 468042A0 */  cvt.s.w    $ft3, $ft2
    /* EF6C 8000E36C 460084A1 */  cvt.d.s    $ft5, $ft4
    /* EF70 8000E370 46326101 */  sub.d      $ft0, $fa0, $ft5
    /* EF74 8000E374 44819000 */  mtc1       $at, $ft5
    /* EF78 8000E378 462C2183 */  div.d      $ft1, $ft0, $fa0
    /* EF7C 8000E37C 46203020 */  cvt.s.d    $fv0, $ft1
    /* EF80 8000E380 46005402 */  mul.s      $ft4, $ft3, $fv0
    /* EF84 8000E384 46128100 */  add.s      $ft0, $ft4, $ft5
    /* EF88 8000E388 4600218D */  trunc.w.s  $ft1, $ft0
    /* EF8C 8000E38C 440E3000 */  mfc1       $t6, $ft1
    /* EF90 8000E390 00000000 */  nop
    /* EF94 8000E394 A56E0000 */  sh         $t6, 0x0($t3)
  .L8000E398:
    /* EF98 8000E398 3C028006 */  lui        $v0, %hi(D_80059CD2)
    /* EF9C 8000E39C 24429CD2 */  addiu      $v0, $v0, %lo(D_80059CD2)
    /* EFA0 8000E3A0 84580000 */  lh         $t8, 0x0($v0)
    /* EFA4 8000E3A4 3C014490 */  lui        $at, (0x44900000 >> 16)
    /* EFA8 8000E3A8 44819000 */  mtc1       $at, $ft5
    /* EFAC 8000E3AC 270D0480 */  addiu      $t5, $t8, 0x480
    /* EFB0 8000E3B0 448D4000 */  mtc1       $t5, $ft2
    /* EFB4 8000E3B4 00000000 */  nop
    /* EFB8 8000E3B8 468042A0 */  cvt.s.w    $ft3, $ft2
    /* EFBC 8000E3BC 46005402 */  mul.s      $ft4, $ft3, $fv0
    /* EFC0 8000E3C0 46128101 */  sub.s      $ft0, $ft4, $ft5
    /* EFC4 8000E3C4 4600218D */  trunc.w.s  $ft1, $ft0
    /* EFC8 8000E3C8 440F3000 */  mfc1       $t7, $ft1
    /* EFCC 8000E3CC 00000000 */  nop
    /* EFD0 8000E3D0 A44F0000 */  sh         $t7, 0x0($v0)
    /* EFD4 8000E3D4 03E00008 */  jr         $ra
    /* EFD8 8000E3D8 00000000 */   nop

glabel func_8000E3DC
    /* EFDC 8000E3DC 3C038006 */  lui        $v1, %hi(D_8005BAE8)
    /* EFE0 8000E3E0 2463BAE8 */  addiu      $v1, $v1, %lo(D_8005BAE8)
    /* EFE4 8000E3E4 8C620000 */  lw         $v0, 0x0($v1)
    /* EFE8 8000E3E8 AFA40000 */  sw         $a0, 0x0($sp)
    /* EFEC 8000E3EC AFA50004 */  sw         $a1, 0x4($sp)
    /* EFF0 8000E3F0 AFA60008 */  sw         $a2, 0x8($sp)
    /* EFF4 8000E3F4 AFA7000C */  sw         $a3, 0xC($sp)
    /* EFF8 8000E3F8 C4440000 */  lwc1       $ft0, 0x0($v0)
    /* EFFC 8000E3FC C446000C */  lwc1       $ft1, 0xC($v0)
    /* F000 8000E400 3C018003 */  lui        $at, %hi(D_80037648)
    /* F004 8000E404 00067400 */  sll        $t6, $a2, 16
    /* F008 8000E408 46062200 */  add.s      $ft2, $ft0, $ft1
    /* F00C 8000E40C 000E7C03 */  sra        $t7, $t6, 16
    /* F010 8000E410 000F4200 */  sll        $t0, $t7, 8
    /* F014 8000E414 0007C400 */  sll        $t8, $a3, 16
    /* F018 8000E418 E4480000 */  swc1       $ft2, 0x0($v0)
    /* F01C 8000E41C 8C620000 */  lw         $v0, 0x0($v1)
    /* F020 8000E420 0018CC03 */  sra        $t9, $t8, 16
    /* F024 8000E424 00195A00 */  sll        $t3, $t9, 8
    /* F028 8000E428 C44A0004 */  lwc1       $ft3, 0x4($v0)
    /* F02C 8000E42C C4500010 */  lwc1       $ft4, 0x10($v0)
    /* F030 8000E430 46105480 */  add.s      $ft5, $ft3, $ft4
    /* F034 8000E434 E4520004 */  swc1       $ft5, 0x4($v0)
    /* F038 8000E438 8C620000 */  lw         $v0, 0x0($v1)
    /* F03C 8000E43C D4287648 */  ldc1       $ft2, %lo(D_80037648)($at)
    /* F040 8000E440 3C018006 */  lui        $at, %hi(D_80059CD2)
    /* F044 8000E444 C4440010 */  lwc1       $ft0, 0x10($v0)
    /* F048 8000E448 460021A1 */  cvt.d.s    $ft1, $ft0
    /* F04C 8000E44C 44882000 */  mtc1       $t0, $ft0
    /* F050 8000E450 46283280 */  add.d      $ft3, $ft1, $ft2
    /* F054 8000E454 468021A0 */  cvt.s.w    $ft1, $ft0
    /* F058 8000E458 46205420 */  cvt.s.d    $ft4, $ft3
    /* F05C 8000E45C E4500010 */  swc1       $ft4, 0x10($v0)
    /* F060 8000E460 8C620000 */  lw         $v0, 0x0($v1)
    /* F064 8000E464 C4520000 */  lwc1       $ft5, 0x0($v0)
    /* F068 8000E468 46069200 */  add.s      $ft2, $ft5, $ft1
    /* F06C 8000E46C 448B9000 */  mtc1       $t3, $ft5
    /* F070 8000E470 4600428D */  trunc.w.s  $ft3, $ft2
    /* F074 8000E474 468091A0 */  cvt.s.w    $ft1, $ft5
    /* F078 8000E478 440A5000 */  mfc1       $t2, $ft3
    /* F07C 8000E47C 00000000 */  nop
    /* F080 8000E480 A42A9CD2 */  sh         $t2, %lo(D_80059CD2)($at)
    /* F084 8000E484 C4500004 */  lwc1       $ft4, 0x4($v0)
    /* F088 8000E488 3C018006 */  lui        $at, %hi(D_80059CD4)
    /* F08C 8000E48C 46008107 */  neg.s      $ft0, $ft4
    /* F090 8000E490 46062201 */  sub.s      $ft2, $ft0, $ft1
    /* F094 8000E494 4600428D */  trunc.w.s  $ft3, $ft2
    /* F098 8000E498 440D5000 */  mfc1       $t5, $ft3
    /* F09C 8000E49C 00000000 */  nop
    /* F0A0 8000E4A0 A42D9CD4 */  sh         $t5, %lo(D_80059CD4)($at)
    /* F0A4 8000E4A4 3C018006 */  lui        $at, %hi(D_80059CD6)
    /* F0A8 8000E4A8 03E00008 */  jr         $ra
    /* F0AC 8000E4AC A4209CD6 */   sh        $zero, %lo(D_80059CD6)($at)

glabel func_8000E4B0
    /* F0B0 8000E4B0 3C018006 */  lui        $at, %hi(D_8005BAEC)
    /* F0B4 8000E4B4 AC24BAEC */  sw         $a0, %lo(D_8005BAEC)($at)
    /* F0B8 8000E4B8 3C018006 */  lui        $at, %hi(D_8005BAF0)
    /* F0BC 8000E4BC 03E00008 */  jr         $ra
    /* F0C0 8000E4C0 AC25BAF0 */   sw        $a1, %lo(D_8005BAF0)($at)

glabel func_8000E4C4
    /* F0C4 8000E4C4 3C0F8003 */  lui        $t7, %hi(D_80031A90)
    /* F0C8 8000E4C8 3C038006 */  lui        $v1, %hi(D_80059CDC)
    /* F0CC 8000E4CC 25EF1A90 */  addiu      $t7, $t7, %lo(D_80031A90)
    /* F0D0 8000E4D0 00047140 */  sll        $t6, $a0, 5
    /* F0D4 8000E4D4 24639CDC */  addiu      $v1, $v1, %lo(D_80059CDC)
    /* F0D8 8000E4D8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* F0DC 8000E4DC 01CFC021 */  addu       $t8, $t6, $t7
    /* F0E0 8000E4E0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* F0E4 8000E4E4 AC780000 */  sw         $t8, 0x0($v1)
    /* F0E8 8000E4E8 87190004 */  lh         $t9, 0x4($t8)
    /* F0EC 8000E4EC 3C018006 */  lui        $at, %hi(D_80059CD0)
    /* F0F0 8000E4F0 3C048026 */  lui        $a0, %hi(D_80267080)
    /* F0F4 8000E4F4 A4399CD0 */  sh         $t9, %lo(D_80059CD0)($at)
    /* F0F8 8000E4F8 C7040008 */  lwc1       $ft0, 0x8($t8)
    /* F0FC 8000E4FC 3C018006 */  lui        $at, %hi(D_80059CE0)
    /* F100 8000E500 3C05803E */  lui        $a1, %hi(D_803DA800)
    /* F104 8000E504 E4249CE0 */  swc1       $ft0, %lo(D_80059CE0)($at)
    /* F108 8000E508 3C018006 */  lui        $at, %hi(D_80059CD8)
    /* F10C 8000E50C A4209CD8 */  sh         $zero, %lo(D_80059CD8)($at)
    /* F110 8000E510 24A5A800 */  addiu      $a1, $a1, %lo(D_803DA800)
    /* F114 8000E514 0C003727 */  jal        func_8000DC9C
    /* F118 8000E518 24847080 */   addiu     $a0, $a0, %lo(D_80267080)
    /* F11C 8000E51C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* F120 8000E520 27BD0018 */  addiu      $sp, $sp, 0x18
    /* F124 8000E524 03E00008 */  jr         $ra
    /* F128 8000E528 00000000 */   nop

glabel func_8000E52C
    /* F12C 8000E52C 00840019 */  multu      $a0, $a0
    /* F130 8000E530 00001012 */  mflo       $v0
    /* F134 8000E534 03E00008 */  jr         $ra
    /* F138 8000E538 00000000 */   nop

glabel func_8000E53C
    /* F13C 8000E53C 27BDFEC0 */  addiu      $sp, $sp, -0x140
    /* F140 8000E540 AFB50044 */  sw         $s5, 0x44($sp)
    /* F144 8000E544 3C158006 */  lui        $s5, %hi(D_8005BAEC)
    /* F148 8000E548 26B5BAEC */  addiu      $s5, $s5, %lo(D_8005BAEC)
    /* F14C 8000E54C 8EA30000 */  lw         $v1, 0x0($s5)
    /* F150 8000E550 AFB3003C */  sw         $s3, 0x3C($sp)
    /* F154 8000E554 3C138006 */  lui        $s3, %hi(D_8005BB2C)
    /* F158 8000E558 2673BB2C */  addiu      $s3, $s3, %lo(D_8005BB2C)
    /* F15C 8000E55C 8E620000 */  lw         $v0, 0x0($s3)
    /* F160 8000E560 00037823 */  negu       $t7, $v1
    /* F164 8000E564 AFBF0054 */  sw         $ra, 0x54($sp)
    /* F168 8000E568 24590008 */  addiu      $t9, $v0, 0x8
    /* F16C 8000E56C AFBE0050 */  sw         $fp, 0x50($sp)
    /* F170 8000E570 AFB7004C */  sw         $s7, 0x4C($sp)
    /* F174 8000E574 AFB60048 */  sw         $s6, 0x48($sp)
    /* F178 8000E578 AFB40040 */  sw         $s4, 0x40($sp)
    /* F17C 8000E57C AFB20038 */  sw         $s2, 0x38($sp)
    /* F180 8000E580 AFB10034 */  sw         $s1, 0x34($sp)
    /* F184 8000E584 AFB00030 */  sw         $s0, 0x30($sp)
    /* F188 8000E588 AE790000 */  sw         $t9, 0x0($s3)
    /* F18C 8000E58C 3C128006 */  lui        $s2, %hi(D_8005BAF0)
    /* F190 8000E590 2652BAF0 */  addiu      $s2, $s2, %lo(D_8005BAF0)
    /* F194 8000E594 3C108006 */  lui        $s0, %hi(D_8005BB38)
    /* F198 8000E598 2610BB38 */  addiu      $s0, $s0, %lo(D_8005BB38)
    /* F19C 8000E59C 27B40136 */  addiu      $s4, $sp, 0x136
    /* F1A0 8000E5A0 04610003 */  bgez       $v1, .L8000E5B0
    /* F1A4 8000E5A4 00037103 */   sra       $t6, $v1, 4
    /* F1A8 8000E5A8 2461000F */  addiu      $at, $v1, 0xF
    /* F1AC 8000E5AC 00017103 */  sra        $t6, $at, 4
  .L8000E5B0:
    /* F1B0 8000E5B0 AFAE0120 */  sw         $t6, 0x120($sp)
    /* F1B4 8000E5B4 05E10003 */  bgez       $t7, .L8000E5C4
    /* F1B8 8000E5B8 000FC043 */   sra       $t8, $t7, 1
    /* F1BC 8000E5BC 25E10001 */  addiu      $at, $t7, 0x1
    /* F1C0 8000E5C0 0001C043 */  sra        $t8, $at, 1
  .L8000E5C4:
    /* F1C4 8000E5C4 AFB80118 */  sw         $t8, 0x118($sp)
    /* F1C8 8000E5C8 3C0EE700 */  lui        $t6, (0xE7000000 >> 16)
    /* F1CC 8000E5CC AC4E0000 */  sw         $t6, 0x0($v0)
    /* F1D0 8000E5D0 AC400004 */  sw         $zero, 0x4($v0)
    /* F1D4 8000E5D4 8E620000 */  lw         $v0, 0x0($s3)
    /* F1D8 8000E5D8 3C18E800 */  lui        $t8, (0xE8000000 >> 16)
    /* F1DC 8000E5DC 3C0EB600 */  lui        $t6, (0xB6000000 >> 16)
    /* F1E0 8000E5E0 244F0008 */  addiu      $t7, $v0, 0x8
    /* F1E4 8000E5E4 AE6F0000 */  sw         $t7, 0x0($s3)
    /* F1E8 8000E5E8 AC400004 */  sw         $zero, 0x4($v0)
    /* F1EC 8000E5EC AC580000 */  sw         $t8, 0x0($v0)
    /* F1F0 8000E5F0 8E620000 */  lw         $v0, 0x0($s3)
    /* F1F4 8000E5F4 3C0F0002 */  lui        $t7, (0x23001 >> 16)
    /* F1F8 8000E5F8 35EF3001 */  ori        $t7, $t7, (0x23001 & 0xFFFF)
    /* F1FC 8000E5FC 24590008 */  addiu      $t9, $v0, 0x8
    /* F200 8000E600 AE790000 */  sw         $t9, 0x0($s3)
    /* F204 8000E604 AC4F0004 */  sw         $t7, 0x4($v0)
    /* F208 8000E608 AC4E0000 */  sw         $t6, 0x0($v0)
    /* F20C 8000E60C 8E620000 */  lw         $v0, 0x0($s3)
    /* F210 8000E610 3C0E0055 */  lui        $t6, (0x552048 >> 16)
    /* F214 8000E614 3C19B900 */  lui        $t9, (0xB900031D >> 16)
    /* F218 8000E618 24580008 */  addiu      $t8, $v0, 0x8
    /* F21C 8000E61C AE780000 */  sw         $t8, 0x0($s3)
    /* F220 8000E620 3739031D */  ori        $t9, $t9, (0xB900031D & 0xFFFF)
    /* F224 8000E624 35CE2048 */  ori        $t6, $t6, (0x552048 & 0xFFFF)
    /* F228 8000E628 AC4E0004 */  sw         $t6, 0x4($v0)
    /* F22C 8000E62C AC590000 */  sw         $t9, 0x0($v0)
    /* F230 8000E630 8E620000 */  lw         $v0, 0x0($s3)
    /* F234 8000E634 3C198000 */  lui        $t9, (0x80008000 >> 16)
    /* F238 8000E638 3C18BB00 */  lui        $t8, (0xBB000001 >> 16)
    /* F23C 8000E63C 244F0008 */  addiu      $t7, $v0, 0x8
    /* F240 8000E640 AE6F0000 */  sw         $t7, 0x0($s3)
    /* F244 8000E644 37180001 */  ori        $t8, $t8, (0xBB000001 & 0xFFFF)
    /* F248 8000E648 37398000 */  ori        $t9, $t9, (0x80008000 & 0xFFFF)
    /* F24C 8000E64C AC590004 */  sw         $t9, 0x4($v0)
    /* F250 8000E650 AC580000 */  sw         $t8, 0x0($v0)
    /* F254 8000E654 8E620000 */  lw         $v0, 0x0($s3)
    /* F258 8000E658 3C0FBA00 */  lui        $t7, (0xBA001301 >> 16)
    /* F25C 8000E65C 35EF1301 */  ori        $t7, $t7, (0xBA001301 & 0xFFFF)
    /* F260 8000E660 244E0008 */  addiu      $t6, $v0, 0x8
    /* F264 8000E664 AE6E0000 */  sw         $t6, 0x0($s3)
    /* F268 8000E668 3C180008 */  lui        $t8, (0x80000 >> 16)
    /* F26C 8000E66C AC580004 */  sw         $t8, 0x4($v0)
    /* F270 8000E670 AC4F0000 */  sw         $t7, 0x0($v0)
    /* F274 8000E674 8E620000 */  lw         $v0, 0x0($s3)
    /* F278 8000E678 3C0EBA00 */  lui        $t6, (0xBA000C02 >> 16)
    /* F27C 8000E67C 35CE0C02 */  ori        $t6, $t6, (0xBA000C02 & 0xFFFF)
    /* F280 8000E680 24590008 */  addiu      $t9, $v0, 0x8
    /* F284 8000E684 AE790000 */  sw         $t9, 0x0($s3)
    /* F288 8000E688 AC400004 */  sw         $zero, 0x4($v0)
    /* F28C 8000E68C AC4E0000 */  sw         $t6, 0x0($v0)
    /* F290 8000E690 8E580000 */  lw         $t8, 0x0($s2)
    /* F294 8000E694 8EAF0000 */  lw         $t7, 0x0($s5)
    /* F298 8000E698 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* F29C 8000E69C 44984000 */  mtc1       $t8, $ft2
    /* F2A0 8000E6A0 448F2000 */  mtc1       $t7, $ft0
    /* F2A4 8000E6A4 44819000 */  mtc1       $at, $ft5
    /* F2A8 8000E6A8 468042A0 */  cvt.s.w    $ft3, $ft2
    /* F2AC 8000E6AC 3C018003 */  lui        $at, %hi(D_80037650)
    /* F2B0 8000E6B0 8E040000 */  lw         $a0, 0x0($s0)
    /* F2B4 8000E6B4 02802825 */  or         $a1, $s4, $zero
    /* F2B8 8000E6B8 3C0641F0 */  lui        $a2, (0x41F00000 >> 16)
    /* F2BC 8000E6BC 468021A0 */  cvt.s.w    $ft1, $ft0
    /* F2C0 8000E6C0 C4247650 */  lwc1       $ft0, %lo(D_80037650)($at)
    /* F2C4 8000E6C4 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* F2C8 8000E6C8 44814000 */  mtc1       $at, $ft2
    /* F2CC 8000E6CC E7B20010 */  swc1       $ft5, 0x10($sp)
    /* F2D0 8000E6D0 E7A40014 */  swc1       $ft0, 0x14($sp)
    /* F2D4 8000E6D4 460A3403 */  div.s      $ft4, $ft1, $ft3
    /* F2D8 8000E6D8 E7A80018 */  swc1       $ft2, 0x18($sp)
    /* F2DC 8000E6DC 44078000 */  mfc1       $a3, $ft4
    /* F2E0 8000E6E0 0C007964 */  jal        func_8001E590
    /* F2E4 8000E6E4 00000000 */   nop
    /* F2E8 8000E6E8 8E620000 */  lw         $v0, 0x0($s3)
    /* F2EC 8000E6EC 3C0EBC00 */  lui        $t6, (0xBC00000E >> 16)
    /* F2F0 8000E6F0 35CE000E */  ori        $t6, $t6, (0xBC00000E & 0xFFFF)
    /* F2F4 8000E6F4 24590008 */  addiu      $t9, $v0, 0x8
    /* F2F8 8000E6F8 AE790000 */  sw         $t9, 0x0($s3)
    /* F2FC 8000E6FC AC540004 */  sw         $s4, 0x4($v0)
    /* F300 8000E700 AC4E0000 */  sw         $t6, 0x0($v0)
    /* F304 8000E704 8E620000 */  lw         $v0, 0x0($s3)
    /* F308 8000E708 3C180103 */  lui        $t8, (0x1030040 >> 16)
    /* F30C 8000E70C 37180040 */  ori        $t8, $t8, (0x1030040 & 0xFFFF)
    /* F310 8000E710 244F0008 */  addiu      $t7, $v0, 0x8
    /* F314 8000E714 AE6F0000 */  sw         $t7, 0x0($s3)
    /* F318 8000E718 AC580000 */  sw         $t8, 0x0($v0)
    /* F31C 8000E71C 8E190000 */  lw         $t9, 0x0($s0)
    /* F320 8000E720 3C111FFF */  lui        $s1, (0x1FFFFFFF >> 16)
    /* F324 8000E724 3631FFFF */  ori        $s1, $s1, (0x1FFFFFFF & 0xFFFF)
    /* F328 8000E728 03317024 */  and        $t6, $t9, $s1
    /* F32C 8000E72C AC4E0004 */  sw         $t6, 0x4($v0)
    /* F330 8000E730 8E0F0000 */  lw         $t7, 0x0($s0)
    /* F334 8000E734 3C018003 */  lui        $at, %hi(D_80037654)
    /* F338 8000E738 25F80040 */  addiu      $t8, $t7, 0x40
    /* F33C 8000E73C AE180000 */  sw         $t8, 0x0($s0)
    /* F340 8000E740 0C00797C */  jal        func_8001E5F0
    /* F344 8000E744 C42C7654 */   lwc1      $fa0, %lo(D_80037654)($at)
    /* F348 8000E748 3C018003 */  lui        $at, %hi(D_80037658)
    /* F34C 8000E74C C42C7658 */  lwc1       $fa0, %lo(D_80037658)($at)
    /* F350 8000E750 0C0079EC */  jal        func_8001E7B0
    /* F354 8000E754 E7A000A0 */   swc1      $fv0, 0xA0($sp)
    /* F358 8000E758 C7A600A0 */  lwc1       $ft1, 0xA0($sp)
    /* F35C 8000E75C 8E590000 */  lw         $t9, 0x0($s2)
    /* F360 8000E760 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* F364 8000E764 46003283 */  div.s      $ft3, $ft1, $fv0
    /* F368 8000E768 44818000 */  mtc1       $at, $ft4
    /* F36C 8000E76C 44992000 */  mtc1       $t9, $ft0
    /* F370 8000E770 44801000 */  mtc1       $zero, $fv1
    /* F374 8000E774 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* F378 8000E778 46802220 */  cvt.s.w    $ft2, $ft0
    /* F37C 8000E77C 44051000 */  mfc1       $a1, $fv1
    /* F380 8000E780 44061000 */  mfc1       $a2, $fv1
    /* F384 8000E784 8E040000 */  lw         $a0, 0x0($s0)
    /* F388 8000E788 E7A20010 */  swc1       $fv1, 0x10($sp)
    /* F38C 8000E78C E7A20014 */  swc1       $fv1, 0x14($sp)
    /* F390 8000E790 E7A20018 */  swc1       $fv1, 0x18($sp)
    /* F394 8000E794 E7A2001C */  swc1       $fv1, 0x1C($sp)
    /* F398 8000E798 E7A20024 */  swc1       $fv1, 0x24($sp)
    /* F39C 8000E79C 46105482 */  mul.s      $ft5, $ft3, $ft4
    /* F3A0 8000E7A0 44815000 */  mtc1       $at, $ft3
    /* F3A4 8000E7A4 00000000 */  nop
    /* F3A8 8000E7A8 E7AA0020 */  swc1       $ft3, 0x20($sp)
    /* F3AC 8000E7AC 46124183 */  div.s      $ft1, $ft2, $ft5
    /* F3B0 8000E7B0 44073000 */  mfc1       $a3, $ft1
    /* F3B4 8000E7B4 0C00779A */  jal        func_8001DE68
    /* F3B8 8000E7B8 00000000 */   nop
    /* F3BC 8000E7BC 8E620000 */  lw         $v0, 0x0($s3)
    /* F3C0 8000E7C0 3C0F0101 */  lui        $t7, (0x1010040 >> 16)
    /* F3C4 8000E7C4 35EF0040 */  ori        $t7, $t7, (0x1010040 & 0xFFFF)
    /* F3C8 8000E7C8 244E0008 */  addiu      $t6, $v0, 0x8
    /* F3CC 8000E7CC AE6E0000 */  sw         $t6, 0x0($s3)
    /* F3D0 8000E7D0 AC4F0000 */  sw         $t7, 0x0($v0)
    /* F3D4 8000E7D4 8E180000 */  lw         $t8, 0x0($s0)
    /* F3D8 8000E7D8 00401825 */  or         $v1, $v0, $zero
    /* F3DC 8000E7DC 24050014 */  addiu      $a1, $zero, 0x14
    /* F3E0 8000E7E0 0311C824 */  and        $t9, $t8, $s1
    /* F3E4 8000E7E4 AC590004 */  sw         $t9, 0x4($v0)
    /* F3E8 8000E7E8 8E0E0000 */  lw         $t6, 0x0($s0)
    /* F3EC 8000E7EC 8E620000 */  lw         $v0, 0x0($s3)
    /* F3F0 8000E7F0 3C190102 */  lui        $t9, (0x1020040 >> 16)
    /* F3F4 8000E7F4 25CF0040 */  addiu      $t7, $t6, 0x40
    /* F3F8 8000E7F8 AE0F0000 */  sw         $t7, 0x0($s0)
    /* F3FC 8000E7FC 3C0E8003 */  lui        $t6, %hi(D_80031120)
    /* F400 8000E800 24580008 */  addiu      $t8, $v0, 0x8
    /* F404 8000E804 AE780000 */  sw         $t8, 0x0($s3)
    /* F408 8000E808 25CE1120 */  addiu      $t6, $t6, %lo(D_80031120)
    /* F40C 8000E80C 01D17824 */  and        $t7, $t6, $s1
    /* F410 8000E810 37390040 */  ori        $t9, $t9, (0x1020040 & 0xFFFF)
    /* F414 8000E814 AC590000 */  sw         $t9, 0x0($v0)
    /* F418 8000E818 AC4F0004 */  sw         $t7, 0x4($v0)
    /* F41C 8000E81C 8E580000 */  lw         $t8, 0x0($s2)
    /* F420 8000E820 00402025 */  or         $a0, $v0, $zero
    /* F424 8000E824 A7A000FC */  sh         $zero, 0xFC($sp)
    /* F428 8000E828 0305001A */  div        $zero, $t8, $a1
    /* F42C 8000E82C 0000C810 */  mfhi       $t9
    /* F430 8000E830 00B94023 */  subu       $t0, $a1, $t9
    /* F434 8000E834 14A00002 */  bnez       $a1, .L8000E840
    /* F438 8000E838 00000000 */   nop
    /* F43C 8000E83C 0007000D */  break      7
  .L8000E840:
    /* F440 8000E840 2401FFFF */  addiu      $at, $zero, -0x1
    /* F444 8000E844 14A10004 */  bne        $a1, $at, .L8000E858
    /* F448 8000E848 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* F44C 8000E84C 17010002 */  bne        $t8, $at, .L8000E858
    /* F450 8000E850 00000000 */   nop
    /* F454 8000E854 0006000D */  break      6
  .L8000E858:
    /* F458 8000E858 27A400FC */  addiu      $a0, $sp, 0xFC
    /* F45C 8000E85C 15050002 */  bne        $t0, $a1, .L8000E868
    /* F460 8000E860 00003025 */   or        $a2, $zero, $zero
    /* F464 8000E864 00004025 */  or         $t0, $zero, $zero
  .L8000E868:
    /* F468 8000E868 00087023 */  negu       $t6, $t0
    /* F46C 8000E86C A7AE00FE */  sh         $t6, 0xFE($sp)
    /* F470 8000E870 A7A00100 */  sh         $zero, 0x100($sp)
    /* F474 8000E874 00002825 */  or         $a1, $zero, $zero
    /* F478 8000E878 0C000E74 */  jal        func_800039D0
    /* F47C 8000E87C 8E070000 */   lw        $a3, 0x0($s0)
    /* F480 8000E880 8E620000 */  lw         $v0, 0x0($s3)
    /* F484 8000E884 3C180100 */  lui        $t8, (0x1000040 >> 16)
    /* F488 8000E888 37180040 */  ori        $t8, $t8, (0x1000040 & 0xFFFF)
    /* F48C 8000E88C 244F0008 */  addiu      $t7, $v0, 0x8
    /* F490 8000E890 AE6F0000 */  sw         $t7, 0x0($s3)
    /* F494 8000E894 AC580000 */  sw         $t8, 0x0($v0)
    /* F498 8000E898 8E190000 */  lw         $t9, 0x0($s0)
    /* F49C 8000E89C 3C1E8006 */  lui        $fp, %hi(D_80059CD2)
    /* F4A0 8000E8A0 3C178006 */  lui        $s7, %hi(D_80059CD6)
    /* F4A4 8000E8A4 03317024 */  and        $t6, $t9, $s1
    /* F4A8 8000E8A8 AC4E0004 */  sw         $t6, 0x4($v0)
    /* F4AC 8000E8AC 8E0F0000 */  lw         $t7, 0x0($s0)
    /* F4B0 8000E8B0 3C0E803E */  lui        $t6, %hi(D_803DA800)
    /* F4B4 8000E8B4 25CEA800 */  addiu      $t6, $t6, %lo(D_803DA800)
    /* F4B8 8000E8B8 25F80040 */  addiu      $t8, $t7, 0x40
    /* F4BC 8000E8BC AE180000 */  sw         $t8, 0x0($s0)
    /* F4C0 8000E8C0 24180014 */  addiu      $t8, $zero, 0x14
    /* F4C4 8000E8C4 240F0078 */  addiu      $t7, $zero, 0x78
    /* F4C8 8000E8C8 24190001 */  addiu      $t9, $zero, 0x1
    /* F4CC 8000E8CC 3C168006 */  lui        $s6, %hi(D_8005BB34)
    /* F4D0 8000E8D0 26D6BB34 */  addiu      $s6, $s6, %lo(D_8005BB34)
    /* F4D4 8000E8D4 AFB90084 */  sw         $t9, 0x84($sp)
    /* F4D8 8000E8D8 AFAF0060 */  sw         $t7, 0x60($sp)
    /* F4DC 8000E8DC AFB80058 */  sw         $t8, 0x58($sp)
    /* F4E0 8000E8E0 AFAE0074 */  sw         $t6, 0x74($sp)
    /* F4E4 8000E8E4 AFA00070 */  sw         $zero, 0x70($sp)
    /* F4E8 8000E8E8 AFA00064 */  sw         $zero, 0x64($sp)
    /* F4EC 8000E8EC 26F79CD6 */  addiu      $s7, $s7, %lo(D_80059CD6)
    /* F4F0 8000E8F0 27DE9CD2 */  addiu      $fp, $fp, %lo(D_80059CD2)
    /* F4F4 8000E8F4 00001825 */  or         $v1, $zero, $zero
  .L8000E8F8:
    /* F4F8 8000E8F8 8FA40070 */  lw         $a0, 0x70($sp)
    /* F4FC 8000E8FC 24190001 */  addiu      $t9, $zero, 0x1
    /* F500 8000E900 AFB9008C */  sw         $t9, 0x8C($sp)
    /* F504 8000E904 00037400 */  sll        $t6, $v1, 16
    /* F508 8000E908 0004C080 */  sll        $t8, $a0, 2
    /* F50C 8000E90C 8FBF0120 */  lw         $ra, 0x120($sp)
    /* F510 8000E910 33190FFF */  andi       $t9, $t8, 0xFFF
    /* F514 8000E914 000E7C03 */  sra        $t7, $t6, 16
    /* F518 8000E918 8FB80118 */  lw         $t8, 0x118($sp)
    /* F51C 8000E91C AFAF007C */  sw         $t7, 0x7C($sp)
    /* F520 8000E920 00007180 */  sll        $t6, $zero, 6
    /* F524 8000E924 001F7980 */  sll        $t7, $ra, 6
    /* F528 8000E928 AFAF0098 */  sw         $t7, 0x98($sp)
    /* F52C 8000E92C AFAE0068 */  sw         $t6, 0x68($sp)
    /* F530 8000E930 AFB9006C */  sw         $t9, 0x6C($sp)
    /* F534 8000E934 00006825 */  or         $t5, $zero, $zero
    /* F538 8000E938 00006025 */  or         $t4, $zero, $zero
    /* F53C 8000E93C AFB8005C */  sw         $t8, 0x5C($sp)
  .L8000E940:
    /* F540 8000E940 8ED40000 */  lw         $s4, 0x0($s6)
    /* F544 8000E944 3C038006 */  lui        $v1, %hi(D_8005BAEC)
    /* F548 8000E948 8FAE0058 */  lw         $t6, 0x58($sp)
    /* F54C 8000E94C 26900010 */  addiu      $s0, $s4, 0x10
    /* F550 8000E950 26110010 */  addiu      $s1, $s0, 0x10
    /* F554 8000E954 AED00000 */  sw         $s0, 0x0($s6)
    /* F558 8000E958 26320010 */  addiu      $s2, $s1, 0x10
    /* F55C 8000E95C AED10000 */  sw         $s1, 0x0($s6)
    /* F560 8000E960 AED20000 */  sw         $s2, 0x0($s6)
    /* F564 8000E964 26590010 */  addiu      $t9, $s2, 0x10
    /* F568 8000E968 AED90000 */  sw         $t9, 0x0($s6)
    /* F56C 8000E96C 8C63BAEC */  lw         $v1, %lo(D_8005BAEC)($v1)
    /* F570 8000E970 AFAC0114 */  sw         $t4, 0x114($sp)
    /* F574 8000E974 03E05825 */  or         $t3, $ra, $zero
    /* F578 8000E978 007F082A */  slt        $at, $v1, $ra
    /* F57C 8000E97C 10200002 */  beqz       $at, .L8000E988
    /* F580 8000E980 AFAE0108 */   sw        $t6, 0x108($sp)
    /* F584 8000E984 00605825 */  or         $t3, $v1, $zero
  .L8000E988:
    /* F588 8000E988 3C028006 */  lui        $v0, %hi(D_8005BAF0)
    /* F58C 8000E98C 8C42BAF0 */  lw         $v0, %lo(D_8005BAF0)($v0)
    /* F590 8000E990 8FAF0058 */  lw         $t7, 0x58($sp)
    /* F594 8000E994 000DAC00 */  sll        $s5, $t5, 16
    /* F598 8000E998 240E0078 */  addiu      $t6, $zero, 0x78
    /* F59C 8000E99C 004F082A */  slt        $at, $v0, $t7
    /* F5A0 8000E9A0 10200002 */  beqz       $at, .L8000E9AC
    /* F5A4 8000E9A4 00157C03 */   sra       $t7, $s5, 16
    /* F5A8 8000E9A8 AFA20108 */  sw         $v0, 0x108($sp)
  .L8000E9AC:
    /* F5AC 8000E9AC 8FB8005C */  lw         $t8, 0x5C($sp)
    /* F5B0 8000E9B0 8FB90108 */  lw         $t9, 0x108($sp)
    /* F5B4 8000E9B4 3C018006 */  lui        $at, %hi(D_80059CD2)
    /* F5B8 8000E9B8 A4389CD2 */  sh         $t8, %lo(D_80059CD2)($at)
    /* F5BC 8000E9BC 3C018006 */  lui        $at, %hi(D_80059CD4)
    /* F5C0 8000E9C0 01D91023 */  subu       $v0, $t6, $t9
    /* F5C4 8000E9C4 A4229CD4 */  sh         $v0, %lo(D_80059CD4)($at)
    /* F5C8 8000E9C8 A6E00000 */  sh         $zero, 0x0($s7)
    /* F5CC 8000E9CC 3C0E8006 */  lui        $t6, %hi(D_80059CDC)
    /* F5D0 8000E9D0 8DCE9CDC */  lw         $t6, %lo(D_80059CDC)($t6)
    /* F5D4 8000E9D4 AFA20094 */  sw         $v0, 0x94($sp)
    /* F5D8 8000E9D8 AFAB0110 */  sw         $t3, 0x110($sp)
    /* F5DC 8000E9DC AFAC0090 */  sw         $t4, 0x90($sp)
    /* F5E0 8000E9E0 AFBF0088 */  sw         $ra, 0x88($sp)
    /* F5E4 8000E9E4 8DD90000 */  lw         $t9, 0x0($t6)
    /* F5E8 8000E9E8 000F2400 */  sll        $a0, $t7, 16
    /* F5EC 8000E9EC 0004C403 */  sra        $t8, $a0, 16
    /* F5F0 8000E9F0 03002025 */  or         $a0, $t8, $zero
    /* F5F4 8000E9F4 01E0A825 */  or         $s5, $t7, $zero
    /* F5F8 8000E9F8 87A5007E */  lh         $a1, 0x7E($sp)
    /* F5FC 8000E9FC 00003025 */  or         $a2, $zero, $zero
    /* F600 8000EA00 0320F809 */  jalr       $t9
    /* F604 8000EA04 24070001 */   addiu     $a3, $zero, 0x1
    /* F608 8000EA08 87CF0000 */  lh         $t7, 0x0($fp)
    /* F60C 8000EA0C 8FA20094 */  lw         $v0, 0x94($sp)
    /* F610 8000EA10 8FAB0110 */  lw         $t3, 0x110($sp)
    /* F614 8000EA14 3C088006 */  lui        $t0, %hi(D_80059CD4)
    /* F618 8000EA18 25089CD4 */  addiu      $t0, $t0, %lo(D_80059CD4)
    /* F61C 8000EA1C A68F0000 */  sh         $t7, 0x0($s4)
    /* F620 8000EA20 85180000 */  lh         $t8, 0x0($t0)
    /* F624 8000EA24 00152400 */  sll        $a0, $s5, 16
    /* F628 8000EA28 00047C03 */  sra        $t7, $a0, 16
    /* F62C 8000EA2C A6980002 */  sh         $t8, 0x2($s4)
    /* F630 8000EA30 86EE0000 */  lh         $t6, 0x0($s7)
    /* F634 8000EA34 3C188006 */  lui        $t8, %hi(D_80059CDC)
    /* F638 8000EA38 01E02025 */  or         $a0, $t7, $zero
    /* F63C 8000EA3C A68E0004 */  sh         $t6, 0x4($s4)
    /* F640 8000EA40 8FB90118 */  lw         $t9, 0x118($sp)
    /* F644 8000EA44 A6E00000 */  sh         $zero, 0x0($s7)
    /* F648 8000EA48 A5020000 */  sh         $v0, 0x0($t0)
    /* F64C 8000EA4C 01791821 */  addu       $v1, $t3, $t9
    /* F650 8000EA50 A7C30000 */  sh         $v1, 0x0($fp)
    /* F654 8000EA54 8F189CDC */  lw         $t8, %lo(D_80059CDC)($t8)
    /* F658 8000EA58 AFA30078 */  sw         $v1, 0x78($sp)
    /* F65C 8000EA5C 87A5007E */  lh         $a1, 0x7E($sp)
    /* F660 8000EA60 8F190000 */  lw         $t9, 0x0($t8)
    /* F664 8000EA64 24060001 */  addiu      $a2, $zero, 0x1
    /* F668 8000EA68 24070001 */  addiu      $a3, $zero, 0x1
    /* F66C 8000EA6C 0320F809 */  jalr       $t9
    /* F670 8000EA70 00000000 */   nop
    /* F674 8000EA74 87CE0000 */  lh         $t6, 0x0($fp)
    /* F678 8000EA78 3C0F8006 */  lui        $t7, %hi(D_80059CD4)
    /* F67C 8000EA7C 3C018006 */  lui        $at, %hi(D_80059CD2)
    /* F680 8000EA80 A60E0000 */  sh         $t6, 0x0($s0)
    /* F684 8000EA84 85EF9CD4 */  lh         $t7, %lo(D_80059CD4)($t7)
    /* F688 8000EA88 00152400 */  sll        $a0, $s5, 16
    /* F68C 8000EA8C 00003025 */  or         $a2, $zero, $zero
    /* F690 8000EA90 A60F0002 */  sh         $t7, 0x2($s0)
    /* F694 8000EA94 86F80000 */  lh         $t8, 0x0($s7)
    /* F698 8000EA98 00047C03 */  sra        $t7, $a0, 16
    /* F69C 8000EA9C 01E02025 */  or         $a0, $t7, $zero
    /* F6A0 8000EAA0 A6180004 */  sh         $t8, 0x4($s0)
    /* F6A4 8000EAA4 8FB9005C */  lw         $t9, 0x5C($sp)
    /* F6A8 8000EAA8 8FAE0060 */  lw         $t6, 0x60($sp)
    /* F6AC 8000EAAC 3C188006 */  lui        $t8, %hi(D_80059CDC)
    /* F6B0 8000EAB0 A4399CD2 */  sh         $t9, %lo(D_80059CD2)($at)
    /* F6B4 8000EAB4 3C018006 */  lui        $at, %hi(D_80059CD4)
    /* F6B8 8000EAB8 A42E9CD4 */  sh         $t6, %lo(D_80059CD4)($at)
    /* F6BC 8000EABC A6E00000 */  sh         $zero, 0x0($s7)
    /* F6C0 8000EAC0 8F189CDC */  lw         $t8, %lo(D_80059CDC)($t8)
    /* F6C4 8000EAC4 87A5007E */  lh         $a1, 0x7E($sp)
    /* F6C8 8000EAC8 00003825 */  or         $a3, $zero, $zero
    /* F6CC 8000EACC 8F190000 */  lw         $t9, 0x0($t8)
    /* F6D0 8000EAD0 0320F809 */  jalr       $t9
    /* F6D4 8000EAD4 00000000 */   nop
    /* F6D8 8000EAD8 87CE0000 */  lh         $t6, 0x0($fp)
    /* F6DC 8000EADC 8FAB0110 */  lw         $t3, 0x110($sp)
    /* F6E0 8000EAE0 8FAC0090 */  lw         $t4, 0x90($sp)
    /* F6E4 8000EAE4 8FBF0088 */  lw         $ra, 0x88($sp)
    /* F6E8 8000EAE8 3C0F8006 */  lui        $t7, %hi(D_80059CD4)
    /* F6EC 8000EAEC A62E0000 */  sh         $t6, 0x0($s1)
    /* F6F0 8000EAF0 85EF9CD4 */  lh         $t7, %lo(D_80059CD4)($t7)
    /* F6F4 8000EAF4 3C018006 */  lui        $at, %hi(D_80059CD4)
    /* F6F8 8000EAF8 3C038006 */  lui        $v1, %hi(D_8005BAEC)
    /* F6FC 8000EAFC A62F0002 */  sh         $t7, 0x2($s1)
    /* F700 8000EB00 86F80000 */  lh         $t8, 0x0($s7)
    /* F704 8000EB04 00152400 */  sll        $a0, $s5, 16
    /* F708 8000EB08 A6380004 */  sh         $t8, 0x4($s1)
    /* F70C 8000EB0C 8FB90078 */  lw         $t9, 0x78($sp)
    /* F710 8000EB10 8FAE0060 */  lw         $t6, 0x60($sp)
    /* F714 8000EB14 0004C403 */  sra        $t8, $a0, 16
    /* F718 8000EB18 A7D90000 */  sh         $t9, 0x0($fp)
    /* F71C 8000EB1C A42E9CD4 */  sh         $t6, %lo(D_80059CD4)($at)
    /* F720 8000EB20 A6E00000 */  sh         $zero, 0x0($s7)
    /* F724 8000EB24 8C63BAEC */  lw         $v1, %lo(D_8005BAEC)($v1)
    /* F728 8000EB28 87CF0000 */  lh         $t7, 0x0($fp)
    /* F72C 8000EB2C 3C198006 */  lui        $t9, %hi(D_80059CDC)
    /* F730 8000EB30 03002025 */  or         $a0, $t8, $zero
    /* F734 8000EB34 006F082A */  slt        $at, $v1, $t7
    /* F738 8000EB38 10200002 */  beqz       $at, .L8000EB44
    /* F73C 8000EB3C 00000000 */   nop
    /* F740 8000EB40 A7C30000 */  sh         $v1, 0x0($fp)
  .L8000EB44:
    /* F744 8000EB44 8F399CDC */  lw         $t9, %lo(D_80059CDC)($t9)
    /* F748 8000EB48 AFAB0110 */  sw         $t3, 0x110($sp)
    /* F74C 8000EB4C AFAC0090 */  sw         $t4, 0x90($sp)
    /* F750 8000EB50 AFBF0088 */  sw         $ra, 0x88($sp)
    /* F754 8000EB54 8F390000 */  lw         $t9, 0x0($t9)
    /* F758 8000EB58 87A5007E */  lh         $a1, 0x7E($sp)
    /* F75C 8000EB5C 24060001 */  addiu      $a2, $zero, 0x1
    /* F760 8000EB60 0320F809 */  jalr       $t9
    /* F764 8000EB64 00003825 */   or        $a3, $zero, $zero
    /* F768 8000EB68 87CE0000 */  lh         $t6, 0x0($fp)
    /* F76C 8000EB6C 8FA60064 */  lw         $a2, 0x64($sp)
    /* F770 8000EB70 8FA70068 */  lw         $a3, 0x68($sp)
    /* F774 8000EB74 8FAB0110 */  lw         $t3, 0x110($sp)
    /* F778 8000EB78 8FAC0090 */  lw         $t4, 0x90($sp)
    /* F77C 8000EB7C 8FBF0088 */  lw         $ra, 0x88($sp)
    /* F780 8000EB80 3C0F8006 */  lui        $t7, %hi(D_80059CD4)
    /* F784 8000EB84 A64E0000 */  sh         $t6, 0x0($s2)
    /* F788 8000EB88 85EF9CD4 */  lh         $t7, %lo(D_80059CD4)($t7)
    /* F78C 8000EB8C 000B2180 */  sll        $a0, $t3, 6
    /* F790 8000EB90 240500FF */  addiu      $a1, $zero, 0xFF
    /* F794 8000EB94 A64F0002 */  sh         $t7, 0x2($s2)
    /* F798 8000EB98 86F80000 */  lh         $t8, 0x0($s7)
    /* F79C 8000EB9C 240300FF */  addiu      $v1, $zero, 0xFF
    /* F7A0 8000EBA0 3C01F510 */  lui        $at, (0xF5100000 >> 16)
    /* F7A4 8000EBA4 A6580004 */  sh         $t8, 0x4($s2)
    /* F7A8 8000EBA8 A6270008 */  sh         $a3, 0x8($s1)
    /* F7AC 8000EBAC A6870008 */  sh         $a3, 0x8($s4)
    /* F7B0 8000EBB0 8FA20108 */  lw         $v0, 0x108($sp)
    /* F7B4 8000EBB4 3C18FD10 */  lui        $t8, (0xFD10013F >> 16)
    /* F7B8 8000EBB8 3718013F */  ori        $t8, $t8, (0xFD10013F & 0xFFFF)
    /* F7BC 8000EBBC 0002C980 */  sll        $t9, $v0, 6
    /* F7C0 8000EBC0 A619000A */  sh         $t9, 0xA($s0)
    /* F7C4 8000EBC4 A699000A */  sh         $t9, 0xA($s4)
    /* F7C8 8000EBC8 A6040008 */  sh         $a0, 0x8($s0)
    /* F7CC 8000EBCC A6440008 */  sh         $a0, 0x8($s2)
    /* F7D0 8000EBD0 A646000A */  sh         $a2, 0xA($s2)
    /* F7D4 8000EBD4 A626000A */  sh         $a2, 0xA($s1)
    /* F7D8 8000EBD8 A285000C */  sb         $a1, 0xC($s4)
    /* F7DC 8000EBDC A285000D */  sb         $a1, 0xD($s4)
    /* F7E0 8000EBE0 A285000E */  sb         $a1, 0xE($s4)
    /* F7E4 8000EBE4 A285000F */  sb         $a1, 0xF($s4)
    /* F7E8 8000EBE8 A203000C */  sb         $v1, 0xC($s0)
    /* F7EC 8000EBEC A203000D */  sb         $v1, 0xD($s0)
    /* F7F0 8000EBF0 A203000E */  sb         $v1, 0xE($s0)
    /* F7F4 8000EBF4 A203000F */  sb         $v1, 0xF($s0)
    /* F7F8 8000EBF8 A223000C */  sb         $v1, 0xC($s1)
    /* F7FC 8000EBFC A223000D */  sb         $v1, 0xD($s1)
    /* F800 8000EC00 A223000E */  sb         $v1, 0xE($s1)
    /* F804 8000EC04 A223000F */  sb         $v1, 0xF($s1)
    /* F808 8000EC08 A243000C */  sb         $v1, 0xC($s2)
    /* F80C 8000EC0C A243000D */  sb         $v1, 0xD($s2)
    /* F810 8000EC10 A243000E */  sb         $v1, 0xE($s2)
    /* F814 8000EC14 A243000F */  sb         $v1, 0xF($s2)
    /* F818 8000EC18 8E620000 */  lw         $v0, 0x0($s3)
    /* F81C 8000EC1C 000B4080 */  sll        $t0, $t3, 2
    /* F820 8000EC20 244F0008 */  addiu      $t7, $v0, 0x8
    /* F824 8000EC24 AE6F0000 */  sw         $t7, 0x0($s3)
    /* F828 8000EC28 AC580000 */  sw         $t8, 0x0($v0)
    /* F82C 8000EC2C 8FB90074 */  lw         $t9, 0x74($sp)
    /* F830 8000EC30 016C7823 */  subu       $t7, $t3, $t4
    /* F834 8000EC34 000FC040 */  sll        $t8, $t7, 1
    /* F838 8000EC38 AC590004 */  sw         $t9, 0x4($v0)
    /* F83C 8000EC3C 8E620000 */  lw         $v0, 0x0($s3)
    /* F840 8000EC40 27190009 */  addiu      $t9, $t8, 0x9
    /* F844 8000EC44 244E0008 */  addiu      $t6, $v0, 0x8
    /* F848 8000EC48 AE6E0000 */  sw         $t6, 0x0($s3)
    /* F84C 8000EC4C 001970C3 */  sra        $t6, $t9, 3
    /* F850 8000EC50 31CF01FF */  andi       $t7, $t6, 0x1FF
    /* F854 8000EC54 000FC240 */  sll        $t8, $t7, 9
    /* F858 8000EC58 3C0E0708 */  lui        $t6, (0x7080200 >> 16)
    /* F85C 8000EC5C 35CE0200 */  ori        $t6, $t6, (0x7080200 & 0xFFFF)
    /* F860 8000EC60 0301C825 */  or         $t9, $t8, $at
    /* F864 8000EC64 AC590000 */  sw         $t9, 0x0($v0)
    /* F868 8000EC68 AC4E0004 */  sw         $t6, 0x4($v0)
    /* F86C 8000EC6C 8E620000 */  lw         $v0, 0x0($s3)
    /* F870 8000EC70 3C18E600 */  lui        $t8, (0xE6000000 >> 16)
    /* F874 8000EC74 000C7080 */  sll        $t6, $t4, 2
    /* F878 8000EC78 244F0008 */  addiu      $t7, $v0, 0x8
    /* F87C 8000EC7C AE6F0000 */  sw         $t7, 0x0($s3)
    /* F880 8000EC80 AC400004 */  sw         $zero, 0x4($v0)
    /* F884 8000EC84 AC580000 */  sw         $t8, 0x0($v0)
    /* F888 8000EC88 8E620000 */  lw         $v0, 0x0($s3)
    /* F88C 8000EC8C 31CF0FFF */  andi       $t7, $t6, 0xFFF
    /* F890 8000EC90 8FAE006C */  lw         $t6, 0x6C($sp)
    /* F894 8000EC94 24590008 */  addiu      $t9, $v0, 0x8
    /* F898 8000EC98 AE790000 */  sw         $t9, 0x0($s3)
    /* F89C 8000EC9C 000FC300 */  sll        $t8, $t7, 12
    /* F8A0 8000ECA0 3C01F400 */  lui        $at, (0xF4000000 >> 16)
    /* F8A4 8000ECA4 0301C825 */  or         $t9, $t8, $at
    /* F8A8 8000ECA8 032E7825 */  or         $t7, $t9, $t6
    /* F8AC 8000ECAC AC4F0000 */  sw         $t7, 0x0($v0)
    /* F8B0 8000ECB0 8FA90108 */  lw         $t1, 0x108($sp)
    /* F8B4 8000ECB4 31180FFF */  andi       $t8, $t0, 0xFFF
    /* F8B8 8000ECB8 00184300 */  sll        $t0, $t8, 12
    /* F8BC 8000ECBC 3C010700 */  lui        $at, (0x7000000 >> 16)
    /* F8C0 8000ECC0 00097080 */  sll        $t6, $t1, 2
    /* F8C4 8000ECC4 31C90FFF */  andi       $t1, $t6, 0xFFF
    /* F8C8 8000ECC8 0101C025 */  or         $t8, $t0, $at
    /* F8CC 8000ECCC 0309C825 */  or         $t9, $t8, $t1
    /* F8D0 8000ECD0 AC590004 */  sw         $t9, 0x4($v0)
    /* F8D4 8000ECD4 8E620000 */  lw         $v0, 0x0($s3)
    /* F8D8 8000ECD8 3C0FE700 */  lui        $t7, (0xE7000000 >> 16)
    /* F8DC 8000ECDC 3C01F510 */  lui        $at, (0xF5100000 >> 16)
    /* F8E0 8000ECE0 244E0008 */  addiu      $t6, $v0, 0x8
    /* F8E4 8000ECE4 AE6E0000 */  sw         $t6, 0x0($s3)
    /* F8E8 8000ECE8 AC4F0000 */  sw         $t7, 0x0($v0)
    /* F8EC 8000ECEC 8FAD008C */  lw         $t5, 0x8C($sp)
    /* F8F0 8000ECF0 8FB10114 */  lw         $s1, 0x114($sp)
    /* F8F4 8000ECF4 8FA70120 */  lw         $a3, 0x120($sp)
    /* F8F8 8000ECF8 AC400004 */  sw         $zero, 0x4($v0)
    /* F8FC 8000ECFC 8E620000 */  lw         $v0, 0x0($s3)
    /* F900 8000ED00 0171C823 */  subu       $t9, $t3, $s1
    /* F904 8000ED04 00197040 */  sll        $t6, $t9, 1
    /* F908 8000ED08 24580008 */  addiu      $t8, $v0, 0x8
    /* F90C 8000ED0C AE780000 */  sw         $t8, 0x0($s3)
    /* F910 8000ED10 25CF0009 */  addiu      $t7, $t6, 0x9
    /* F914 8000ED14 000FC0C3 */  sra        $t8, $t7, 3
    /* F918 8000ED18 331901FF */  andi       $t9, $t8, 0x1FF
    /* F91C 8000ED1C 00197240 */  sll        $t6, $t9, 9
    /* F920 8000ED20 3C180008 */  lui        $t8, (0x80200 >> 16)
    /* F924 8000ED24 37180200 */  ori        $t8, $t8, (0x80200 & 0xFFFF)
    /* F928 8000ED28 01C17825 */  or         $t7, $t6, $at
    /* F92C 8000ED2C AC4F0000 */  sw         $t7, 0x0($v0)
    /* F930 8000ED30 AC580004 */  sw         $t8, 0x4($v0)
    /* F934 8000ED34 8E620000 */  lw         $v0, 0x0($s3)
    /* F938 8000ED38 00117080 */  sll        $t6, $s1, 2
    /* F93C 8000ED3C 31CF0FFF */  andi       $t7, $t6, 0xFFF
    /* F940 8000ED40 24590008 */  addiu      $t9, $v0, 0x8
    /* F944 8000ED44 8FAE006C */  lw         $t6, 0x6C($sp)
    /* F948 8000ED48 AE790000 */  sw         $t9, 0x0($s3)
    /* F94C 8000ED4C 000FC300 */  sll        $t8, $t7, 12
    /* F950 8000ED50 3C01F200 */  lui        $at, (0xF2000000 >> 16)
    /* F954 8000ED54 0301C825 */  or         $t9, $t8, $at
    /* F958 8000ED58 0109C025 */  or         $t8, $t0, $t1
    /* F95C 8000ED5C 032E7825 */  or         $t7, $t9, $t6
    /* F960 8000ED60 AC4F0000 */  sw         $t7, 0x0($v0)
    /* F964 8000ED64 AC580004 */  sw         $t8, 0x4($v0)
    /* F968 8000ED68 8E620000 */  lw         $v0, 0x0($s3)
    /* F96C 8000ED6C 3C011FFF */  lui        $at, (0x1FFFFFFF >> 16)
    /* F970 8000ED70 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
    /* F974 8000ED74 24590008 */  addiu      $t9, $v0, 0x8
    /* F978 8000ED78 AE790000 */  sw         $t9, 0x0($s3)
    /* F97C 8000ED7C 3C0E0400 */  lui        $t6, (0x400103F >> 16)
    /* F980 8000ED80 35CE103F */  ori        $t6, $t6, (0x400103F & 0xFFFF)
    /* F984 8000ED84 02817824 */  and        $t7, $s4, $at
    /* F988 8000ED88 AC4F0004 */  sw         $t7, 0x4($v0)
    /* F98C 8000ED8C AC4E0000 */  sw         $t6, 0x0($v0)
    /* F990 8000ED90 8E620000 */  lw         $v0, 0x0($s3)
    /* F994 8000ED94 3C0E0002 */  lui        $t6, (0x20406 >> 16)
    /* F998 8000ED98 3C19B100 */  lui        $t9, (0xB1000204 >> 16)
    /* F99C 8000ED9C 24580008 */  addiu      $t8, $v0, 0x8
    /* F9A0 8000EDA0 AE780000 */  sw         $t8, 0x0($s3)
    /* F9A4 8000EDA4 37390204 */  ori        $t9, $t9, (0xB1000204 & 0xFFFF)
    /* F9A8 8000EDA8 35CE0406 */  ori        $t6, $t6, (0x20406 & 0xFFFF)
    /* F9AC 8000EDAC AC4E0004 */  sw         $t6, 0x4($v0)
    /* F9B0 8000EDB0 AC590000 */  sw         $t9, 0x0($v0)
    /* F9B4 8000EDB4 8FAF0068 */  lw         $t7, 0x68($sp)
    /* F9B8 8000EDB8 8FB80098 */  lw         $t8, 0x98($sp)
    /* F9BC 8000EDBC 8FAE005C */  lw         $t6, 0x5C($sp)
    /* F9C0 8000EDC0 24010010 */  addiu      $at, $zero, 0x10
    /* F9C4 8000EDC4 01F8C821 */  addu       $t9, $t7, $t8
    /* F9C8 8000EDC8 25B00001 */  addiu      $s0, $t5, 0x1
    /* F9CC 8000EDCC 01C77821 */  addu       $t7, $t6, $a3
    /* F9D0 8000EDD0 AFAF005C */  sw         $t7, 0x5C($sp)
    /* F9D4 8000EDD4 AFB0008C */  sw         $s0, 0x8C($sp)
    /* F9D8 8000EDD8 AFB90068 */  sw         $t9, 0x68($sp)
    /* F9DC 8000EDDC 01876021 */  addu       $t4, $t4, $a3
    /* F9E0 8000EDE0 15A1FED7 */  bne        $t5, $at, .L8000E940
    /* F9E4 8000EDE4 03E7F821 */   addu      $ra, $ra, $a3
    /* F9E8 8000EDE8 8FB80070 */  lw         $t8, 0x70($sp)
    /* F9EC 8000EDEC 8FAE0064 */  lw         $t6, 0x64($sp)
    /* F9F0 8000EDF0 8FA30084 */  lw         $v1, 0x84($sp)
    /* F9F4 8000EDF4 27190014 */  addiu      $t9, $t8, 0x14
    /* F9F8 8000EDF8 25CF0500 */  addiu      $t7, $t6, 0x500
    /* F9FC 8000EDFC 8FAE0058 */  lw         $t6, 0x58($sp)
    /* FA00 8000EE00 8FB80060 */  lw         $t8, 0x60($sp)
    /* FA04 8000EE04 AFAF0064 */  sw         $t7, 0x64($sp)
    /* FA08 8000EE08 AFB90070 */  sw         $t9, 0x70($sp)
    /* FA0C 8000EE0C 2401000C */  addiu      $at, $zero, 0xC
    /* FA10 8000EE10 24620001 */  addiu      $v0, $v1, 0x1
    /* FA14 8000EE14 25CF0014 */  addiu      $t7, $t6, 0x14
    /* FA18 8000EE18 2719FFEC */  addiu      $t9, $t8, -0x14
    /* FA1C 8000EE1C AFB90060 */  sw         $t9, 0x60($sp)
    /* FA20 8000EE20 AFAF0058 */  sw         $t7, 0x58($sp)
    /* FA24 8000EE24 1461FEB4 */  bne        $v1, $at, .L8000E8F8
    /* FA28 8000EE28 AFA20084 */   sw        $v0, 0x84($sp)
    /* FA2C 8000EE2C 3C028006 */  lui        $v0, %hi(D_80059CDC)
    /* FA30 8000EE30 8C429CDC */  lw         $v0, %lo(D_80059CDC)($v0)
    /* FA34 8000EE34 3C058006 */  lui        $a1, %hi(D_80059CD0)
    /* FA38 8000EE38 24A59CD0 */  addiu      $a1, $a1, %lo(D_80059CD0)
    /* FA3C 8000EE3C 84A40000 */  lh         $a0, 0x0($a1)
    /* FA40 8000EE40 84430010 */  lh         $v1, 0x10($v0)
    /* FA44 8000EE44 3C068006 */  lui        $a2, %hi(D_80059CE0)
    /* FA48 8000EE48 24C69CE0 */  addiu      $a2, $a2, %lo(D_80059CE0)
    /* FA4C 8000EE4C 0064082A */  slt        $at, $v1, $a0
    /* FA50 8000EE50 50200007 */  beql       $at, $zero, .L8000EE70
    /* FA54 8000EE54 44842000 */   mtc1      $a0, $ft0
    /* FA58 8000EE58 44808000 */  mtc1       $zero, $ft4
    /* FA5C 8000EE5C A4A30000 */  sh         $v1, 0x0($a1)
    /* FA60 8000EE60 24020001 */  addiu      $v0, $zero, 0x1
    /* FA64 8000EE64 10000019 */  b          .L8000EECC
    /* FA68 8000EE68 E4D00000 */   swc1      $ft4, 0x0($a2)
    /* FA6C 8000EE6C 44842000 */  mtc1       $a0, $ft0
  .L8000EE70:
    /* FA70 8000EE70 3C068006 */  lui        $a2, %hi(D_80059CE0)
    /* FA74 8000EE74 24C69CE0 */  addiu      $a2, $a2, %lo(D_80059CE0)
    /* FA78 8000EE78 46802220 */  cvt.s.w    $ft2, $ft0
    /* FA7C 8000EE7C C4C00000 */  lwc1       $fv0, 0x0($a2)
    /* FA80 8000EE80 3C038006 */  lui        $v1, %hi(D_80059CD8)
    /* FA84 8000EE84 24639CD8 */  addiu      $v1, $v1, %lo(D_80059CD8)
    /* FA88 8000EE88 846E0000 */  lh         $t6, 0x0($v1)
    /* FA8C 8000EE8C 46004480 */  add.s      $ft5, $ft2, $fv0
    /* FA90 8000EE90 25CF0001 */  addiu      $t7, $t6, 0x1
    /* FA94 8000EE94 4600918D */  trunc.w.s  $ft1, $ft5
    /* FA98 8000EE98 44193000 */  mfc1       $t9, $ft1
    /* FA9C 8000EE9C 00000000 */  nop
    /* FAA0 8000EEA0 A4B90000 */  sh         $t9, 0x0($a1)
    /* FAA4 8000EEA4 C44A000C */  lwc1       $ft3, 0xC($v0)
    /* FAA8 8000EEA8 A46F0000 */  sh         $t7, 0x0($v1)
    /* FAAC 8000EEAC 84780000 */  lh         $t8, 0x0($v1)
    /* FAB0 8000EEB0 460A0400 */  add.s      $ft4, $fv0, $ft3
    /* FAB4 8000EEB4 00001025 */  or         $v0, $zero, $zero
    /* FAB8 8000EEB8 2B010080 */  slti       $at, $t8, 0x80
    /* FABC 8000EEBC 14200003 */  bnez       $at, .L8000EECC
    /* FAC0 8000EEC0 E4D00000 */   swc1      $ft4, 0x0($a2)
    /* FAC4 8000EEC4 2419007F */  addiu      $t9, $zero, 0x7F
    /* FAC8 8000EEC8 A4790000 */  sh         $t9, 0x0($v1)
  .L8000EECC:
    /* FACC 8000EECC 8FBF0054 */  lw         $ra, 0x54($sp)
    /* FAD0 8000EED0 8FB00030 */  lw         $s0, 0x30($sp)
    /* FAD4 8000EED4 8FB10034 */  lw         $s1, 0x34($sp)
    /* FAD8 8000EED8 8FB20038 */  lw         $s2, 0x38($sp)
    /* FADC 8000EEDC 8FB3003C */  lw         $s3, 0x3C($sp)
    /* FAE0 8000EEE0 8FB40040 */  lw         $s4, 0x40($sp)
    /* FAE4 8000EEE4 8FB50044 */  lw         $s5, 0x44($sp)
    /* FAE8 8000EEE8 8FB60048 */  lw         $s6, 0x48($sp)
    /* FAEC 8000EEEC 8FB7004C */  lw         $s7, 0x4C($sp)
    /* FAF0 8000EEF0 8FBE0050 */  lw         $fp, 0x50($sp)
    /* FAF4 8000EEF4 03E00008 */  jr         $ra
    /* FAF8 8000EEF8 27BD0140 */   addiu     $sp, $sp, 0x140
    /* FAFC 8000EEFC 00000000 */  nop
