.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.33.0 */

glabel func_8000EF00
    /* FB00 8000EF00 AFA40000 */  sw         $a0, 0x0($sp)
    /* FB04 8000EF04 AFA50004 */  sw         $a1, 0x4($sp)
    /* FB08 8000EF08 03E00008 */  jr         $ra
    /* FB0C 8000EF0C AFA60008 */   sw        $a2, 0x8($sp)

glabel func_8000EF10
    /* FB10 8000EF10 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* FB14 8000EF14 AFA40020 */  sw         $a0, 0x20($sp)
    /* FB18 8000EF18 3C048004 */  lui        $a0, %hi(D_8003FB20)
    /* FB1C 8000EF1C 3C0E803F */  lui        $t6, (0x803FFFFF >> 16)
    /* FB20 8000EF20 2484FB20 */  addiu      $a0, $a0, %lo(D_8003FB20)
    /* FB24 8000EF24 AFBF001C */  sw         $ra, 0x1C($sp)
    /* FB28 8000EF28 3C018007 */  lui        $at, %hi(D_80068078)
    /* FB2C 8000EF2C 35CEFFFF */  ori        $t6, $t6, (0x803FFFFF & 0xFFFF)
    /* FB30 8000EF30 A4208078 */  sh         $zero, %lo(D_80068078)($at)
    /* FB34 8000EF34 0C007A48 */  jal        func_8001E920
    /* FB38 8000EF38 01C42823 */   subu      $a1, $t6, $a0
    /* FB3C 8000EF3C 0C007834 */  jal        func_8001E0D0
    /* FB40 8000EF40 00000000 */   nop
    /* FB44 8000EF44 3C048006 */  lui        $a0, %hi(D_80067388)
    /* FB48 8000EF48 3C0F8006 */  lui        $t7, %hi(D_8005C760)
    /* FB4C 8000EF4C 24847388 */  addiu      $a0, $a0, %lo(D_80067388)
    /* FB50 8000EF50 25EFC760 */  addiu      $t7, $t7, %lo(D_8005C760)
    /* FB54 8000EF54 3C068001 */  lui        $a2, %hi(func_8000EFB8)
    /* FB58 8000EF58 2418000A */  addiu      $t8, $zero, 0xA
    /* FB5C 8000EF5C AC800000 */  sw         $zero, 0x0($a0)
    /* FB60 8000EF60 AC800008 */  sw         $zero, 0x8($a0)
    /* FB64 8000EF64 AFB80014 */  sw         $t8, 0x14($sp)
    /* FB68 8000EF68 24C6EFB8 */  addiu      $a2, $a2, %lo(func_8000EFB8)
    /* FB6C 8000EF6C AFAF0010 */  sw         $t7, 0x10($sp)
    /* FB70 8000EF70 24050001 */  addiu      $a1, $zero, 0x1
    /* FB74 8000EF74 0C006BA4 */  jal        func_8001AE90
    /* FB78 8000EF78 00003825 */   or        $a3, $zero, $zero
    /* FB7C 8000EF7C 3C048006 */  lui        $a0, %hi(D_80067388)
    /* FB80 8000EF80 0C006BF8 */  jal        func_8001AFE0
    /* FB84 8000EF84 24847388 */   addiu     $a0, $a0, %lo(D_80067388)
    /* FB88 8000EF88 8FBF001C */  lw         $ra, 0x1C($sp)
    /* FB8C 8000EF8C 27BD0020 */  addiu      $sp, $sp, 0x20
    /* FB90 8000EF90 03E00008 */  jr         $ra
    /* FB94 8000EF94 00000000 */   nop

glabel func_8000EF98
    /* FB98 8000EF98 3C028003 */  lui        $v0, %hi(D_80035630)
    /* FB9C 8000EF9C 3C0E0033 */  lui        $t6, (0x330251 >> 16)
    /* FBA0 8000EFA0 24425630 */  addiu      $v0, $v0, %lo(D_80035630)
    /* FBA4 8000EFA4 35CE0251 */  ori        $t6, $t6, (0x330251 & 0xFFFF)
    /* FBA8 8000EFA8 240F036D */  addiu      $t7, $zero, 0x36D
    /* FBAC 8000EFAC AC4E0530 */  sw         $t6, 0x530($v0)
    /* FBB0 8000EFB0 03E00008 */  jr         $ra
    /* FBB4 8000EFB4 AC4F052C */   sw        $t7, 0x52C($v0)

glabel func_8000EFB8
    /* FBB8 8000EFB8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* FBBC 8000EFBC 3C028026 */  lui        $v0, %hi(D_80267080)
    /* FBC0 8000EFC0 3C03802B */  lui        $v1, %hi(D_802B2080)
    /* FBC4 8000EFC4 AFBF001C */  sw         $ra, 0x1C($sp)
    /* FBC8 8000EFC8 AFA40020 */  sw         $a0, 0x20($sp)
    /* FBCC 8000EFCC 24632080 */  addiu      $v1, $v1, %lo(D_802B2080)
    /* FBD0 8000EFD0 24427080 */  addiu      $v0, $v0, %lo(D_80267080)
  .L8000EFD4:
    /* FBD4 8000EFD4 24420008 */  addiu      $v0, $v0, 0x8
    /* FBD8 8000EFD8 A440FFFA */  sh         $zero, -0x6($v0)
    /* FBDC 8000EFDC A440FFFC */  sh         $zero, -0x4($v0)
    /* FBE0 8000EFE0 A440FFFE */  sh         $zero, -0x2($v0)
    /* FBE4 8000EFE4 1443FFFB */  bne        $v0, $v1, .L8000EFD4
    /* FBE8 8000EFE8 A440FFF8 */   sh        $zero, -0x8($v0)
    /* FBEC 8000EFEC 0C007A70 */  jal        func_8001E9C0
    /* FBF0 8000EFF0 240400FE */   addiu     $a0, $zero, 0xFE
    /* FBF4 8000EFF4 3C028000 */  lui        $v0, %hi(D_80000300)
    /* FBF8 8000EFF8 8C420300 */  lw         $v0, %lo(D_80000300)($v0)
    /* FBFC 8000EFFC 54400009 */  bnel       $v0, $zero, .L8000F024
    /* FC00 8000F000 24010002 */   addiu     $at, $zero, 0x2
    /* FC04 8000F004 0C003BE6 */  jal        func_8000EF98
    /* FC08 8000F008 00000000 */   nop
    /* FC0C 8000F00C 3C048003 */  lui        $a0, %hi(D_80035B30)
    /* FC10 8000F010 0C007B60 */  jal        func_8001ED80
    /* FC14 8000F014 24845B30 */   addiu     $a0, $a0, %lo(D_80035B30)
    /* FC18 8000F018 1000000B */  b          .L8000F048
    /* FC1C 8000F01C 00000000 */   nop
    /* FC20 8000F020 24010002 */  addiu      $at, $zero, 0x2
  .L8000F024:
    /* FC24 8000F024 14410006 */  bne        $v0, $at, .L8000F040
    /* FC28 8000F028 3C048003 */   lui       $a0, %hi(D_800356D0)
    /* FC2C 8000F02C 3C048003 */  lui        $a0, %hi(D_80035F90)
    /* FC30 8000F030 0C007B60 */  jal        func_8001ED80
    /* FC34 8000F034 24845F90 */   addiu     $a0, $a0, %lo(D_80035F90)
    /* FC38 8000F038 10000003 */  b          .L8000F048
    /* FC3C 8000F03C 00000000 */   nop
  .L8000F040:
    /* FC40 8000F040 0C007B60 */  jal        func_8001ED80
    /* FC44 8000F044 248456D0 */   addiu     $a0, $a0, %lo(D_800356D0)
  .L8000F048:
    /* FC48 8000F048 3C048026 */  lui        $a0, %hi(D_80267080)
    /* FC4C 8000F04C 0C007B7C */  jal        func_8001EDF0
    /* FC50 8000F050 24847080 */   addiu     $a0, $a0, %lo(D_80267080)
    /* FC54 8000F054 3C048006 */  lui        $a0, %hi(D_80067538)
    /* FC58 8000F058 3C0E8006 */  lui        $t6, %hi(D_8005CF68)
    /* FC5C 8000F05C 24847538 */  addiu      $a0, $a0, %lo(D_80067538)
    /* FC60 8000F060 25CECF68 */  addiu      $t6, $t6, %lo(D_8005CF68)
    /* FC64 8000F064 3C068001 */  lui        $a2, %hi(func_8000F6B0)
    /* FC68 8000F068 240F0008 */  addiu      $t7, $zero, 0x8
    /* FC6C 8000F06C AC800000 */  sw         $zero, 0x0($a0)
    /* FC70 8000F070 AC800008 */  sw         $zero, 0x8($a0)
    /* FC74 8000F074 AFAF0014 */  sw         $t7, 0x14($sp)
    /* FC78 8000F078 24C6F6B0 */  addiu      $a2, $a2, %lo(func_8000F6B0)
    /* FC7C 8000F07C AFAE0010 */  sw         $t6, 0x10($sp)
    /* FC80 8000F080 24050006 */  addiu      $a1, $zero, 0x6
    /* FC84 8000F084 0C006BA4 */  jal        func_8001AE90
    /* FC88 8000F088 8FA70020 */   lw        $a3, 0x20($sp)
    /* FC8C 8000F08C 3C048006 */  lui        $a0, %hi(D_800676E8)
    /* FC90 8000F090 3C188006 */  lui        $t8, %hi(D_80064F70)
    /* FC94 8000F094 248476E8 */  addiu      $a0, $a0, %lo(D_800676E8)
    /* FC98 8000F098 27184F70 */  addiu      $t8, $t8, %lo(D_80064F70)
    /* FC9C 8000F09C 3C068001 */  lui        $a2, %hi(func_8000FE50)
    /* FCA0 8000F0A0 24190004 */  addiu      $t9, $zero, 0x4
    /* FCA4 8000F0A4 AC800000 */  sw         $zero, 0x0($a0)
    /* FCA8 8000F0A8 AC800008 */  sw         $zero, 0x8($a0)
    /* FCAC 8000F0AC AFB90014 */  sw         $t9, 0x14($sp)
    /* FCB0 8000F0B0 24C6FE50 */  addiu      $a2, $a2, %lo(func_8000FE50)
    /* FCB4 8000F0B4 AFB80010 */  sw         $t8, 0x10($sp)
    /* FCB8 8000F0B8 24050003 */  addiu      $a1, $zero, 0x3
    /* FCBC 8000F0BC 0C006BA4 */  jal        func_8001AE90
    /* FCC0 8000F0C0 8FA70020 */   lw        $a3, 0x20($sp)
    /* FCC4 8000F0C4 3C048006 */  lui        $a0, %hi(D_80067898)
    /* FCC8 8000F0C8 3C088006 */  lui        $t0, %hi(D_80066780)
    /* FCCC 8000F0CC 24847898 */  addiu      $a0, $a0, %lo(D_80067898)
    /* FCD0 8000F0D0 25086780 */  addiu      $t0, $t0, %lo(D_80066780)
    /* FCD4 8000F0D4 3C068000 */  lui        $a2, %hi(func_80002EF8)
    /* FCD8 8000F0D8 24090005 */  addiu      $t1, $zero, 0x5
    /* FCDC 8000F0DC AC800000 */  sw         $zero, 0x0($a0)
    /* FCE0 8000F0E0 AC800008 */  sw         $zero, 0x8($a0)
    /* FCE4 8000F0E4 AFA90014 */  sw         $t1, 0x14($sp)
    /* FCE8 8000F0E8 24C62EF8 */  addiu      $a2, $a2, %lo(func_80002EF8)
    /* FCEC 8000F0EC AFA80010 */  sw         $t0, 0x10($sp)
    /* FCF0 8000F0F0 24050007 */  addiu      $a1, $zero, 0x7
    /* FCF4 8000F0F4 0C006BA4 */  jal        func_8001AE90
    /* FCF8 8000F0F8 8FA70020 */   lw        $a3, 0x20($sp)
    /* FCFC 8000F0FC 0C003C86 */  jal        func_8000F218
    /* FD00 8000F100 00000000 */   nop
    /* FD04 8000F104 3C058007 */  lui        $a1, %hi(D_80068060)
    /* FD08 8000F108 3C068007 */  lui        $a2, %hi(D_80068040)
    /* FD0C 8000F10C 24C68040 */  addiu      $a2, $a2, %lo(D_80068040)
    /* FD10 8000F110 24A58060 */  addiu      $a1, $a1, %lo(D_80068060)
    /* FD14 8000F114 24040096 */  addiu      $a0, $zero, 0x96
    /* FD18 8000F118 0C007B90 */  jal        func_8001EE40
    /* FD1C 8000F11C 24070008 */   addiu     $a3, $zero, 0x8
    /* FD20 8000F120 24040009 */  addiu      $a0, $zero, 0x9
    /* FD24 8000F124 0C0011F4 */  jal        func_800047D0
    /* FD28 8000F128 24050005 */   addiu     $a1, $zero, 0x5
    /* FD2C 8000F12C 3C048006 */  lui        $a0, %hi(D_80067538)
    /* FD30 8000F130 0C006BF8 */  jal        func_8001AFE0
    /* FD34 8000F134 24847538 */   addiu     $a0, $a0, %lo(D_80067538)
    /* FD38 8000F138 3C048006 */  lui        $a0, %hi(D_80067898)
    /* FD3C 8000F13C 0C006BF8 */  jal        func_8001AFE0
    /* FD40 8000F140 24847898 */   addiu     $a0, $a0, %lo(D_80067898)
    /* FD44 8000F144 3C048006 */  lui        $a0, %hi(D_800676E8)
    /* FD48 8000F148 0C006BF8 */  jal        func_8001AFE0
    /* FD4C 8000F14C 248476E8 */   addiu     $a0, $a0, %lo(D_800676E8)
    /* FD50 8000F150 00002025 */  or         $a0, $zero, $zero
    /* FD54 8000F154 0C007BF4 */  jal        func_8001EFD0
    /* FD58 8000F158 00002825 */   or        $a1, $zero, $zero
  .L8000F15C:
    /* FD5C 8000F15C 1000FFFF */  b          .L8000F15C
    /* FD60 8000F160 00000000 */   nop
    /* FD64 8000F164 00000000 */  nop
    /* FD68 8000F168 00000000 */  nop
    /* FD6C 8000F16C 00000000 */  nop
    /* FD70 8000F170 00000000 */  nop
    /* FD74 8000F174 00000000 */  nop
    /* FD78 8000F178 00000000 */  nop
    /* FD7C 8000F17C 00000000 */  nop
    /* FD80 8000F180 8FBF001C */  lw         $ra, 0x1C($sp)
    /* FD84 8000F184 27BD0020 */  addiu      $sp, $sp, 0x20
    /* FD88 8000F188 03E00008 */  jr         $ra
    /* FD8C 8000F18C 00000000 */   nop

glabel func_8000F190
    /* FD90 8000F190 00803025 */  or         $a2, $a0, $zero
    /* FD94 8000F194 3C048006 */  lui        $a0, %hi(D_80067A48)
    /* FD98 8000F198 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* FD9C 8000F19C 3C0E8006 */  lui        $t6, %hi(D_80067388)
    /* FDA0 8000F1A0 AFBF001C */  sw         $ra, 0x1C($sp)
    /* FDA4 8000F1A4 24847A48 */  addiu      $a0, $a0, %lo(D_80067A48)
    /* FDA8 8000F1A8 25CE7388 */  addiu      $t6, $t6, %lo(D_80067388)
    /* FDAC 8000F1AC 240F0003 */  addiu      $t7, $zero, 0x3
    /* FDB0 8000F1B0 AC800000 */  sw         $zero, 0x0($a0)
    /* FDB4 8000F1B4 AC800008 */  sw         $zero, 0x8($a0)
    /* FDB8 8000F1B8 AFAF0014 */  sw         $t7, 0x14($sp)
    /* FDBC 8000F1BC AFAE0010 */  sw         $t6, 0x10($sp)
    /* FDC0 8000F1C0 24050008 */  addiu      $a1, $zero, 0x8
    /* FDC4 8000F1C4 0C006BA4 */  jal        func_8001AE90
    /* FDC8 8000F1C8 00003825 */   or        $a3, $zero, $zero
    /* FDCC 8000F1CC 3C048006 */  lui        $a0, %hi(D_80067A48)
    /* FDD0 8000F1D0 0C006BF8 */  jal        func_8001AFE0
    /* FDD4 8000F1D4 24847A48 */   addiu     $a0, $a0, %lo(D_80067A48)
    /* FDD8 8000F1D8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* FDDC 8000F1DC 27BD0020 */  addiu      $sp, $sp, 0x20
    /* FDE0 8000F1E0 03E00008 */  jr         $ra
    /* FDE4 8000F1E4 00000000 */   nop

glabel func_8000F1E8
    /* FDE8 8000F1E8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* FDEC 8000F1EC AFBF0014 */  sw         $ra, 0x14($sp)
    /* FDF0 8000F1F0 3C048006 */  lui        $a0, %hi(D_80067A48)
    /* FDF4 8000F1F4 0C007C2C */  jal        func_8001F0B0
    /* FDF8 8000F1F8 24847A48 */   addiu     $a0, $a0, %lo(D_80067A48)
    /* FDFC 8000F1FC 3C048006 */  lui        $a0, %hi(D_80067A48)
    /* FE00 8000F200 0C007C5C */  jal        func_8001F170
    /* FE04 8000F204 24847A48 */   addiu     $a0, $a0, %lo(D_80067A48)
    /* FE08 8000F208 8FBF0014 */  lw         $ra, 0x14($sp)
    /* FE0C 8000F20C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* FE10 8000F210 03E00008 */  jr         $ra
    /* FE14 8000F214 00000000 */   nop

glabel func_8000F218
    /* FE18 8000F218 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* FE1C 8000F21C AFBF0014 */  sw         $ra, 0x14($sp)
    /* FE20 8000F220 3C048006 */  lui        $a0, %hi(D_80067F58)
    /* FE24 8000F224 3C058007 */  lui        $a1, %hi(D_8006A7E0)
    /* FE28 8000F228 24A5A7E0 */  addiu      $a1, $a1, %lo(D_8006A7E0)
    /* FE2C 8000F22C 24847F58 */  addiu      $a0, $a0, %lo(D_80067F58)
    /* FE30 8000F230 0C006B98 */  jal        func_8001AE60
    /* FE34 8000F234 24060032 */   addiu     $a2, $zero, 0x32
    /* FE38 8000F238 3C048006 */  lui        $a0, %hi(D_80067F70)
    /* FE3C 8000F23C 3C058006 */  lui        $a1, %hi(D_80067FF0)
    /* FE40 8000F240 24A57FF0 */  addiu      $a1, $a1, %lo(D_80067FF0)
    /* FE44 8000F244 24847F70 */  addiu      $a0, $a0, %lo(D_80067F70)
    /* FE48 8000F248 0C006B98 */  jal        func_8001AE60
    /* FE4C 8000F24C 24060010 */   addiu     $a2, $zero, 0x10
    /* FE50 8000F250 3C048006 */  lui        $a0, %hi(D_80067F88)
    /* FE54 8000F254 3C058007 */  lui        $a1, %hi(D_80068030)
    /* FE58 8000F258 24A58030 */  addiu      $a1, $a1, %lo(D_80068030)
    /* FE5C 8000F25C 24847F88 */  addiu      $a0, $a0, %lo(D_80067F88)
    /* FE60 8000F260 0C006B98 */  jal        func_8001AE60
    /* FE64 8000F264 24060001 */   addiu     $a2, $zero, 0x1
    /* FE68 8000F268 3C048006 */  lui        $a0, %hi(D_80067FA0)
    /* FE6C 8000F26C 3C058006 */  lui        $a1, %hi(D_80067FE8)
    /* FE70 8000F270 24A57FE8 */  addiu      $a1, $a1, %lo(D_80067FE8)
    /* FE74 8000F274 24847FA0 */  addiu      $a0, $a0, %lo(D_80067FA0)
    /* FE78 8000F278 0C006B98 */  jal        func_8001AE60
    /* FE7C 8000F27C 24060001 */   addiu     $a2, $zero, 0x1
    /* FE80 8000F280 3C058006 */  lui        $a1, %hi(D_80067FA0)
    /* FE84 8000F284 3C068007 */  lui        $a2, %hi(D_80068038)
    /* FE88 8000F288 8CC68038 */  lw         $a2, %lo(D_80068038)($a2)
    /* FE8C 8000F28C 24A57FA0 */  addiu      $a1, $a1, %lo(D_80067FA0)
    /* FE90 8000F290 0C007324 */  jal        func_8001CC90
    /* FE94 8000F294 24040004 */   addiu     $a0, $zero, 0x4
    /* FE98 8000F298 3C048006 */  lui        $a0, %hi(D_80067FB8)
    /* FE9C 8000F29C 3C058006 */  lui        $a1, %hi(D_80067FEC)
    /* FEA0 8000F2A0 24A57FEC */  addiu      $a1, $a1, %lo(D_80067FEC)
    /* FEA4 8000F2A4 24847FB8 */  addiu      $a0, $a0, %lo(D_80067FB8)
    /* FEA8 8000F2A8 0C006B98 */  jal        func_8001AE60
    /* FEAC 8000F2AC 24060001 */   addiu     $a2, $zero, 0x1
    /* FEB0 8000F2B0 3C048006 */  lui        $a0, %hi(D_80067FB8)
    /* FEB4 8000F2B4 3C058007 */  lui        $a1, %hi(D_80068038)
    /* FEB8 8000F2B8 8CA58038 */  lw         $a1, %lo(D_80068038)($a1)
    /* FEBC 8000F2BC 24847FB8 */  addiu      $a0, $a0, %lo(D_80067FB8)
    /* FEC0 8000F2C0 0C007C9C */  jal        func_8001F270
    /* FEC4 8000F2C4 24060001 */   addiu     $a2, $zero, 0x1
    /* FEC8 8000F2C8 3C048007 */  lui        $a0, %hi(D_8006A8D0)
    /* FECC 8000F2CC 3C058007 */  lui        $a1, %hi(D_8006A8C8)
    /* FED0 8000F2D0 24A5A8C8 */  addiu      $a1, $a1, %lo(D_8006A8C8)
    /* FED4 8000F2D4 2484A8D0 */  addiu      $a0, $a0, %lo(D_8006A8D0)
    /* FED8 8000F2D8 0C006B98 */  jal        func_8001AE60
    /* FEDC 8000F2DC 24060001 */   addiu     $a2, $zero, 0x1
    /* FEE0 8000F2E0 3C048007 */  lui        $a0, %hi(D_8006A8B0)
    /* FEE4 8000F2E4 3C058007 */  lui        $a1, %hi(D_8006A8A8)
    /* FEE8 8000F2E8 24A5A8A8 */  addiu      $a1, $a1, %lo(D_8006A8A8)
    /* FEEC 8000F2EC 2484A8B0 */  addiu      $a0, $a0, %lo(D_8006A8B0)
    /* FEF0 8000F2F0 0C006B98 */  jal        func_8001AE60
    /* FEF4 8000F2F4 24060001 */   addiu     $a2, $zero, 0x1
    /* FEF8 8000F2F8 3C048007 */  lui        $a0, %hi(D_8006A8F0)
    /* FEFC 8000F2FC 3C058007 */  lui        $a1, %hi(D_8006A8E8)
    /* FF00 8000F300 24A5A8E8 */  addiu      $a1, $a1, %lo(D_8006A8E8)
    /* FF04 8000F304 2484A8F0 */  addiu      $a0, $a0, %lo(D_8006A8F0)
    /* FF08 8000F308 0C006B98 */  jal        func_8001AE60
    /* FF0C 8000F30C 24060001 */   addiu     $a2, $zero, 0x1
    /* FF10 8000F310 3C048007 */  lui        $a0, %hi(D_8006A908)
    /* FF14 8000F314 3C058007 */  lui        $a1, %hi(D_8006A920)
    /* FF18 8000F318 24A5A920 */  addiu      $a1, $a1, %lo(D_8006A920)
    /* FF1C 8000F31C 2484A908 */  addiu      $a0, $a0, %lo(D_8006A908)
    /* FF20 8000F320 0C006B98 */  jal        func_8001AE60
    /* FF24 8000F324 24060008 */   addiu     $a2, $zero, 0x8
    /* FF28 8000F328 3C048006 */  lui        $a0, %hi(D_80067FD0)
    /* FF2C 8000F32C 3C058007 */  lui        $a1, %hi(D_80068034)
    /* FF30 8000F330 24A58034 */  addiu      $a1, $a1, %lo(D_80068034)
    /* FF34 8000F334 24847FD0 */  addiu      $a0, $a0, %lo(D_80067FD0)
    /* FF38 8000F338 0C006B98 */  jal        func_8001AE60
    /* FF3C 8000F33C 24060001 */   addiu     $a2, $zero, 0x1
    /* FF40 8000F340 3C048007 */  lui        $a0, %hi(D_80068060)
    /* FF44 8000F344 3C058007 */  lui        $a1, %hi(D_80068040)
    /* FF48 8000F348 24A58040 */  addiu      $a1, $a1, %lo(D_80068040)
    /* FF4C 8000F34C 24848060 */  addiu      $a0, $a0, %lo(D_80068060)
    /* FF50 8000F350 0C006B98 */  jal        func_8001AE60
    /* FF54 8000F354 24060008 */   addiu     $a2, $zero, 0x8
    /* FF58 8000F358 8FBF0014 */  lw         $ra, 0x14($sp)
    /* FF5C 8000F35C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* FF60 8000F360 03E00008 */  jr         $ra
    /* FF64 8000F364 00000000 */   nop

glabel func_8000F368
    /* FF68 8000F368 3C028003 */  lui        $v0, %hi(D_80031B84)
    /* FF6C 8000F36C 8C421B84 */  lw         $v0, %lo(D_80031B84)($v0)
    /* FF70 8000F370 3C0F801D */  lui        $t7, %hi(D_801CE710)
    /* FF74 8000F374 3C048006 */  lui        $a0, %hi(D_8005BB20)
    /* FF78 8000F378 000270C0 */  sll        $t6, $v0, 3
    /* FF7C 8000F37C 01C27021 */  addu       $t6, $t6, $v0
    /* FF80 8000F380 000E7080 */  sll        $t6, $t6, 2
    /* FF84 8000F384 01C27023 */  subu       $t6, $t6, $v0
    /* FF88 8000F388 000E7080 */  sll        $t6, $t6, 2
    /* FF8C 8000F38C 01C27023 */  subu       $t6, $t6, $v0
    /* FF90 8000F390 000E7080 */  sll        $t6, $t6, 2
    /* FF94 8000F394 01C27023 */  subu       $t6, $t6, $v0
    /* FF98 8000F398 000E7200 */  sll        $t6, $t6, 8
    /* FF9C 8000F39C 25EFE710 */  addiu      $t7, $t7, %lo(D_801CE710)
    /* FFA0 8000F3A0 2484BB20 */  addiu      $a0, $a0, %lo(D_8005BB20)
    /* FFA4 8000F3A4 01EEC023 */  subu       $t8, $t7, $t6
    /* FFA8 8000F3A8 AC980000 */  sw         $t8, 0x0($a0)
    /* FFAC 8000F3AC 3C018006 */  lui        $at, %hi(D_8005BB28)
    /* FFB0 8000F3B0 AC38BB28 */  sw         $t8, %lo(D_8005BB28)($at)
    /* FFB4 8000F3B4 3C018006 */  lui        $at, %hi(D_8005BB3C)
    /* FFB8 8000F3B8 27190180 */  addiu      $t9, $t8, 0x180
    /* FFBC 8000F3BC AC39BB3C */  sw         $t9, %lo(D_8005BB3C)($at)
    /* FFC0 8000F3C0 3C018006 */  lui        $at, %hi(D_8005BB40)
    /* FFC4 8000F3C4 27080200 */  addiu      $t0, $t8, 0x200
    /* FFC8 8000F3C8 AC28BB40 */  sw         $t0, %lo(D_8005BB40)($at)
    /* FFCC 8000F3CC 3C018006 */  lui        $at, %hi(D_8005BB2C)
    /* FFD0 8000F3D0 27090280 */  addiu      $t1, $t8, 0x280
    /* FFD4 8000F3D4 AC29BB2C */  sw         $t1, %lo(D_8005BB2C)($at)
    /* FFD8 8000F3D8 3401E380 */  ori        $at, $zero, 0xE380
    /* FFDC 8000F3DC 03015021 */  addu       $t2, $t8, $at
    /* FFE0 8000F3E0 3C018006 */  lui        $at, %hi(D_8005BB30)
    /* FFE4 8000F3E4 AC2ABB30 */  sw         $t2, %lo(D_8005BB30)($at)
    /* FFE8 8000F3E8 3401F500 */  ori        $at, $zero, 0xF500
    /* FFEC 8000F3EC 03015821 */  addu       $t3, $t8, $at
    /* FFF0 8000F3F0 3C018006 */  lui        $at, %hi(D_8005BB34)
    /* FFF4 8000F3F4 AC2BBB34 */  sw         $t3, %lo(D_8005BB34)($at)
    /* FFF8 8000F3F8 3C010001 */  lui        $at, (0x1E280 >> 16)
    /* FFFC 8000F3FC 3421E280 */  ori        $at, $at, (0x1E280 & 0xFFFF)
    /* 10000 8000F400 03016021 */  addu       $t4, $t8, $at
    /* 10004 8000F404 3C068007 */  lui        $a2, %hi(D_80068084)
    /* 10008 8000F408 3C018006 */  lui        $at, %hi(D_8005BB38)
    /* 1000C 8000F40C 24C68084 */  addiu      $a2, $a2, %lo(D_80068084)
    /* 10010 8000F410 AC2CBB38 */  sw         $t4, %lo(D_8005BB38)($at)
    /* 10014 8000F414 8CD80000 */  lw         $t8, 0x0($a2)
    /* 10018 8000F418 3C0F8003 */  lui        $t7, %hi(D_80031B60)
    /* 1001C 8000F41C 3C058006 */  lui        $a1, %hi(D_8005BB24)
    /* 10020 8000F420 25EF1B60 */  addiu      $t7, $t7, %lo(D_80031B60)
    /* 10024 8000F424 00026900 */  sll        $t5, $v0, 4
    /* 10028 8000F428 24A5BB24 */  addiu      $a1, $a1, %lo(D_8005BB24)
    /* 1002C 8000F42C 01AF7021 */  addu       $t6, $t5, $t7
    /* 10030 8000F430 3C078007 */  lui        $a3, %hi(D_80068088)
    /* 10034 8000F434 ACAE0000 */  sw         $t6, 0x0($a1)
    /* 10038 8000F438 0018C840 */  sll        $t9, $t8, 1
    /* 1003C 8000F43C 24E78088 */  addiu      $a3, $a3, %lo(D_80068088)
    /* 10040 8000F440 A5D90000 */  sh         $t9, 0x0($t6)
    /* 10044 8000F444 8CE90000 */  lw         $t1, 0x0($a3)
    /* 10048 8000F448 8CAB0000 */  lw         $t3, 0x0($a1)
    /* 1004C 8000F44C 00095040 */  sll        $t2, $t1, 1
    /* 10050 8000F450 A56A0002 */  sh         $t2, 0x2($t3)
    /* 10054 8000F454 8CCC0000 */  lw         $t4, 0x0($a2)
    /* 10058 8000F458 8CAF0000 */  lw         $t7, 0x0($a1)
    /* 1005C 8000F45C 000C6840 */  sll        $t5, $t4, 1
    /* 10060 8000F460 A5ED0008 */  sh         $t5, 0x8($t7)
    /* 10064 8000F464 8CEE0000 */  lw         $t6, 0x0($a3)
    /* 10068 8000F468 8CB90000 */  lw         $t9, 0x0($a1)
    /* 1006C 8000F46C 000EC040 */  sll        $t8, $t6, 1
    /* 10070 8000F470 03E00008 */  jr         $ra
    /* 10074 8000F474 A738000A */   sh        $t8, 0xA($t9)

glabel func_8000F478
    /* 10078 8000F478 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1007C 8000F47C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 10080 8000F480 0C007CB8 */  jal        func_8001F2E0
    /* 10084 8000F484 AFA40018 */   sw        $a0, 0x18($sp)
    /* 10088 8000F488 3C028006 */  lui        $v0, %hi(D_8005BB20)
    /* 1008C 8000F48C 2442BB20 */  addiu      $v0, $v0, %lo(D_8005BB20)
    /* 10090 8000F490 8C4E0000 */  lw         $t6, 0x0($v0)
    /* 10094 8000F494 8FA50018 */  lw         $a1, 0x18($sp)
    /* 10098 8000F498 3C188006 */  lui        $t8, %hi(D_8005BB2C)
    /* 1009C 8000F49C 25CF0280 */  addiu      $t7, $t6, 0x280
    /* 100A0 8000F4A0 ACAF0040 */  sw         $t7, 0x40($a1)
    /* 100A4 8000F4A4 8C590000 */  lw         $t9, 0x0($v0)
    /* 100A8 8000F4A8 8F18BB2C */  lw         $t8, %lo(D_8005BB2C)($t8)
    /* 100AC 8000F4AC 3C038003 */  lui        $v1, %hi(func_8002DE10)
    /* 100B0 8000F4B0 3C0E8003 */  lui        $t6, %hi(func_8002DEE0)
    /* 100B4 8000F4B4 03194023 */  subu       $t0, $t8, $t9
    /* 100B8 8000F4B8 2509FD80 */  addiu      $t1, $t0, -0x280
    /* 100BC 8000F4BC 000950C3 */  sra        $t2, $t1, 3
    /* 100C0 8000F4C0 2463DE10 */  addiu      $v1, $v1, %lo(func_8002DE10)
    /* 100C4 8000F4C4 25CEDEE0 */  addiu      $t6, $t6, %lo(func_8002DEE0)
    /* 100C8 8000F4C8 3C198004 */  lui        $t9, %hi(D_8003E860)
    /* 100CC 8000F4CC 000A58C0 */  sll        $t3, $t2, 3
    /* 100D0 8000F4D0 240C0001 */  addiu      $t4, $zero, 0x1
    /* 100D4 8000F4D4 240D0006 */  addiu      $t5, $zero, 0x6
    /* 100D8 8000F4D8 01C37823 */  subu       $t7, $t6, $v1
    /* 100DC 8000F4DC 3C188003 */  lui        $t8, %hi(func_8002DEE0)
    /* 100E0 8000F4E0 2739E860 */  addiu      $t9, $t9, %lo(D_8003E860)
    /* 100E4 8000F4E4 24090800 */  addiu      $t1, $zero, 0x800
    /* 100E8 8000F4E8 2718DEE0 */  addiu      $t8, $t8, %lo(func_8002DEE0)
    /* 100EC 8000F4EC 24081000 */  addiu      $t0, $zero, 0x1000
    /* 100F0 8000F4F0 ACAC0010 */  sw         $t4, 0x10($a1)
    /* 100F4 8000F4F4 ACAD0014 */  sw         $t5, 0x14($a1)
    /* 100F8 8000F4F8 ACB90028 */  sw         $t9, 0x28($a1)
    /* 100FC 8000F4FC ACA9002C */  sw         $t1, 0x2C($a1)
    /* 10100 8000F500 8CA90088 */  lw         $t1, 0x88($a1)
    /* 10104 8000F504 3C0A8016 */  lui        $t2, %hi(D_80160300)
    /* 10108 8000F508 3C0C8016 */  lui        $t4, %hi(D_80161700)
    /* 1010C 8000F50C 3C0D8016 */  lui        $t5, %hi(D_80165700)
    /* 10110 8000F510 3C0E8016 */  lui        $t6, %hi(D_80160B00)
    /* 10114 8000F514 3C198007 */  lui        $t9, %hi(D_8006A908)
    /* 10118 8000F518 ACAB0044 */  sw         $t3, 0x44($a1)
    /* 1011C 8000F51C ACAF001C */  sw         $t7, 0x1C($a1)
    /* 10120 8000F520 ACB80020 */  sw         $t8, 0x20($a1)
    /* 10124 8000F524 ACA80024 */  sw         $t0, 0x24($a1)
    /* 10128 8000F528 254A0300 */  addiu      $t2, $t2, %lo(D_80160300)
    /* 1012C 8000F52C 240B0400 */  addiu      $t3, $zero, 0x400
    /* 10130 8000F530 258C1700 */  addiu      $t4, $t4, %lo(D_80161700)
    /* 10134 8000F534 25AD5700 */  addiu      $t5, $t5, %lo(D_80165700)
    /* 10138 8000F538 25CE0B00 */  addiu      $t6, $t6, %lo(D_80160B00)
    /* 1013C 8000F53C 240F0C00 */  addiu      $t7, $zero, 0xC00
    /* 10140 8000F540 24180063 */  addiu      $t8, $zero, 0x63
    /* 10144 8000F544 2739A908 */  addiu      $t9, $t9, %lo(D_8006A908)
    /* 10148 8000F548 3C048007 */  lui        $a0, %hi(D_800680A0)
    /* 1014C 8000F54C 24A80068 */  addiu      $t0, $a1, 0x68
    /* 10150 8000F550 248480A0 */  addiu      $a0, $a0, %lo(D_800680A0)
    /* 10154 8000F554 ACA30018 */  sw         $v1, 0x18($a1)
    /* 10158 8000F558 ACAA0030 */  sw         $t2, 0x30($a1)
    /* 1015C 8000F55C ACAB0034 */  sw         $t3, 0x34($a1)
    /* 10160 8000F560 ACAC0038 */  sw         $t4, 0x38($a1)
    /* 10164 8000F564 ACAD003C */  sw         $t5, 0x3C($a1)
    /* 10168 8000F568 ACAE0048 */  sw         $t6, 0x48($a1)
    /* 1016C 8000F56C ACAF004C */  sw         $t7, 0x4C($a1)
    /* 10170 8000F570 ACA00000 */  sw         $zero, 0x0($a1)
    /* 10174 8000F574 ACB80008 */  sw         $t8, 0x8($a1)
    /* 10178 8000F578 ACB90050 */  sw         $t9, 0x50($a1)
    /* 1017C 8000F57C ACA80054 */  sw         $t0, 0x54($a1)
    /* 10180 8000F580 0C006E18 */  jal        func_8001B860
    /* 10184 8000F584 ACA9000C */   sw        $t1, 0xC($a1)
    /* 10188 8000F588 8FA50018 */  lw         $a1, 0x18($sp)
    /* 1018C 8000F58C 00402025 */  or         $a0, $v0, $zero
    /* 10190 8000F590 0C0070F4 */  jal        func_8001C3D0
    /* 10194 8000F594 24060001 */   addiu     $a2, $zero, 0x1
    /* 10198 8000F598 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1019C 8000F59C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 101A0 8000F5A0 03E00008 */  jr         $ra
    /* 101A4 8000F5A4 00000000 */   nop

glabel func_8000F5A8
    /* 101A8 8000F5A8 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 101AC 8000F5AC AFBF0024 */  sw         $ra, 0x24($sp)
    /* 101B0 8000F5B0 AFA40040 */  sw         $a0, 0x40($sp)
    /* 101B4 8000F5B4 AFA50044 */  sw         $a1, 0x44($sp)
    /* 101B8 8000F5B8 0C007CB8 */  jal        func_8001F2E0
    /* 101BC 8000F5BC AFA60048 */   sw        $a2, 0x48($sp)
    /* 101C0 8000F5C0 8FAE0044 */  lw         $t6, 0x44($sp)
    /* 101C4 8000F5C4 8FAF0048 */  lw         $t7, 0x48($sp)
    /* 101C8 8000F5C8 3C188006 */  lui        $t8, %hi(D_80067FD0)
    /* 101CC 8000F5CC 27187FD0 */  addiu      $t8, $t8, %lo(D_80067FD0)
    /* 101D0 8000F5D0 AFB80018 */  sw         $t8, 0x18($sp)
    /* 101D4 8000F5D4 27A40028 */  addiu      $a0, $sp, 0x28
    /* 101D8 8000F5D8 00002825 */  or         $a1, $zero, $zero
    /* 101DC 8000F5DC 00003025 */  or         $a2, $zero, $zero
    /* 101E0 8000F5E0 8FA70040 */  lw         $a3, 0x40($sp)
    /* 101E4 8000F5E4 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 101E8 8000F5E8 0C007148 */  jal        func_8001C520
    /* 101EC 8000F5EC AFAF0014 */   sw        $t7, 0x14($sp)
    /* 101F0 8000F5F0 3C048006 */  lui        $a0, %hi(D_80067FD0)
    /* 101F4 8000F5F4 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 101F8 8000F5F8 24A58038 */  addiu      $a1, $a1, %lo(D_80068038)
    /* 101FC 8000F5FC 24847FD0 */  addiu      $a0, $a0, %lo(D_80067FD0)
    /* 10200 8000F600 0C006E9C */  jal        func_8001BA70
    /* 10204 8000F604 24060001 */   addiu     $a2, $zero, 0x1
    /* 10208 8000F608 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 1020C 8000F60C 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 10210 8000F610 03E00008 */  jr         $ra
    /* 10214 8000F614 00000000 */   nop

glabel func_8000F618
    /* 10218 8000F618 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 1021C 8000F61C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 10220 8000F620 0C002858 */  jal        func_8000A160
    /* 10224 8000F624 00000000 */   nop
    /* 10228 8000F628 0C007CC4 */  jal        func_8001F310
    /* 1022C 8000F62C 24040002 */   addiu     $a0, $zero, 0x2
    /* 10230 8000F630 0C007CC4 */  jal        func_8001F310
    /* 10234 8000F634 24040040 */   addiu     $a0, $zero, 0x40
    /* 10238 8000F638 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 1023C 8000F63C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 10240 8000F640 03E00008 */  jr         $ra
    /* 10244 8000F644 00000000 */   nop

glabel func_8000F648
    /* 10248 8000F648 44842000 */  mtc1       $a0, $ft0
    /* 1024C 8000F64C 3C018007 */  lui        $at, %hi(D_80068084)
    /* 10250 8000F650 AC248084 */  sw         $a0, %lo(D_80068084)($at)
    /* 10254 8000F654 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 10258 8000F658 3C0143A0 */  lui        $at, (0x43A00000 >> 16)
    /* 1025C 8000F65C 44814000 */  mtc1       $at, $ft2
    /* 10260 8000F660 3C018007 */  lui        $at, %hi(D_8006808C)
    /* 10264 8000F664 240E0002 */  addiu      $t6, $zero, 0x2
    /* 10268 8000F668 46083283 */  div.s      $ft3, $ft1, $ft2
    /* 1026C 8000F66C E42A808C */  swc1       $ft3, %lo(D_8006808C)($at)
    /* 10270 8000F670 3C018007 */  lui        $at, %hi(D_8006809C)
    /* 10274 8000F674 03E00008 */  jr         $ra
    /* 10278 8000F678 AC2E809C */   sw        $t6, %lo(D_8006809C)($at)

glabel func_8000F67C
    /* 1027C 8000F67C 44842000 */  mtc1       $a0, $ft0
    /* 10280 8000F680 3C018007 */  lui        $at, %hi(D_80068088)
    /* 10284 8000F684 AC248088 */  sw         $a0, %lo(D_80068088)($at)
    /* 10288 8000F688 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 1028C 8000F68C 3C014370 */  lui        $at, (0x43700000 >> 16)
    /* 10290 8000F690 44814000 */  mtc1       $at, $ft2
    /* 10294 8000F694 3C018007 */  lui        $at, %hi(D_80068090)
    /* 10298 8000F698 240E0002 */  addiu      $t6, $zero, 0x2
    /* 1029C 8000F69C 46083283 */  div.s      $ft3, $ft1, $ft2
    /* 102A0 8000F6A0 E42A8090 */  swc1       $ft3, %lo(D_80068090)($at)
    /* 102A4 8000F6A4 3C018007 */  lui        $at, %hi(D_8006809C)
    /* 102A8 8000F6A8 03E00008 */  jr         $ra
    /* 102AC 8000F6AC AC2E809C */   sw        $t6, %lo(D_8006809C)($at)

glabel func_8000F6B0
    /* 102B0 8000F6B0 27BDFF60 */  addiu      $sp, $sp, -0xA0
    /* 102B4 8000F6B4 3C028000 */  lui        $v0, %hi(D_80000300)
    /* 102B8 8000F6B8 8C420300 */  lw         $v0, %lo(D_80000300)($v0)
    /* 102BC 8000F6BC AFB50034 */  sw         $s5, 0x34($sp)
    /* 102C0 8000F6C0 AFB40030 */  sw         $s4, 0x30($sp)
    /* 102C4 8000F6C4 AFB00020 */  sw         $s0, 0x20($sp)
    /* 102C8 8000F6C8 AFBF0044 */  sw         $ra, 0x44($sp)
    /* 102CC 8000F6CC AFBE0040 */  sw         $fp, 0x40($sp)
    /* 102D0 8000F6D0 AFB7003C */  sw         $s7, 0x3C($sp)
    /* 102D4 8000F6D4 AFB60038 */  sw         $s6, 0x38($sp)
    /* 102D8 8000F6D8 AFB3002C */  sw         $s3, 0x2C($sp)
    /* 102DC 8000F6DC AFB20028 */  sw         $s2, 0x28($sp)
    /* 102E0 8000F6E0 AFB10024 */  sw         $s1, 0x24($sp)
    /* 102E4 8000F6E4 AFA400A0 */  sw         $a0, 0xA0($sp)
    /* 102E8 8000F6E8 AFA0007C */  sw         $zero, 0x7C($sp)
    /* 102EC 8000F6EC 0000A025 */  or         $s4, $zero, $zero
    /* 102F0 8000F6F0 00008025 */  or         $s0, $zero, $zero
    /* 102F4 8000F6F4 1440000D */  bnez       $v0, .L8000F72C
    /* 102F8 8000F6F8 0000A825 */   or        $s5, $zero, $zero
    /* 102FC 8000F6FC 3C118007 */  lui        $s1, %hi(D_800680A0)
    /* 10300 8000F700 263180A0 */  addiu      $s1, $s1, %lo(D_800680A0)
    /* 10304 8000F704 3C058007 */  lui        $a1, %hi(D_8006A330)
    /* 10308 8000F708 240E0001 */  addiu      $t6, $zero, 0x1
    /* 1030C 8000F70C AFAE0010 */  sw         $t6, 0x10($sp)
    /* 10310 8000F710 24A5A330 */  addiu      $a1, $a1, %lo(D_8006A330)
    /* 10314 8000F714 02202025 */  or         $a0, $s1, $zero
    /* 10318 8000F718 2406000C */  addiu      $a2, $zero, 0xC
    /* 1031C 8000F71C 0C006E50 */  jal        func_8001B940
    /* 10320 8000F720 24070010 */   addiu     $a3, $zero, 0x10
    /* 10324 8000F724 10000019 */  b          .L8000F78C
    /* 10328 8000F728 00000000 */   nop
  .L8000F72C:
    /* 1032C 8000F72C 24010002 */  addiu      $at, $zero, 0x2
    /* 10330 8000F730 1441000D */  bne        $v0, $at, .L8000F768
    /* 10334 8000F734 3C118007 */   lui       $s1, %hi(D_800680A0)
    /* 10338 8000F738 3C118007 */  lui        $s1, %hi(D_800680A0)
    /* 1033C 8000F73C 263180A0 */  addiu      $s1, $s1, %lo(D_800680A0)
    /* 10340 8000F740 3C058007 */  lui        $a1, %hi(D_8006A330)
    /* 10344 8000F744 240F0001 */  addiu      $t7, $zero, 0x1
    /* 10348 8000F748 AFAF0010 */  sw         $t7, 0x10($sp)
    /* 1034C 8000F74C 24A5A330 */  addiu      $a1, $a1, %lo(D_8006A330)
    /* 10350 8000F750 02202025 */  or         $a0, $s1, $zero
    /* 10354 8000F754 2406000C */  addiu      $a2, $zero, 0xC
    /* 10358 8000F758 0C006E50 */  jal        func_8001B940
    /* 1035C 8000F75C 2407001E */   addiu     $a3, $zero, 0x1E
    /* 10360 8000F760 1000000A */  b          .L8000F78C
    /* 10364 8000F764 00000000 */   nop
  .L8000F768:
    /* 10368 8000F768 263180A0 */  addiu      $s1, $s1, %lo(D_800680A0)
    /* 1036C 8000F76C 3C058007 */  lui        $a1, %hi(D_8006A330)
    /* 10370 8000F770 24180001 */  addiu      $t8, $zero, 0x1
    /* 10374 8000F774 AFB80010 */  sw         $t8, 0x10($sp)
    /* 10378 8000F778 24A5A330 */  addiu      $a1, $a1, %lo(D_8006A330)
    /* 1037C 8000F77C 02202025 */  or         $a0, $s1, $zero
    /* 10380 8000F780 2406000C */  addiu      $a2, $zero, 0xC
    /* 10384 8000F784 0C006E50 */  jal        func_8001B940
    /* 10388 8000F788 24070002 */   addiu     $a3, $zero, 0x2
  .L8000F78C:
    /* 1038C 8000F78C 3C098007 */  lui        $t1, %hi(D_8006A940)
    /* 10390 8000F790 2529A940 */  addiu      $t1, $t1, %lo(D_8006A940)
    /* 10394 8000F794 3C038026 */  lui        $v1, %hi(D_80267080)
    /* 10398 8000F798 3C078029 */  lui        $a3, %hi(D_8028C880)
    /* 1039C 8000F79C 3C088006 */  lui        $t0, %hi(D_8005BB48)
    /* 103A0 8000F7A0 2508BB48 */  addiu      $t0, $t0, %lo(D_8005BB48)
    /* 103A4 8000F7A4 24E7C880 */  addiu      $a3, $a3, %lo(D_8028C880)
    /* 103A8 8000F7A8 24637080 */  addiu      $v1, $v1, %lo(D_80267080)
    /* 103AC 8000F7AC 24020002 */  addiu      $v0, $zero, 0x2
    /* 103B0 8000F7B0 A5220068 */  sh         $v0, 0x68($t1)
    /* 103B4 8000F7B4 A52200F8 */  sh         $v0, 0xF8($t1)
    /* 103B8 8000F7B8 AD230088 */  sw         $v1, 0x88($t1)
    /* 103BC 8000F7BC AD270118 */  sw         $a3, 0x118($t1)
    /* 103C0 8000F7C0 AD030000 */  sw         $v1, 0x0($t0)
    /* 103C4 8000F7C4 AD070004 */  sw         $a3, 0x4($t0)
    /* 103C8 8000F7C8 3C018003 */  lui        $at, %hi(D_80031B84)
    /* 103CC 8000F7CC 3C068007 */  lui        $a2, %hi(D_8006A908)
    /* 103D0 8000F7D0 AC201B84 */  sw         $zero, %lo(D_80031B84)($at)
    /* 103D4 8000F7D4 24C6A908 */  addiu      $a2, $a2, %lo(D_8006A908)
    /* 103D8 8000F7D8 02202025 */  or         $a0, $s1, $zero
    /* 103DC 8000F7DC 0C006E3C */  jal        func_8001B8F0
    /* 103E0 8000F7E0 27A50080 */   addiu     $a1, $sp, 0x80
    /* 103E4 8000F7E4 0C004A9D */  jal        func_80012A74
    /* 103E8 8000F7E8 00000000 */   nop
    /* 103EC 8000F7EC 3C048007 */  lui        $a0, %hi(D_8006A8D0)
    /* 103F0 8000F7F0 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 103F4 8000F7F4 8CA58038 */  lw         $a1, %lo(D_80068038)($a1)
    /* 103F8 8000F7F8 2484A8D0 */  addiu      $a0, $a0, %lo(D_8006A8D0)
    /* 103FC 8000F7FC 0C0070F4 */  jal        func_8001C3D0
    /* 10400 8000F800 24060001 */   addiu     $a2, $zero, 0x1
    /* 10404 8000F804 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 10408 8000F808 44810000 */  mtc1       $at, $fv0
    /* 1040C 8000F80C 3C018007 */  lui        $at, %hi(D_8006832C)
    /* 10410 8000F810 240A0000 */  addiu      $t2, $zero, 0x0
    /* 10414 8000F814 240B0CEC */  addiu      $t3, $zero, 0xCEC
    /* 10418 8000F818 AC2B832C */  sw         $t3, %lo(D_8006832C)($at)
    /* 1041C 8000F81C AC2A8328 */  sw         $t2, %lo(D_80068328)($at)
    /* 10420 8000F820 3C018006 */  lui        $at, %hi(D_8005BB54)
    /* 10424 8000F824 240C0000 */  addiu      $t4, $zero, 0x0
    /* 10428 8000F828 240D0CEC */  addiu      $t5, $zero, 0xCEC
    /* 1042C 8000F82C AC2DBB54 */  sw         $t5, %lo(D_8005BB54)($at)
    /* 10430 8000F830 AC2CBB50 */  sw         $t4, %lo(D_8005BB50)($at)
    /* 10434 8000F834 3C018006 */  lui        $at, %hi(D_8005BF5C)
    /* 10438 8000F838 240E0000 */  addiu      $t6, $zero, 0x0
    /* 1043C 8000F83C 240F0CEC */  addiu      $t7, $zero, 0xCEC
    /* 10440 8000F840 AC2FBF5C */  sw         $t7, %lo(D_8005BF5C)($at)
    /* 10444 8000F844 AC2EBF58 */  sw         $t6, %lo(D_8005BF58)($at)
    /* 10448 8000F848 3C018006 */  lui        $at, %hi(D_8005C764)
    /* 1044C 8000F84C 24180000 */  addiu      $t8, $zero, 0x0
    /* 10450 8000F850 24190CEC */  addiu      $t9, $zero, 0xCEC
    /* 10454 8000F854 AC39C764 */  sw         $t9, %lo(D_8005C764)($at)
    /* 10458 8000F858 AC38C760 */  sw         $t8, %lo(D_8005C760)($at)
    /* 1045C 8000F85C 3C018006 */  lui        $at, %hi(D_8005CF68)
    /* 10460 8000F860 AC2ACF68 */  sw         $t2, %lo(D_8005CF68)($at)
    /* 10464 8000F864 AC2BCF6C */  sw         $t3, %lo(D_8005CF6C)($at)
    /* 10468 8000F868 3C018006 */  lui        $at, %hi(D_80064F70)
    /* 1046C 8000F86C AC2C4F70 */  sw         $t4, %lo(D_80064F70)($at)
    /* 10470 8000F870 AC2D4F74 */  sw         $t5, %lo(D_80064F74)($at)
    /* 10474 8000F874 3C018006 */  lui        $at, %hi(D_80065F78)
    /* 10478 8000F878 AC2E5F78 */  sw         $t6, %lo(D_80065F78)($at)
    /* 1047C 8000F87C AC2F5F7C */  sw         $t7, %lo(D_80065F7C)($at)
    /* 10480 8000F880 3C018006 */  lui        $at, %hi(D_80066780)
    /* 10484 8000F884 AC386780 */  sw         $t8, %lo(D_80066780)($at)
    /* 10488 8000F888 AC396784 */  sw         $t9, %lo(D_80066784)($at)
    /* 1048C 8000F88C 3C118007 */  lui        $s1, %hi(D_8006809C)
    /* 10490 8000F890 3C138007 */  lui        $s3, %hi(D_8006807C)
    /* 10494 8000F894 3C168007 */  lui        $s6, %hi(D_80068080)
    /* 10498 8000F898 26D68080 */  addiu      $s6, $s6, %lo(D_80068080)
    /* 1049C 8000F89C 2673807C */  addiu      $s3, $s3, %lo(D_8006807C)
    /* 104A0 8000F8A0 2631809C */  addiu      $s1, $s1, %lo(D_8006809C)
    /* 104A4 8000F8A4 AEC00000 */  sw         $zero, 0x0($s6)
    /* 104A8 8000F8A8 AE600000 */  sw         $zero, 0x0($s3)
    /* 104AC 8000F8AC AE200000 */  sw         $zero, 0x0($s1)
    /* 104B0 8000F8B0 3C018007 */  lui        $at, %hi(D_80068094)
    /* 104B4 8000F8B4 E4208094 */  swc1       $fv0, %lo(D_80068094)($at)
    /* 104B8 8000F8B8 3C018007 */  lui        $at, %hi(D_80068098)
    /* 104BC 8000F8BC 24040140 */  addiu      $a0, $zero, 0x140
    /* 104C0 8000F8C0 0C003D92 */  jal        func_8000F648
    /* 104C4 8000F8C4 E4208098 */   swc1      $fv0, %lo(D_80068098)($at)
    /* 104C8 8000F8C8 0C003D9F */  jal        func_8000F67C
    /* 104CC 8000F8CC 240400F0 */   addiu     $a0, $zero, 0xF0
    /* 104D0 8000F8D0 240A0400 */  addiu      $t2, $zero, 0x400
    /* 104D4 8000F8D4 3C018003 */  lui        $at, %hi(D_80035B5C)
    /* 104D8 8000F8D8 AC2A5B5C */  sw         $t2, %lo(D_80035B5C)($at)
    /* 104DC 8000F8DC 0C007D34 */  jal        func_8001F4D0
    /* 104E0 8000F8E0 24040001 */   addiu     $a0, $zero, 0x1
    /* 104E4 8000F8E4 241E0004 */  addiu      $fp, $zero, 0x4
    /* 104E8 8000F8E8 AEDE0000 */  sw         $fp, 0x0($s6)
    /* 104EC 8000F8EC 24170001 */  addiu      $s7, $zero, 0x1
    /* 104F0 8000F8F0 8FB20068 */  lw         $s2, 0x68($sp)
  .L8000F8F4:
    /* 104F4 8000F8F4 3C0C8007 */  lui        $t4, %hi(D_80068328)
    /* 104F8 8000F8F8 8D8C8328 */  lw         $t4, %lo(D_80068328)($t4)
    /* 104FC 8000F8FC 3C0D8007 */  lui        $t5, %hi(D_8006832C)
    /* 10500 8000F900 8DAD832C */  lw         $t5, %lo(D_8006832C)($t5)
    /* 10504 8000F904 15800002 */  bnez       $t4, .L8000F910
    /* 10508 8000F908 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 1050C 8000F90C 11A10003 */  beq        $t5, $at, .L8000F91C
  .L8000F910:
    /* 10510 8000F910 3C048003 */   lui       $a0, %hi(D_80037660)
    /* 10514 8000F914 0C00731B */  jal        func_8001CC6C
    /* 10518 8000F918 24847660 */   addiu     $a0, $a0, %lo(D_80037660)
  .L8000F91C:
    /* 1051C 8000F91C 3C0E8006 */  lui        $t6, %hi(D_8005BB50)
    /* 10520 8000F920 8DCEBB50 */  lw         $t6, %lo(D_8005BB50)($t6)
    /* 10524 8000F924 3C0F8006 */  lui        $t7, %hi(D_8005BB54)
    /* 10528 8000F928 8DEFBB54 */  lw         $t7, %lo(D_8005BB54)($t7)
    /* 1052C 8000F92C 15C00002 */  bnez       $t6, .L8000F938
    /* 10530 8000F930 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 10534 8000F934 11E10003 */  beq        $t7, $at, .L8000F944
  .L8000F938:
    /* 10538 8000F938 3C048003 */   lui       $a0, %hi(D_8003767C)
    /* 1053C 8000F93C 0C00731B */  jal        func_8001CC6C
    /* 10540 8000F940 2484767C */   addiu     $a0, $a0, %lo(D_8003767C)
  .L8000F944:
    /* 10544 8000F944 3C188006 */  lui        $t8, %hi(D_8005BF58)
    /* 10548 8000F948 8F18BF58 */  lw         $t8, %lo(D_8005BF58)($t8)
    /* 1054C 8000F94C 3C198006 */  lui        $t9, %hi(D_8005BF5C)
    /* 10550 8000F950 8F39BF5C */  lw         $t9, %lo(D_8005BF5C)($t9)
    /* 10554 8000F954 17000002 */  bnez       $t8, .L8000F960
    /* 10558 8000F958 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 1055C 8000F95C 13210003 */  beq        $t9, $at, .L8000F96C
  .L8000F960:
    /* 10560 8000F960 3C048003 */   lui       $a0, %hi(D_80037694)
    /* 10564 8000F964 0C00731B */  jal        func_8001CC6C
    /* 10568 8000F968 24847694 */   addiu     $a0, $a0, %lo(D_80037694)
  .L8000F96C:
    /* 1056C 8000F96C 3C0A8006 */  lui        $t2, %hi(D_8005C760)
    /* 10570 8000F970 8D4AC760 */  lw         $t2, %lo(D_8005C760)($t2)
    /* 10574 8000F974 3C0B8006 */  lui        $t3, %hi(D_8005C764)
    /* 10578 8000F978 8D6BC764 */  lw         $t3, %lo(D_8005C764)($t3)
    /* 1057C 8000F97C 15400002 */  bnez       $t2, .L8000F988
    /* 10580 8000F980 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 10584 8000F984 11610003 */  beq        $t3, $at, .L8000F994
  .L8000F988:
    /* 10588 8000F988 3C048003 */   lui       $a0, %hi(D_800376AC)
    /* 1058C 8000F98C 0C00731B */  jal        func_8001CC6C
    /* 10590 8000F990 248476AC */   addiu     $a0, $a0, %lo(D_800376AC)
  .L8000F994:
    /* 10594 8000F994 3C0C8006 */  lui        $t4, %hi(D_8005CF68)
    /* 10598 8000F998 8D8CCF68 */  lw         $t4, %lo(D_8005CF68)($t4)
    /* 1059C 8000F99C 3C0D8006 */  lui        $t5, %hi(D_8005CF6C)
    /* 105A0 8000F9A0 8DADCF6C */  lw         $t5, %lo(D_8005CF6C)($t5)
    /* 105A4 8000F9A4 15800002 */  bnez       $t4, .L8000F9B0
    /* 105A8 8000F9A8 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 105AC 8000F9AC 11A10003 */  beq        $t5, $at, .L8000F9BC
  .L8000F9B0:
    /* 105B0 8000F9B0 3C048003 */   lui       $a0, %hi(D_800376C0)
    /* 105B4 8000F9B4 0C00731B */  jal        func_8001CC6C
    /* 105B8 8000F9B8 248476C0 */   addiu     $a0, $a0, %lo(D_800376C0)
  .L8000F9BC:
    /* 105BC 8000F9BC 3C0E8006 */  lui        $t6, %hi(D_80064F70)
    /* 105C0 8000F9C0 8DCE4F70 */  lw         $t6, %lo(D_80064F70)($t6)
    /* 105C4 8000F9C4 3C0F8006 */  lui        $t7, %hi(D_80064F74)
    /* 105C8 8000F9C8 8DEF4F74 */  lw         $t7, %lo(D_80064F74)($t7)
    /* 105CC 8000F9CC 15C00002 */  bnez       $t6, .L8000F9D8
    /* 105D0 8000F9D0 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 105D4 8000F9D4 11E10003 */  beq        $t7, $at, .L8000F9E4
  .L8000F9D8:
    /* 105D8 8000F9D8 3C048003 */   lui       $a0, %hi(D_800376D8)
    /* 105DC 8000F9DC 0C00731B */  jal        func_8001CC6C
    /* 105E0 8000F9E0 248476D8 */   addiu     $a0, $a0, %lo(D_800376D8)
  .L8000F9E4:
    /* 105E4 8000F9E4 3C188006 */  lui        $t8, %hi(D_80065F78)
    /* 105E8 8000F9E8 8F185F78 */  lw         $t8, %lo(D_80065F78)($t8)
    /* 105EC 8000F9EC 3C198006 */  lui        $t9, %hi(D_80065F7C)
    /* 105F0 8000F9F0 8F395F7C */  lw         $t9, %lo(D_80065F7C)($t9)
    /* 105F4 8000F9F4 17000002 */  bnez       $t8, .L8000FA00
    /* 105F8 8000F9F8 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 105FC 8000F9FC 13210003 */  beq        $t9, $at, .L8000FA0C
  .L8000FA00:
    /* 10600 8000FA00 3C048003 */   lui       $a0, %hi(D_800376F0)
    /* 10604 8000FA04 0C00731B */  jal        func_8001CC6C
    /* 10608 8000FA08 248476F0 */   addiu     $a0, $a0, %lo(D_800376F0)
  .L8000FA0C:
    /* 1060C 8000FA0C 3C0A8006 */  lui        $t2, %hi(D_80066780)
    /* 10610 8000FA10 8D4A6780 */  lw         $t2, %lo(D_80066780)($t2)
    /* 10614 8000FA14 3C0B8006 */  lui        $t3, %hi(D_80066784)
    /* 10618 8000FA18 8D6B6784 */  lw         $t3, %lo(D_80066784)($t3)
    /* 1061C 8000FA1C 15400002 */  bnez       $t2, .L8000FA28
    /* 10620 8000FA20 24010CEC */   addiu     $at, $zero, 0xCEC
    /* 10624 8000FA24 11610003 */  beq        $t3, $at, .L8000FA34
  .L8000FA28:
    /* 10628 8000FA28 3C048003 */   lui       $a0, %hi(D_8003770C)
    /* 1062C 8000FA2C 0C00731B */  jal        func_8001CC6C
    /* 10630 8000FA30 2484770C */   addiu     $a0, $a0, %lo(D_8003770C)
  .L8000FA34:
    /* 10634 8000FA34 3C048007 */  lui        $a0, %hi(D_8006A908)
    /* 10638 8000FA38 2484A908 */  addiu      $a0, $a0, %lo(D_8006A908)
    /* 1063C 8000FA3C 27A50070 */  addiu      $a1, $sp, 0x70
    /* 10640 8000FA40 0C006E9C */  jal        func_8001BA70
    /* 10644 8000FA44 02E03025 */   or        $a2, $s7, $zero
    /* 10648 8000FA48 8FAC0070 */  lw         $t4, 0x70($sp)
    /* 1064C 8000FA4C 3C028003 */  lui        $v0, %hi(D_800313D4)
    /* 10650 8000FA50 244213D4 */  addiu      $v0, $v0, %lo(D_800313D4)
    /* 10654 8000FA54 85830000 */  lh         $v1, 0x0($t4)
    /* 10658 8000FA58 24010002 */  addiu      $at, $zero, 0x2
    /* 1065C 8000FA5C 50770008 */  beql       $v1, $s7, .L8000FA80
    /* 10660 8000FA60 8C4D0000 */   lw        $t5, 0x0($v0)
    /* 10664 8000FA64 106100A7 */  beq        $v1, $at, .L8000FD04
    /* 10668 8000FA68 00000000 */   nop
    /* 1066C 8000FA6C 107E00C1 */  beq        $v1, $fp, .L8000FD74
    /* 10670 8000FA70 00000000 */   nop
    /* 10674 8000FA74 1000FF9F */  b          .L8000F8F4
    /* 10678 8000FA78 00000000 */   nop
    /* 1067C 8000FA7C 8C4D0000 */  lw         $t5, 0x0($v0)
  .L8000FA80:
    /* 10680 8000FA80 26B50001 */  addiu      $s5, $s5, 0x1
    /* 10684 8000FA84 00157C00 */  sll        $t7, $s5, 16
    /* 10688 8000FA88 2A010002 */  slti       $at, $s0, 0x2
    /* 1068C 8000FA8C 25AE0001 */  addiu      $t6, $t5, 0x1
    /* 10690 8000FA90 AC4E0000 */  sw         $t6, 0x0($v0)
    /* 10694 8000FA94 14200002 */  bnez       $at, .L8000FAA0
    /* 10698 8000FA98 000FAC03 */   sra       $s5, $t7, 16
    /* 1069C 8000FA9C 26520001 */  addiu      $s2, $s2, 0x1
  .L8000FAA0:
    /* 106A0 8000FAA0 2A41000B */  slti       $at, $s2, 0xB
    /* 106A4 8000FAA4 14200004 */  bnez       $at, .L8000FAB8
    /* 106A8 8000FAA8 3C048003 */   lui       $a0, %hi(D_80037728)
    /* 106AC 8000FAAC 24847728 */  addiu      $a0, $a0, %lo(D_80037728)
    /* 106B0 8000FAB0 0C00731B */  jal        func_8001CC6C
    /* 106B4 8000FAB4 00009025 */   or        $s2, $zero, $zero
  .L8000FAB8:
    /* 106B8 8000FAB8 0C004E06 */  jal        func_80013818
    /* 106BC 8000FABC 00000000 */   nop
    /* 106C0 8000FAC0 0C00130D */  jal        func_80004C34
    /* 106C4 8000FAC4 00000000 */   nop
    /* 106C8 8000FAC8 3C028005 */  lui        $v0, %hi(D_80052ACA)
    /* 106CC 8000FACC 90422ACA */  lbu        $v0, %lo(D_80052ACA)($v0)
    /* 106D0 8000FAD0 24010002 */  addiu      $at, $zero, 0x2
    /* 106D4 8000FAD4 3C0B8005 */  lui        $t3, %hi(D_80052ACC)
    /* 106D8 8000FAD8 10400007 */  beqz       $v0, .L8000FAF8
    /* 106DC 8000FADC 00000000 */   nop
    /* 106E0 8000FAE0 10410005 */  beq        $v0, $at, .L8000FAF8
    /* 106E4 8000FAE4 24010005 */   addiu     $at, $zero, 0x5
    /* 106E8 8000FAE8 10410003 */  beq        $v0, $at, .L8000FAF8
    /* 106EC 8000FAEC 00000000 */   nop
    /* 106F0 8000FAF0 17C2000A */  bne        $fp, $v0, .L8000FB1C
    /* 106F4 8000FAF4 00171C00 */   sll       $v1, $s7, 16
  .L8000FAF8:
    /* 106F8 8000FAF8 3C028005 */  lui        $v0, %hi(D_80052ADC)
    /* 106FC 8000FAFC 8C422ADC */  lw         $v0, %lo(D_80052ADC)($v0)
    /* 10700 8000FB00 24010006 */  addiu      $at, $zero, 0x6
    /* 10704 8000FB04 14410003 */  bne        $v0, $at, .L8000FB14
    /* 10708 8000FB08 00000000 */   nop
    /* 1070C 8000FB0C 10000007 */  b          .L8000FB2C
    /* 10710 8000FB10 24030002 */   addiu     $v1, $zero, 0x2
  .L8000FB14:
    /* 10714 8000FB14 10000005 */  b          .L8000FB2C
    /* 10718 8000FB18 24030003 */   addiu     $v1, $zero, 0x3
  .L8000FB1C:
    /* 1071C 8000FB1C 0003CC03 */  sra        $t9, $v1, 16
    /* 10720 8000FB20 3C028005 */  lui        $v0, %hi(D_80052ADC)
    /* 10724 8000FB24 8C422ADC */  lw         $v0, %lo(D_80052ADC)($v0)
    /* 10728 8000FB28 03201825 */  or         $v1, $t9, $zero
  .L8000FB2C:
    /* 1072C 8000FB2C 10400009 */  beqz       $v0, .L8000FB54
    /* 10730 8000FB30 2401000E */   addiu     $at, $zero, 0xE
    /* 10734 8000FB34 10410007 */  beq        $v0, $at, .L8000FB54
    /* 10738 8000FB38 24010007 */   addiu     $at, $zero, 0x7
    /* 1073C 8000FB3C 50410006 */  beql       $v0, $at, .L8000FB58
    /* 10740 8000FB40 00171C00 */   sll       $v1, $s7, 16
    /* 10744 8000FB44 13C20003 */  beq        $fp, $v0, .L8000FB54
    /* 10748 8000FB48 24010010 */   addiu     $at, $zero, 0x10
    /* 1074C 8000FB4C 14410004 */  bne        $v0, $at, .L8000FB60
    /* 10750 8000FB50 00000000 */   nop
  .L8000FB54:
    /* 10754 8000FB54 00171C00 */  sll        $v1, $s7, 16
  .L8000FB58:
    /* 10758 8000FB58 00035403 */  sra        $t2, $v1, 16
    /* 1075C 8000FB5C 01401825 */  or         $v1, $t2, $zero
  .L8000FB60:
    /* 10760 8000FB60 916B2ACC */  lbu        $t3, %lo(D_80052ACC)($t3)
    /* 10764 8000FB64 2A010002 */  slti       $at, $s0, 0x2
    /* 10768 8000FB68 11600002 */  beqz       $t3, .L8000FB74
    /* 1076C 8000FB6C 00000000 */   nop
    /* 10770 8000FB70 24030002 */  addiu      $v1, $zero, 0x2
  .L8000FB74:
    /* 10774 8000FB74 1020FF5F */  beqz       $at, .L8000F8F4
    /* 10778 8000FB78 00000000 */   nop
    /* 1077C 8000FB7C 02A3082A */  slt        $at, $s5, $v1
    /* 10780 8000FB80 1420FF5C */  bnez       $at, .L8000F8F4
    /* 10784 8000FB84 00000000 */   nop
    /* 10788 8000FB88 0C003CDA */  jal        func_8000F368
    /* 1078C 8000FB8C 0000A825 */   or        $s5, $zero, $zero
    /* 10790 8000FB90 0C000C19 */  jal        func_80003064
    /* 10794 8000FB94 00000000 */   nop
    /* 10798 8000FB98 0C007D50 */  jal        func_8001F540
    /* 1079C 8000FB9C 00000000 */   nop
    /* 107A0 8000FBA0 8EC30000 */  lw         $v1, 0x0($s6)
    /* 107A4 8000FBA4 AFA20058 */  sw         $v0, 0x58($sp)
    /* 107A8 8000FBA8 10600003 */  beqz       $v1, .L8000FBB8
    /* 107AC 8000FBAC 246CFFFF */   addiu     $t4, $v1, -0x1
    /* 107B0 8000FBB0 AE770000 */  sw         $s7, 0x0($s3)
    /* 107B4 8000FBB4 AECC0000 */  sw         $t4, 0x0($s6)
  .L8000FBB8:
    /* 107B8 8000FBB8 8E6D0000 */  lw         $t5, 0x0($s3)
    /* 107BC 8000FBBC 11A0001D */  beqz       $t5, .L8000FC34
    /* 107C0 8000FBC0 00000000 */   nop
    /* 107C4 8000FBC4 8ECE0000 */  lw         $t6, 0x0($s6)
    /* 107C8 8000FBC8 3C048003 */  lui        $a0, %hi(D_80037750)
    /* 107CC 8000FBCC 15C0000E */  bnez       $t6, .L8000FC08
    /* 107D0 8000FBD0 00000000 */   nop
    /* 107D4 8000FBD4 3C048003 */  lui        $a0, %hi(D_8003773C)
    /* 107D8 8000FBD8 0C00731B */  jal        func_8001CC6C
    /* 107DC 8000FBDC 2484773C */   addiu     $a0, $a0, %lo(D_8003773C)
    /* 107E0 8000FBE0 0C007D34 */  jal        func_8001F4D0
    /* 107E4 8000FBE4 00002025 */   or        $a0, $zero, $zero
    /* 107E8 8000FBE8 240F036D */  addiu      $t7, $zero, 0x36D
    /* 107EC 8000FBEC 3C018003 */  lui        $at, %hi(D_80035B5C)
    /* 107F0 8000FBF0 AC2F5B5C */  sw         $t7, %lo(D_80035B5C)($at)
    /* 107F4 8000FBF4 3C018007 */  lui        $at, %hi(D_80068090)
    /* 107F8 8000FBF8 0C007D54 */  jal        func_8001F550
    /* 107FC 8000FBFC C42C8090 */   lwc1      $fa0, %lo(D_80068090)($at)
    /* 10800 8000FC00 1000000C */  b          .L8000FC34
    /* 10804 8000FC04 AE600000 */   sw        $zero, 0x0($s3)
  .L8000FC08:
    /* 10808 8000FC08 0C00731B */  jal        func_8001CC6C
    /* 1080C 8000FC0C 24847750 */   addiu     $a0, $a0, %lo(D_80037750)
    /* 10810 8000FC10 24180400 */  addiu      $t8, $zero, 0x400
    /* 10814 8000FC14 3C018003 */  lui        $at, %hi(D_80035B5C)
    /* 10818 8000FC18 AC385B5C */  sw         $t8, %lo(D_80035B5C)($at)
    /* 1081C 8000FC1C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 10820 8000FC20 44816000 */  mtc1       $at, $fa0
    /* 10824 8000FC24 0C007D54 */  jal        func_8001F550
    /* 10828 8000FC28 00000000 */   nop
    /* 1082C 8000FC2C 0C007D34 */  jal        func_8001F4D0
    /* 10830 8000FC30 24040001 */   addiu     $a0, $zero, 0x1
  .L8000FC34:
    /* 10834 8000FC34 3C048007 */  lui        $a0, %hi(D_8006A8D0)
    /* 10838 8000FC38 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 1083C 8000FC3C 8CA58038 */  lw         $a1, %lo(D_80068038)($a1)
    /* 10840 8000FC40 2484A8D0 */  addiu      $a0, $a0, %lo(D_8006A8D0)
    /* 10844 8000FC44 0C0070F4 */  jal        func_8001C3D0
    /* 10848 8000FC48 02E03025 */   or        $a2, $s7, $zero
    /* 1084C 8000FC4C 8E230000 */  lw         $v1, 0x0($s1)
    /* 10850 8000FC50 24010002 */  addiu      $at, $zero, 0x2
    /* 10854 8000FC54 3C048007 */  lui        $a0, %hi(D_8006A8B0)
    /* 10858 8000FC58 14610003 */  bne        $v1, $at, .L8000FC68
    /* 1085C 8000FC5C 2484A8B0 */   addiu     $a0, $a0, %lo(D_8006A8B0)
    /* 10860 8000FC60 2479FFFF */  addiu      $t9, $v1, -0x1
    /* 10864 8000FC64 AE390000 */  sw         $t9, 0x0($s1)
  .L8000FC68:
    /* 10868 8000FC68 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 1086C 8000FC6C 24A58038 */  addiu      $a1, $a1, %lo(D_80068038)
    /* 10870 8000FC70 0C006E9C */  jal        func_8001BA70
    /* 10874 8000FC74 02E03025 */   or        $a2, $s7, $zero
    /* 10878 8000FC78 0C007D50 */  jal        func_8001F540
    /* 1087C 8000FC7C 00000000 */   nop
    /* 10880 8000FC80 8FAA0058 */  lw         $t2, 0x58($sp)
    /* 10884 8000FC84 3C038006 */  lui        $v1, %hi(D_8005BB20)
    /* 10888 8000FC88 8C63BB20 */  lw         $v1, %lo(D_8005BB20)($v1)
    /* 1088C 8000FC8C 3C018005 */  lui        $at, %hi(D_80052B38)
    /* 10890 8000FC90 004A5823 */  subu       $t3, $v0, $t2
    /* 10894 8000FC94 AC2B2B38 */  sw         $t3, %lo(D_80052B38)($at)
    /* 10898 8000FC98 001468C0 */  sll        $t5, $s4, 3
    /* 1089C 8000FC9C 3401E378 */  ori        $at, $zero, 0xE378
    /* 108A0 8000FCA0 01B46821 */  addu       $t5, $t5, $s4
    /* 108A4 8000FCA4 3C0E8007 */  lui        $t6, %hi(D_8006A940)
    /* 108A8 8000FCA8 3C0CB800 */  lui        $t4, (0xB8000000 >> 16)
    /* 108AC 8000FCAC 25CEA940 */  addiu      $t6, $t6, %lo(D_8006A940)
    /* 108B0 8000FCB0 000D6900 */  sll        $t5, $t5, 4
    /* 108B4 8000FCB4 00611821 */  addu       $v1, $v1, $at
    /* 108B8 8000FCB8 AC6C0000 */  sw         $t4, 0x0($v1)
    /* 108BC 8000FCBC AC600004 */  sw         $zero, 0x4($v1)
    /* 108C0 8000FCC0 0C003D1E */  jal        func_8000F478
    /* 108C4 8000FCC4 01AE2021 */   addu      $a0, $t5, $t6
    /* 108C8 8000FCC8 0C007D50 */  jal        func_8001F540
    /* 108CC 8000FCCC 00000000 */   nop
    /* 108D0 8000FCD0 00147880 */  sll        $t7, $s4, 2
    /* 108D4 8000FCD4 03AFC021 */  addu       $t8, $sp, $t7
    /* 108D8 8000FCD8 3C038003 */  lui        $v1, %hi(D_80031B84)
    /* 108DC 8000FCDC 24631B84 */  addiu      $v1, $v1, %lo(D_80031B84)
    /* 108E0 8000FCE0 AF02005C */  sw         $v0, 0x5C($t8)
    /* 108E4 8000FCE4 8C790000 */  lw         $t9, 0x0($v1)
    /* 108E8 8000FCE8 240A0001 */  addiu      $t2, $zero, 0x1
    /* 108EC 8000FCEC 3A8C0001 */  xori       $t4, $s4, 0x1
    /* 108F0 8000FCF0 01595823 */  subu       $t3, $t2, $t9
    /* 108F4 8000FCF4 AC6B0000 */  sw         $t3, 0x0($v1)
    /* 108F8 8000FCF8 0180A025 */  or         $s4, $t4, $zero
    /* 108FC 8000FCFC 1000FEFD */  b          .L8000F8F4
    /* 10900 8000FD00 26100001 */   addiu     $s0, $s0, 0x1
  .L8000FD04:
    /* 10904 8000FD04 0C007D50 */  jal        func_8001F540
    /* 10908 8000FD08 00009025 */   or        $s2, $zero, $zero
    /* 1090C 8000FD0C 8FA3007C */  lw         $v1, 0x7C($sp)
    /* 10910 8000FD10 3C018005 */  lui        $at, %hi(D_80052B3C)
    /* 10914 8000FD14 2610FFFF */  addiu      $s0, $s0, -0x1
    /* 10918 8000FD18 00036880 */  sll        $t5, $v1, 2
    /* 1091C 8000FD1C 03AD7021 */  addu       $t6, $sp, $t5
    /* 10920 8000FD20 8DCE005C */  lw         $t6, 0x5C($t6)
    /* 10924 8000FD24 38780001 */  xori       $t8, $v1, 0x1
    /* 10928 8000FD28 AFB8007C */  sw         $t8, 0x7C($sp)
    /* 1092C 8000FD2C 004E7823 */  subu       $t7, $v0, $t6
    /* 10930 8000FD30 AC2F2B3C */  sw         $t7, %lo(D_80052B3C)($at)
    /* 10934 8000FD34 8E2A0000 */  lw         $t2, 0x0($s1)
    /* 10938 8000FD38 16EAFEEE */  bne        $s7, $t2, .L8000F8F4
    /* 1093C 8000FD3C 00000000 */   nop
    /* 10940 8000FD40 8E790000 */  lw         $t9, 0x0($s3)
    /* 10944 8000FD44 3C018007 */  lui        $at, %hi(D_8006808C)
    /* 10948 8000FD48 1720FEEA */  bnez       $t9, .L8000F8F4
    /* 1094C 8000FD4C 00000000 */   nop
    /* 10950 8000FD50 0C007D6C */  jal        func_8001F5B0
    /* 10954 8000FD54 C42C808C */   lwc1      $fa0, %lo(D_8006808C)($at)
    /* 10958 8000FD58 3C018007 */  lui        $at, %hi(D_80068090)
    /* 1095C 8000FD5C 0C007D54 */  jal        func_8001F550
    /* 10960 8000FD60 C42C8090 */   lwc1      $fa0, %lo(D_80068090)($at)
    /* 10964 8000FD64 8E2B0000 */  lw         $t3, 0x0($s1)
    /* 10968 8000FD68 256CFFFF */  addiu      $t4, $t3, -0x1
    /* 1096C 8000FD6C 1000FEE1 */  b          .L8000F8F4
    /* 10970 8000FD70 AE2C0000 */   sw        $t4, 0x0($s1)
  .L8000FD74:
    /* 10974 8000FD74 3C018007 */  lui        $at, %hi(D_80068078)
    /* 10978 8000FD78 A4378078 */  sh         $s7, %lo(D_80068078)($at)
    /* 1097C 8000FD7C 00001025 */  or         $v0, $zero, $zero
    /* 10980 8000FD80 0000A025 */  or         $s4, $zero, $zero
    /* 10984 8000FD84 00008025 */  or         $s0, $zero, $zero
    /* 10988 8000FD88 0000A825 */  or         $s5, $zero, $zero
    /* 1098C 8000FD8C 00009025 */  or         $s2, $zero, $zero
    /* 10990 8000FD90 0C005667 */  jal        func_8001599C
    /* 10994 8000FD94 24030001 */   addiu     $v1, $zero, 0x1
    /* 10998 8000FD98 0C000442 */  jal        func_80001108
    /* 1099C 8000FD9C 00000000 */   nop
    /* 109A0 8000FDA0 3C028003 */  lui        $v0, %hi(D_80035630)
    /* 109A4 8000FDA4 3C0E005F */  lui        $t6, (0x5F0239 >> 16)
    /* 109A8 8000FDA8 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 109AC 8000FDAC 24425630 */  addiu      $v0, $v0, %lo(D_80035630)
    /* 109B0 8000FDB0 240D0400 */  addiu      $t5, $zero, 0x400
    /* 109B4 8000FDB4 35CE0239 */  ori        $t6, $t6, (0x5F0239 & 0xFFFF)
    /* 109B8 8000FDB8 44816000 */  mtc1       $at, $fa0
    /* 109BC 8000FDBC AC4D052C */  sw         $t5, 0x52C($v0)
    /* 109C0 8000FDC0 0C007D6C */  jal        func_8001F5B0
    /* 109C4 8000FDC4 AC4E0530 */   sw        $t6, 0x530($v0)
    /* 109C8 8000FDC8 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 109CC 8000FDCC 44816000 */  mtc1       $at, $fa0
    /* 109D0 8000FDD0 0C007D54 */  jal        func_8001F550
    /* 109D4 8000FDD4 00000000 */   nop
    /* 109D8 8000FDD8 0C007D34 */  jal        func_8001F4D0
    /* 109DC 8000FDDC 24040001 */   addiu     $a0, $zero, 0x1
    /* 109E0 8000FDE0 3C048006 */  lui        $a0, %hi(D_80067DA8)
    /* 109E4 8000FDE4 0C007C5C */  jal        func_8001F170
    /* 109E8 8000FDE8 24847DA8 */   addiu     $a0, $a0, %lo(D_80067DA8)
    /* 109EC 8000FDEC 3C048006 */  lui        $a0, %hi(D_80067898)
    /* 109F0 8000FDF0 0C007C5C */  jal        func_8001F170
    /* 109F4 8000FDF4 24847898 */   addiu     $a0, $a0, %lo(D_80067898)
    /* 109F8 8000FDF8 3C048006 */  lui        $a0, %hi(D_800676E8)
    /* 109FC 8000FDFC 0C007C5C */  jal        func_8001F170
    /* 10A00 8000FE00 248476E8 */   addiu     $a0, $a0, %lo(D_800676E8)
  .L8000FE04:
    /* 10A04 8000FE04 1000FFFF */  b          .L8000FE04
    /* 10A08 8000FE08 00000000 */   nop
    /* 10A0C 8000FE0C 00000000 */  nop
    /* 10A10 8000FE10 00000000 */  nop
    /* 10A14 8000FE14 00000000 */  nop
    /* 10A18 8000FE18 00000000 */  nop
    /* 10A1C 8000FE1C 00000000 */  nop
    /* 10A20 8000FE20 8FBF0044 */  lw         $ra, 0x44($sp)
    /* 10A24 8000FE24 8FB00020 */  lw         $s0, 0x20($sp)
    /* 10A28 8000FE28 8FB10024 */  lw         $s1, 0x24($sp)
    /* 10A2C 8000FE2C 8FB20028 */  lw         $s2, 0x28($sp)
    /* 10A30 8000FE30 8FB3002C */  lw         $s3, 0x2C($sp)
    /* 10A34 8000FE34 8FB40030 */  lw         $s4, 0x30($sp)
    /* 10A38 8000FE38 8FB50034 */  lw         $s5, 0x34($sp)
    /* 10A3C 8000FE3C 8FB60038 */  lw         $s6, 0x38($sp)
    /* 10A40 8000FE40 8FB7003C */  lw         $s7, 0x3C($sp)
    /* 10A44 8000FE44 8FBE0040 */  lw         $fp, 0x40($sp)
    /* 10A48 8000FE48 03E00008 */  jr         $ra
    /* 10A4C 8000FE4C 27BD00A0 */   addiu     $sp, $sp, 0xA0

glabel func_8000FE50
    /* 10A50 8000FE50 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 10A54 8000FE54 AFA40018 */  sw         $a0, 0x18($sp)
    /* 10A58 8000FE58 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 10A5C 8000FE5C 3C048007 */  lui        $a0, %hi(D_8006A8D0)
    /* 10A60 8000FE60 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 10A64 8000FE64 24A58038 */  addiu      $a1, $a1, %lo(D_80068038)
    /* 10A68 8000FE68 2484A8D0 */  addiu      $a0, $a0, %lo(D_8006A8D0)
    /* 10A6C 8000FE6C 0C006E9C */  jal        func_8001BA70
    /* 10A70 8000FE70 24060001 */   addiu     $a2, $zero, 0x1
    /* 10A74 8000FE74 0C007CC4 */  jal        func_8001F310
    /* 10A78 8000FE78 24040040 */   addiu     $a0, $zero, 0x40
    /* 10A7C 8000FE7C 0C003D86 */  jal        func_8000F618
    /* 10A80 8000FE80 00000000 */   nop
    /* 10A84 8000FE84 240E0003 */  addiu      $t6, $zero, 0x3
    /* 10A88 8000FE88 3C018005 */  lui        $at, %hi(D_80052ACA)
    /* 10A8C 8000FE8C 0C0015AA */  jal        func_800056A8
    /* 10A90 8000FE90 A02E2ACA */   sb        $t6, %lo(D_80052ACA)($at)
    /* 10A94 8000FE94 0C0015AA */  jal        func_800056A8
    /* 10A98 8000FE98 00000000 */   nop
    /* 10A9C 8000FE9C 3C048007 */  lui        $a0, %hi(D_8006A8F0)
    /* 10AA0 8000FEA0 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 10AA4 8000FEA4 24A58038 */  addiu      $a1, $a1, %lo(D_80068038)
    /* 10AA8 8000FEA8 2484A8F0 */  addiu      $a0, $a0, %lo(D_8006A8F0)
    /* 10AAC 8000FEAC 0C006E9C */  jal        func_8001BA70
    /* 10AB0 8000FEB0 24060001 */   addiu     $a2, $zero, 0x1
    /* 10AB4 8000FEB4 0C000661 */  jal        func_80001984
    /* 10AB8 8000FEB8 00000000 */   nop
    /* 10ABC 8000FEBC 3C048003 */  lui        $a0, %hi(D_80037764)
    /* 10AC0 8000FEC0 3C050002 */  lui        $a1, (0x28928 >> 16)
    /* 10AC4 8000FEC4 34A58928 */  ori        $a1, $a1, (0x28928 & 0xFFFF)
    /* 10AC8 8000FEC8 0C00731B */  jal        func_8001CC6C
    /* 10ACC 8000FECC 24847764 */   addiu     $a0, $a0, %lo(D_80037764)
    /* 10AD0 8000FED0 0C00457D */  jal        func_800115F4
    /* 10AD4 8000FED4 00000000 */   nop
    /* 10AD8 8000FED8 0C01C09C */  jal        func_80070270
    /* 10ADC 8000FEDC 24040001 */   addiu     $a0, $zero, 0x1
    /* 10AE0 8000FEE0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 10AE4 8000FEE4 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 10AE8 8000FEE8 03E00008 */  jr         $ra
    /* 10AEC 8000FEEC 00000000 */   nop

glabel func_8000FEF0
    /* 10AF0 8000FEF0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 10AF4 8000FEF4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 10AF8 8000FEF8 240E0001 */  addiu      $t6, $zero, 0x1
    /* 10AFC 8000FEFC 3C018003 */  lui        $at, %hi(D_80031B54)
    /* 10B00 8000FF00 3C048006 */  lui        $a0, %hi(D_8005BB08)
    /* 10B04 8000FF04 3C058006 */  lui        $a1, %hi(D_8005BB00)
    /* 10B08 8000FF08 AC2E1B54 */  sw         $t6, %lo(D_80031B54)($at)
    /* 10B0C 8000FF0C 24A5BB00 */  addiu      $a1, $a1, %lo(D_8005BB00)
    /* 10B10 8000FF10 2484BB08 */  addiu      $a0, $a0, %lo(D_8005BB08)
    /* 10B14 8000FF14 0C006B98 */  jal        func_8001AE60
    /* 10B18 8000FF18 24060001 */   addiu     $a2, $zero, 0x1
    /* 10B1C 8000FF1C 3C048006 */  lui        $a0, %hi(D_8005BB08)
    /* 10B20 8000FF20 2484BB08 */  addiu      $a0, $a0, %lo(D_8005BB08)
    /* 10B24 8000FF24 00002825 */  or         $a1, $zero, $zero
    /* 10B28 8000FF28 0C0070F4 */  jal        func_8001C3D0
    /* 10B2C 8000FF2C 00003025 */   or        $a2, $zero, $zero
    /* 10B30 8000FF30 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 10B34 8000FF34 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 10B38 8000FF38 03E00008 */  jr         $ra
    /* 10B3C 8000FF3C 00000000 */   nop

glabel func_8000FF40
    /* 10B40 8000FF40 3C0E8003 */  lui        $t6, %hi(D_80031B54)
    /* 10B44 8000FF44 8DCE1B54 */  lw         $t6, %lo(D_80031B54)($t6)
    /* 10B48 8000FF48 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 10B4C 8000FF4C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 10B50 8000FF50 15C00003 */  bnez       $t6, .L8000FF60
    /* 10B54 8000FF54 00000000 */   nop
    /* 10B58 8000FF58 0C003FBC */  jal        func_8000FEF0
    /* 10B5C 8000FF5C 00000000 */   nop
  .L8000FF60:
    /* 10B60 8000FF60 3C048006 */  lui        $a0, %hi(D_8005BB08)
    /* 10B64 8000FF64 3C058007 */  lui        $a1, %hi(D_80068038)
    /* 10B68 8000FF68 24A58038 */  addiu      $a1, $a1, %lo(D_80068038)
    /* 10B6C 8000FF6C 2484BB08 */  addiu      $a0, $a0, %lo(D_8005BB08)
    /* 10B70 8000FF70 0C006E9C */  jal        func_8001BA70
    /* 10B74 8000FF74 24060001 */   addiu     $a2, $zero, 0x1
    /* 10B78 8000FF78 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 10B7C 8000FF7C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 10B80 8000FF80 03E00008 */  jr         $ra
    /* 10B84 8000FF84 00000000 */   nop

glabel func_8000FF88
    /* 10B88 8000FF88 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 10B8C 8000FF8C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 10B90 8000FF90 3C048006 */  lui        $a0, %hi(D_8005BB08)
    /* 10B94 8000FF94 2484BB08 */  addiu      $a0, $a0, %lo(D_8005BB08)
    /* 10B98 8000FF98 00002825 */  or         $a1, $zero, $zero
    /* 10B9C 8000FF9C 0C0070F4 */  jal        func_8001C3D0
    /* 10BA0 8000FFA0 00003025 */   or        $a2, $zero, $zero
    /* 10BA4 8000FFA4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 10BA8 8000FFA8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 10BAC 8000FFAC 03E00008 */  jr         $ra
    /* 10BB0 8000FFB0 00000000 */   nop
    /* 10BB4 8000FFB4 00000000 */  nop
    /* 10BB8 8000FFB8 00000000 */  nop
    /* 10BBC 8000FFBC 00000000 */  nop
