.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.33.0 */

dlabel D_80039BF0
    /* 3A7F0 80039BF0 */ .byte 0x00
    /* 3A7F1 80039BF1 */ .byte 0x14
    /* 3A7F2 80039BF2 */ .byte 0x18
    /* 3A7F3 80039BF3 */ .byte 0x18
    /* 3A7F4 80039BF4 */ .byte 0x1C
    /* 3A7F5 80039BF5 */ .byte 0x1C
    /* 3A7F6 80039BF6 */ .byte 0x1C
    /* 3A7F7 80039BF7 */ .byte 0x1C
    /* 3A7F8 80039BF8 */ .byte 0x20
    /* 3A7F9 80039BF9 */ .byte 0x20
    /* 3A7FA 80039BFA */ .byte 0x20
    /* 3A7FB 80039BFB */ .byte 0x20
    /* 3A7FC 80039BFC */ .byte 0x20
    /* 3A7FD 80039BFD */ .byte 0x20
    /* 3A7FE 80039BFE */ .byte 0x20
    /* 3A7FF 80039BFF */ .byte 0x20
    /* 3A800 80039C00 */ .byte 0x00
    /* 3A801 80039C01 */ .byte 0x04
    /* 3A802 80039C02 */ .byte 0x08
    /* 3A803 80039C03 */ .byte 0x08
    /* 3A804 80039C04 */ .byte 0x0C
    /* 3A805 80039C05 */ .byte 0x0C
    /* 3A806 80039C06 */ .byte 0x0C
    /* 3A807 80039C07 */ .byte 0x0C
    /* 3A808 80039C08 */ .byte 0x10
    /* 3A809 80039C09 */ .byte 0x10
    /* 3A80A 80039C0A */ .byte 0x10
    /* 3A80B 80039C0B */ .byte 0x10
    /* 3A80C 80039C0C */ .byte 0x10
    /* 3A80D 80039C0D */ .byte 0x10
    /* 3A80E 80039C0E */ .byte 0x10
    /* 3A80F 80039C0F */ .byte 0x10

dlabel jtbl_80039C10
    /* 3A810 80039C10 80023568 */ .word .L80023568
    /* 3A814 80039C14 80023530 */ .word .L80023530
    /* 3A818 80039C18 80023510 */ .word .L80023510
    /* 3A81C 80039C1C 80023374 */ .word .L80023374
    /* 3A820 80039C20 80023320 */ .word .L80023320
    /* 3A824 80039C24 800234B4 */ .word .L800234B4
    /* 3A828 80039C28 800232E8 */ .word .L800232E8
    /* 3A82C 80039C2C 800232F4 */ .word .L800232F4
    /* 3A830 80039C30 80023300 */ .word .L80023300
    /* 3A834 80039C34 00000000 */ .word 0x00000000
    /* 3A838 80039C38 00000000 */ .word 0x00000000
    /* 3A83C 80039C3C 00000000 */ .word 0x00000000
