.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.33.0 */

dlabel D_80039C40
    /* 3A840 80039C40 */ .short 0x0555
    /* 3A842 80039C42 */ .short 0x0556
    /* 3A844 80039C44 */ .short 0x0559
    /* 3A846 80039C46 */ .short 0x055A
    /* 3A848 80039C48 */ .short 0x0565
    /* 3A84A 80039C4A */ .short 0x0566
    /* 3A84C 80039C4C */ .short 0x0569
    /* 3A84E 80039C4E */ .short 0x056A
    /* 3A850 80039C50 */ .short 0x0595
    /* 3A852 80039C52 */ .short 0x0596
    /* 3A854 80039C54 */ .short 0x0599
    /* 3A856 80039C56 */ .short 0x059A
    /* 3A858 80039C58 */ .short 0x05A5
    /* 3A85A 80039C5A */ .short 0x05A6
    /* 3A85C 80039C5C */ .short 0x05A9
    /* 3A85E 80039C5E */ .short 0x05AA
    /* 3A860 80039C60 */ .short 0x0655
    /* 3A862 80039C62 */ .short 0x0656
    /* 3A864 80039C64 */ .short 0x0659
    /* 3A866 80039C66 */ .short 0x065A
    /* 3A868 80039C68 */ .short 0x0665
    /* 3A86A 80039C6A */ .short 0x0666
    /* 3A86C 80039C6C */ .short 0x0669
    /* 3A86E 80039C6E */ .short 0x066A
    /* 3A870 80039C70 */ .short 0x0695
    /* 3A872 80039C72 */ .short 0x0696
    /* 3A874 80039C74 */ .short 0x0699
    /* 3A876 80039C76 */ .short 0x069A
    /* 3A878 80039C78 */ .short 0x06A5
    /* 3A87A 80039C7A */ .short 0x06A6
    /* 3A87C 80039C7C */ .short 0x06A9
    /* 3A87E 80039C7E */ .short 0x06AA
    /* 3A880 80039C80 */ .short 0x0955
    /* 3A882 80039C82 */ .short 0x0956
    /* 3A884 80039C84 */ .short 0x0959
    /* 3A886 80039C86 */ .short 0x095A
    /* 3A888 80039C88 */ .short 0x0965
    /* 3A88A 80039C8A */ .short 0x0966
    /* 3A88C 80039C8C */ .short 0x0969
    /* 3A88E 80039C8E */ .short 0x096A
    /* 3A890 80039C90 */ .short 0x0995
    /* 3A892 80039C92 */ .short 0x0996
    /* 3A894 80039C94 */ .short 0x0999
    /* 3A896 80039C96 */ .short 0x099A
    /* 3A898 80039C98 */ .short 0x09A5
    /* 3A89A 80039C9A */ .short 0x09A6
    /* 3A89C 80039C9C */ .short 0x09A9
    /* 3A89E 80039C9E */ .short 0x09AA
    /* 3A8A0 80039CA0 */ .short 0x0A55
    /* 3A8A2 80039CA2 */ .short 0x0A56
    /* 3A8A4 80039CA4 */ .short 0x0A59
    /* 3A8A6 80039CA6 */ .short 0x0A5A
    /* 3A8A8 80039CA8 */ .short 0x0A65
    /* 3A8AA 80039CAA */ .short 0x0A66
    /* 3A8AC 80039CAC */ .short 0x0A69
    /* 3A8AE 80039CAE */ .short 0x0A6A
    /* 3A8B0 80039CB0 */ .short 0x0A95
    /* 3A8B2 80039CB2 */ .short 0x0A96
    /* 3A8B4 80039CB4 */ .short 0x0A99
    /* 3A8B6 80039CB6 */ .short 0x0A9A
    /* 3A8B8 80039CB8 */ .short 0x0AA5
    /* 3A8BA 80039CBA */ .short 0x0AA6
    /* 3A8BC 80039CBC */ .short 0x0AA9
    /* 3A8BE 80039CBE */ .short 0x0AAA

dlabel jtbl_80039CC0
    /* 3A8C0 80039CC0 80024448 */ .word .L80024448
    /* 3A8C4 80039CC4 80024454 */ .word .L80024454
    /* 3A8C8 80039CC8 8002446C */ .word .L8002446C
    /* 3A8CC 80039CCC 80024478 */ .word .L80024478
    /* 3A8D0 80039CD0 80024460 */ .word .L80024460
    /* 3A8D4 80039CD4 80024484 */ .word .L80024484

dlabel D_80039CD8
    /* 3A8D8 80039CD8 4105221B3D3FB61B */ .double 173123.404906676005

dlabel jtbl_80039CE0
    /* 3A8E0 80039CE0 80025550 */ .word .L80025550
    /* 3A8E4 80039CE4 800255E0 */ .word .L800255E0
    /* 3A8E8 80039CE8 800255E0 */ .word .L800255E0
    /* 3A8EC 80039CEC 80025558 */ .word .L80025558
    /* 3A8F0 80039CF0 800255E0 */ .word .L800255E0
    /* 3A8F4 80039CF4 800255E0 */ .word .L800255E0
    /* 3A8F8 80039CF8 800255C4 */ .word .L800255C4
    /* 3A8FC 80039CFC 800255D4 */ .word .L800255D4
    /* 3A900 80039D00 80025594 */ .word .L80025594
    /* 3A904 80039D04 00000000 */ .word 0x00000000

dlabel D_80039D08
    /* 3A908 80039D08 3FFFFFD60E94EE39 */ .double 1.99995999999999996

dlabel D_80039D10
    /* 3A910 80039D10 3FFFFEB0 */ .float 1.999959946
    /* 3A914 80039D14 00000000 */ .float 0
    /* 3A918 80039D18 00000000 */ .float 0
    /* 3A91C 80039D1C 00000000 */ .float 0
