.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.33.0 */

.align 2
dlabel D_80037660
    /* 38260 80037660 */ .asciz "Schedule Stack Overflow\n"
.align 2

.align 2
dlabel D_8003767C
    /* 3827C 8003767C */ .asciz "Boot Stack Overflow\n"
.align 2

.align 2
dlabel D_80037694
    /* 38294 80037694 */ .asciz "Idle Stack Overflow\n"
.align 2

.align 2
dlabel D_800376AC
    /* 382AC 800376AC */ .asciz "IO Stack Overflow\n"
.align 2

.align 2
dlabel D_800376C0
    /* 382C0 800376C0 */ .asciz "Main Stack Overflow\n"
.align 2

.align 2
dlabel D_800376D8
    /* 382D8 800376D8 */ .asciz "Rmon Stack Overflow\n"
.align 2

.align 2
dlabel D_800376F0
    /* 382F0 800376F0 */ .asciz "Controller Stack Overflow\n"
.align 2

.align 2
dlabel D_8003770C
    /* 3830C 8003770C */ .asciz "Load Level Stack Overflow\n"
.align 2

.align 2
dlabel D_80037728
    /* 38328 80037728 */ .asciz "RCP hang detected\n"
.align 2

.align 2
dlabel D_8003773C
    /* 3833C 8003773C */ .asciz "black screen off\n"
.align 2

.align 2
dlabel D_80037750
    /* 38350 80037750 */ .asciz "black screen on\n"
.align 2

.align 2
dlabel D_80037764
    /* 38364 80037764 */ .asciz "level data %x\n"
.align 2
.align 2
    /* 38374 80037774 */ .asciz ""
.align 2
.align 2
    /* 38378 80037778 */ .asciz ""
.align 2
.align 2
    /* 3837C 8003777C */ .asciz ""
.align 2

.align 2
dlabel D_80037780
    /* 38380 80037780 */ .asciz "PI_STATUS_IO_BUSY\n"
.align 2

.align 2
dlabel D_80037794
    /* 38394 80037794 */ .asciz "PI_STATUS_DMA_BUSY\n"
.align 2

.align 2
dlabel D_800377A8
    /* 383A8 800377A8 */ .asciz "PI_STATUS_ERROR\n"
.align 2

.align 2
dlabel D_800377BC
    /* 383BC 800377BC */ .asciz "PI_STATUS_IO_BUSY\n"
.align 2

.align 2
dlabel D_800377D0
    /* 383D0 800377D0 */ .asciz "PI_STATUS_DMA_BUSY\n"
.align 2

.align 2
dlabel D_800377E4
    /* 383E4 800377E4 */ .asciz "PI_STATUS_ERROR\n"
.align 2

.align 2
dlabel D_800377F8
    /* 383F8 800377F8 */ .asciz "romsize %6d, "
.align 2

.align 2
dlabel D_80037808
    /* 38408 80037808 */ .asciz "header ID wrong, "
.align 2

.align 2
dlabel D_8003781C
    /* 3841C 8003781C */ .asciz "packed %6d, unpacked %6d, "
.align 2

.align 2
dlabel D_80037838
    /* 38438 80037838 */ .asciz "\n\nLoading level %d\n\n"
.align 2

.align 2
dlabel D_80037850
    /* 38450 80037850 */ .asciz "------------------------------\n"
.align 2

.align 2
dlabel D_80037870
    /* 38470 80037870 */ .asciz "  Start of anim data: %x\n"
.align 2

.align 2
dlabel D_8003788C
    /* 3848C 8003788C */ .asciz "    End of anim data: %x\n"
.align 2

.align 2
dlabel D_800378A8
    /* 384A8 800378A8 */ .asciz "                Size: %x (%.2fK)\n"
.align 2

.align 2
dlabel D_800378CC
    /* 384CC 800378CC */ .asciz "OK"
.align 2

.align 2
dlabel D_800378D0
    /* 384D0 800378D0 */ .asciz "**** ERROR ****"
.align 2

.align 2
dlabel D_800378E0
    /* 384E0 800378E0 */ .asciz "         postData:"
.align 2

.align 2
dlabel D_800378F4
    /* 384F4 800378F4 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037908
    /* 38508 80037908 */ .asciz "      texBlockMap:"
.align 2

.align 2
dlabel D_8003791C
    /* 3851C 8003791C */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037930
    /* 38530 80037930 */ .asciz " landscapeColours:"
.align 2

.align 2
dlabel D_80037944
    /* 38544 80037944 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037958
    /* 38558 80037958 */ .asciz " landscapePalette:"
.align 2

.align 2
dlabel D_8003796C
    /* 3856C 8003796C */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037980
    /* 38580 80037980 */ .asciz "      treeStructs:"
.align 2

.align 2
dlabel D_80037994
    /* 38594 80037994 */ .asciz "should be %6d, Free structs:%d\n"
.align 2

.align 2
dlabel D_800379B4
    /* 385B4 800379B4 */ .asciz "            trees:"
.align 2

.align 2
dlabel D_800379C8
    /* 385C8 800379C8 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_800379DC
    /* 385DC 800379DC */ .asciz "          treeGfx:                                "
.align 2

.align 2
dlabel D_80037A10
    /* 38610 80037A10 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037A24
    /* 38624 80037A24 */ .asciz " WaterTableHeight:                                "
.align 2

.align 2
dlabel D_80037A58
    /* 38658 80037A58 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037A6C
    /* 3866C 80037A6C */ .asciz "    BuildingTypes:                                "
.align 2

.align 2
dlabel D_80037AA0
    /* 386A0 80037AA0 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037AB4
    /* 386B4 80037AB4 */ .asciz "        Buildings:                                "
.align 2

.align 2
dlabel D_80037AE8
    /* 386E8 80037AE8 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037AFC
    /* 386FC 80037AFC */ .asciz "     triggerArray:                                "
.align 2

.align 2
dlabel D_80037B30
    /* 38730 80037B30 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037B44
    /* 38744 80037B44 */ .asciz "      nextTrigger:                                "
.align 2

.align 2
dlabel D_80037B78
    /* 38778 80037B78 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037B8C
    /* 3878C 80037B8C */ .asciz "    levelWaveData:                                "
.align 2

.align 2
dlabel D_80037BC0
    /* 387C0 80037BC0 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037BD4
    /* 387D4 80037BD4 */ .asciz "VehicleStartInfos:                                "
.align 2

.align 2
dlabel D_80037C08
    /* 38808 80037C08 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037C1C
    /* 3881C 80037C1C */ .asciz "         Missions:                                "
.align 2

.align 2
dlabel D_80037C50
    /* 38850 80037C50 */ .asciz "should be %6d, %s, "
.align 2

.align 2
dlabel D_80037C64
    /* 38864 80037C64 */ .asciz "data verified\n"
.align 2

.align 2
dlabel D_80037C74
    /* 38874 80037C74 */ .asciz "**** DATA BAD ****\n"
.align 2

.align 2
dlabel D_80037C88
    /* 38888 80037C88 */ .asciz "  terrainTextures:"
.align 2

.align 2
dlabel D_80037C9C
    /* 3889C 80037C9C */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037CB0
    /* 388B0 80037CB0 */ .asciz "      terrainCMAP:"
.align 2

.align 2
dlabel D_80037CC4
    /* 388C4 80037CC4 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037CD8
    /* 388D8 80037CD8 */ .asciz "      skyBackDrop:"
.align 2

.align 2
dlabel D_80037CEC
    /* 388EC 80037CEC */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037D00
    /* 38900 80037D00 */ .asciz "  skyBackDropCMAP:"
.align 2

.align 2
dlabel D_80037D14
    /* 38914 80037D14 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037D28
    /* 38928 80037D28 */ .asciz "        typeArray:                                "
.align 2

.align 2
dlabel D_80037D5C
    /* 3895C 80037D5C */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037D70
    /* 38970 80037D70 */ .asciz "     LandVehicles:                                "
.align 2

.align 2
dlabel D_80037DA4
    /* 389A4 80037DA4 */ .asciz "should be %6d, %s, "
.align 2

.align 2
dlabel D_80037DB8
    /* 389B8 80037DB8 */ .asciz "data verified\n"
.align 2

.align 2
dlabel D_80037DC8
    /* 389C8 80037DC8 */ .asciz "**** DATA BAD ****\n"
.align 2

.align 2
dlabel D_80037DDC
    /* 389DC 80037DDC */ .asciz "     SignPostData:                                "
.align 2

.align 2
dlabel D_80037E10
    /* 38A10 80037E10 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037E24
    /* 38A24 80037E24 */ .asciz "      SignStrings:  %d version                              "
.align 2

.align 2
dlabel D_80037E64
    /* 38A64 80037E64 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037E78
    /* 38A78 80037E78 */ .asciz "    signs_dialogue_offsets:    "
.align 2

.align 2
dlabel D_80037E98
    /* 38A98 80037E98 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037EAC
    /* 38AAC 80037EAC */ .asciz "    commsMessages:                                "
.align 2

.align 2
dlabel D_80037EE0
    /* 38AE0 80037EE0 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037EF4
    /* 38AF4 80037EF4 */ .asciz "    comms_dialogue_offsets:    "
.align 2

.align 2
dlabel D_80037F14
    /* 38B14 80037F14 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037F28
    /* 38B28 80037F28 */ .asciz "commsSentenceInfo:                                "
.align 2

.align 2
dlabel D_80037F5C
    /* 38B5C 80037F5C */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037F70
    /* 38B70 80037F70 */ .asciz "            Doors:                                "
.align 2

.align 2
dlabel D_80037FA4
    /* 38BA4 80037FA4 */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80037FB8
    /* 38BB8 80037FB8 */ .asciz "         BCPoints:                                "
.align 2

.align 2
dlabel D_80037FEC
    /* 38BEC 80037FEC */ .asciz "should be %6d, %s\n"
.align 2

.align 2
dlabel D_80038000
    /* 38C00 80038000 */ .asciz "Loading level %d code\n"
.align 2

.align 2
dlabel D_80038018
    /* 38C18 80038018 */ .asciz "%x from %x size %x\n"
.align 2

.align 2
dlabel D_8003802C
    /* 38C2C 8003802C */ .asciz "end %x\n"
.align 2

.align 2
dlabel D_80038034
    /* 38C34 80038034 */ .asciz " ******************************************\n"
.align 2

.align 2
dlabel D_80038064
    /* 38C64 80038064 */ .asciz " *\n * WARNING: inside textures too large\n *\n"
.align 2

.align 2
dlabel D_80038094
    /* 38C94 80038094 */ .asciz " ******************************************\n"
.align 2

.align 2
dlabel D_800380C4
    /* 38CC4 800380C4 */ .asciz "------------------------------\n"
.align 2

.align 2
dlabel D_800380E4
    /* 38CE4 800380E4 */ .asciz "Start of model segment: %8x\n"
.align 2

.align 2
dlabel D_80038104
    /* 38D04 80038104 */ .asciz "free>0"
.align 2

.align 2
dlabel D_8003810C
    /* 38D0C 8003810C */ .asciz "src/loader.c"
.align 2

.align 2
dlabel D_8003811C
    /* 38D1C 8003811C */ .asciz "------------------------------\n"
.align 2

.align 2
dlabel D_8003813C
    /* 38D3C 8003813C */ .asciz "End of model segment: %8x\n"
.align 2

.align 2
dlabel D_80038158
    /* 38D58 80038158 */ .asciz "    Start of ZBuffer: %8x\n"
.align 2

.align 2
dlabel D_80038174
    /* 38D74 80038174 */ .asciz "                Free: %x, (%.2fK)\n"
.align 2

.align 2
dlabel D_80038198
    /* 38D98 80038198 */ .asciz "------------------------------\n"
.align 2
.align 2
    /* 38DB8 800381B8 */ .asciz ""
.align 2
.align 2
    /* 38DBC 800381BC */ .asciz ""
.align 2

.align 2
dlabel D_800381C0
    /* 38DC0 800381C0 */ .asciz "Sounds playing"
.align 2

.align 2
dlabel D_800381D0
    /* 38DD0 800381D0 */ .asciz " ID%d obj %lx Slot%d State%d Vol %d T %ld Ct %d\n"
.align 2

.align 2
dlabel D_80038204
    /* 38E04 80038204 */ .asciz "\nSounds pending\n"
.align 2

.align 2
dlabel D_80038218
    /* 38E18 80038218 */ .asciz " Snd ID%d obj %lx Slot%d State%d Vol %d\n"
.align 2

.align 2
dlabel D_80038244
    /* 38E44 80038244 */ .asciz "\nSounds to be deleted\n"
.align 2

.align 2
dlabel D_8003825C
    /* 38E5C 8003825C */ .asciz " Snd ID%d obj %lx Slot%d State%d Vol %d\n"
.align 2

.align 2
dlabel D_80038288
    /* 38E88 80038288 */ .asciz "\n"
.align 2

.align 2
dlabel D_8003828C
    /* 38E8C 8003828C */ .asciz "house offset %d\n"
.align 2

.align 2
dlabel D_800382A0
    /* 38EA0 800382A0 */ .asciz "Error:GetFreeSeqPlayer - Tell Ciaran\n"
.align 2

.align 2
dlabel D_800382C8
    /* 38EC8 800382C8 */ .asciz "Error: GetFreeSeqPlayer2 - Tell Ciaran\n"
.align 2

dlabel D_800382F0
    /* 38EF0 800382F0 4826FE00 */ .float 171000
    /* 38EF4 800382F4 00000000 */ .float 0

dlabel D_800382F8
    /* 38EF8 800382F8 3FB999999999999A */ .double 0.100000000000000006

dlabel D_80038300
    /* 38F00 80038300 44898000 */ .float 1100

dlabel jtbl_80038304
    /* 38F04 80038304 8001470C */ .word .L8001470C
    /* 38F08 80038308 80014738 */ .word .L80014738
    /* 38F0C 8003830C 800147E8 */ .word .L800147E8
    /* 38F10 80038310 80014764 */ .word .L80014764
    /* 38F14 80038314 800147E8 */ .word .L800147E8
    /* 38F18 80038318 800147BC */ .word .L800147BC
    /* 38F1C 8003831C 800147E8 */ .word .L800147E8
    /* 38F20 80038320 80014790 */ .word .L80014790

dlabel D_80038324
    /* 38F24 80038324 46BE7C00 */ .float 24382

dlabel D_80038328
    /* 38F28 80038328 46186400 */ .float 9753

dlabel D_8003832C
    /* 38F2C 8003832C 458CA000 */ .float 4500

dlabel D_80038330
    /* 38F30 80038330 3FB999999999999A */ .double 0.100000000000000006

dlabel D_80038338
    /* 38F38 80038338 3DCCCCCD */ .float 0.1000000015

dlabel D_8003833C
    /* 38F3C 8003833C 45BB8000 */ .float 6000

dlabel D_80038340
    /* 38F40 80038340 453B8000 */ .float 3000
    /* 38F44 80038344 00000000 */ .float 0

dlabel D_80038348
    /* 38F48 80038348 3FE999999999999A */ .double 0.800000000000000044

dlabel D_80038350
    /* 38F50 80038350 45BB8000 */ .float 6000
    /* 38F54 80038354 00000000 */ .float 0

dlabel D_80038358
    /* 38F58 80038358 3FB999999999999A */ .double 0.100000000000000006

dlabel jtbl_80038360
    /* 38F60 80038360 80015CFC */ .word .L80015CFC
    /* 38F64 80038364 80015D88 */ .word .L80015D88
    /* 38F68 80038368 80015E18 */ .word .L80015E18
    /* 38F6C 8003836C 80016058 */ .word .L80016058
    /* 38F70 80038370 800160DC */ .word .L800160DC
    /* 38F74 80038374 80016010 */ .word .L80016010
    /* 38F78 80038378 80016160 */ .word .L80016160
    /* 38F7C 8003837C 800164B4 */ .word .L800164B4
    /* 38F80 80038380 800161A8 */ .word .L800161A8
    /* 38F84 80038384 80016238 */ .word .L80016238
    /* 38F88 80038388 800162C8 */ .word .L800162C8
    /* 38F8C 8003838C 80015F80 */ .word .L80015F80
    /* 38F90 80038390 80016358 */ .word .L80016358
    /* 38F94 80038394 800163A0 */ .word .L800163A0
    /* 38F98 80038398 800164B4 */ .word .L800164B4
    /* 38F9C 8003839C 80016430 */ .word .L80016430
    /* 38FA0 800383A0 80016478 */ .word .L80016478
    /* 38FA4 800383A4 00000000 */ .word 0x00000000
    /* 38FA8 800383A8 00000000 */ .word 0x00000000
    /* 38FAC 800383AC 00000000 */ .word 0x00000000
