.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.33.0 */

dlabel D_8003FB20
    /* 8003FB20 */ .space 0x08

dlabel D_8003FB28
    /* 8003FB28 */ .space 0x04

dlabel D_8003FB2C
    /* 8003FB2C */ .space 0x0C

dlabel D_8003FB38
    /* 8003FB38 */ .space 0x1B0

dlabel D_8003FCE8
    /* 8003FCE8 */ .space 0x18

dlabel D_8003FD00
    /* 8003FD00 */ .space 0x20

dlabel D_8003FD20
    /* 8003FD20 */ .space 0x18

dlabel D_8003FD38
    /* 8003FD38 */ .space 0x20

dlabel D_8003FD58
    /* 8003FD58 */ .space 0x3050

dlabel D_80042DA8
    /* 80042DA8 */ .space 0x10

dlabel D_80042DB8
    /* 80042DB8 */ .space 0x14

dlabel D_80042DCC
    /* 80042DCC */ .space 0x3D4

dlabel D_800431A0
    /* 800431A0 */ .space 0x04

dlabel D_800431A4
    /* 800431A4 */ .space 0x04

dlabel D_800431A8
    /* 800431A8 */ .space 0x04

dlabel D_800431AC
    /* 800431AC */ .space 0x08

dlabel D_800431B4
    /* 800431B4 */ .space 0x0C

dlabel D_800431C0
    /* 800431C0 */ .space 0x08

dlabel D_800431C8
    /* 800431C8 */ .space 0x01

dlabel D_800431C9
    /* 800431C9 */ .space 0x7A

dlabel D_80043243
    /* 80043243 */ .space 0x13A

dlabel D_8004337D
    /* 8004337D */ .space 0x03

dlabel D_80043380
    /* 80043380 */ .space 0x08

dlabel D_80043388
    /* 80043388 */ .space 0x18

dlabel D_800433A0
    /* 800433A0 */ .space 0x04

dlabel D_800433A4
    /* 800433A4 */ .space 0x04

dlabel D_800433A8
    /* 800433A8 */ .space 0x18

dlabel D_800433C0
    /* 800433C0 */ .space 0x08

dlabel D_800433C8
    /* 800433C8 */ .space 0x41B0

dlabel D_80047578
    /* 80047578 */ .space 0x0C

dlabel D_80047584
    /* 80047584 */ .space 0x04

dlabel D_80047588
    /* 80047588 */ .space 0x02

dlabel D_8004758A
    /* 8004758A */ .space 0x04

dlabel D_8004758E
    /* 8004758E */ .space 0x06

dlabel D_80047594
    /* 80047594 */ .space 0x06

dlabel D_8004759A
    /* 8004759A */ .space 0x08

dlabel D_800475A2
    /* 800475A2 */ .space 0x10

dlabel D_800475B2
    /* 800475B2 */ .space 0x06

dlabel D_800475B8
    /* 800475B8 */ .space 0x18

dlabel D_800475D0
    /* 800475D0 */ .space 0x08

dlabel D_800475D8
    /* 800475D8 */ .space 0x02

dlabel D_800475DA
    /* 800475DA */ .space 0x02

dlabel D_800475DC
    /* 800475DC */ .space 0x02

dlabel D_800475DE
    /* 800475DE */ .space 0x02

dlabel D_800475E0
    /* 800475E0 */ .space 0x02

dlabel D_800475E2
    /* 800475E2 */ .space 0x02

dlabel D_800475E4
    /* 800475E4 */ .space 0x02

dlabel D_800475E6
    /* 800475E6 */ .space 0x02

dlabel D_800475E8
    /* 800475E8 */ .space 0x04

dlabel D_800475EC
    /* 800475EC */ .space 0x04

dlabel D_800475F0
    /* 800475F0 */ .space 0x04

dlabel D_800475F4
    /* 800475F4 */ .space 0x04

dlabel D_800475F8
    /* 800475F8 */ .space 0x04

dlabel D_800475FC
    /* 800475FC */ .space 0x04

dlabel D_80047600
    /* 80047600 */ .space 0x04

dlabel D_80047604
    /* 80047604 */ .space 0x04

dlabel D_80047608
    /* 80047608 */ .space 0x08

dlabel D_80047610
    /* 80047610 */ .space 0x68

dlabel D_80047678
    /* 80047678 */ .space 0x04

dlabel D_8004767C
    /* 8004767C */ .space 0x04

dlabel D_80047680
    /* 80047680 */ .space 0x04

dlabel D_80047684
    /* 80047684 */ .space 0x04

dlabel D_80047688
    /* 80047688 */ .space 0x04

dlabel D_8004768C
    /* 8004768C */ .space 0x04

dlabel D_80047690
    /* 80047690 */ .space 0x04

dlabel D_80047694
    /* 80047694 */ .space 0x04

dlabel D_80047698
    /* 80047698 */ .space 0x04

dlabel D_8004769C
    /* 8004769C */ .space 0x04

dlabel D_800476A0
    /* 800476A0 */ .space 0x02

dlabel D_800476A2
    /* 800476A2 */ .space 0x02

dlabel D_800476A4
    /* 800476A4 */ .space 0x04

dlabel D_800476A8
    /* 800476A8 */ .space 0x04

dlabel D_800476AC
    /* 800476AC */ .space 0x04

dlabel D_800476B0
    /* 800476B0 */ .space 0x10

dlabel D_800476C0
    /* 800476C0 */ .space 0x08

dlabel D_800476C8
    /* 800476C8 */ .space 0x28

dlabel D_800476F0
    /* 800476F0 */ .space 0x18

dlabel D_80047708
    /* 80047708 */ .space 0x12

dlabel D_8004771A
    /* 8004771A */ .space 0x02

dlabel D_8004771C
    /* 8004771C */ .space 0x04

dlabel D_80047720
    /* 80047720 */ .space 0x0C

dlabel D_8004772C
    /* 8004772C */ .space 0x04

dlabel D_80047730
    /* 80047730 */ .space 0x04

dlabel D_80047734
    /* 80047734 */ .space 0x04

dlabel D_80047738
    /* 80047738 */ .space 0x01

dlabel D_80047739
    /* 80047739 */ .space 0x01

dlabel D_8004773A
    /* 8004773A */ .space 0x02

dlabel D_8004773C
    /* 8004773C */ .space 0x04

dlabel D_80047740
    /* 80047740 */ .space 0x03

dlabel D_80047743
    /* 80047743 */ .space 0x01

dlabel D_80047744
    /* 80047744 */ .space 0x01

dlabel D_80047745
    /* 80047745 */ .space 0x03

dlabel D_80047748
    /* 80047748 */ .space 0x206

dlabel D_8004794E
    /* 8004794E */ .space 0x06

dlabel D_80047954
    /* 80047954 */ .space 0x04

dlabel D_80047958
    /* 80047958 */ .space 0x04

dlabel D_8004795C
    /* 8004795C */ .space 0x04

dlabel D_80047960
    /* 80047960 */ .space 0x04

dlabel D_80047964
    /* 80047964 */ .space 0x0C

dlabel D_80047970
    /* 80047970 */ .space 0x200

dlabel D_80047B70
    /* 80047B70 */ .space 0x1D0

dlabel D_80047D40
    /* 80047D40 */ .space 0x200

dlabel D_80047F40
    /* 80047F40 */ .space 0x20

dlabel D_80047F60
    /* 80047F60 */ .space 0x1E

dlabel D_80047F7E
    /* 80047F7E */ .space 0x06

dlabel D_80047F84
    /* 80047F84 */ .space 0x04

dlabel D_80047F88
    /* 80047F88 */ .space 0x04

dlabel D_80047F8C
    /* 80047F8C */ .space 0x04

dlabel D_80047F90
    /* 80047F90 */ .space 0x03

dlabel D_80047F93
    /* 80047F93 */ .space 0x01

dlabel D_80047F94
    /* 80047F94 */ .space 0x04

dlabel D_80047F98
    /* 80047F98 */ .space 0x04

dlabel D_80047F9C
    /* 80047F9C */ .space 0x04

dlabel D_80047FA0
    /* 80047FA0 */ .space 0x08

dlabel D_80047FA8
    /* 80047FA8 */ .space 0x06

dlabel D_80047FAE
    /* 80047FAE */ .space 0x0A

dlabel D_80047FB8
    /* 80047FB8 */ .space 0x64

dlabel D_8004801C
    /* 8004801C */ .space 0x04

dlabel D_80048020
    /* 80048020 */ .space 0x06

dlabel D_80048026
    /* 80048026 */ .space 0x02

dlabel D_80048028
    /* 80048028 */ .space 0x04

dlabel D_8004802C
    /* 8004802C */ .space 0x04

dlabel D_80048030
    /* 80048030 */ .space 0x04

dlabel D_80048034
    /* 80048034 */ .space 0x04

dlabel D_80048038
    /* 80048038 */ .space 0x100

dlabel D_80048138
    /* 80048138 */ .space 0x01

dlabel D_80048139
    /* 80048139 */ .space 0x01

dlabel D_8004813A
    /* 8004813A */ .space 0x05

dlabel D_8004813F
    /* 8004813F */ .space 0x01

dlabel D_80048140
    /* 80048140 */ .space 0x1C

dlabel D_8004815C
    /* 8004815C */ .space 0x02

dlabel D_8004815E
    /* 8004815E */ .space 0x02

dlabel D_80048160
    /* 80048160 */ .space 0x02

dlabel D_80048162
    /* 80048162 */ .space 0x08

dlabel D_8004816A
    /* 8004816A */ .space 0x2E

dlabel D_80048198
    /* 80048198 */ .space 0x4FB8

dlabel D_8004D150
    /* 8004D150 */ .space 0x04

dlabel D_8004D154
    /* 8004D154 */ .space 0x04

dlabel D_8004D158
    /* 8004D158 */ .space 0x08

dlabel D_8004D160
    /* 8004D160 */ .space 0x01

dlabel D_8004D161
    /* 8004D161 */ .space 0x1F

dlabel D_8004D180
    /* 8004D180 */ .space 0x30

dlabel D_8004D1B0
    /* 8004D1B0 */ .space 0x10

dlabel D_8004D1C0
    /* 8004D1C0 */ .space 0x08

dlabel D_8004D1C8
    /* 8004D1C8 */ .space 0x180

dlabel D_8004D348
    /* 8004D348 */ .space 0x08

dlabel D_8004D350
    /* 8004D350 */ .space 0x8F0

dlabel D_8004DC40
    /* 8004DC40 */ .space 0x08

dlabel D_8004DC48
    /* 8004DC48 */ .space 0x04

dlabel D_8004DC4C
    /* 8004DC4C */ .space 0x04

dlabel D_8004DC50
    /* 8004DC50 */ .space 0x04

dlabel D_8004DC54
    /* 8004DC54 */ .space 0x08

dlabel D_8004DC5C
    /* 8004DC5C */ .space 0x02

dlabel D_8004DC5E
    /* 8004DC5E */ .space 0x02

dlabel D_8004DC60
    /* 8004DC60 */ .space 0x08

dlabel D_8004DC68
    /* 8004DC68 */ .space 0x0C

dlabel D_8004DC74
    /* 8004DC74 */ .space 0x4C

dlabel D_8004DCC0
    /* 8004DCC0 */ .space 0x10

dlabel D_8004DCD0
    /* 8004DCD0 */ .space 0x1C

dlabel D_8004DCEC
    /* 8004DCEC */ .space 0x2DEC

dlabel D_80050AD8
    /* 80050AD8 */ .space 0x08

dlabel D_80050AE0
    /* 80050AE0 */ .space 0x17E0

dlabel D_800522C0
    /* 800522C0 */ .space 0x280

dlabel D_80052540
    /* 80052540 */ .space 0x14

dlabel D_80052554
    /* 80052554 */ .space 0x0C

dlabel D_80052560
    /* 80052560 */ .space 0x530

dlabel D_80052A90
    /* 80052A90 */ .space 0x04

dlabel D_80052A94
    /* 80052A94 */ .space 0x04

dlabel D_80052A98
    /* 80052A98 */ .space 0x30

dlabel D_80052AC8
    /* 80052AC8 */ .space 0x02

dlabel D_80052ACA
    /* 80052ACA */ .space 0x02

dlabel D_80052ACC
    /* 80052ACC */ .space 0x01

dlabel D_80052ACD
    /* 80052ACD */ .space 0x03

dlabel D_80052AD0
    /* 80052AD0 */ .space 0x04

dlabel D_80052AD4
    /* 80052AD4 */ .space 0x04

dlabel D_80052AD8
    /* 80052AD8 */ .space 0x04

dlabel D_80052ADC
    /* 80052ADC */ .space 0x0C

dlabel D_80052AE8
    /* 80052AE8 */ .space 0x44

dlabel D_80052B2C
    /* 80052B2C */ .space 0x08

dlabel D_80052B34
    /* 80052B34 */ .space 0x04

dlabel D_80052B38
    /* 80052B38 */ .space 0x04

dlabel D_80052B3C
    /* 80052B3C */ .space 0x24

dlabel D_80052B60
    /* 80052B60 */ .space 0x40

dlabel D_80052BA0
    /* 80052BA0 */ .space 0x40

dlabel D_80052BE0
    /* 80052BE0 */ .space 0xFFF

dlabel D_80053BDF
    /* 80053BDF */ .space 0x01

dlabel D_80053BE0
    /* 80053BE0 */ .space 0x02

dlabel D_80053BE2
    /* 80053BE2 */ .space 0x02

dlabel D_80053BE4
    /* 80053BE4 */ .space 0x04

dlabel D_80053BE8
    /* 80053BE8 */ .space 0x04

dlabel D_80053BEC
    /* 80053BEC */ .space 0x04

dlabel D_80053BF0
    /* 80053BF0 */ .space 0x01

dlabel D_80053BF1
    /* 80053BF1 */ .space 0x01

dlabel D_80053BF2
    /* 80053BF2 */ .space 0x01

dlabel D_80053BF3
    /* 80053BF3 */ .space 0x01

dlabel D_80053BF4
    /* 80053BF4 */ .space 0x01

dlabel D_80053BF5
    /* 80053BF5 */ .space 0x01

dlabel D_80053BF6
    /* 80053BF6 */ .space 0x02

dlabel D_80053BF8
    /* 80053BF8 */ .space 0x01

dlabel D_80053BF9
    /* 80053BF9 */ .space 0x01

dlabel D_80053BFA
    /* 80053BFA */ .space 0x01

dlabel D_80053BFB
    /* 80053BFB */ .space 0x01

dlabel D_80053BFC
    /* 80053BFC */ .space 0x01

dlabel D_80053BFD
    /* 80053BFD */ .space 0x01

dlabel D_80053BFE
    /* 80053BFE */ .space 0x82

dlabel D_80053C80
    /* 80053C80 */ .space 0x02

dlabel D_80053C82
    /* 80053C82 */ .space 0x02

dlabel D_80053C84
    /* 80053C84 */ .space 0x02

dlabel D_80053C86
    /* 80053C86 */ .space 0x02

dlabel D_80053C88
    /* 80053C88 */ .space 0x04

dlabel D_80053C8C
    /* 80053C8C */ .space 0x04

dlabel D_80053C90
    /* 80053C90 */ .space 0x02

dlabel D_80053C92
    /* 80053C92 */ .space 0x02

dlabel D_80053C94
    /* 80053C94 */ .space 0x02

dlabel D_80053C96
    /* 80053C96 */ .space 0x02

dlabel D_80053C98
    /* 80053C98 */ .space 0x9D0

dlabel D_80054668
    /* 80054668 */ .space 0x18

dlabel D_80054680
    /* 80054680 */ .space 0x5610

dlabel D_80059C90
    /* 80059C90 */ .space 0x40

dlabel D_80059CD0
    /* 80059CD0 */ .space 0x02

dlabel D_80059CD2
    /* 80059CD2 */ .space 0x02

dlabel D_80059CD4
    /* 80059CD4 */ .space 0x02

dlabel D_80059CD6
    /* 80059CD6 */ .space 0x02

dlabel D_80059CD8
    /* 80059CD8 */ .space 0x04

dlabel D_80059CDC
    /* 80059CDC */ .space 0x04

dlabel D_80059CE0
    /* 80059CE0 */ .space 0x1E08

dlabel D_8005BAE8
    /* 8005BAE8 */ .space 0x04

dlabel D_8005BAEC
    /* 8005BAEC */ .space 0x04

dlabel D_8005BAF0
    /* 8005BAF0 */ .space 0x10

dlabel D_8005BB00
    /* 8005BB00 */ .space 0x08

dlabel D_8005BB08
    /* 8005BB08 */ .space 0x18

dlabel D_8005BB20
    /* 8005BB20 */ .space 0x04

dlabel D_8005BB24
    /* 8005BB24 */ .space 0x04

dlabel D_8005BB28
    /* 8005BB28 */ .space 0x04

dlabel D_8005BB2C
    /* 8005BB2C */ .space 0x04

dlabel D_8005BB30
    /* 8005BB30 */ .space 0x04

dlabel D_8005BB34
    /* 8005BB34 */ .space 0x04

dlabel D_8005BB38
    /* 8005BB38 */ .space 0x04

dlabel D_8005BB3C
    /* 8005BB3C */ .space 0x04

dlabel D_8005BB40
    /* 8005BB40 */ .space 0x08

dlabel D_8005BB48
    /* 8005BB48 */ .space 0x04

dlabel D_8005BB4C
    /* 8005BB4C */ .space 0x04

dlabel D_8005BB50
    /* 8005BB50 */ .space 0x04

dlabel D_8005BB54
    /* 8005BB54 */ .space 0x404

dlabel D_8005BF58
    /* 8005BF58 */ .space 0x04

dlabel D_8005BF5C
    /* 8005BF5C */ .space 0x804

dlabel D_8005C760
    /* 8005C760 */ .space 0x04

dlabel D_8005C764
    /* 8005C764 */ .space 0x804

dlabel D_8005CF68
    /* 8005CF68 */ .space 0x04

dlabel D_8005CF6C
    /* 8005CF6C */ .space 0x8004

dlabel D_80064F70
    /* 80064F70 */ .space 0x04

dlabel D_80064F74
    /* 80064F74 */ .space 0x1004

dlabel D_80065F78
    /* 80065F78 */ .space 0x04

dlabel D_80065F7C
    /* 80065F7C */ .space 0x804

dlabel D_80066780
    /* 80066780 */ .space 0x04

dlabel D_80066784
    /* 80066784 */ .space 0xC04

dlabel D_80067388
    /* 80067388 */ .space 0x1B0

dlabel D_80067538
    /* 80067538 */ .space 0x1B0

dlabel D_800676E8
    /* 800676E8 */ .space 0x1B0

dlabel D_80067898
    /* 80067898 */ .space 0x1B0

dlabel D_80067A48
    /* 80067A48 */ .space 0x360

dlabel D_80067DA8
    /* 80067DA8 */ .space 0x1B0

dlabel D_80067F58
    /* 80067F58 */ .space 0x18

dlabel D_80067F70
    /* 80067F70 */ .space 0x18

dlabel D_80067F88
    /* 80067F88 */ .space 0x18

dlabel D_80067FA0
    /* 80067FA0 */ .space 0x18

dlabel D_80067FB8
    /* 80067FB8 */ .space 0x18

dlabel D_80067FD0
    /* 80067FD0 */ .space 0x18

dlabel D_80067FE8
    /* 80067FE8 */ .space 0x04

dlabel D_80067FEC
    /* 80067FEC */ .space 0x04

dlabel D_80067FF0
    /* 80067FF0 */ .space 0x40

dlabel D_80068030
    /* 80068030 */ .space 0x04

dlabel D_80068034
    /* 80068034 */ .space 0x04

dlabel D_80068038
    /* 80068038 */ .space 0x08

dlabel D_80068040
    /* 80068040 */ .space 0x20

dlabel D_80068060
    /* 80068060 */ .space 0x18

dlabel D_80068078
    /* 80068078 */ .space 0x04

dlabel D_8006807C
    /* 8006807C */ .space 0x04

dlabel D_80068080
    /* 80068080 */ .space 0x04

dlabel D_80068084
    /* 80068084 */ .space 0x04

dlabel D_80068088
    /* 80068088 */ .space 0x04

dlabel D_8006808C
    /* 8006808C */ .space 0x04

dlabel D_80068090
    /* 80068090 */ .space 0x04

dlabel D_80068094
    /* 80068094 */ .space 0x04

dlabel D_80068098
    /* 80068098 */ .space 0x04

dlabel D_8006809C
    /* 8006809C */ .space 0x04

dlabel D_800680A0
    /* 800680A0 */ .space 0x288

dlabel D_80068328
    /* 80068328 */ .space 0x04

dlabel D_8006832C
    /* 8006832C */ .space 0x2004

dlabel D_8006A330
    /* 8006A330 */ .space 0x4B0

dlabel D_8006A7E0
    /* 8006A7E0 */ .space 0xC8

dlabel D_8006A8A8
    /* 8006A8A8 */ .space 0x08

dlabel D_8006A8B0
    /* 8006A8B0 */ .space 0x18

dlabel D_8006A8C8
    /* 8006A8C8 */ .space 0x08

dlabel D_8006A8D0
    /* 8006A8D0 */ .space 0x18

dlabel D_8006A8E8
    /* 8006A8E8 */ .space 0x08

dlabel D_8006A8F0
    /* 8006A8F0 */ .space 0x18

dlabel D_8006A908
    /* 8006A908 */ .space 0x18

dlabel D_8006A920
    /* 8006A920 */ .space 0x20

dlabel D_8006A940
    /* 8006A940 */ .space 0x120

dlabel D_8006AA60
    /* 8006AA60 */ .space 0x04

dlabel D_8006AA64
    /* 8006AA64 */ .space 0x04

dlabel D_8006AA68
    /* 8006AA68 */ .space 0x04

dlabel D_8006AA6C
    /* 8006AA6C */ .space 0x04

dlabel D_8006AA70
    /* 8006AA70 */ .space 0x04

dlabel D_8006AA74
    /* 8006AA74 */ .space 0x0C

dlabel D_8006AA80
    /* 8006AA80 */ .space 0x04

dlabel D_8006AA84
    /* 8006AA84 */ .space 0x04

dlabel D_8006AA88
    /* 8006AA88 */ .space 0x40

dlabel D_8006AAC8
    /* 8006AAC8 */ .space 0x08

dlabel D_8006AAD0
    /* 8006AAD0 */ .space 0x40

dlabel D_8006AB10
    /* 8006AB10 */ .space 0x04

dlabel D_8006AB14
    /* 8006AB14 */ .space 0x04

dlabel D_8006AB18
    /* 8006AB18 */ .space 0x08

dlabel D_8006AB20
    /* 8006AB20 */ .space 0x08

dlabel D_8006AB28
    /* 8006AB28 */ .space 0x08

dlabel D_8006AB30
    /* 8006AB30 */ .space 0x08

dlabel D_8006AB38
    /* 8006AB38 */ .space 0x04

dlabel D_8006AB3C
    /* 8006AB3C */ .space 0x08

dlabel D_8006AB44
    /* 8006AB44 */ .space 0x04

dlabel D_8006AB48
    /* 8006AB48 */ .space 0x04

dlabel D_8006AB4C
    /* 8006AB4C */ .space 0x04

dlabel D_8006AB50
    /* 8006AB50 */ .space 0x38

dlabel D_8006AB88
    /* 8006AB88 */ .space 0x04

dlabel D_8006AB8C
    /* 8006AB8C */ .space 0x04

dlabel D_8006AB90
    /* 8006AB90 */ .space 0x08

dlabel D_8006AB98
    /* 8006AB98 */ .space 0x10

dlabel D_8006ABA8
    /* 8006ABA8 */ .space 0x10

dlabel D_8006ABB8
    /* 8006ABB8 */ .space 0x58

dlabel D_8006AC10
    /* 8006AC10 */ .space 0x1800

dlabel D_8006C410
    /* 8006C410 */ .space 0x40

dlabel D_8006C450
    /* 8006C450 */ .space 0x100

dlabel D_8006C550
    /* 8006C550 */ .space 0x04

dlabel D_8006C554
    /* 8006C554 */ .space 0x04

dlabel D_8006C558
    /* 8006C558 */ .space 0x02

dlabel D_8006C55A
    /* 8006C55A */ .space 0x02

dlabel D_8006C55C
    /* 8006C55C */ .space 0x02

dlabel D_8006C55E
    /* 8006C55E */ .space 0x02

dlabel D_8006C560
    /* 8006C560 */ .space 0x04

dlabel D_8006C564
    /* 8006C564 */ .space 0x02

dlabel D_8006C566
    /* 8006C566 */ .space 0x02

dlabel D_8006C568
    /* 8006C568 */ .space 0x02

dlabel D_8006C56A
    /* 8006C56A */ .space 0x02

dlabel D_8006C56C
    /* 8006C56C */ .space 0x01

dlabel D_8006C56D
    /* 8006C56D */ .space 0x01

dlabel D_8006C56E
    /* 8006C56E */ .space 0x02

dlabel D_8006C570
    /* 8006C570 */ .space 0x04

dlabel D_8006C574
    /* 8006C574 */ .space 0x02

dlabel D_8006C576
    /* 8006C576 */ .space 0x02

dlabel D_8006C578
    /* 8006C578 */ .space 0x08

dlabel D_8006C580
    /* 8006C580 */ .space 0x140

dlabel D_8006C6C0
    /* 8006C6C0 */ .space 0x02

dlabel D_8006C6C2
    /* 8006C6C2 */ .space 0x02

dlabel D_8006C6C4
    /* 8006C6C4 */ .space 0x02

dlabel D_8006C6C6
    /* 8006C6C6 */ .space 0x02

dlabel D_8006C6C8
    /* 8006C6C8 */ .space 0x04

dlabel D_8006C6CC
    /* 8006C6CC */ .space 0x02

dlabel D_8006C6CE
    /* 8006C6CE */ .space 0x02

dlabel D_8006C6D0
    /* 8006C6D0 */ .space 0x04

dlabel D_8006C6D4
    /* 8006C6D4 */ .space 0x04

dlabel D_8006C6D8
    /* 8006C6D8 */ .space 0x01

dlabel D_8006C6D9
    /* 8006C6D9 */ .space 0x27

dlabel D_8006C700
    /* 8006C700 */ .space 0x100

dlabel D_8006C800
    /* 8006C800 */ .space 0x100

dlabel D_8006C900
    /* 8006C900 */ .space 0x20

dlabel D_8006C920
    /* 8006C920 */ .space 0x20

dlabel D_8006C940
    /* 8006C940 */ .space 0x80

dlabel D_8006C9C0
    /* 8006C9C0 */ .space 0x3C

dlabel D_8006C9FC
    /* 8006C9FC */ .space 0x04

dlabel D_8006CA00
    /* 8006CA00 */ .space 0x01

dlabel D_8006CA01
    /* 8006CA01 */ .space 0x07

dlabel D_8006CA08
    /* 8006CA08 */ .space 0x20

dlabel D_8006CA28
    /* 8006CA28 */ .space 0x18

dlabel D_8006CA40
    /* 8006CA40 */ .space 0x10

dlabel D_8006CA50
    /* 8006CA50 */ .space 0x10

dlabel D_8006CA60
    /* 8006CA60 */ .space 0x10

dlabel D_8006CA70
    /* 8006CA70 */ .space 0x1B0

dlabel D_8006CC20
    /* 8006CC20 */ .space 0x1000

dlabel D_8006DC20
    /* 8006DC20 */ .space 0x18

dlabel D_8006DC38
    /* 8006DC38 */ .space 0x18

dlabel D_8006DC50
    /* 8006DC50 */ .space 0x02

dlabel D_8006DC52
    /* 8006DC52 */ .space 0x02

dlabel D_8006DC54
    /* 8006DC54 */ .space 0x14

dlabel D_8006DC68
    /* 8006DC68 */ .space 0x02

dlabel D_8006DC6A
    /* 8006DC6A */ .space 0x02

dlabel D_8006DC6C
    /* 8006DC6C */ .space 0x14

dlabel D_8006DC80
    /* 8006DC80 */ .space 0x10

dlabel D_8006DC90
    /* 8006DC90 */ .space 0x1B0

dlabel D_8006DE40
    /* 8006DE40 */ .space 0x1000

dlabel D_8006EE40
    /* 8006EE40 */ .space 0x18

dlabel D_8006EE58
    /* 8006EE58 */ .space 0x08

dlabel D_8006EE60
    /* 8006EE60 */ .space 0x10

dlabel D_8006EE70
    /* 8006EE70 */ .space 0x10

dlabel D_8006EE80
    /* 8006EE80 */ .space 0x40

dlabel D_8006EEC0
    /* 8006EEC0 */ .space 0x3C

dlabel D_8006EEFC
    /* 8006EEFC */ .space 0x04

dlabel D_8006EF00
    /* 8006EF00 */ .space 0x08

dlabel D_8006EF08
    /* 8006EF08 */ .space 0x18

dlabel D_8006EF20
    /* 8006EF20 */ .space 0x3C

dlabel D_8006EF5C
    /* 8006EF5C */ .space 0x04

dlabel D_8006EF60
    /* 8006EF60 */ .space 0x20

dlabel D_8006EF80
    /* 8006EF80 */ .space 0x04

dlabel D_8006EF84
    /* 8006EF84 */ .space 0x04

dlabel D_8006EF88
    /* 8006EF88 */ .space 0x04

dlabel D_8006EF8C
    /* 8006EF8C */ .space 0x04

dlabel D_8006EF90
    /* 8006EF90 */ .space 0x10

dlabel D_8006EFA0
    /* 8006EFA0 */ .space 0x04

dlabel D_8006EFA4
    /* 8006EFA4 */ .space 0x01

dlabel D_8006EFA5
    /* 8006EFA5 */ .space 0x01

dlabel D_8006EFA6
    /* 8006EFA6 */ .space 0x01

dlabel D_8006EFA7
    /* 8006EFA7 */ .space 0x01

dlabel D_8006EFA8
    /* 8006EFA8 */ .space 0x01

dlabel D_8006EFA9
    /* 8006EFA9 */ .space 0x03

dlabel D_8006EFAC
    /* 8006EFAC */ .space 0x74

dlabel D_8006F020
    /* 8006F020 */ .space 0x04

dlabel D_8006F024
    /* 8006F024 */ .space 0x01

dlabel D_8006F025
    /* 8006F025 */ .space 0x01

dlabel D_8006F026
    /* 8006F026 */ .space 0x02

dlabel D_8006F028
    /* 8006F028 */ .space 0x01

dlabel D_8006F029
    /* 8006F029 */ .space 0x03

dlabel D_8006F02C
    /* 8006F02C */ .space 0x68

dlabel D_8006F094
    /* 8006F094 */ .space 0x0C

dlabel D_8006F0A0
    /* 8006F0A0 */ .space 0x08

dlabel D_8006F0A8
    /* 8006F0A8 */ .space 0x18

dlabel D_8006F0C0
    /* 8006F0C0 */ .space 0x1B0

dlabel D_8006F270
    /* 8006F270 */ .space 0x1000
